### ISSUE TITLE
RFI/Help wanted - using sp-local-tag

### ISSUE THREAD

**Issue by rileyrg** [Fuco1/smartparens#1000]
## Expected behavior
When I select a region and press "b" then it encloses the region with tags to make it bold.
## Actual behavior
my region is deleted and "b" is inserted ;)
## Steps to reproduce the problem
```
  (use-package smartparens
    :commands (smartparens-mode)
    :diminish smartparens-mode
    :config
    (setq sp-show-pair-from-inside nil)
    (require 'smartparens-config)
    (sp-local-tag '(mhtml-mode html-mode) "b" "<span class=\"bold\">" "</span>")
    (smartparens-global-mode t)
    )

```
The sp-local-tag call is from the docs.

I open an mhtml-mode file (t.html)... And smartparens is on and the mode is mhtml mode.

Am I doing something really stupid here and totally misread the docs?

**Comment by Fuco1** [comment]
The `sp-local-tag` does not exist anymore.  Where did you find it? I need to remove it from the docs.

**Comment by Fuco1** [comment]
Also congrats on the # 1000 :D :tada: :tada: :tada:
