### ISSUE TITLE
Customize pair inserting

### ISSUE THREAD

**Issue by ema2159** [Fuco1/smartparens#1001]
## Expected behavior
When inserting a "(" at te left of something that's not another type of parenthesis/bracket or space, don't insert the pair. For example (^ represents the cursor):
 
 foo 
^
insert "(":

(foo

Then insert "(" at the end:

(foo ()

## Actual behavior
()foo ()

Couldn't find that customization in the docs.

**Comment by Fuco1** [comment]
There used to be an option for this but it was removed in favour of a more general system.  This should help: https://smartparens.readthedocs.io/en/latest/permissions.html#filters

**Comment by ema2159** [comment]
Done! I simply set:
``` elisp
  (sp-pair "(" nil :unless '(sp-point-before-word-p))
  (sp-pair "[" nil :unless '(sp-point-before-word-p))
  (sp-pair "{" nil :unless '(sp-point-before-word-p))
  (sp-pair "\"" nil :unless '(sp-point-before-word-p))
  (sp-pair "'" nil :unless '(sp-point-before-word-p))
```

Thanks!
