### ISSUE TITLE
elisp modes, slurping and comments/semicolons

### ISSUE THREAD

**Issue by bymoz089** [Fuco1/smartparens#1010]
sluping fails, when comments or semicolons are involved in elisp modes.      
This are maybe two different issues.

Two examples, with cursor at location `|` and command `sp-forward-slurp-sexp` evaled **multiple** times.
Both examples are located at the end of an buffer, otherwise, there will be no errormessage, but weird slurping of other sexps.

### first example 

    (foo (gah|) ?\; bar baz)
    
### second example

    (foo (baz|) ;; bar
         moo
         mee)

### first

    (foo (gah ?\; bar baz))

### second

    (foo (baz ;; bar
         moo
         mee))

### first

    (foo (gah ?)\; bar baz)

Error message: 

 > funcall-interactively: Wrong type argument: number-or-marker-p, nil

### second

    (foo (baz ;; bar)
         moo
         mee)

 > Search failed: there is an unmatched expression somewhere or we are at the beginning/end of file.

## Environment & version information

- `smartparens` version: recent MELPA: 2020.02.03
- Active major-mode: interactive-lisp-mode (elisp-mode)
- Emacs version (`M-x emacs-version`): 25.x
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: vanilla
- OS: Linux

**Comment by Fuco1** [comment]
The second example works for me on E26.1 in emacs-lisp-mode.

The first one is broken. Are you loading `smartparens-config.el`? It contains some additional setup.

**Comment by Fuco1** [comment]
I fixed the first case on master now.

**Comment by bymoz089** [comment]
Both seem to be fixed.
This is one of my favourite packages, thanks for the trouble of releasing and bugfixing!

**Comment by Fuco1** [comment]
@bymoz089 thanks for the kind words, cheers!
