### ISSUE TITLE
Possible to select the entire sexp?

### ISSUE THREAD

**Issue by introom** [Fuco1/smartparens#1012]
Suppose the code is the following, where the cursor is at |.

> (def a (fo|obar))

Invoking the function once will select (foobar), and a second time will select (def a (foobar)).

**Comment by Fuco1** [comment]
You can do it with `C-u C-u M-x sp-select-next-thing` called twice.  More convenient might be the expand-region package or your own wrapper function.

**Comment by introom** [comment]
Thanks.  expand-region really heplps.
