### ISSUE TITLE
Incorrect splitting of Python's triple-quoted strings

### ISSUE THREAD

**Issue by dsedivec** [Fuco1/smartparens#1015]
## Expected behavior

In a python-mode buffer (from `python.el` that ships with Emacs),  with cursor at "`|`" in the code

```python
"""foo|bar"""
```

I expected <kbd>M-x</kbd> `sp-split-sexp` <kbd>RET</kbd> to produce

```python
"""foo"""|"""bar"""
```

## Actual behavior

Result of `sp-split-sexp` is instead:

```python
"""foo"|"bar"""
```

## Steps to reproduce the problem

1. Start with empty Emacs config
2. Configure MELPA and install `smartparens`
3. <kbd>M-:</kbd> `(require 'smartparens-config)` <kbd>RET</kbd>
4. <kbd>C-x</kbd> <kbd>C-f</kbd> `/tmp/scratch.py` <kbd>RET</kbd>
5. Type `"""foobar"""` into the buffer and move point between `foo` and `bar`
6. <kbd>M-x</kbd> `sp-split-sexp` <kbd>RET</kbd>

## Backtraces if necessary (`M-x toggle-debug-on-error`)

N/A

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: 20200229.1752
- Active `major-mode`: `python-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 26.3 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.60 Version 10.13.6 (Build 17G8030)) of 2019-11-08
- Starterkit/Distribution: None (vanilla Emacs)
- OS: darwin

Thank you for all your work on Smartparens!

**Comment by Fuco1** [comment]
I've managed to reproduce this and have a fix ready.
