### ISSUE TITLE
Disabling single quotes in source blocks

### ISSUE THREAD

**Issue by jagrg** [Fuco1/smartparens#1017]
In the smartparens-config library, pairing single quotes (') is disabled in sp-lisp-modes. What do you think of also disabling it in source blocks? For example:

```
(defun sp-in-src-block-p (_id _action _context)
  (when (org-in-src-block-p)
    (let* ((el (org-element-at-point))
           (lang (org-element-property :language el))
           (mode (intern (concat lang "-mode"))))
      (memq mode sp-lisp-modes))))

(sp-local-pair 'org-mode "'" "'"
               :unless '(:add sp-in-src-block-p))

```

- `smartparens` version: 20200229.1752
- Active `major-mode`: `lisp-interaction-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-16
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

**Comment by JasZhe** [comment]
If someone else is stumbling upon this, note I had to change this slightly on emacs 28 using doom since instead of "elisp-mode" it's now "emacs-lisp-mode"

```
(defun sp-in-src-block-p (_id _action _context)
  (when (org-in-src-block-p)
    (let* ((el (org-element-at-point))
            (lang (org-element-property :language el))
            (mode (intern (concat (if (string= lang "elisp") "emacs-lisp" lang) "-mode"))))
      (memq mode sp-lisp-modes))))
```

**Comment by Fuco1** [comment]
This is a good idea, I've implemented it based on the two snippets here.  It's pushed to master branch now.

Thank you both!
