### ISSUE TITLE
support for automatic js-jsx-syntax in js-mode

### ISSUE THREAD

**Issue by mallt** [Fuco1/smartparens#1018]
Starting from emacs 27 the JSX syntax is automatically detected and enabled in `js-mode` without the need to enable `js-jsx-mode`. If the `js-jsx-syntax` variable is `t` this means the automatic JSX support is active. It would be great if smartparens would also provide support for this.

I've tried to simply add `js-mode` to `sp--html-modes` but that doesn't seem to do much. Does someone have an idea what would need to be changed to provide support for this?

Thanks a lot!

**Comment by mallt** [comment]
@jacksonrayhamilton Could you perhaps help me out to find the best way to determine if the point is inside a jsx code block? 

Thanks a lot!

**Comment by Fuco1** [comment]
Do you mean to make the "html" elements navigable as pairs?

I've now tried it in `typescript-mode` (tsx) with react:

    (add-to-list 'sp-navigate-consider-sgml-tags 'typescript-mode)

works for me.

![](https://i.imgur.com/Nx35cCf.png)

**Comment by mallt** [comment]
@Fuco1 Great, thanks a lot! I've added `js-mode` to `sp-navigate-consider-sgml-tags` and everything seems to work perfectly now! It was especially the consistent killing of tags that I was looking for.

Thanks again!
