### ISSUE TITLE
in clojure, sp-up-sexp doesn't work with vector

### ISSUE THREAD

**Issue by introom** [Fuco1/smartparens#1022]
```
(if [:a | :b] 
  (some c))
```

| is where the caret is.  Run `sp-up-sexp`  several times, the caret halts at the ending ] without going further.

**Comment by andreyorst** [comment]
doesn't seem to reproduce

**Comment by Fuco1** [comment]
I can't reproduce either.

**Comment by introom** [comment]
To reproduce this, evil mode must be enabled.  The direct reason is because of evil-move-beyond-eol being nil.

**Comment by Fuco1** [comment]
There's nothing we can do then, this is a behaviour of evil-mode.
