### ISSUE TITLE
[RFE] Do not add a pair if a word is just after the caret

### ISSUE THREAD

**Issue by Hi-Angel** [Fuco1/smartparens#1024]
I'm wondering if authors would welcome contribution to change behavior of inserting a pair so, that if a caret is before a word, a pair would not be created. That is because usually when the caret is just before word, more often than not you want to enclose the following text inside parentheses/braces, so you have to manually remove the pair created.

I have [this config](https://github.com/Hi-Angel/dotfiles/blob/bbd08c6883daed98b9feaad7f86304d332f51e3d/.emacs.d/lisp/sp-sublimelike.el) which does that. I called it "sublime-like" because when I created this rule I was inspired by SublimeText, which has amazingly non-intrusive autopairs. That said, I haven't used ST for many years and modified config at some point, so I can't be sure it still matches their behavior. Still, this config I also used for years and I'm pretty satisfied with this behavior.

**Comment by Hi-Angel** [comment]
Okay, thanks! Right, well, it's just that I remember that back when I crafted up that heuristic, my colleagues were using CodeBlocks IDE, which has no heuristic for autopairs. So pressing a `(` always gets you a `)`. I remember nobody liked that feature, it was causing too many misses which was irritating. So nobody used autopairs in CodeBlocks. Judging from this experience, I am not sure that always inserting a pair makes good defaults.

Anyway, you're the boss, thank you :)

**Comment by Fuco1** [comment]
I wouldn't mind shipping some other configuration stacks, but not enabled by default.  In other words, people can pick and choose what kind of strictness they prefer.  Something like "profiles".

**Comment by Hi-Angel** [comment]
Okay, apparently, [someone else](https://www.reddit.com/r/emacs/comments/kcvimc/how_to_move_inserted_semicolon_after_closing/gfyyip2?utm_source=share&utm_medium=web2x&context=3) *(a link to a reddit comment — my browser for some reason doesn't scroll down to it, but it's highlighted)* is interested in such behavior, so I might send a PR then with this being disabled by default.

> I wouldn't mind shipping some other configuration stacks, but not enabled by default

Okay, so, if there's no oppositions, I think of creating a PR with [this file](https://github.com/Hi-Angel/dotfiles/blob/master/.emacs.d/lisp/sp-sublimelike.el) being added similar to, for example, `smartparens-c.el`. *(well, I'll add a header similar to one in the file and a comment about why it's called "sublime-like")*.
