### ISSUE TITLE
")" to move out of sexp design question

### ISSUE THREAD

**Issue by lewang** [Fuco1/smartparens#103]
I'm trying to understand the process that led up to this implementation.

What I see is ")" inserted immediately, then some delay later something comes along and deletes it and moves my point after the current sexp.

This is an inferior experience to paredit.  And if my buffer wasn't edited, now it is, and my undo history is somehow manipulated.

Why is this complexity necessary?  Is there a way to get the paredit behaviour?

**Comment by Fuco1** [comment]
This issue should be fixed by the code in the `reworking-input-system` branch.  If anyone using the blink/electric setup can verify, it would be sweet.
