### ISSUE TITLE
Smartparens doesn't insert this (“ ”) quote pair.

### ISSUE THREAD

**Issue by DanGNU** [Fuco1/smartparens#1034]
## Expected behavior

Set the quote pair by any of these means:

`(sp-pair "“" "”")`
`(sp-local-pair 'org-mode "“" "”")`
`(sp-with-modes 'org-mode (sp-local-pair "“" "”")`

When typing in org mode get the quote pair inserted automatically, as « », for example.

## Actual behavior

Only the opening quote is inserted. I tried with other utf-8 characters and all of them, when defined as a pair, get inserted properly, even the closing quote is inserted when the opening is anything different than “. The hexadecimal value of these quotes is \#x201c for “, and \#x201d for ”.

I also tried scaping the character as in the normal double quote, like `(sp-pair "\“" "\”")` but it also didn't work.

## Steps to reproduce the problem

Evaluate the following code to insert quotes easily:

```
(defun drp-insert-open-quotes ()
  (interactive)
  (insert-char '#x201c))
(defun drp-insert-close-quotes ()
  (interactive)
  (insert-char '#x201d))
(global-set-key (kbd "C-x 8 ` \"") 'drp-insert-open-quotes)
(global-set-key (kbd "C-x 8 ' \"") 'drp-insert-close-quotes)
```

Evaluate any one of the following lines

```
(sp-pair "“" "”")
(sp-local-pair 'org-mode "“" "”")
(sp-with-modes 'org-mode (sp-local-pair "“" "”")
```

Try inserting the opening quote with 
```
C-x 8 ` "
```
 or with
```
C-x 8 RET 201c
```

## Backtraces if necessary (`M-x toggle-debug-on-error`)

There isn't an error.

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: 20200324.2147
- Active `major-mode`: `org-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 27.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.17) of 2020-04-09
- Starterkit/Distribution: vanilla
- OS: gnu/linux

**Comment by Fuco1** [comment]
I remember that the newer Emacs does some craziness with the "fancy quotes", it might very well be replacing them internally by something else when it comes to calculations/syntax.

Is this only a problem in org-mode?  It might also be something in org.

**Comment by Fuco1** [comment]
When I add the config

    (sp-local-pair 'org-mode "“" "”" :actions '(insert navigate))

I can navigate using this pair and `show-smartparens-mode` highlights it properly.  Right now only characters inserted using `self-insert-command` are considered for completion.

If you change your function to

```emacs-lisp
(defun drp-insert-open-quotes ()
  (interactive)
  (execute-kbd-macro "“"))
```

it will work.

**Comment by DanGNU** [comment]
Sorry for answering so late, got the emails, tried it and was happy with the outcome, so I forgot about it. 

If this can't get fixed any more than what you reccomended due to Emacs itself, I guess we can consider it closed.

**Comment by Fuco1** [comment]
Well, is there even something left to "fix any more than [this]"? :) 

If you have more questions go ahead!  Otherwise I think we can close indeed.

**Comment by DanGNU** [comment]
My only request is to refere people here in case they have the same situation, maybe with an edit in the documentation, apart of that, the problem is basically fixed.
