### ISSUE TITLE
Do not overwrite clipboard contents on C-Backspace

### ISSUE THREAD

**Issue by phoe** [Fuco1/smartparens#1040]
## Expected behavior

I want `C-Backspace` to **not** overwrite the most recent thing I have pasted in the clipboard.

## Actual behavior

Hitting `C-Backspace` puts the deleted characters into the kill ring, overwriting whatever I had in the clipboard.

## Steps to reproduce the problem

Hit `C-Backspace` and then try to paste.

## Environment & version information
- `smartparens` version: 20200324.2147
- Active `major-mode`: `slime-repl-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-17, modified by Debian
- Starterkit/Distribution: Spacemacs
- OS: gnu/linux

**Comment by phoe** [comment]
Fixed by remapping `C-Backspace` to `sp-backward-delete-word`.

**Comment by phoe** [comment]
Actually *not* fixed. Issuing `(define-key smartparens-mode-map (kbd "<C-backspace>") 'sp-backward-delete-word)` in IELM causes erratic behavior, as the kill ring is seemingly cycled over.

**Comment by Fuco1** [comment]
Fixed in #1169
