### ISSUE TITLE
Doesnt' work with emacs27 cc mode

### ISSUE THREAD

**Issue by introom** [Fuco1/smartparens#1041]
Emacs27.0.91

Suppose the cursor is at |,  and the text is ( ), so we have ( | )

when we type ), the desired behavior would be: ( ) |

however, smartparen shows ( ) | ), and after a second, the last ) automatically disappears and becomes the correct ( ) |.

when in emacs26, the extra redundant ) will never appear.

**Comment by Fuco1** [comment]
I can't reproduce this anymore on emacs 28
