### ISSUE TITLE
Just sp-backward-up-sexp remove spaces

### ISSUE THREAD

**Issue by conao3** [Fuco1/smartparens#1042]
## Expected behavior
Just navigate point without remove anything.

## Actual behavior
navigate point and remove spaces.

## Steps to reproduce the problem
1. Write below and make major-mode `lisp-interaction-mode`. (`_` is pointer potision)
```emacs-lisp
(


  (_a))
```
2. Invoke `sp-backward-up-sexp` buffer should be...
```emacs-lisp
(


  _(a))
```
4. and invoke `sp-backward-up-sexp` once again, buffer should be...
```emacs-lisp
_((a))
```

Why smartparens remove spaces? I don't atempt to do that, I want to just move point.

## Backtraces if necessary (`M-x toggle-debug-on-error`)
None

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: 20200324.2147
- Active `major-mode`: `lisp-interaction-mode`
- Smartparens strict mode: t
- Emacs version (`M-x emacs-version`): GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-04-04
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

**Comment by mihaiolteanu** [comment]
This is a non-issue.
The documentation for `sp-backward-up-sexp` says:

```
If called interactively and `sp-navigate-reindent-after-up' is
enabled for current major-mode, remove the whitespace between
beginning of the expression and the first \"thing\" inside the
expression.
```

Just set the `sp-navigate-reindent-after-up` variable accordingly if you don't want this behavior.
