### ISSUE TITLE
C89 comment behavior after space

### ISSUE THREAD

**Issue by mat-xc** [Fuco1/smartparens#1044]
## Expected behavior
When I press `SPC` after `/*` format the comment like this:
`/*-|-*/`. Where `|` is the point and `-` is a space.

## Actual behavior
The comment is like this:
`/*--|-*/` (double space in the front).

## Steps to reproduce the problem
Enable `smartparens` and load `smartparens-c`.
Then type `/* ` in a c-mode buffer.

## Environment & version information

- `smartparens` version: melpa (but not sure)
- Active major-mode: c-mode
- Emacs version (`M-x emacs-version`): 27.0.91
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Doom
- OS: Arch Linux

**Comment by mat-xc** [comment]
I think the problem is in smartparens-c.el:
`(" | " "SPC")` should be `("| " "SPC")`.
If so, I can make a pull request.

**Comment by omar-polo** [comment]
Today I was particularly upset with how comments gets expanded in C buffers, so I took a look and it seems that your fix is the correct one indeed.  Since this issue was stale for ~2 months I took the liberty to make a PR for it, hope you don't mind :)

**Comment by Fuco1** [comment]
Thank you both for reporting the bug and the solution.  Sorry it took me so long :blush:

**Comment by omar-polo** [comment]
no problem at all, thank you for maintaining this package :)

cheers!
