### ISSUE TITLE
Incorrectly matching Elisp character literals.

### ISSUE THREAD

**Issue by Janfel** [Fuco1/smartparens#1045]
## Expected behavior

In the following code, smartparens should match the outer parens, ignoring the `?(` and `?\(` character literals.

```elisp
(string ?( )
(string ?\( )
```

## Actual behavior

As shown by `show-smartparens-mode`, the `?(` and `?\(` literals are incorrectly matching and matched by the closing paren.

## Steps to reproduce the problem

1. Open an `emacs-lisp-mode` buffer.
1. Type the code from above.
1. Start `show-smartparens-mode`.
1. Navigate the parentheses.

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.
- `smartparens` version: 555626a43f9bb1985aa9a0eb675f2b88b29702c
- Active `major-mode`: `emacs-lisp-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21) of 2020-08-11
- Starterkit/Distribution: Doom including Evil
- OS: gnu/linux

**Comment by Fuco1** [comment]
I can't reproduce this.  Make sure that the option `sp-navigate-skip-match` includes `emacs-lisp-mode` with the function `sp--elisp-skip-match`.  This should be the default if you have `emacs-lisp-mode` configured as one of the `sp-lisp-modes`.

Try also to `(require 'smartparens-config)` which has some additional default settings.

**Comment by Janfel** [comment]
I have looked into `sp-navigate-skip-match` and found out that the issue lies with [these lines](https://github.com/hlissner/doom-emacs/blob/77646c5f42ef1d3586af7526c06af932d1340ca5/modules/config/default/config.el#L80-L86) in Doom Emacs which set `sp-navigate-skip-match` to `nil`. After deactivating the offending function everything works as expected.
