### ISSUE TITLE
smartparens-global-mode does not enable smartparens

### ISSUE THREAD

**Issue by zck** [Fuco1/smartparens#1052]
## Expected behavior
After calling `(smartparens-global-mode t)`, I expect smartparens to be enabled.

## Actual behavior
Smartparens is not enabled. Typing an open parenthesis does not also insert the close paren.

## Steps to reproduce the problem
From `emacs -Q`, put this code in `*scratch*`, and evaluate it:

```
(require 'package)
(package-initialize)

(require 'smartparens)
(smartparens-global-mode t)
```

Then type an open parenthesis, and notice that no close parenthesis is inserted.

We can verify that smartparens is _not_ enabled by running `C-h m` (for `describe-mode`), which displays a buffer with the list of enabled minor modes. Smartparens is not there.

## Backtraces if necessary (`M-x toggle-debug-on-error`)
No error is thrown.

##  Debugging
Looking through smartparens.el, I got down to the function `turn-on-smartparens-mode`. When it's called, it conditionally calls `(smartparens-mode t)`.

Running this code in `*scratch*` does not enable smartparens mode. However, running `(smartparens-mode)` with no argument _does_ turn on smartparens.

## Environment & version information

I noticed this when I built a new version of Emacs from the git repo and updated Smartparens. So I don't know if this is a problem with Emacs or a problem with Smartparens.

- `smartparens` version: 20201007.1753
- Active `major-mode`: `lisp-interaction-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2020-11-02
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

**Comment by jakelinnzy** [comment]
Exactly same issue here on Emacs 28 (`GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.1.0, NS appkit-2022.10 Version 11.0.1 (Build 20B29)) of 2020-11-18`).

**Comment by zck** [comment]
This was fixed in Emacs as [this commit](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=2a4b0da28c3d25f2eea17c9dc95f7a244bdf4535), from November 1st.
