### ISSUE TITLE
sp-(forward|backward)-symbol issues in clojure

### ISSUE THREAD

**Issue by achikin** [Fuco1/smartparens#1053]
## Expected behavior
`sp-forward-symbol` moves to the next symbol correctly in Clojure
Same for backward command
## Actual behavior
The behavior of `sp-forward-symbol` is inconsistent on clojure syntax. Please see detailed explanations below.
Same for backward command
## Steps to reproduce the problem

If I place cursor on `map` and call `sp-forward-symbol` several times I observe the following behavior
Captions are above images
_
Initial position (the cursor is orange and blue denotes a pairing bracket)
![image](https://user-images.githubusercontent.com/611419/98467147-e436f880-21e4-11eb-974a-95473c0eea54.png)
_
For some reason the cursor stops before `#` which is not a symbol in clojure but a part of function definition macro `#()`
![image](https://user-images.githubusercontent.com/611419/98467154-eef18d80-21e4-11eb-9ca6-b9807acbb38e.png)
_
Now cursor is on an open bracket which is not a symbol (it looks like `sp-forward-symbol` stops on a position right before the symbol but I'm not sure if it is valid behavior because when you do `sp-backward-symbol` - the cursor stops on the first character of the symbol)
![image](https://user-images.githubusercontent.com/611419/98467163-f9138c00-21e4-11eb-8938-accc829e2c5c.png)
_
Now the cursor moved to the closing bracket which is not a symbol and there is no symbol after a bracket
![image](https://user-images.githubusercontent.com/611419/98467167-003a9a00-21e5-11eb-85a3-45f3c3002ec6.png)
_
I keep calling `sp-forward-symbol` now the cursor is between `:a` and `1`. Is `:a` skipped for some reason?
![image](https://user-images.githubusercontent.com/611419/98467177-0892d500-21e5-11eb-8226-b43197ff7d90.png)
_
Now the cursor is on `1` and any further calls to `sp-forward-symbol` does not move the cursor to `:b` as expected
P.S. as suggested in https://github.com/Fuco1/smartparens/issues/1037 setting `evil-move-beyond-eol` to `t` fixes this issue
![image](https://user-images.githubusercontent.com/611419/98467183-0fb9e300-21e5-11eb-88f2-07a4883af8a1.png)
_
`sp-backward-symbol` works better but is stuck on `#(`
![image](https://user-images.githubusercontent.com/611419/98467662-91ab0b80-21e7-11eb-970b-d82862f163a6.png)
![Screenshot 2020-11-08 at 17 26 52](https://user-images.githubusercontent.com/611419/98467668-9cfe3700-21e7-11eb-827f-99b9a25bf695.png) 
![image](https://user-images.githubusercontent.com/611419/98467674-a5ef0880-21e7-11eb-8cc8-f2e57582a254.png)
Etc....
![image](https://user-images.githubusercontent.com/611419/98467697-bf905000-21e7-11eb-8df7-d60a6069045c.png)
![image](https://user-images.githubusercontent.com/611419/98467704-c919b800-21e7-11eb-806c-4c4cf4fd00b5.png)
Now the cursor is stuck and further calls to `sp-backward-symbol` do nothing.

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

```
- `smartparens` version: 20201007.1753
- Active `major-mode`: `clojurescript-mode`
- Smartparens strict mode: t
- Emacs version (`M-x emacs-version`): GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2020-08-12
- Starterkit/Distribution: Spacemacs
- OS: darwin
```
Spacemacs is on `develop` branch.

**Comment by achikin** [comment]
I skimmed through the code and it seems to me that the `#()` also affects `evil-cleverparens` that relies on smartparens for primitives definitions.

**Comment by Fuco1** [comment]
For the first point, ending after map is correct, we end on the first character after the symbol.  However, moving by paren is definitely odd.

**Comment by Fuco1** [comment]
Maybe there is a confusion about what is called symbol in clojure syntax and what is called symbol in emacs "buffer syntax".  Emacs has its own syntactic naming conventions codified in [syntax tables](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Table-Internals.html).  Basically any word is a symbol, such as `identity` here is a symbol, because it's a "word".  Not only `:a` is a symbol, which semantically within clojure is a keyword or something but that's not what we mean by saying symbol within smartparens.

The only bug here is that it considers the `#` prefix as a symbol in itself.
