### ISSUE TITLE
Error running timer ‘sp-show--pair-function’: (invalid-function sp--while-no-input)

### ISSUE THREAD

**Issue by TatriX** [Fuco1/smartparens#1055]
After upgrading I'm getting error in `*scratch*` or any other non-special buffer.
It seems that it only happens after native compilation.

## Backtraces
```
Debugger entered--Lisp error: (invalid-function sp--while-no-input)
  sp--while-no-input(nil)
  sp-show--pair-function()
  apply(sp-show--pair-function nil)
  timer-event-handler([t 0 0 125000 t sp-show--pair-function nil idle 0])
```

## Environment & version information

- `smartparens` version: 20201113.951
- Active `major-mode`: `lisp-interaction-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.17.3) of 2020-11-17
- Starterkit/Distribution: Vanilla / nativegcc branch
- OS: gnu/linux

**Comment by ChillingHsu** [comment]
I have the same problem, but there's a simple work around is that you can delete `smartparens-*` files in your `.emacs.d/eln-cache` then restart your emacs.

**Comment by henrythebuilder** [comment]
Hi, same here, after upgrading error in any buffer with/without hook to `smartparens-mode`:

### Emacs config
Global config:
```
(require 'smartparens-config)
(show-smartparens-global-mode t)
```
plus some hook to 'special file' es. `(add-hook 'elixir-mode-hook #'smartparens-mode) `

### \*Backtrace\*
```
Debugger entered--Lisp error: (invalid-function sp--while-no-input)
  sp--while-no-input(nil)
  sp-show--pair-function()
  apply(sp-show--pair-function nil)
  timer-event-handler([t 0 0 125000 t sp-show--pair-function nil idle 0])
```
###  Smartparens rebuild log
[smartparens-compile.log](https://github.com/Fuco1/smartparens/files/5558861/smartparens-compile.log)

### Environment Information
- Smartparens 20201113.951
- Emacs build from source: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-08-13
- Debian GNU/Linux 10 (buster)

**Comment by henrythebuilder** [comment]
_Information update:_
The error "_seam disappear_" after rebuilding all Emacs packages with `M-: (byte-recompile-directory package-user-dir nil 'force)`
Current Smartparents version/requirement:
- smartparens 20201113.951
- dash 20200803.1520
- cl-lib  1.0 (builtin)
- same emacs configuration (no change)

**Comment by ChillingHsu** [comment]
I got the same problem, and I've tried the method supplied by @henrythebuilder but unfortunately, it didn't work.
It seems this problem is caused by the native-comp process which didn't treat macro correctly. So my workaround is to delete the `smartparens-(some alphanumeric code).eln` in the directory `~/.emacs.d/eln-cache/(your emacs version)/`. then add the following code to your config file:
```
(require 'comp)
(add-to-list 'comp-bootstrap-black-list "smartparens")
(add-to-list 'comp-deferred-compilation-black-list "smartparens")
```
which forbid native-comp to comp `smartparens`, and the problem is gone.
hope it helps

**Comment by dangom** [comment]
This problem is not related to native-comp as the issue appears on Emacs 27.1 as well.

**Comment by thblt** [comment]
This is a byte-compilation issue, #1054 fixes it.

**Comment by thblt** [comment]
(I mean it should affect all compilation modes)

**Comment by thblt** [comment]
I believe #1054 fixed this issue, which can now be closed.
