### ISSUE TITLE
Lua do keyword is not matched with end

### ISSUE THREAD

**Issue by andreyorst** [Fuco1/smartparens#1067]
With the given Lua code:

``` lua
function f() do
  local res = nil
  do
    -- side-effects
    res = 1 + 2
  end
end
```

Smartparens matches end of the function incorrectly:

![image](https://user-images.githubusercontent.com/19470159/104152671-484a8880-53f1-11eb-98b1-694f1bc6f43b.png)

This is extremely similar to #707 and can be fixed similarly, but raises the question if Smartparens should have a way to declare some heuristics for possible ambiguity in matches?

**Comment by Fuco1** [comment]
Well, since we're using mostly just regexp and stack for parsing, these things ought to happen.  Maybe with the recent push to include actual parsers into Emacs we could use something more powerful.

Of course all this can be fixed with custom code.
