### ISSUE TITLE
Finding and fixing the missing brackets for tcl script with smartparens.

### ISSUE THREAD

**Issue by hongyi-zhao** [Fuco1/smartparens#1069]
On Ubuntu 20.10, I'm using the latest git master version of Emacs and trying to troubleshoot the following TCL script snippet:
```
[...]
set sendcmds [lmap l [split [string trim $sendcmds] \n] {
if {[regexp {^\s*#} $l} continue
string trim $l
}]
[...]
```
In the above code snippets, two close brackets are missed. But finding
and fixing this sort of error manually is indeed a tedious and
laborious job. Can the smartparens package help me find the right spot and fix the
problem quickly for this scenario?

Best,
HY

**Comment by Fuco1** [comment]
I don't know TCL so I don't know where the pair should be inserted.  There is a feature which can insert missing brackets to preserve balance, but it simply works at point, there is no logic to understand the code.  See command `sp-up-sexp` and setting `sp-navigate-close-if-unbalanced`.

**Comment by hongyi-zhao** [comment]
> there is no logic to understand the code. 

Is it impossible to understand the logic of code with code's AI?

> See command sp-up-sexp and setting sp-navigate-close-if-unbalanced.

Do you mean the accurate/precise key sequence as shown below:

`M-x RET sp-up-sexp RET sp-navigate-close-if-unbalanced`

**Comment by Fuco1** [comment]
Put `(setq sp-navigate-close-if-unbalanced t)` in your config somewhere.  Then executing `sp-up-sexp` will add closing delimiter if the buffer is unbalanced.

> Is it impossible to understand the logic of code with code's AI?

If you're asking in general, then no as this would probably solve halting problem.  If you're asking about this specific package, there is no AI, it's only a parser.

**Comment by hongyi-zhao** [comment]
Got it. Thanks a lot.

**Comment by Fuco1** [comment]
It's a feature designed mostly for lisp and likely won't be extended.  It is impossible to solve this in the general case.

I'll close this as there is no resolution.

**Comment by hongyi-zhao** [comment]
I have always heard that Emacs is the world's most powerful editor. Isn't elisp capable of handling such problems in nature? OTOH, do you know whether there are other Emacs packages available to solve problems like this?

**Comment by Fuco1** [comment]
I don't know.
