### ISSUE TITLE
Check for derived modes instead of listing all the modes, and comint buffers problem.

### ISSUE THREAD

**Issue by vspinu** [Fuco1/smartparens#107]
SP configuration relies on explicitly listing modes. For example in
sp-local-pair and a couple of other places.

Would it be feasible for sp to check for derived modes (derived-mode-p)?

Then, instead of giving the full list as in sp--lisp-modes one would give only
the parent mode 'lisp-mode. Similarly for comint buffers. There are hundredes of
derived modes from comint out there.

The commint mode is also marked as special mode. Thus sp is not activated there,
and this is unfortunate because comint buffers are also editable by users and sp
should work there as well. This is related to #83 as inferior ESS is also a
comint buffer.

**Comment by Fuco1** [comment]
This is now implemented, see http://smartparens.readthedocs.io/en/latest/pair-management.html#local-pair-definitions
