### ISSUE TITLE
SP behavior differs in `mhtml-mode` and `html-mode`

### ISSUE THREAD

**Issue by thomasheartman** [Fuco1/smartparens#1089]
Hi! 🙋🏾  I love smartparens, so thanks for all the work that's been put into it! 

However, I ran into an issue today and I don't know whether it's expected or not. It seems counterintuitive to me, at least The issue concerns `mhtml-mode` and `html-mode`.

Regardless of whether this is intended or not: is there a way to make smartparens act the same in `mhtml-mode` as in `html-mode`?

## Expected behavior

When in `mhtml-mode`, a major mode derived from `html-mode`, smartparens should behave the same. In particular, slurping and barfing and movement (such as `sp-up-sexp`) should behave the same.

## Actual behavior

In `mhtml-mode`, slurping, barfing, and expression-based movement doesn't work or works differently than in `html-mode`

## Steps to reproduce the problem

(Reproducible with `emacs -q`)

1. Use the following contents in a buffer with `html-mode`:
```html
<div id="one"></div>
<div id="two"></div>
```
2. With the cursor at the start of the buffer, notice how `sp-forward-sexp` moves the cursor to the end of the first closing div tag. The opposite goes for `sp-backward-sexp`
3. With the cursor inside the first div (`one`), notice you can slurp (and subsequently barf) the following div (`two`)
4. Switch to `mhtml-mode` and attempt steps 2 and 3. Notice how the movements now don't act on the HTML tags as expressions in the same way and how slurping and barfing just doesn't work.

## Backtraces if necessary (`M-x toggle-debug-on-error`)

None. No errors that cause backtraces.

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: on branch `master`, using commit 911cc896a0f2eb8b5fbdd6fc8331523ad9889a3a from May 29th (via straight.el)
- Active `major-mode`: `mhtml-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.16.0)
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

Thank you!

**Comment by Fuco1** [comment]
Hi.  Sorry for the delayed reaction.  Let's first try to add the mode to the "html modes" list:

    (add-to-list 'sp--html-modes 'mhtml-mode)

The items on the list intentionally do not respect inheritance so that might be the issue.

**Comment by thomasheartman** [comment]
No worries! Thanks for getting back to me.

Adding it to `sp--html-modes` seems to have done the trick in new Emacs instances, but not in a currently running instance. That is: if I add it to the configuration (via `use-package`) and start a new instance, it seems to work as expected (🥳), but it doesn't seem to update correctly if I try and evaluate it in a running Emacs instance. After adding it to the list I both reloaded the major mode and smartparens-mode, but it still acts the same as if before I added it.

Of course, this isn't a big deal (I could just restart my current Emacs instance -- though using EXWM, that means restarting my desktop session), but I'm curious as to why it doesn't seem to work in a running instance. Does the variable have to be set before something else happens or something?

Anyway, it seems to work correctly now, so thank you very much! 🙏🏾  I'll go ahead and close the issue, but if you know what the issue with the running Emacs instance is, I'd love to know.

Also, yeah, making it a defcustom sounds like it'd be a good idea, I think.

**Comment by Fuco1** [comment]
It's because the file `smartparens-html.el` which is loaded when you load the package sets the configuration to all the modes in the list.  So you would need to reload that file and it should work.

An example configuration that is there looks like this

```
(--each sp--html-modes  ;; <- do something for all the modes in the list
  (add-to-list 'sp-navigate-consider-sgml-tags it))
```

which obviously does not run if you update the variable later.

Glad the issue is resolved.  Is `mhtml-mode` common?  We can add it to the list by default, which would make sense if it is something more people can come across.

**Comment by thomasheartman** [comment]
Ah, okay, got it. Thanks! ☺️ 

About `mhtml-mode`: According to the docs it was added in Emacs 26.1 (so it's an included major mode) and I think it's now the default for `.html` files.

According to the function docs:

> Major mode based on ‘html-mode’, but works with embedded JS and CSS.
>
> Code inside a <script> element is indented using the rules from
> ‘js-mode’; and code inside a <style> element is indented using
> the rules from ‘css-mode’.

So judging from that, I think it would make sense to add it to the list by default.
