### ISSUE TITLE
Error when editing SAS or Stata source code

### ISSUE THREAD

**Issue by jia-j-chen** [Fuco1/smartparens#1090]
## Expected behavior
No error messages when editing SAS or Stata source code files.

## Actual behavior
An error message shows up: sp--post-self-insert-hook-handler: (wrong-type-argument stringp nil)

## Steps to reproduce the problem
1. Open a SAS or Stata source code file (both are statistics programming language)
2. Start typing
3. The error appears

## Backtraces if necessary (`M-x toggle-debug-on-error`)
`Debugger entered--Lisp error: (wrong-type-argument stringp nil) re-search-forward(nil 2 t) sp--looking-back(nil nil nil) sp--looking-back-p(nil) sp-ess-roxy-str-p("'" insert comment) sp--do-action-p("'" insert) sp--all-pairs-to-insert(nil nil) sp--pair-to-insert() sp-insert-pair() sp--post-self-insert-hook-handler() self-insert-command(1 32) funcall-interactively(self-insert-command 1 32) call-interactively(self-insert-command nil nil) command-execute(self-insert-command)`

## Environment & version information
- `smartparens` version: 20210529.1129
- Active `major-mode`: `emacs-lisp-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2021-06-03
- Starterkit/Distribution: Spacemacs
- OS: gnu/linux

**Comment by Fuco1** [comment]
There was a bug in some ESS code which was only relevant to R-mode but got applied to all the "ess modes".
