### ISSUE TITLE
Function to list all defined pairs

### ISSUE THREAD

**Issue by BlueDrink9** [Fuco1/smartparens#1092]
I would like to apply a filter on all pairs.
The wiki gives examples like `(sp-pair "[" nil :unless sp-point-before-eol-p)`, which I would like to replicate for all pairs, even though they may change depending on the mode. I don't want to have to know in advance what a mode's pairs will be.
Ideally I would have something like 

```elisp
(loop for pair in (sp-get-pairs)
   do (sp-pair pair nil :unless sp-point-before-eol-p)
   )
```

Could such a function be exposed?

**Comment by Fuco1** [comment]
They are exposed in the variable `sp-pair-list` which is buffer-local and re-set when you change the major-mode.

To get details of a specific pair you can use `sp-get-pair` function.

**Comment by BlueDrink9** [comment]
Thank you. I missed where it was documented. It might be worth making that explicit on the filters page
