### ISSUE TITLE
Distributing spartparens in NonGNU ELPA

### ISSUE THREAD

**Issue by phikal** [Fuco1/smartparens#1095]
Hi,

I'm currently packaging a few popular packages for NonGNU ELPA, pending the next release of Emacs that will be adding the repository to the default `package-archives` list.

For the most part, it seems to be working, the only problem is that compared to MELPA, NonGNU ELPA uses the commit that bumps the version tag to tag a new release. Without such a tag, it is necessary to manually tag every new release. While cumbersome, it is possible if you are not interested.

In case, as indicated in other issues, a new release shouldn't be tagged now, you can also create a separate branch for NonGNU ELPA, and update the version tag there. The repository will then be tracking this branch, until you can merge it and the master branch can be merged.

**Comment by Fuco1** [comment]
I don't understand what is the action.  There are tagged commits, those won't be picked?  Or is the system listening only to the new commits?

I can probably prepare a new tag, it's not like there's any activity going on so the current HEAD is as stable as any.

Let me know what steps I should take.  I have no issues tagging the latest commit as a release if that's required.

**Comment by phikal** [comment]
No, ELPA creates a new release whenever the `Version` tag in the package header is incremented, instead of when a commit is taged (as with MELPA).

All that has to be done is to add a line like 

    Version: 1.13.0

and update it whenever a release is made.

But there is no hurry/necessity to do anything now: the suggestion for the [current package specification](https://lists.gnu.org/archive/html/emacs-devel/2021-08/txtcv9LD8PFsd.txt) has a manually chosen commit to package, that can be removed when the next release is ready.

**Comment by phikal** [comment]
On a related note, the package has now been added to NonGNU ELPA with a manually tagged commit: https://elpa.nongnu.org/nongnu/smartparens.html

It might be worth documenting this to make the installation easier for Emacs 28+ users.

**Comment by Fuco1** [comment]
Any idea why the version is 4.7.1? https://elpa.nongnu.org/nongnu/smartparens.html

**Comment by phikal** [comment]
Matus Goljer ***@***.***> writes:

> Any idea why the version is 4.7.1? https://elpa.nongnu.org/nongnu/smartparens.html

That was a mistake in the (manual) package specification, I'll fix that.

Thank you for noticing!

-- 
	Philip Kaludercic

**Comment by phikal** [comment]
I have tried building smartparens locally once again, and it is now being generated with version 1.11.0.

I think the best way to fix the issue would be to add a `Version` attribute in the package header, and setting it to 1.11.1 or something like that.

**Comment by Fuco1** [comment]
Is this still relevant? I see this https://elpa.nongnu.org/nongnu/smartparens.html 

Is this really shipping the tagged version though? That is more than five years old and really super not relevant :D

**Comment by Fuco1** [comment]
Well, two things

1. can we close this issue?
2. I should probably tag a new release, because 1.11 is really old.

**Comment by monnier** [comment]
> 2. I should probably tag a new release, because 1.11 is really old.

Side note: (Non)GNU ELPA doesn't pay attention to tags, it uses
instead the commit where the` Version:` header is changed in
`smartparens.el`.

**Comment by Fuco1** [comment]
I'm going to close this issue because I don't really understand what's going on with NonGNU ELPA and to be quite honest my capacity is very limited at this moment.  If you guys want to distribute this package in any way whatsoever you always can, but I can't spend time on this now.

Thanks.

**Comment by phikal** [comment]
Nothing has changed on our end since [this comment](https://github.com/Fuco1/smartparens/issues/1095#issuecomment-909237471).  I see there has been a commit (6cd739af01d75038a4d7b80a49afd10d97198166) that added a `Version` header, which can be used as the reference commit to distribute smartparens.  Whenever you want to update the package, you just need to update this header in `smartparens.el`.
