### ISSUE TITLE
`sp-char-escaped-p` errors out when `point` at `point-min`

### ISSUE THREAD

**Issue by Janfel** [Fuco1/smartparens#1111]
## Expected behavior

`sp-char-escaped-p` returns `nil` when `point` at `point-min`.

## Actual behavior

`sp-char-escaped-p` errors out when `point` at `point-min`.

## Steps to reproduce the problem

1. Add `sp-char-escaped-p` as an `:unless` condition to a pair.
2. Try to insert this pair at `point-min`.

## Backtraces if necessary (`M-x toggle-debug-on-error`)

Could not get a backtrace, even with `debug-on-error` set to `t`.

## Environment & version information

- `smartparens` version: 2834c66c4f09778d0c57e99886c329188eed591a
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 28.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-10-05
- Starterkit/Distribution: Doom Emacs
- OS: gnu/linux

**Comment by Fuco1** [comment]
Thanks for the report, fixed.
