### ISSUE TITLE
Ruby curly brackets not working

### ISSUE THREAD

**Issue by the-moriarty** [Fuco1/smartparens#1119]
Explain of issue:
https://github.com/hlissner/doom-emacs/issues/5931

**Comment by Fuco1** [comment]
This is not a smartparens feature.  Something configures this behaviour in doom emacs for () and [] but not for {}.  You can add it manually for your config if you want:

    (sp-local-pair 'ruby-mode "{" nil :post-handlers '(("||\n[i]" "RET")))
