### ISSUE TITLE
Is it possible not to activate pair overlay

### ISSUE THREAD

**Issue by wang1zhen** [Fuco1/smartparens#1130]
Hi, I am a evil user and I really love your package. I wonder if it is possible not to activate the pair overlay whenever I insert a pair? As I use `C-g` to switch back to evil normal state, when smartparens is activated, it is bind to  `sp-remove-active-pair-overlay`, and as a result, when I insert something like `(a (b (c (d))))`, it would take several times of `C-g` to get to evil normal state.

Even if I manually unbind `C-g` in `smartparens-mode-map` with `(general-unbind smartparens-mode-map "C-g")`, pressing `C-g` still executes `sp-remove-active-pair-overlay`. `describe-function sp-remove-active-pair-overlay` gives the following information, so I have no idea how to modify it

```
Key Bindings
This command is not in any keymaps.
```

**Comment by Fuco1** [comment]
Try to unbind it from `sp-pair-overlay-keymap`.

**Comment by Fuco1** [comment]
Closing this to sort through the open issues.  If the above did not work, feel free to reopen.
