### ISSUE TITLE
Disable the auto pair in specified mode is not work?

### ISSUE THREAD

**Issue by zw963** [Fuco1/smartparens#1133]
I want to disable auto pair the "=" on org-mode completely.

so, i try this:

```cl
(sp-local-pair 'org-mode "=" "=" :when nil)
```

But it work. 

Thank you.

**Comment by titanofold** [comment]
The correct solution is:

    (sp-local-pair 'org-mode "=" nil :actions nil)

This is noted in the function documentation.

**Comment by zw963** [comment]
Thanks, it works!

**Comment by Fuco1** [comment]
Sorry for the horrible API.  Maybe I should make some wrappers for these common cases to make it more discoverable.
