### ISSUE TITLE
Does anyone know how to enable smartparens-strict-mode by default on startup?

### ISSUE THREAD

**Issue by aykaramba** [Fuco1/smartparens#1134]
Hi.

I can start SmartParens by default with the following in my .emacs config file:

(require 'smartparens)
(smart-parens-global-mode t)

This works, but it doesn't start strict mode on startup.  Does anyone know how to enabled it by default?

Thanks.

**Comment by jasonhemann** [comment]
You will want to use the function `turn-on-smartparens-strict-mode`.

**Comment by aykaramba** [comment]
This works, thanks!

**Comment by Fuco1** [comment]
There is also `smartparens-global-strict-mode`

**Comment by aykaramba** [comment]
Aha!  Thank you kindly.
