### ISSUE TITLE
global-smartparens-mode no longer exists?

### ISSUE THREAD

**Issue by jleonard-r7** [Fuco1/smartparens#1146]
See:
https://github.com/syl20bnr/spacemacs/issues/15922

Now that this symbol's definition is void, how would one go about enabling smartparens globally?

**Comment by Fuco1** [comment]
It exists 
![image](https://user-images.githubusercontent.com/2664959/219895758-bee345cc-2c33-4d63-be5f-39f34400c092.png)

**Comment by jleonard-r7** [comment]
So it was renamed?

**Comment by jleonard-r7** [comment]
And technically the symbol I asked about does not exist. A different one (the rename) does.

**Comment by Fuco1** [comment]
literally did not change since the first commit 
![image](https://user-images.githubusercontent.com/2664959/219900331-66a490f3-bda1-4c97-a939-4170248d6d6c.png)

**Comment by jleonard-r7** [comment]
Very strange. I guess I followed the naming convention of other packages which typically start with the global- and never noticed that an error was being emitted during startup until just recently. Sorry about that!
