### ISSUE TITLE
Replicate VIM's ci"

### ISSUE THREAD

**Issue by Fuco1** [Fuco1/smartparens#115]
Should ask user for opening pair (like `sp-rewrap-sexp`), then descend into sexp of that type and call `C-0 sp-kill-sexp`.

**Comment by Wilfred** [comment]
`C-u C-u M-x sp-kill-hybrid-sexp` does this, doesn't it?

I often use https://github.com/magnars/change-inner.el for this too.

**Comment by Fuco1** [comment]
No, consider

    foo | (bar "baz")

In vim `ci"` jumps to `bar`, kills it, and enters the insert mode with point between `""`.

**Comment by Fuco1** [comment]
I have made this operate on the next sexp only.  That is the 99% use-case... reading in the delimiter is annoying to me and so that's that.  Some evil integration mode could probably enhance this if they want to.
