### ISSUE TITLE
Error on Emacs init 

### ISSUE THREAD

**Issue by jjpe** [Fuco1/smartparens#1150]
## Expected behavior
Emacs initializing without errors

## Actual behavior
When Emacs tries to init, it opens a `*Warnings*` buffer with the following content:
 
```
Warning (initialization): An error occurred while loading ‘/home/j/.emacs.d/init.el’:

error: Keyword argument (sp-in-string-p) not one of (:trigger :trigger-wrap :actions :when :unless :pre-handlers :post-handlers :wrap :bind :insert :prefix :suffix :skip-match)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
Warning (comp): /home/j/.emacs.d/modules/prelude-c.el: Error: Symbol's function definition is void sp-pair Disable showing Disable logging
Warning (comp): /home/j/.emacs.d/modules/prelude-emacs-lisp.el: Error: Symbol's function definition is void sp-pair Disable showing Disable logging
Warning (comp): /home/j/.emacs.d/modules/prelude-perl.el: Error: Symbol's function definition is void sp-pair Disable showing Disable logging
Warning (comp): /home/j/.emacs.d/modules/prelude-lisp.el: Error: Symbol's function definition is void sp-pair Disable showing Disable logging
Warning (comp): /home/j/.emacs.d/modules/prelude-js.el: Error: Symbol's function definition is void sp-pair Disable showing Disable logging

```

## Steps to reproduce the problem

- Install version `20230225.1026` (I did so using `list-packages`)
- (not sure if relevant) compile the code to native
- try to restart Emacs

## Backtraces if necessary (`M-x toggle-debug-on-error`)
The error occurs before I can execute commands.

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: `20230225.1026`
- Active major-mode: N/A
- Emacs version (`M-x emacs-version`): 28.2
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla:
- OS: NixOS

**Comment by Fuco1** [comment]
This line suggests that you did not load the package properly. 

    Symbol's function definition is void sp-pair Disable showing Disable logging

Try to load an empty emacs with just smartparens and see if you can reproduce this problem.

**Comment by jjpe** [comment]
Turns out it was an update to `prelude.el` that broke the functionality:
Another `prelude.el` update has just fixed it.
