### ISSUE TITLE
Would you be open to a PR removing the anaphoric `dash` functions?

### ISSUE THREAD

**Issue by LemonBreezes** [Fuco1/smartparens#1172]
Hi. I've seen some benchmarks such as https://kisaragi-hiu.com/performance-cl-lib-dash-seq indicating that anaphoric versions of dash functionals such as `--filter` are much slower than their non-anaphoric counterparts like `-filter`. I am interested in going through the code and these replacements, as well as minor performance tweaks if any do come up. Would you be open to such a PR?

**Comment by Fuco1** [comment]
When you install packages they are usually compiled so there shouldn't be any difference. In non compiled code it can be a bit slower.

I don't really mind such a change but maybe it's not really necessary.

**Comment by LemonBreezes** [comment]
> When you install packages they are usually compiled so there shouldn't be any difference. In non compiled code it can be a bit slower.
> 
> I don't really mind such a change but maybe it's not really necessary.

Ohhh sorry. I read the benchmarks wrong. The anaphoric versions are the same speed for us since the functions they are called in are compiled.
