### ISSUE TITLE
Do not reindent after kill in yaml modes

### ISSUE THREAD

**Issue by rudi** [Fuco1/smartparens#1188]
Since yaml is indentation-sensitive, `yaml-mode` (on gnu elpa) and `yaml-ts-mode` (part of the next Emacs release) should be added to `sp-no-reindent-after-kill-modes`.

https://github.com/Fuco1/smartparens/blob/0778a8a84064cf2bc3a9857bd0e7a4619cc1e5c3/smartparens.el#L614

**Comment by Fuco1** [comment]
Thanks for reporting!
