### ISSUE TITLE
In Python (and other langs) no need to escape ' if it's inside " quotes, and vice versa

### ISSUE THREAD

**Issue by vmalloc** [Fuco1/smartparens#12]
currently typing:

    'this is a "string"'

causes:

    'this is a \"string\"'

**Comment by andreas-roehler** [comment]
Seems gone. Close?

**Comment by expez** [comment]
@andreas-roehler Are you in the correct major-mode when you are testing these issues?

**Comment by andreas-roehler** [comment]
Yes, think so. BTW being in python-mode from python-mode.el. However, that should not matter.
BTW also tried in elixir-mode - fine there too.

**Comment by Fuco1** [comment]
THis is "fixed" on master because escaping has been completely removed.

**Comment by andreas-roehler** [comment]
So close it?

**Comment by Fuco1** [comment]
No, because the solution is not satisfactory. What I did was simply remove escaping alltogether. It's not a fix until it's in the release.

**Comment by Fuco1** [comment]
Fixed in version 1.8 where the autoescape was added but is now more context-aware.  See the release notes.
