### ISSUE TITLE
sp-get-buffer-char-syntax: Symbol’s function definition is void: syntax-class-to-char

### ISSUE THREAD

**Issue by rechvs** [Fuco1/smartparens#1200]
## Expected behavior
Calling `sp-backward-kill-word` kills the word before point.

## Actual behavior
The function displays the following error in the minibuffer:
> sp-get-buffer-char-syntax: Symbol’s function definition is void: syntax-class-to-char

## Steps to reproduce the problem
In any file with Smartparens mode active, call `sp-backward-kill-word`.

## Backtraces if necessary (`M-x toggle-debug-on-error`)

```
Debugger entered--Lisp error: (void-function syntax-class-to-char)
  syntax-class-to-char(2)
  sp-get-buffer-char-syntax(49219)
  sp-syntax-before()
  sp-skip-backward-to-symbol()
  sp-get-symbol(t)
  sp-backward-kill-symbol(1 t)
  sp-backward-kill-word(1)
  funcall-interactively(sp-backward-kill-word 1)
  call-interactively(sp-backward-kill-word nil nil)
  command-execute(sp-backward-kill-word)
```

## Environment & version information

- `smartparens` version: 20240403.2143
- Active `major-mode`: `emacs-lisp-mode`
- Smartparens strict mode: t
- Emacs version (`M-x emacs-version`): GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2023-02-23, modified by Debian
- Starterkit/Distribution: 
- OS: gnu/linux

**Comment by Fuco1** [comment]
Hmm, seems like the function `syntax-class-to-char` was introduced in Emacs 28.  I'll add a compat function for it.

**Comment by rechvs** [comment]
@Fuco1 I’m afraid the problem still persists. Should I open a new issue?
## Backtraces
```
Debugger entered--Lisp error: (void-function sp--syntax-class-to-char)
  sp--syntax-class-to-char(0)
  sp-get-buffer-char-syntax(50349)
  sp-syntax-before()
  sp-skip-backward-to-symbol()
  sp-get-symbol(t)
  sp-backward-kill-symbol(1 t)
  sp-backward-kill-word(1)
  funcall-interactively(sp-backward-kill-word 1)
  call-interactively(sp-backward-kill-word nil nil)
  command-execute(sp-backward-kill-word)
```
## Environment & version information
- `smartparens` version: 20240410.1709
- Active `major-mode`: `emacs-lisp-mode`
- Smartparens strict mode: t
- Emacs version (`M-x emacs-version`): GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2023-02-23, modified by Debian
- Starterkit/Distribution: 
- OS: gnu/linux

**Comment by Fuco1** [comment]
@rechvs thanks for checking it out, there is already an issue for it #1204
