### ISSUE TITLE
Either fix ert failures or mark them as expected

### ISSUE THREAD

**Issue by temyurchenko** [Fuco1/smartparens#1201]
## Expected behavior

Running `cask exec ert-runner` results in no failing tests.

## Actual behavior

First, `ert-runner` complains about duplicated test names. However, even after we fix those, we get 42 failures. The best and simplest way to deal with those is to mark them as [«expected failures»](https://www.gnu.org/software/emacs/manual/html_mono/ert.html#Expected-Failures). It is slightly complicated due to some tests being wrapped in macros.

## Steps to reproduce the problem

Run `cask build` followed by `cask exec ert-runner`. 

## Environment & version information

- `smartparens` version: 20231024.1804
- Active `major-mode`: `fundamental-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 29.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.40, cairo version 1.18.0)
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

**Comment by Fuco1** [comment]
The failing test cases need to be corrected, they should not be failing.  I am slowly fixing some but it's a long process.

**Comment by temyurchenko** [comment]
> The failing test cases need to be corrected, they should not be failing. I am slowly fixing some but it's a long process.

Oh, yes, I absolutely get that. Sorry, if that sounded pressuring. I was just reading the contributing guide, which advised to run a test-suite, which I ran and it showed a lot of errors. I haven't found any documentation about that in the repo, so I decided to make an issue for others who might be confused.

**Comment by Fuco1** [comment]
No worries :)

**Comment by Fuco1** [comment]
I'll make a new issue with all the failing tests so I can track progress individually.
