### ISSUE TITLE
Use-package declaration in readme doesn't load properly

### ISSUE THREAD

**Issue by Esnos33** [Fuco1/smartparens#1207]
## Expected behavior
When code from readme is in init.el
```
(use-package smartparens-mode
  :ensure smartparens  ;; install the package
  :hook (prog-mode text-mode markdown-mode) ;; add `smartparens-mode` to these hooks
  :config
  ;; load default config
  (require 'smartparens-config))
```
The smartparens-config should be loaded when opening .lisp or .el file, in particular  
```
(sp-with-modes sp-lisp-modes
  ;; disable ', it's the quote character!
  (sp-local-pair "'" nil :actions nil))
```
should be loaded, and typing quote `'` shouldn't make pair `''`.

## Actual behavior
After typing `'`, the pair `''` is typed.

My current fix to is to change `:config` to `:init` in use-package declaration.

## Steps to reproduce the problem
Copy paste use-package declaration to init.el
eval init.el
type `'` in blank line

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: 20240416.2253
- Active `major-mode`: `emacs-lisp-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

**Comment by sg2002** [comment]
It seems like absolutely nothing from the :config section gets evaluated. This can be easily tested by trying something like (message "smartparens loaded") there.

In addition non-defered loading causes an error: "Error (use-package): Cannot load smartparens-mode" This can be reproduced by removing the :hook section from the above recipe.

**Comment by Fuco1** [comment]
The package name after `use-package` needs to be the `provide` of the packege, so `smartparens`, not `smartparens-mode`.  I will fix it.
