### ISSUE TITLE
[minor] harmless typo

### ISSUE THREAD

**Issue by hunt0r** [Fuco1/smartparens#1214]
https://github.com/Fuco1/smartparens/blob/71eab0b1a92137453375590425378edc8748f4a7/smartparens.el#L5856

Line should say ... "next symbol object". (Not "next pair object".)

There is no loss of meaning, intent is clear. Feel free to reject. Thanks for a great package!

**Comment by Fuco1** [comment]
Good catch, thanks! I pushed a fix :)
