### ISSUE TITLE
Proper initialization

### ISSUE THREAD

**Issue by bbatsov** [Fuco1/smartparens#129]
This code is problematic:

``` lisp
;; global initialization
(sp--update-trigger-keys)
(defadvice delete-backward-char (before sp-delete-pair-advice activate)
  (save-match-data
    (sp-delete-pair (ad-get-arg 0))))
(add-hook 'post-command-hook 'sp--post-command-hook-handler)
(add-hook 'pre-command-hook 'sp--pre-command-hook-handler)
(sp--set-base-key-bindings)
(sp--update-override-key-bindings)

(defadvice ac-complete (after sp-auto-complete-advice activate)
  (when smartparens-mode
    (setq sp-recent-keys (reverse (split-string ad-return-value "")))
    (sp-insert-pair))
  ad-return-value)
```

Now the code is triggered only once - when the package is required. It should actually be triggered by the mode activation and the hooks and advices should be removed on mode deactivation.

**Comment by Fuco1** [comment]
I cleaned it up as best as possible.  There's still some advices left over which I will port to nadvice.el (see #1143) and add/remove in the minor mode hook.  Lot of this code was useless anyway since Emacs changed a lot from 10 years ago.
