### ISSUE TITLE
Auto-inserting closing tag should work even after hitting backspace while writting

### ISSUE THREAD

**Issue by Jell** [Fuco1/smartparens#137]
Before:

```scheme
be|

beg|

bega|

beg|

begi|

begin|

begin |
```

After:
```scheme
be|

beg|

bega|

beg|

begi|

begin|

begin |
end
```

I think popping the last key in the list of last key presses instead of inserting the delete key in the list should work. My understanding of the "latest key presses" based on the current implementation:

`("n" "i" "<DEL>" "a" "g" "e" "b")`

after:

`("n" "i" "g" "e" "b")`

**Comment by Fuco1** [comment]
This has actually been solved as a side-effect of the new input-handling mechanism.
