### ISSUE TITLE
Markdown-mode defaults config

### ISSUE THREAD

**Issue by bbatsov** [Fuco1/smartparens#141]
A continuation of our discussion from #136.

In Markdown mode:
- ` cannot be nested (it can appear within other delimiters like []), but there is a second delimiter that's ``` (no idea how we can handle that one.
- \* cannot be nested, but there a second delimiter **. Unfortunately \* is also used for bullet points, so I guess it cannot be something we pair automatically
- `_` is also a paired delimiter, when at the beginning of some text

**Comment by Fuco1** [comment]
1. The tripple escape can only be at the BOL so we can test that
2. Same
3. We should check if the point is after word and if so not pair (see `'` in default config)

**Comment by Fuco1** [comment]
And here I thought this would be simple... turns out the new input system totally can't handle these nested delimiters with shared suffixes.  Makes me doubt if the rewrite was useful at all.

**Comment by Fuco1** [comment]
The new setup was hold back for so long by another bug that was really messing up the nested stars markup.  I think I fixed that in a2c1186 and d5221cb so this should now work as one would expect.

I invite everyone to look at the test cases and if something is missing feel free to report back or add a pull request with failing tests.

Thanks!
