### ISSUE TITLE
double quote and open paren respond slow and weird in some large org-mode buffers

### ISSUE THREAD

**Issue by jiyoo** [Fuco1/smartparens#148]
I have a large org file, and when I press double quote or open paren in certain places in that org file, it responds slow and it says "Search failed.  This means there is unmatched expression somewhere or we are at the beginning/end of file" which is the weird part.

I have managed to reduce that particular org file into a small version:

```
* slow
Start a double quoted string in the following blank line.

** example
#+BEGIN_SRC elisp
  (key-binding (kbd "M-}"))
  ;; => forward-paragraph
#+END_SRC
** more
#+BEGIN_SRC elisp
  ;; M-}
#+END_SRC
```

If I press double quote in the indicated place within that small org file, same thing happens, except the slow part is gone because the file is now small.

One can test the bug with that small org file by running `emacs -q --load min.el` where contents of `min.el` is:

```
(setq debug-on-error t)
(setq package-load-list '((dash t)
                          (smartparens t)
                          (org t)))

(package-initialize)
(setq package-enable-at-startup nil)

(find-file "~/that-small-org-file.org")
(smartparens-mode)
```

versions:
org-20130812   (either from GNU ELPA or Marmalade, I suppose this is a stable version)
smartparens-20130811.1359   (from MELPA)

Probably the lonely curly parens in the org file have something to do with this.

**Comment by gsingh93** [comment]
I think there is a regression here, I can still reproduce the error with the original reproduction steps (When point is right after the second `M-}`). My system info:
```
- `smartparens` version: 20230225.1026
- Active `major-mode`: `org-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 28.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2023-04-02
- Starterkit/Distribution: Vanilla
- OS: gnu/linux
```

I can also reproduce this with an org file that just looks like this:
```
#+BEGIN_SRC elisp
(sp-pair "\"" nil :unless '(sp-point-before-word-p))
#+END_SRC
```
where point is at the end of the line.
