### ISSUE TITLE
sp-* functions are very slow with large latex buffers

### ISSUE THREAD

**Issue by dinojr** [Fuco1/smartparens#157]
For example sp-forward-sexp takes several seconds to do the following:
\\(|\\) -> \\(\\)| 
in a >1000 lines buffer whereas it's instantaneous in a small buffer. Is there a way to improve things ?
Julien.

**Comment by pharpend** [comment]
I am having this same issue, a year and a half later. (My buffer is ~500 lines long). Any solution in sight?

**Comment by dinojr** [comment]
Peter Harpending <notifications@github.com> writes:

> I am having this same issue, a year and a half later. (My buffer is
> ~500 lines long). Any solution in sight?

Actually I don't have this problem anymore with the standard smartparens
configuration and much longer LaTeX buffers. Maybe there's something
broken in your configuration. Try running emacs -Q, then load
smartparens and see if the problem is still there.

Good luck,

Julien.

**Comment by Fuco1** [comment]
Closing this as there's very little reproducibility right now.  If any concrete constructs come up as being terribly slow, please open a new issue.
