### ISSUE TITLE
[show-smartparens-mode] Highlighting the wrong matching quote

### ISSUE THREAD

**Issue by bbatsov** [Fuco1/smartparens#179]
Not sure if this is `ruby-mode` specific problem, but here's a screenshot:

![screen shot 2013-10-09 at 5 02 26 pm](https://f.cloud.github.com/assets/103882/1306109/990cc46c-31a9-11e3-8481-2898b6d2459c.png)

I've also noticed that double-quotes are matched by `show-smartparens-mode`, but single-quotes aren't. Seems like another bug to me:

![screen shot 2013-10-10 at 3 45 53 pm](https://f.cloud.github.com/assets/103882/1306126/ff434ba2-31a9-11e3-923d-4c0d97d2bc3f.png)
![screen shot 2013-10-10 at 3 46 06 pm](https://f.cloud.github.com/assets/103882/1306127/ff43e8e6-31a9-11e3-962b-3414b4fb9639.png)

**Comment by Fuco1** [comment]
This issue here seems to be fixed.  If you come across it please reopen or raise a new issue.
