### ISSUE TITLE
Misbehaving wrapping inside string

### ISSUE THREAD

**Issue by purcell** [Fuco1/smartparens#212]
Consider

```
"M-["
```

with the `[` selected as a region. Pressing `"` should ideally result in:

```
"M-\"[\""
```

but it actually results in:

```
"M-"[""
```

I guess that in every case where a pair is inserted, it should be checked whether or not the current region is completely contained in a string.

**Comment by Fuco1** [comment]
This now works when the mark < point, but not the other way around.  Odd :D
