### ISSUE TITLE
Garbage in code samples in the wiki

### ISSUE THREAD

**Issue by deprecated** [Fuco1/smartparens#222]
Some of the wiki pages have what looks like SHA hashes inserted in the code samples.  
Surely this is not intended. 

Here is [one example](https://github.com/Fuco1/smartparens/wiki/Tips-and-tricks#use-wrapping-with-tags-to-create-shortcuts-for-common-wrapping-operations):

```lisp
(sp-local-tag 'html-mode "b" "<span class=976ed07b406da05fe41ccde6731b4444c5f92452quot;bold976ed07b406da05fe41ccde6731b4444c5f92452quot;>" "</span>")
```

Another is the [Example Configuration](https://github.com/Fuco1/smartparens/wiki/Example-configuration)

**Comment by Fuco1** [comment]
This has been fixed by github.
