### ISSUE TITLE
Killing a region in strict mode breaks the code structure

### ISSUE THREAD

**Issue by bbatsov** [Fuco1/smartparens#230]
I think `smartparens-strict-mode` should override the default `kill-region` with some sexp-aware version of it, otherwise it becomes too easy to break your code structure accidentally. As usual - paredit can be used as a source of inspiration.

**Comment by Fuco1** [comment]
@expez Do you think it would be possible to port the functionality from evil-smartparens to do something like this?  I think `vd` supports this.

**Comment by Fuco1** [comment]
Since we now have `sp-region-ok-p` it should be trivial to add a wrapper for kill-region (and other region-killing commands)

**Comment by expez** [comment]
@Fuco1 Just reminding you that `sp-region-ok-p` isn't bug free.  IIRC it doesn't handle prefixes correctly.  

As we discussed some time ago fixing that would be a huge undertaking.  In my day to day coding I never experience this as a problem, though.

**Comment by Fuco1** [comment]
Well, having some protection is better than none.  When the problems come we'll deal with them.

If you know some example right out of the top of your head, we should throw in test cases (disabled for now) so we have a collection of tests for when we decide to fix it. Feel free to add those :)
