### ISSUE TITLE
Whitespace padded delimiters

### ISSUE THREAD

**Issue by pseudonamed** [Fuco1/smartparens#233]
Firstly, thanks for this minor-mode. Really enjoying it.

One thing I'm struggling with is, I'd like to recreate the functionality of autopair with [autopair-padding](https://raw.github.com/lewang/le_emacs_libs/master/autopair-padding.el).

I can create a hook to add the initial whitespace but I'd like it to not include the padding if the parens are empty. Also related to this is I'd like to not have to do forward-char forward-char (or similar) to leave the parens. It would be nice if I could just type the closing delimiter and it would jump over the space and the delimiter.

I can't seem to find a way to run a hook on insertion of the closing delimiter. I could conceivably do it if there was a hook for that. Or would this be done another way in smartparens?

I asked this on [Reddit](http://www.reddit.com/r/emacs/comments/1qrfgr/smartparens_whitespace_padded_delimiters/). I'll update the question there if you answer.

Much thanks,
Donavan

**Comment by Fuco1** [comment]
The "jump out of current sexp" functionality was introduced with strict mode, I don't remember when.  It is governed by the variable `sp-autoskip-closing-pair`.  I've added a post-hook for this action as described in my comment from 17 Nov 2013.

\</necromancer\>
