### ISSUE TITLE
sp-forward-slurp-sexp keeps space after itself in python-mode

### ISSUE THREAD

**Issue by k-bx** [Fuco1/smartparens#236]
Imagine yourself having this python code:

```
foo(bar)
```

You want to place `boo()` on top of this call. What I do is (`|` is a cursor):

```
|foo(bar)
boo|foo(bar)
boo(|)foo(bar)
```

Then I press `C-rightarrow` (`sp-forward-slurp-sexp`) and it transforms into:

```
boo(|foo)(bar)
```

which is ok. But then I again press `C-rightarrow` and get:

```
boo(|foo (bar))
```

Which leaves a space after foo.

**Comment by Fuco1** [comment]
Related to #404.  We should come up with a solution there.

**Comment by c-oreills** [comment]
This is not actually a duplicate - #404 has been fixed (relating to . characters moving) but the testcase at the top of this file still fails.

The code above could be included in smartparens-python

**Comment by Fuco1** [comment]
Thanks for catching this.  By code above you mean the code I wrote or something else?  Have you verified it works?

**Comment by Wilfred** [comment]
FWIW, `sp-slurp-hybrid-sexp` doesn't suffer from this problem.

**Comment by c-oreills** [comment]
Thank you, that's solved it! =)

**Comment by Fuco1** [comment]
And we only had to wait 2 years :D

Well, thanks everyone for chipping in!
