### ISSUE TITLE
sp-splice-sexp-killing-around breaks in (Lisp) comments

### ISSUE THREAD

**Issue by pank** [Fuco1/smartparens#243]
When using `sp-splice-sexp-killing-around` in Emacs-Lisp mode comments it breaks.  It works in paredit, as far as I recall.  Here's an example that can be run from the `*scratch*` buffer.

```emacs-lisp
(package-initialize) ;; I assume smartparents installed via ELPA.
(require 'smartparens)
(progn 
  (switch-to-buffer "sp-test.el")
  (delete-region (point-min) (point-max))
  (emacs-lisp-mode)
  (insert ";; \"quote\" here\nand \"here\"")
  (goto-char 22)
  (sp-splice-sexp-killing-around)
  (message "Works!")
  (goto-char 5)
  (sp-splice-sexp-killing-around)
  (message "Breaks..."))
```

Here's the error on my machine
```
Debugger entered--Lisp error: (args-out-of-range 0 17)
  sp--splice-sexp-do-killing(5 10 (:beg 1 :end 17 :op "" :cl "" :prefix ";") nil)
  sp-splice-sexp-killing-around()
  (progn (switch-to-buffer "sp-test.el") (delete-region (point-min) (point-max)) (emacs-lisp-mode) (insert ";; \"quote\" here\nand \"here\"") (goto-char 22) (sp-splice-sexp-killing-around) (message "Works!") (goto-char 5) (sp-splice-sexp-killing-around) (message "Breaks..."))
  eval((progn (switch-to-buffer "sp-test.el") (delete-region (point-min) (point-max)) (emacs-lisp-mode) (insert ";; \"quote\" here\nand \"here\"") (goto-char 22) (sp-splice-sexp-killing-around) (message "Works!") (goto-char 5) (sp-splice-sexp-killing-around) (message "Breaks...")) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by andreas-roehler** [comment]
May confirm that. IMO when called inside a comment it should return nil.

**Comment by Fuco1** [comment]
This works for me as expected, with point at either position the text is removed and I get no error.

**Comment by andreas-roehler** [comment]
Am 05.06.2015 um 17:11 schrieb Matus Goljer:
>
> This works for me as expected, with point at either position the text 
> is removed and I get no error.
>
>

See attachment, error in minibuffer.

**Comment by Fuco1** [comment]
This works for me now.  Can you confirm?  There had been a rewrite of the splicing stuff a while back.

**Comment by Fuco1** [comment]
Also, you must enable `emacs-lisp-mode` in `sp-navigate-consider-stringlike-sexp` for this to work.

That variable is a cludge around some oddities of emacs, the plan is to get rid of it but it's going to stay for a while.
