### ISSUE TITLE
In HTML or ERB Tag Functions

### ISSUE THREAD

**Issue by Sammidysam** [Fuco1/smartparens#267]
Currently to handle ERB within RHTML mode, I have the following.

```lisp
(sp-with-modes '(rhtml-mode)
	(sp-local-pair "%" "%"
				   :unless '(sp-in-string-or-word-p)
				   :post-handlers '(
									(space-and-space-on-each-side "SPC")
									(space-on-each-side "=" "#")
									)))
```

It works wonderfully.  It is only in a `sp-with-modes` block because I plan on adding other matching in the future.  One match I would like to add is matching all of the Ruby keywords that are matched with `end` in `smartparens-ruby` to Rails matching.  Some of the keywords will obviously not be used, but it would be good to have crucial ones such as `do`, `for`, `if`, `unless`, etc.

For example, when I enter if in the following code (the `%>` would be present because of my matching code above)

```rhtml
<% if %>
```

I would like it to expand to

```rhtml
<% if %>
<% end %>
```

In order to make this match, I would need to call some code when I find the match.  Ideally when I make the match I immediately call a post-handler and only call a post-handler.  It is as follows

```lisp
(defun erb-end (&rest _ignored)
  "Insert <% end %> on line below current line."
  (save-excursion
	(end-of-line)
	(newline)
	(insert "<% end %>")
	(indent-according-to-mode)))
```

I believe that this would work correctly for me to have the behavior I want.  How exactly would I match a pair with only a post-handler and not any actual match?  I'm sure it is written somewhere, so I will look for it soon.  If I find it, I'll retract that question.

In order to make this behave more nicely (not happen at the wrong times), it would be nice to detect if the current pair is within a HTML tag.  Could a function called `sp-in-html-tag-p` be added?  Better yet, could one that handles ERB (all it has to check is `<%` and `%>` instead of `<` and `>`) tags be added as well?  Then I could add the function to the `:when` of the match, a la `:when '(sp-in-html-tag-p)` or `:when '(sp-in-erb-tag-p)`.

**Comment by Fuco1** [comment]
In case you decide to pursue this further, open a new issue or pull request, or reopen this one.
