### ISSUE TITLE
cua-replace-region no longer available in Emacs 24.3.50.2 cua-base.el

### ISSUE THREAD

**Issue by jeffkowalski** [Fuco1/smartparens#271]
smartparens references cua-replace-region (cua-base.el), which has been removed in Emacs 24.3.50.2 (see http://repo.or.cz/w/emacs.git/commitdiff/f38bbfce43b11667ee1a09acf4f4f932bf7c9043).

In the current version, smartparens will load just fine, but trying to overtype a highlighted region results in the error "sp--cua-replace-region: Symbol's function definition is void: cua-replace-region".

I don't know what the solution could be, but it looks like Stephan Monnier was trying to use (rather than conflict with) delete-selection-mode in cua-mode, according to the title of his commit.

(Just as an aside, re-evaluating the traditional definition of cua-replace-region restores the expected behavior as a temporary workaround, but this is in conflict with the intention of the changes to cua-base.)

**Comment by Fuco1** [comment]
@genovese I have removed the hooks and simulations so this should no longer be a problem. 

As for the rest of te thread, please see #396 and report possible issues there.

**Comment by genovese** [comment]
Thanks!
