### ISSUE TITLE
Unclear how to wrap region of text with tags from elisp code

### ISSUE THREAD

**Issue by suryakiran** [Fuco1/smartparens#279]
I googled for this but could not find an answer. I know the below mentioned issue is not a bug, but please bear with me.

I can create pair using sp-local-pair and can wrap region from lisp code using (sp-wrap-with-pair ...) Similar function for tag is missing (sp-wrap-with-tag, may be). I tried keyboard macros but it did not help.

For example in latex-mode I've a custom macro \ml{}. So to wrap a region of text around with I've created a local tag like this

(sp-local-tag '(latex-mode) "m" "\\ml{" "}")

So, when ever a region is selected and "m" will wrap the region with \ml{ and }. This is good. But sometimes, I want a line to be selected if no region was active before. So, my plan was to do something like this

(defun latex/wrap-line-or-region ()
   (interactive)
   (unless (region-active-p) (execute-kbd-macro [home S-end])) ;; select the line
    (sp-wrap-with-tag "m")) ;; Non existent function here.

I could use :pre-handlers to do the line selecting stuff, but then when ever i type "m" a line is selected which is not what I want. if I could have sp-wrap-with-tag or similar function, I can bind the above function to any of the function keys (for example). 

Is there any way to achieve this in smartparens ?

**Comment by Fuco1** [comment]
The wrapping settings api should be enough to support this.  The tags aren't coming back.
