### ISSUE TITLE
`-pair in LaTeX-mode conflicts with useful bindings in LaTeX-mode

### ISSUE THREAD

**Issue by CQQL** [Fuco1/smartparens#284]
Today some change in my emacs config changed the require order of LaTeX and smartparens, so that sp is required after LaTeX-mode and it's pairs overwrite the default bindings.

Typing
```
`s
```
in LaTeX-mode results in `\sigma`, whereas with smartparens enabled/loaded after, you get 
```
`s-
```
I find the former to be by far more useful.

My workaround for now is explicitly requiring `smartparens-latex` before `latex`.

A fix could be removing the pair or making smartparens not overwrite existing bindings.

**Comment by Fuco1** [comment]
I have an experimental branch `reworking-input-system` that removed bunch of now useless hooks and advices, the way SP grabs user input is now much cleaner and simpler.  This problem should be fixed "for free". If any of you want to try it, please report back any findings :)

**Comment by Fuco1** [comment]
This is fixed for me on the mainlain.  If the problem persist please reopen or start a new issue.
