### ISSUE TITLE
String-like delimiters and `sp-show-pair-from-inside`

### ISSUE THREAD

**Issue by ThibautVerron** [Fuco1/smartparens#289]
Hello,

Depending on the value of `sp-show-pair-from-inside` I see the following behavior: 

Consider the following text in a latex buffer:

```
$({})$
```

Assume the value of `sp-show-pair-from-inside` is nil (the default).
If the point is before `}` nothing is highlighted.
If the point is before `)` the pair of braces is highlighted.
If the point is before `$` the pair of dollars is highlighted.
If the point is after `$` the pair of dollars is highlighted.

At no point is the pair of brackets highlighted.

If the value of `sp-show-pair-from-inside` is `t`, the pair corresponding to the character after the point is highlighted, as expected.

Is this the intended behavior? Based on the docstring of `sp-show-pair-from-inside`, if set to `nil`, I would expect the pair of brackets to be highlighted when the point is just after them.

(Possibly linked to https://github.com/Fuco1/smartparens/issues/179 )

Thanks!

**Comment by Fuco1** [comment]
Hello folks, Is this issue fixed?

**Comment by ThibautVerron** [comment]
I am not sure that I understand what I wrote in the first post back then. `:)`

Based on my observations today, I'd say the behavior with `sp-show-pair-from-inside` disabled is fixed, and the behavior with `sp-show-pair-from-inside` is slightly broken.

Here's what I observe as of today, with `$({})$` in a latex buffer.

With `sp-show-pair-from-inside` set to nil, depending on the value of `point`:

1. dollars
2. parentheses
3. braces
4. nothing
5. braces
6. parentheses
7. dollars

With `sp-show-pair-from-inside` set to t:

1. dollars
2. parentheses
3. parentheses
4. braces
5. braces 
6. parentheses
7. dollars

According to the variable docstring, I understand that the expected behavior with `sp-show-pair-from-inside` enabled would be the first behavior, shifted to the "inside":

1. nothing or dollars
2. dollars (the point is after the opening dollar)
3. parenthese
4. braces 
5. parentheses (the point is after the closing brace, but before the closing parenthesis)
6. dollars (idem)
7. nothing or dollars

Incidentally, iirc I was looking for a way to highlight the pair just *after* the point (no matter if we are looking at the opening or closing part of the pair), so that it always highlights the pair *under* the cursor (with a non-bar cursor). The current behavior of `sp-show-pair-from-inside` comes close to achieving a similar behavior...

**Comment by Fuco1** [comment]
I added an extended explanation to the option `sp-show-pair-from-inside` and fixed some inconsistency issues and added test cases for the OP test case both with the setting as `nil` and `t`.  Now it works as I think is "correct", but it might not work exactly as an evil user would expect.  We can improve it further.
