### ISSUE TITLE
cannot sp-forward-slurp-sexp past last ; in c-mode

### ISSUE THREAD

**Issue by jasonblewis** [Fuco1/smartparens#297]
If you have the following in a c-mode buffer:

```c
void main() {
}

somefunc();
```
and place the cursor before the closing curly brace, then C-right repeatedly to slurp. you can't slurp past the final ; and you get an error: Wrong type argument: number-or-marker-p, nil

I expect it would  be able to slurp the final ; without producing an error.

**Comment by Wilfred** [comment]
I think this now works. I can use `sp-forward-slurp-sexp` twice and I get the following:

```c
void main() {


    somefunc ();}
```

However, I'd recommend `sp-forward-slurp-hybrid-sexp` in this case. It does the right thing for both `{` and for `(` in Fuco's example above.
