### ISSUE TITLE
[ruby-mode] Broken show-smartparens-mode for %-style literals

### ISSUE THREAD

**Issue by bbatsov** [Fuco1/smartparens#307]
A picture is worth a thousand words:

![image](https://f.cloud.github.com/assets/103882/2295365/10b91e58-a08f-11e3-9190-36a166609271.png)

As you can see the opening `(` should have been highlighted, but instead the preceding array brackets are highlighted. 

@Jell

**Comment by Fuco1** [comment]
This seems to be fixed.
