### ISSUE TITLE
flycheck warning messages with smartparens-config

### ISSUE THREAD

**Issue by joe9** [Fuco1/smartparens#309]
Hello,

With this line (require 'smartparens-config), I get the below message from flycheck.

  110   1 warning  the following functions might not be
    defined at runtime: sp-wrap-region-init, sp-wrap-region, sp-insert-pair,
    sp-skip-closing-pair (emacs-lisp)

Just want to check if there is any way to fix the above.

Thanks
Joe

**Comment by Fuco1** [comment]
Should be fixed by #407.
