### ISSUE TITLE
wrap like wrap-region

### ISSUE THREAD

**Issue by Pitometsu** [Fuco1/smartparens#311]
Is there any way to configure smartparens to wrap region on insertion closed parenthesis. Like in wrap-region place of mark and point of wrapped region should be depend on which (opened/closed) parenthesis inserted.

**Comment by Fuco1** [comment]
This is now implemented in the master, I expect it to be fully working with the 1.7 release (which should come soonish)

**Comment by Pitometsu** [comment]
Thank you a lot for your work!

**Comment by Pitometsu** [comment]
But can it be configured now to jump on end when used `)` and on begin when used `(`?

**Comment by Fuco1** [comment]
Could possibly be achieved with a hook of some sort, I'm not sure.

But I think it would make sense to have a global setting for this.

**Comment by Fuco1** [comment]
Ah, you created another issue for this :)

#508 So closing this again.
