### ISSUE TITLE
Suggestion: make pairs for autoescaping in string configurable

### ISSUE THREAD

**Issue by tkf** [Fuco1/smartparens#32]
Currently it is hard-coded and only supports double quote.  How about adding a configurable `sp-autoescape-string-quotes` which hold a list of pairs, like this:

```lisp
(defcustom sp-autoescape-string-quotes '(("\"" "\""))
  ...)
(make-variable-buffer-local 'sp-autoescape-string-quotes)
```

It's always buffer local, so user can configure it in mode hook:

```lisp
(add-hook 'python-mode-hook
          (lambda ()
		    (setq sp-autoescape-string-quotes '(("\"" "\"") ("'" "'")))))
```

When it is added, we can remove `sp-autoescape-string-quote` (singular) because its redundant.

**Comment by Fuco1** [comment]
This has now been added to version 1.8.
