### ISSUE TITLE
sp-rewrap-sexp doesn't understand triple-quoted strings

### ISSUE THREAD

**Issue by Wilfred** [Fuco1/smartparens#320]
Given the following buffer state, where | is point:

```
'''|foo'''
```

Typing `M-x sp-rewrap-sexp RET "` gives:

```
"''|foo''"
```

Expected result:

```
"""|foo"""
```

**Comment by Fuco1** [comment]
I tried to make this work but it just doesn't fit in the rewrap thing.  Even when I properly define tripple-quote pairs the rewrap thing doesn't consider pairs with shared prefixes and picks the shortest.  One could add a special handler for python but it's not a priority for me.

I will add a hook for the rewrap function where people can add their code.

**Comment by Fuco1** [comment]
The hook action is `rewrap-sexp`.
