### ISSUE TITLE
Duplicate function

### ISSUE THREAD

**Issue by otijhuis** [Fuco1/smartparens#329]
It is the same as the custom paredit-duplicate-after-point defun you can find online, just with paredit-newline replaced with sp-newline. Personally I used it with paredit all the time. Might be helpful to someone. Would be even better if smartparens had a duplicate function that works better when in the middle of symbols etc. This function just starts duplicating at point.

Example (_ being point):

(defun abc ()
  _(something1 a b c (something2
                                      a b c)))

->

(defun abc ()
  (something1 a b c (something2
                                      a b c))
  (something1 a b c (something2
                                      a b c)))

```lisp
;; Duplicate sexp
(defun sp-duplicate-after-point
  ()
  "Duplicates the content of the line that is after the point."
  (interactive)
  ;; skips to the next sexp
  (while (looking-at " ")
    (forward-char))
  (set-mark-command nil)
  ;; while we find sexps we move forward on the line
  (while (and (<= (point) (car (bounds-of-thing-at-point 'sexp)))
              (not (= (point) (line-end-position))))
    (forward-sexp)
    (while (looking-at " ")
      (forward-char)))
  (kill-ring-save (mark) (point))
  ;; go to the next line and copy the sexprs we encountered
  (sp-newline)
  (set-mark-command nil)
  (yank)
  (exchange-point-and-mark))
```

**Comment by Fuco1** [comment]
I've updated `sp-clone-sexp` to behave in the following manner:

* If you are in front of a sexp, clone it below the current sexp
* If you are not in front of a sexp, clone the enclosing sepx below the current enclosing sexp.

I find this behaviour satisfactory.  Feel free to reopen if you think it could be improved.
