### ISSUE TITLE
Too Intrusive Key Binding Overriding

### ISSUE THREAD

**Issue by nordlow** [Fuco1/smartparens#333]
smartparents is currently too intrusive as `sp--self-insert-command` hijacks `self-insert-command`. This makes it difficult to harmonize with other modes that override behaviour of `self-insert-command` for example when pressing a letter key. I'm using this in my

https://github.com/nordlow/elisp/blob/master/mine/charedit.el

to conveniently for example boldify current selection in text formatting modes such html and latex-mode when the letter `b` is pressed when mark is active.

Not even calling local-set-key in the buffer where smartparens has been loaded works.

Is there an alternative way of solving this?

**Comment by Fuco1** [comment]
On branch `rewriting-input-system` I have replaced bunch of intrusive crap with hooks or very lightweight advices.

If you people want, please check it out and report back if it fixes your issues. (it works on my setup, but you know how emacs is)

**Comment by dbitouze** [comment]
Currently, it seems to be OK: thanks!

**Comment by Fuco1** [comment]
Please open new specific issues if you find any problems, I'm closing this as it has got too broad.  The input system has been rewritten so the issues should now be minimized.
