### ISSUE TITLE
Freezes when it can't find a matching tag

### ISSUE THREAD

**Issue by greduan** [Fuco1/smartparens#335]
I have the following code:

```html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8"/>
		<title>js-stats</title>
		<link href="css/main.css" rel="stylesheet"/>
	</head>
	<body>
		<div id="wrapper">
			<h1>js-stats</h1>

			<input type="file" id="files" name="files[]" multiple />

			<canvas id="myChart" width="400" height="400"></canvas>
		</div>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.js"></script>
		<!--<script src="js/main.js"></script>
	</body>
</html>
```

When I place my cursor on top of the `<` in `<!--` near the bottom my cursor gets stuck, I can't do anything with it and I have to press C-g several times to get out of it.

I am on Arch Linux so I am using the latest Emacs (GUI version) and I am using Evil, if that's relevant.

Any more info you need me to provide please ask. :)

**Comment by Wilfred** [comment]
No longer reproduces on latest smartparens. Hooray!

(Feel free to reopen if you still see issues.)
