### ISSUE TITLE
Quotes escaped in unclosed string

### ISSUE THREAD

**Issue by rdallasgray** [Fuco1/smartparens#34]
In scratch buffer, enter:

```
"test string"|
```

Delete closing quote:

```
"test string|
```

Retype closing quote:

```
"test string\"\"|
```

Basically seems like sp thinks it's in a string when the string isn't actually closed; the expected behaviour would be to just close the string with a double quote.

Had a quick look at the code but couldn't find where the issue might be manifesting -- if you can point me in the right direction I'll raise a pull request with tests.

Thanks for the great library!

**Comment by allenpc** [comment]
Can confirm that I'm also having this problem. Any suggestions or workarounds would be greatly appreciated.

**Comment by Fuco1** [comment]
I'm working on this now.  If you accidentally get into a broken string state and you are inside another sexp, it will try to figure that out and close the string to preserve the outer state.  That is, if

    (foo "bar" baz) 

becomes

    (foo "bar baz)

and you hit " after bar, smartparens will figure out that the outer parens actually are a pair and that the unclosed " breaks the structure, and will insert unescaped quote automatically.

This still won't fix the OP issue, there I'm just thinking of a simple heuristic "if I am at the end of file, close and do not escape".  I have no good heuristic for the top-level situation, except maybe always closing if at word/symbol boundary.  It will need some fine-tuning.

As of 1.8 at least it won't insert a pair but only one escaped quote.

**Comment by cpaulik** [comment]
It seems that the option `sp-autoescape-string-quote` is no longer available so I tried setting `sp-escape-quotes-after-insert` to `nil` with no effect. Would this be the correct setting to disable?

**Comment by Fuco1** [comment]
@cpaulik that depends on what you want to achieve.

Check this out, maybe it helps: http://smartparens.readthedocs.io/en/latest/automatic-escaping.html

**Comment by cpaulik** [comment]
Thanks for the link and sorry for not checking the docs earlier. I want to completely disable autoescaping. 

With `emacs -Q` I executed the following code:

```elisp
(add-to-list 'load-path "~/.emacs.d/elpa/smartparens-20161105.1503")
(add-to-list 'load-path "~/.emacs.d/elpa/dash-20161108.352")
(require 'smartparens)

(setq sp-escape-quotes-after-insert nil
      sp-escape-wrapped-region nil)
```

but I still get autoescaping exactly in the way that OP reported it.

**Comment by Fuco1** [comment]
That is odd.  Try

    (sp-pair "\"" nil :actions '(:rem escape))

**Comment by cpaulik** [comment]
If I add that then I don't get any smartparens for `"`.

Just for my saneness - could you reproduce the behaviour or is there something strange going on on my side?

**Comment by Fuco1** [comment]
@cpaulik Hi, sorry for no reply, apparently this slipped under my radar.  Could you open new issue if this still happens?

For the rest, I've pushed some code that I believe should work correctly (at least for emacs lisp :P): when your buffer is in a state where simply inserting a quote would make it more sane (end-of-buffer state is consistent) it is prefered instead of escaping.

I will test it a bit in other languages and then I think this is good to close.

**Comment by Fuco1** [comment]
The @rdallasgray 's issue seems also to be fixed.  I'm merging this into master :)
