### ISSUE TITLE
Weird behavior with `orgtbl-mode`

### ISSUE THREAD

**Issue by ThibautVerron** [Fuco1/smartparens#343]
Hello,

First, a disclaimer: I don't understand what is going on here, at all, so I will just post what I know and how I worked around the problem. So, sorry in advance if my misunderstanding is making this more difficult than it is.

The problem: in some latex buffers, typically those with `orgtbl-mode` on, I notice the following behavior:

1. Type: `C-q ( f o o )`
2. Emacs hangs for a few seconds. If I press `C-g` or if I wait, the parenthesis is correctly inserted. If I press a motion key, the closing parenthesis is deleted.

The problem is that I could not manage to narrow the scope of the problem. It seems to be related to `orgtbl` (and the workaround I attach only considers `orgtbl`), however in some buffers with `orgtbl` on, but not other modes (`fold-dwim-org`), I couldn't observe the behavior. `fold-dwim-org` doesn't advise or remap the motion keys and `)`. This is a complete mystery, and the best I can imagine is that it is a race condition somewhere. I also could not observe anything special when watching `sp--self-insert-command` with `edebug`.

This is what I changed to get it working (`)` was mapped to `orgtbl-self-insert-command` before `smartparens`): https://github.com/ThibautVerron/smartparens/commit/780a968080407ca77590828338bd8edd071da38b

Once again, I don't understand this code well enough to be sure that these changes didn't break anything.

Thanks!

**Comment by Fuco1** [comment]
Check the branch `reworking-input-system`, that should have the issue fixed.  The code you've patched is no longer present, it is now handled differently.
