### ISSUE TITLE
buffer-local parens?

### ISSUE THREAD

**Issue by wavexx** [Fuco1/smartparens#347]
Is it possible to add a pair just for the current buffer?

By skimming through the source, it looks like most of the relevant variables are _already_ buffer-local, though calling (sp-pair) from within a mode hook results in emacs going crazy.

The reason behind this is having complex modes such as ess-mode do "the right thing"(tm) depending on the real language being used. Unfortunately, the major-mode is always "ess-mode", thought the underlying language could vary (R, SAS, Julia...). Several hooks are provided by ess for this reason.

I'm also baffled as of why (sp-local-pair) requires a mode. Wouldn't be more simple to make (sp-local-pair) simply work on buffer-local variables and just call it from a hook, like most other minor modes do?

**Comment by Fuco1** [comment]
This is now implemented, see the documentation: http://smartparens.readthedocs.io/en/latest/pair-management.html#named-pair-definitions-buffer-local
