### ISSUE TITLE
smartparens highlighting doesn't work unless (show-paren-mode t) is enabled

### ISSUE THREAD

**Issue by anildigital** [Fuco1/smartparens#353]
I have installed smartparens mode and configured as below

``` elisp
(require 'smartparens-config)
(smartparens-global-mode 1)
(show-smartparens-global-mode +1)
```

But unless I do 

``` elisp
(show-paren-mode t)
```

paren highlighting doesn't work. Is this a known issue?

**Comment by Fuco1** [comment]
@anildigital if you still have this problem, please reopen. I'm closing this for now.
