### ISSUE TITLE
`sp-insert-pair` hangs if `sp-autoinsert-if-followed-by-same` is other than 0 or 3 (default)

### ISSUE THREAD

**Issue by knu** [Fuco1/smartparens#354]
Open a new buffer with the following content:

```
(")
```

Make sure you set `sp-autoinsert-if-followed-by-same` to 1, 2 or 4 and turn on `smartparens-mode`, then place the point right after the `(` and type `"`; it hangs.  This happens to me regardless of the major mode, on Emacs 24.3.1 and Emacs 24.3.92.1.

Does this reproduce for any of you?

**Comment by Fuco1** [comment]
Setting doesn't exist anymore
