### ISSUE TITLE
smartparens doesn't work with cc-mode space-before-funcall

### ISSUE THREAD

**Issue by Bklyn** [Fuco1/smartparens#357]
I prefer the GNU style of `space-before-funcall` in my `c-cleanup-list` (see [cc-mode docs](http://www.gnu.org/software/emacs/manual/html_mono/ccmode.html#Clean_002dups)), but with `smartparens-mode` enabled, no space gets inserted.  Presumably this is because its not me that is adding the closing paren of the function call to the buffer.  Is there any way to get smartparens to play nicely with this feature of cc-mode?

**Comment by Fuco1** [comment]
Please look at #333 's last comment.  Could you report if anything changes?

**Comment by Bklyn** [comment]
Will try out the new version as soon as I can figure out how to override the ELPA version of smartparens that Prelude pulls in with my own local copy.

**Comment by Bklyn** [comment]
Yes, the code on the `rewriting-input-system` branch fixes this issue.  Looks like it has been merged to master as well.  Thanks!

**Comment by Fuco1** [comment]
Thanks for confirming.
