### ISSUE TITLE
Selecting sexps one-by-one?

### ISSUE THREAD

**Issue by neongreen** [Fuco1/smartparens#360]
Currently smartparens seems to ignore Shift when doing `sp-backward-sexp` and `sp-forward-sexp`, which makes selecting-by-sexps impossible; `sp-select-next-thing` doesn't work either, because it replaces selection instead of incrementing it. Basically, what I want is for N invocations of `sp-select-next-thing` to be equivalent to `sp-select-next-thing N` (and for `sp-select-prev-thing` to undo 1 invocation of `sp-select-next-thing`). Would it be possible to implement something like this in smartparens?

The attached code demonstates the behavior I'm describing (it's horribly inefficient, being the first piece of code I've ever written in Emacs Lisp – sorry!):

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ elisp
(define-key global-map (kbd "C-S-<left>" ) 'sp-backward-sexp-select)
(define-key global-map (kbd "C-S-<right>") 'sp-forward-sexp-select)

(defvar sp-selection-level 0)
(defvar sp-selection-point nil)
(defun sp-add-and-reselect (arg)
  (interactive "p")
  ; Initialise.
  (unless (use-region-p)
    (setq sp-selection-level 0)
    (setq sp-selection-point nil))
  (unless sp-selection-point
    (setq sp-selection-point (point)))
  ; Clear selection – sp-select-next-thing doesn't work well otherwise.
  (set-mark sp-selection-point)
  (goto-char sp-selection-point)
  ; Increment level.
  (setq sp-selection-level (+ sp-selection-level arg))
  (unless (eq 0 sp-selection-level)
    (sp-select-next-thing sp-selection-level sp-selection-point)
    ; If level is negative/positive, point has to be before/after mark; if
    ; it's not the case, do the swap.
    (unless (or (and (> 0 sp-selection-level) (< (point) (mark)))
                (and (< 0 sp-selection-level) (> (point) (mark))))
      (exchange-point-and-mark))))

(defun sp-backward-sexp-select ()
  (interactive)
  (sp-add-and-reselect -1))
(defun sp-forward-sexp-select ()
  (interactive)
  (sp-add-and-reselect 1))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bobbysmith007** [comment]
> `(defun sp-backward-sexp (&optional arg)...(interactive "^p")...)`
> (put 'sp-forward-sexp  'CUA 'move)
> (put 'sp-backward-sexp 'CUA 'move)

This is hugely important to my workflow, so I tried with success to restore the behavior I needed based on the previous comments.

The "^p" seems to have largely resolved this issue.  Any chance of getting that added more officially so that ELPA installs have this by default?

**Comment by Fuco1** [comment]
Feel free to send a PR. :) I personally don't use this behaviour, so
there's not much motivation.  I can put it in the queue, but that moves
along very slowly these days :/

Sadly I don't have as much time as I used to.

-- 
Best regards,
  Matúš Goljer
