### ISSUE TITLE
Navigation commands and region selection

### ISSUE THREAD

**Issue by joca-bt** [Fuco1/smartparens#363]
Paredit's navigation commands are interoperable with region selection. For example, C-M-f will advance one sexp forward. C-M-S-f will advance one sexp forward and select it.
Smartparens' navigation commands do not allow this. Binding sp-forward-sexp to C-M-f and doing C-M-S-f will advance one sexp forward but without selecting the text.

This would be a nice feature imho.

**Comment by Fuco1** [comment]
See #360 .
