### ISSUE TITLE
Inconsistent behavior of sp-up-sexp when string contains parenthesis 

### ISSUE THREAD

**Issue by syl20bnr** [Fuco1/smartparens#367]
Repo steps on the following snippet:

```elisp
(unless (t)
  ;; additional paths
  (defconst user-home-directory
    (expand-file-name (concat user-emacs-directory "../"))
    "User home directory (~/).")
  (defconst spacemacs-contrib-config-directory
    (expand-file-name (concat user-emacs-directory "contrib/"))
    "Spacemacs contribution layers base directory.")
  (message "done"))
```

- start with point on first parenthesis
- `sp-down-sexp`
- `sp-down-sexp`
- `sp-up-sexp`
- `sp-down-sexp` (point should be at `(|defconst user-home-directory...`)
- `sp-up-sexp`
The point ends at the end of the `unless` sexp instead of being at the end of first `defconst` sexp.

Remove the `(~/)` part of the string on the 5th line and repeat the sequence, now the behavior is as expected.

**Comment by expez** [comment]
I just tried reproducing this and the bug report no longer matches the outcome (tested with my regular setup which includes `evil-mode`

**Comment by Fuco1** [comment]
This was caused by the issue where a paren right before the end of string was incorrectly parsed.  I think #505 fixed it + there are now tests for this case.

We might try to add some tests with evil setup too just in case, but this issue is fixed.  Thanks for the report.
