### ISSUE TITLE
Incorrect behavior with RET + delete-selection-mode

### ISSUE THREAD

**Issue by djl** [Fuco1/smartparens#368]
I *think* I've found a bug with smartparens and delete-selection-mode. When both modes are active the return key only deletes the selection, rather than overwriting it with a newline.

Quick steps to reproduce:

1. Highlight some text
2. Hit `RET`
3. Notice the selection is deleted but a newline is not inserted in its place

This only seems to happen with `RET`. Other keys still function as expected.

**Comment by Fuco1** [comment]
See #396 .
