### ISSUE TITLE
triple-quote python 

### ISSUE THREAD

**Issue by Distopico** [Fuco1/smartparens#369]
when I try to insert triple quote for python insert four """"

**Comment by QiangF** [comment]
Maybe you can type your string first and then quote it with triple quote. This is on the feature list:
Scenario: Repeatedly wrap with pair, point after region
Given I turn on smartparens
When I insert "This is some text"
And I select "is some"
And I exchange point and mark
And I type "(("
Then I should see "This ((is some)) text"
Then the cursor should be at point "17"

**Comment by Wilfred** [comment]
I can't reproduce this -- I think it's no longer an issue.

**Comment by Distopico** [comment]
i'm not use smartparens in actuality and i'm not sure if error persists
