### ISSUE TITLE
Double quote behavior inconsistent 

### ISSUE THREAD

**Issue by jgarvin** [Fuco1/smartparens#374]
Emacs 24.4, running with -Q, loading just dash and smartparens-config. You can get 3 different behaviors when you write a double quote:

1. Write a double quote, then do so a second time without inserting any other characters into the buffer. The first time you press double quote, you get `"|"`. The second time you get `"\"|\""`. Almost certainly not what you want.

2. Write a double quote. then write a word without spaces, then another double quote. The first time you get `"|"`, then you add your word, `"hello|"`, then you press the second quote, and it closes the string, `"hello"|`. This is the behavior I would always expect and the one consistent with how parenthesis behave.

3. Write a double quote, then write two words with a space between them, then another quote. `"|"` -> `"hello world|"` -> `"hello world\"|\""`, similar to the first behavior. Almost certainly not what you want.

**Comment by myeffort** [comment]
With or without escaping, auto-skip currently doesn't apply to empty strings in single and doublequotes.

**Comment by sooheon** [comment]
I see the same behaviour as @myeffort. With 24.4.1 and the latest melpa smartparens.

**Comment by Fuco1** [comment]
The issue with double quotes is now fixed in fa4fb22.  Single quotes still behave somewhat odd (at least in python and php modes). I'm on it right now.

**Comment by Fuco1** [comment]
Could any of you please verify that the problems are gone?

**Comment by sooheon** [comment]
These specific problems are gone, but a new bug is here. Values of `sp-cancel-autoskip-on-backward-movement t` and `sp-autoskip-closing-pair 'always` are not respected. 

With those two variables set, try the following:
1. type `"hello world"
2. M-b back to middle space, and delete it, leaving `"hello|world"`
3. Press `"`

This will split the string, while the above settings means you should get `sp-up-sexp`, i.e. autoskip closing pair.

**Comment by Fuco1** [comment]
Hm, I don't think it ever worked with quotes.  Which is not to say it shouldn't.
