### ISSUE TITLE
Decorator doesn't work with quote and sp-select-next-thing

### ISSUE THREAD

**Issue by jgarvin** [Fuco1/smartparens#375]
Emacs 24.4, running with -Q, loading just dash and smartparens-config. I wrote the following to make it simpler for me to invoke sp funcs only applying to specific pairs (I'm still an elisp neophyte so apologies if this is a PEBKAC problem):

```
(defun single-pair-sexp (p func)
  (lambda (&optional arg)
(interactive "P")
(sp-restrict-to-pairs p func)))

(defun pair-only-sexp (func)
  (lambda (&optional arg)
(interactive "P")
(sp-restrict-to-object 'sp-prefix-pair-object func)))

(defun single-pair-only-sexp (p func)
  (funcall
   (single-pair-sexp p (pair-only-sexp func))))
```

Then in the scratch buffer I write the string "hello" and try to eval my function:

```
(single-pair-only-sexp "\"" 'sp-select-next-thing)
"hello"
```

I get an error: Wrong type argument: number-or-marker-p, nil

It works fine if I use an opening brace instead of a quote.

**Comment by jgarvin** [comment]
I'm not sure if this is the same bug or a different one, but I also can't get sp-restrict-to-pairs to work with sp-get-enclosing-sexp.

    (defun md-pair-bounds (opener)
      (let ((r (sp-restrict-to-pairs opener 'sp-get-enclosing-sexp)))
         (cons (plist-get r :beg)
               (plist-get r :end))))

    (md-pair-bounds "(")

Seems to always return `(nil)` regardless of where I put point before calling. SP 1.6.3, same emacs.

**Comment by Fuco1** [comment]
I think they are only supposed to work with interactive functions not with the parser stuff.

**Comment by Fuco1** [comment]
The function `sp-restrict-to-pairs` uses `(call-interactively function)` to call the function argument, which therefore must be a command (interactive function).  So the example with `sp-get-enclosing-sexp` wouldn't work on current version of smartparens.

This functionality with the "narrowing" isn't very well thought out.  I was trying to mimic some features of vim (text objects) but it's a bit of an ad-hoc feature bolted on top.  I think I will deprecate it and add it in some more universal way.
