### ISSUE TITLE
Smartparens prevents correcting paren imbalance

### ISSUE THREAD

**Issue by jgarvin** [Fuco1/smartparens#376]
Emacs 24.4.

Have this buffer `|hello)`. Now add an opening paren to try and fix the imbalance, and you get `(|)hello)` making the parens unbalanced again. This was what kept me away from autopair, it'd be nice to see a parens package get this right ;)

**Comment by howdoicomputer** [comment]
Ah, I found the ticket that described my problem. I am pretty new to Emacs and am using Spacemacs and I eventually found my way here. I get around this by toggling smartparens when I need to balance an incomplete pair.

**Comment by expez** [comment]
@howdoicomputer you can use `quoted-insert` to insert a char literally.  It's bound to <kbd>C-q</kbd> in regular emacs IIRC.  I too use evil, so I've bound that function to <kbd>C-v</kbd> in insert mode :)

**Comment by Fuco1** [comment]
I think the C-q solution is the only viable one here.  Using strict mode will help with never getting an imbalanced buffer in the first place.
