### ISSUE TITLE
show-smartparens-mode does not work in helm minibuffer

### ISSUE THREAD

**Issue by PythonNut** [Fuco1/smartparens#377]
Title is self-explanatory. Matching pairs are not shown in the minibuffer when `show-smartparens-global-mode` is enabled.

**Comment by Fuco1** [comment]
Any updates?

**Comment by PythonNut** [comment]
Major mode is `emacs-lisp-mode`. I honestly doubt this is work your time fixing, so I'll close this.

**Comment by Fuco1** [comment]
Thanks.  If you figure out how we can fix this I'm happy to take a patch or a hint :)
