### ISSUE TITLE
Smartparens does not work in Aquamacs

### ISSUE THREAD

**Issue by env0der** [Fuco1/smartparens#381]
When I type ```A```, I could not type ```s``` after it - the character does not appear in buffer.

I've debugged this and found out that this happens because in Aquamacs (with default settings) ```(single-key-description 115)``` returns ```S```, but in normal Emacs it returns ```s```.

There is a workaround, though - you can add ```(ns-use-mac-modifier-symbols nil)``` to the config. I've created an issue (https://github.com/davidswelt/aquamacs-emacs/issues/101) in Aquamacs repository, but repo owner thinks that the way ```single-key-description``` is used in Smartparens is a hack.

I'm a newbie in Emacs platform and elisp, so I would not like to judge if he is right or not.

**Comment by Fuco1** [comment]
SP no longer uses history to decide what to insert so this should be fixed.  I'm closing, if you still have the problem feel free to reopen.
