### ISSUE TITLE
Warnings after install

### ISSUE THREAD

**Issue by gozes** [Fuco1/smartparens#383]
Hello I just wanted to let you know that I got this warnings after installing smartparens on emacs 24.4 from debian sid

In sp-lisp-invalid-hyperlink-p:
smartparens-config.el:54:46:Warning: repeated variable _ in lambda-list

In end of data:
smartparens-config.el:101:1:Warning: the following functions might not be
    defined at runtime: sp-wrap-region-init, sp-wrap-region, sp-insert-pair,
    sp-skip-closing-pair

In sp-latex-skip-double-quote:
smartparens-latex.el:67:45:Warning: repeated variable _ in lambda-list

In sp-ruby-post-handler:
smartparens-ruby.el:108:25:Warning: reference to free variable `arg'
smartparens-ruby.el:112:13:Warning: reference to free variable `enc'

In sp-ruby-pre-handler:
smartparens-ruby.el:123:11:Warning: reference to free variable `enc'

In end of data:
smartparens-ruby.el:373:1:Warning: the following functions are not known to be
    defined: enh-ruby-forward-sexp, ruby-forward-sexp, enh-ruby-backward-sexp,
    ruby-backward-sexp

In sp--parse-insertion-spec:
smartparens.el:2454:29:Warning: reference to free variable `spec'
smartparens.el:2455:12:Warning: assignment to free variable `spec'

In sp-restrict-to-object:
smartparens.el:4588:38:Warning: `((symbol-value object) t)' is a malformed
    function

In sp-restrict-to-pairs-interactive:
smartparens.el:4611:48:Warning: `(pairs pairs)' is a malformed function

In sp-restrict-to-object-interactive:
smartparens.el:4635:50:Warning: `(object object)' is a malformed function

In sp-split-sexp:
smartparens.el:6927:19:Warning: `delete-backward-char' is for interactive use
    only; use `delete-char' instead.
smartparens.el:7851:20:Warning: reference to free variable
    `mc/cursor-specific-vars'
smartparens.el:7851:20:Warning: assignment to free variable
    `mc/cursor-specific-vars'

In end of data:
smartparens.el:7861:1:Warning: the following functions are not known to be
    defined: letf, lexical-let

**Comment by Fuco1** [comment]
These should be fixed by #407.
