### ISSUE TITLE
Auto complete of pairs

### ISSUE THREAD

**Issue by isolet** [Fuco1/smartparens#387]
In LaTex, when type "\langle", "\rangle" will be inserted automatically.

But, if one mis-input "\langle", like "\lafdsafdsaf" then backspace backspace ... to "\la", then input "ngle", the pair auto complete will fail.

**Comment by Fuco1** [comment]
This now works on master, but other things are broken (I'm doing some aggresive refactoring). If you want to try and confirm, backup your current installation first.
