### ISSUE TITLE
Swap "(" and "[" keys ?

### ISSUE THREAD

**Issue by Balooga** [Fuco1/smartparens#389]
Is there a smartparens equivalent to paredit's "paredit-open-round" ?  I would like to swap the brackets and parenthesis keys, but only when editing Lisp code.  To do this in paredit, I use the following code;

    (eval-after-load 'paredit
      '(define-key paredit-mode-map (kbd "[") 'paredit-open-round))
    (eval-after-load 'paredit
      '(define-key paredit-mode-map (kbd "]") 'paredit-close-round))
    (eval-after-load 'pareditq
      '(define-key paredit-mode-map (kbd "(") 'paredit-open-square))
    (eval-after-load 'paredit
      '(define-key paredit-mode-map (kbd ")") 'paredit-close-square))

**Comment by Fuco1** [comment]
You can use `sp-insert-pair` to define your own functions for inserting specific pairs. Maybe something like that will come built-in but for the moment it is not a priority.
