### ISSUE TITLE
sp-local-tag does not include whole region (last character missing)

### ISSUE THREAD

**Issue by minintaequ** [Fuco1/smartparens#391]
Hello,

if I try the sp-local-tag 'bi' form the smartparens-latex.el on a marked region,
the last marked character is outside the parens, e.g. applied on the region

```latex
\item oranges
\item bananas
```

I get the following:

```latex
\begin{itemize}\item oranges
\item banana\end{itemize}s
```

The same occurs on user-defined sp-local-tags while sp-local-pairs work fine on marked regions. 
Can anyone reproduce this behaviour? Is this a bug?

**Comment by Fuco1** [comment]
The tag functionality was removed since version 1.7 so this is probably a no-fix.  We will try to add it back in some compatible form, but the old implementation was simply too bad.
