### ISSUE TITLE
Strict mode not taking effect

### ISSUE THREAD

**Issue by sooheon** [Fuco1/smartparens#393]
```
  (smartparens-global-mode 't)
  (add-hook 'emacs-lisp-mode-hook 'smartparens-strict-mode)
  (add-hook 'clojure-mode-hook 'smartparens-strict-mode)
  (add-hook 'cider-repl-mode-hook 'smartparens-strict-mode)
  (setq sp-cancel-autoskip-on-backward-movement 'nil)
```
With the above customisations, smartparens strict mode only works as expected for elisp files. What is strange is that activating strict mode with M-x in even the scratch buffer does not induce the expected behaviour (trailing pairs can be deleted). Toggling this mode only has observable changes in elisp files.

**Comment by Fuco1** [comment]
Do you still experience the issue?

What version of emacs do you run? I have tried again and can't reproduce the issue.

PS: you should never quote the `t` constant.

**Comment by sooheon** [comment]
Issue should be closed as a problem with my settings, an update and reset of settings resolved it.

**Comment by Fuco1** [comment]
Thanks for coming back and resolving this.

**Comment by ChillarAnand** [comment]
i have

    (smartparens-global-mode t)
    (turn-on-smartparens-strict-mode)

in my init file but it is not activating smartparens-strict-mode but if do

    M-x smartparens-strict-mode

it is activating for individual buffer
