### ISSUE TITLE
SP and electric-spacing

### ISSUE THREAD

**Issue by pronobis** [Fuco1/smartparens#398]
This is more of a question than an issue. I found this package:
https://github.com/xwl/electric-spacing
which is handy, but seems to be conflicting with smartparens. Basically, without smartparens, typing
```
Foo * |
foo->|
```
works as expected, but with smartparens it becomes
```
Foo **|
foo-> |
```
Not sure what is the reason, but when running edebug-defun in `electric-spacing-*` the function is invoked twice for some reason when smartparens is running. 

I'd be happy to look into it. If you have a hint where to start looking for the problem, please let me know.

**Comment by Fuco1** [comment]
Can you try the new branch `reworking-input-system` to see if it fixes the problem? I've replaced the advice with a hook.

**Comment by Fuco1** [comment]
@pronobis It is now in the mainlain. Could you please download the latest git/melpa and see if your problem is fixed? (make sure you have a backup of your current smartparens installation as several things are broken on master)

**Comment by pronobis** [comment]
Works great with the new SP! Thanks!

**Comment by Fuco1** [comment]
Thanks for confirming.
