### ISSUE TITLE
sp-forward-symbol infinite loop in special buffers

### ISSUE THREAD

**Issue by pronobis** [Fuco1/smartparens#400]
In buffers such as `*Messages*`, but also e.g. `*Help*`, running `sp-forward-symbol` results in an infinite loop. Anything I can do to helm debuging?

**Comment by PythonNut** [comment]
One simple way is to do a `M-x profiler-start` select `cpu`, then go `sp-symbol-forward` wait a while, then kill it with a `C-g`. Now do a `M-x profiler-report` to see where the CPU got spent.

**Comment by Fuco1** [comment]
`sp--get-allowed-pair-list` returns an empty list, which generates a regexp matching an empty string, which makes the routine that skips non-symbol stuff go into infinite loop.

Pretty amusing bug.

I suppose the solution in such a case is to assume the symbol starts everywhere. Hm...

**Comment by Fuco1** [comment]
Also, this happens because both messages and help are special buffers and SP isn't initialized there by default---you'd need to turn it on in the setup hook for those modes.

**Comment by Fuco1** [comment]
This patch should fix it, please test :)

**Comment by pronobis** [comment]
The fix did it! Thanks!
