### ISSUE TITLE
Smartparens introduces incorrect whitespace in non-lisp modes

### ISSUE THREAD

**Issue by PythonNut** [Fuco1/smartparens#404]
Take for example, this python buffer (here, `|` is the point):

```python
a = |1, 2
```

One way of making the implicit tuple into a list is to type some square brackets and slurp the elements in.

```python
a = [|]1, 2
a = [|1,] 2
a = [|1, 2]
```

(It's a minor detail that the comma should go outside the square brackets, and I'm willing to ignore it).

However, one area where smartparens fails is when I have dot-separated symbols. Here is the slurping and barfing graph

```python
[]a.b, a.d, a.d
[a.]b, a.d, a.d
[a. b,] a.d, a.d
[a. b, a.]d, a.d
[a. b, a. d,] a.d
[a. b, a. d, a.]d
[a. b, a. d, a. d]
[a. b, a. d, a.] d
[a. b, a. d,] a. d
[a. b, a.] d, a. d
[a. b,] a. d, a. d
[a.] b, a. d, a. d
[]a. b, a. d, a. d
```

As you can see, smartparens has added extra spaces, which break the program flow.

**Comment by Fuco1** [comment]
This has been reported and solved before, I don't remember how.  If you have time, do a search in the opened/closed issues.

What is needed is some automatic setup for major modes so that users don't have to deal with it every time.

**Comment by PythonNut** [comment]
#88 and maybe #348?

The problem, I suppose is that the dot is an almost universal operator, present is the majority of languages (with the notable exception of the lisps, and the languages inspired by shell scripts).

**Comment by Fuco1** [comment]
I think the solution from #379 might work.

**Comment by Fuco1** [comment]
This has been solved with the addition of `smartparens-python.el`.

**Comment by PythonNut** [comment]
Ah, sorry. I totally forgot about this.

**Comment by Fuco1** [comment]
Don't worry, me too.  I booked an hour today to review old/stale tasks so I closed/updated a bunch :)
