### ISSUE TITLE
sp-region-ok-p returns nil on valid regions an truthy on invalid

### ISSUE THREAD

**Issue by expez** [Fuco1/smartparens#405]
Hey, I was hoping to build upon `sp-region-ok-p` but it doesn't appear to be as general as I'd hoped.  Is this something you'd be willing to fix?

Examples of stuff that seems weird:

Valid that are considered deemed invalid:
`,` or `.`

I'd expect all text that doesn't contain any sort of pairs to be considered valid.

Invalid that is deemed valid: 

`foo"`

but `foo)` or `foo]` etc are all deemed invalid.  Why is `"` treated differently?

**Comment by Fuco1** [comment]
To be completely honest, I don't know, someone else probably wrote it.  The way it works now seems to be just walking forward with `sp-forward-sexp` and waiting for an error.

As for `foo"`, the parser responsible for quotes is different from the one used for pairs. As the `"` is both opening and closing delimiter it is in general very hard to say what state you're in.

**Comment by expez** [comment]
I've been building `evil-smartparens` on top of this primitive for the last two days.  It seemed to be going quite well; I was getting a lot of functionality from very little code.  Unfortunately, the cases reported above makes it quite unusable.  

If you don't have any interest in improving `sp-region-ok-p` consider turning it private.  I got the impression that this would be safe, because it was public.  If you change your mind just ping me or post in this thread.

**Comment by Fuco1** [comment]
Well it should definitely be fixed.  Patches welcomed.

I'm currently quite under load, so I can't promise you any ETA.  The first of your issues should be rather easy to fix,, for the second, I don't have any solution come to me right away... maybe one can just try to jump back a string and see if it is broken or not.

**Comment by expez** [comment]
Aight, I might take a stab at this myself tomorrow, then.  What's the easy fix for letting text without any pairs go through cleanly?  Just loop over the pairs and see if any matches can be found in the region?
