### ISSUE TITLE
sp--pair-to-insert: Wrong type argument: symbolp, (property . pairs)

### ISSUE THREAD

**Issue by jcf** [Fuco1/smartparens#411]
Hi Matus,

I've just updated smartparens to version `20150111.926`. Now when I type in any buffer I get the following error:

```
sp--pair-to-insert: Wrong type argument: symbolp, (property . pairs)
```

I'm not great at Emacs Lisp, but when I evaluate `(sp--all-pairs-to-insert)` in ielm I get nil back, which maybe is where the problem is coming from?

If I disable smartparens mode the problem goes away.

Let me know if you want/need any more info. In the mean time I'll keep digging.

**Comment by Fuco1** [comment]
You need dash 2.10.

**Comment by jcf** [comment]
Thanks for the tip.

I have the following version of Dash:

```
Version: 20141220.1452
X-Original-Version: 2.10.0
```

I'll try wiping out some `elc` files and make sure there isn't an old version of Dash floating around in my `.cask` directory.

**Comment by jcf** [comment]
I've found the problem. Cask itself depends on `dash`, and installs a version of it in `.cask/bootstrap`.

I removed the dash directory, ran `cask install`, and hey presto got an up-to-date version of `dash`.

Thanks for your tip Matus!

**Comment by leppert** [comment]
@jcf Had the same problem. Many thanks.

**Comment by xiaohanyu** [comment]
Same problem, fixed after upgrading dash. Many thanks!

**Comment by dylan-conlin** [comment]
thanks @jcf!
