### ISSUE TITLE
infinite loop in sp-up-sexp 

### ISSUE THREAD

**Issue by expez** [Fuco1/smartparens#412]
Running `sp-up-sexp` from within this string, in `emacs-lisp-mode`, `"\\([\t ]+\\|\n\\)\\'"` starts an infinite loop.

**Comment by Fuco1** [comment]
It looks like the `\\\\'` at the end is the problem.  I bet it's yet another syntax-table nonsense :/

**Comment by Fuco1** [comment]
Fixed.
