### ISSUE TITLE
sp-backward-up-sexp moves when it shouldn't

### ISSUE THREAD

**Issue by expez** [Fuco1/smartparens#413]
```elisp
(foo bar)     ; comment at eol
```

Hitting `sp-backward-up-sexp` at eol moves point backward, past the comment all the way to the closing paren, which is unexpected.  I'd expect nothing to happen here.

**Comment by expez** [comment]
Do you consider this a bug, or is sp full of stuff like this?  It's not like it really matters for interactive use (it can be written off as user error in that case imo), but when building on top of smartparens this stuff can matter.

**Comment by Fuco1** [comment]
This happens because the comment is also considered a "sexp". This can be disabled with some user setting.
