### ISSUE TITLE
dollar symbol is no longer a delimiter in latex-mode

### ISSUE THREAD

**Issue by makotoy** [Fuco1/smartparens#415]
I noticed a regression in latex-mode between smartparens-20150106.757 and smartparens-20150112.902 pulled from melpa. It seems the dollar symbol (for math) stopped behaving as a delimiter. It used to automatically insert closing dollar when I input an opening dollar. I could also wrap a region with dollars by highlighting it and hit dollar key. After the update these are no more (at least with the same configuration in init.el). I checked that simply replacing smartparens with the old version recovers the above behaviors.

**Comment by Fuco1** [comment]
I've noticed this too, I thought it was my config being broken (I did some changes and haven't had time to investigate yet).  Thanks for the confirmation :)

**Comment by makotoy** [comment]
I tried a bit to figure out the culprit, but it looks like more of a conflict issue. Apparently this does not happen if you launch Emacs with -q and only activate smartparens and dash manually.

**Comment by makotoy** [comment]
It's conflicting with auctex, the vanilla latex-mode didn't have this issue (for my casual test). Sorry, I should have said I was using latex-mode from auctex in the first place. I can cause this by just adding `(load "auctex.el" nil t t)` either before of after loading smartparens.

**Comment by Fuco1** [comment]
Oh yes, I remember having some auctex hacks in place before.  I think this is going to come up with other modes where the "pair" characters are handled specially (like electric c or whatnot).

I'll need to figure out some way to override those.

You can downgrade to the latest tag where the issue shouldn't be present.

**Comment by pharpend** [comment]
Would also like to add that I am too experiencing this issue.

(GitHub doesn't have an issue-voting system, unfortunately.)

**Comment by Fuco1** [comment]
Thanks for confirming.

I'm going to grab some coffee and look at this issue now :)

**Comment by Fuco1** [comment]
Well, it's the stupid latex mode binding `TeX-insert-dollar`... that would be fine if they didn't `insert` the character instead of properly calling `self-insert-command` :/

I see I'll have to add post-command-hook resolver for all these silly non-conforming commands.

**Comment by pharpend** [comment]
Should we maybe file a bug report with LaTeX-mode? They are using non-standard behaviour with no good reason, it's breaking things, seems like a bug.

**Comment by Fuco1** [comment]
I have a simple fix for it already, just haven't pushed it yet in case I want to change something.

Sadly this is way to common in all sorts of modes in emacs (`c-mode` comes to mind) so I will need the kludge anyway :/

**Comment by Fuco1** [comment]
Please test against the latest master.

**Comment by makotoy** [comment]
I confirmed the fix in master, thanks a lot!

**Comment by pharpend** [comment]
Confirmed.
