### ISSUE TITLE
Fix misnamed variable: sp--autoescape-string-quote-if-empty

### ISSUE THREAD

**Issue by tkf** [Fuco1/smartparens#42]
This variable has opposite meaning of what it really does.

Proposed fixes:

1. Add new variable and make the old one as obsolete using `make-obsolete-variable`.
   Suggested names:
   - sp-autoescape-not-if-string-is-empty-in-mode
   - sp-dont-autoescape-if-string-is-empty-in-modes
2. Somehow integrate to the new suggested configuration mechanism: #31

3. Provide another way of inserting triple quote.
   For example, by including smartchr/key-combo functionality: #41

See the previous discussion: https://github.com/Fuco1/smartparens/issues/24#issuecomment-12356040

**Comment by Fuco1** [comment]
Variable no longer exists.
