### ISSUE TITLE
Compilation error (sp--pair-to-insert)

### ISSUE THREAD

**Issue by jeastman** [Fuco1/smartparens#422]
When compiling `smartparens.el`, I run into the following compilation error:

    smartparens.el:3103:8:Error: Wrong type argument: sequencep, pairs

The package I am using is pulled from melpa (20150116.45) and the error appears to be related to a change in commit 9d9d584 (addition of the `sp--pair-to-insert` function). Versions before this commit were working for me. Given that I have not seen any other issues reported against this, I am guessing that the problem is either some sort of conflict or environmental on my end.

The result is that `smartparens-mode` does not work. Any suggestions for resolving this?

**Comment by Fuco1** [comment]
See https://github.com/Fuco1/smartparens/issues/420#issuecomment-70214668

**Comment by jeastman** [comment]
Great. Thanks!

**Comment by jeastman** [comment]
Just an additional note here. I actually had `dash` 2.10 installed (thus did not have the same void symbol problem described in #420). Removing/re-installing each package individually (correct versions) did not solve the problem. I ended up manually evaluating `dash.el` and then re-byte-compiling `smartparens.el` to avoid the error.

**Comment by Fuco1** [comment]
Well, yea, `package.el` won't do that because it is confused when evaluating dependencies.
