### ISSUE TITLE
Compilation error on Emacs 24.4.1

### ISSUE THREAD

**Issue by nordlow** [Fuco1/smartparens#423]
Loading of smartparens.el works but byte-compilation errors as

```
smartparens.el:2532:44:Warning: attempt to let-bind nonvariable `(&keys :open
    open :close close)`
smartparens.el:2531:56:Warning: reference to free variable `open'
smartparens.el:2531:68:Warning: reference to free variable `close'
smartparens.el:3129:8:Error: Wrong type argument: sequencep, pairs
```

on latest stable Emacs 24.4.1.

**Comment by Fuco1** [comment]
You need to get smartparens dependencies, which are listed in the installation instrucitons. 

Currently it's only `dash` version 2.10 or newer.

**Comment by nordlow** [comment]
Thanks.

**Comment by Fuco1** [comment]
If it works for you now, please close the issue :)

**Comment by nordlow** [comment]
Sorry. Forgot that.
