### ISSUE TITLE
sp-local-pair without auto-inserting

### ISSUE THREAD

**Issue by tuhdo** [Fuco1/smartparens#426]
For many pairs, I only want to add pairs for highlighting, navigating and killing, not auto-complete. For example, I want to add the pair `if` and `fi`, the pair `beg` and `end`... just for highlighting when point is on either end, or move back and forth or quick killing without making a region.

Is that possible already? If not, may it be added?

Thanks.

**Comment by Fuco1** [comment]
Yes, you can not include the `insert` symbol from the `:actions` list when defining the pair.

https://github.com/Fuco1/smartparens/wiki/Permissions#actions

**Comment by Fuco1** [comment]
Which reminds me, some of the possible actions are missing in the documentation and I should update it.

You can also `C-h f` on `sp-pair`, there should be the complete list.

**Comment by tuhdo** [comment]
So, I tried this local pair:

```elisp
(sp-local-pair 'sh-mode "if" "fi" :actions '(wrap))
```

It wraps fine, but the pair cannot be highlighted or navigate back and forth.

And this:

```elisp
(sp-local-pair 'sh-mode "if" "fi" :actions '(:rem insert))
```

doesn't do anything after activated, not even wrapping.

**Comment by Fuco1** [comment]
`:rem` only removes options from the global or parent setting. If the pair doesn't exist at all, there's nothing to remove from, so the list will end up empty.

In the documentation for `sp-pair`, the possible actions are listed.  You want: `wrap navigate`

**Comment by tuhdo** [comment]
Silly me. I looked up `sp-local-pair` instead of `sp-pair`. Btw, this works for me, but I don't know if I did it the right way:

```elisp
(defun sh-if-post-handler (&rest ignored)
  (previous-line)
  (beginning-of-line)
  (search-forward "if")
  (save-excursion
    (insert " ; then")
    (open-line 1))
  (forward-char 1))

(sp-local-pair 'sh-mode "if" "\nfi"
               :actions '(wrap navigate)
               :pre-handlers '(sh-if-pre-handler)
               :post-handlers '(sh-if-post-handler))
```

That is, when you press `if` on a region like this in `sh-mode`:

```sh
echo "test"
echo "test"
```

Then, it becomes like this:

```
if []; then
    echo "test"
    echo "test"
fi
```
(`[]` is the cursor)

I tried to open a newline using `pre-handlers`, but it didn't work so I did it all in `post-handlers`. Another thing is, in the closing pair `\nfi`, the newline character works but not in the opening pair.

**Comment by Fuco1** [comment]
In general you shouldn't put whitespace in the pairs. Otherwise looks good.

For wrapping, only post handlers are called.

**Comment by tuhdo** [comment]
Thanks. I will leave the issue open until you update documentation.

**Comment by tuhdo** [comment]
It is possible for `smartparens` to highlight the pair when point is in the middle of the text? Currently, it's only highlight if the cursor is at the beginning of opening pair, or at the end of closing pair.

**Comment by Fuco1** [comment]
That's currently not possible. There's an open issue somewhere about it already :)
