### ISSUE TITLE
sp-get-paired-expression infinite loop

### ISSUE THREAD

**Issue by jgarvin** [Fuco1/smartparens#427]
Open a scratch buffer and put in the following:

    (sp-get-paired-expression)
    
    ;; ()

Importantly you must *NOT* have a trailing newline, () must be the last thing in the buffer. It must also be commented, no idea why.

Then put point after (sp-get-paired-expression) and run eval-last-sexp (C-x,C-e). Emacs will hang, running 24.4.1 with -Q with only dash and latest checkout of smartparens from master loaded.

**Comment by expez** [comment]
bah, referenced the worng issue in the commit message.  Anyway, this is solved now.  Thanks for the bug report, @jgarvin!
