### ISSUE TITLE
Detecting if given character is closing or opening or neither

### ISSUE THREAD

**Issue by jgarvin** [Fuco1/smartparens#428]
Question about the best way to do something.

I'm working on a speech recognition mode and one important aspect of it is being smart about automagically inserting spaces because they're extremely repetitive to manually say. The way I've done this so far is that when the user speaks to insert text, I check the character before point against lists of characters that should trigger/inhibit the insertion of a space. This works OK but it doesn't handle pairs intelligently and I'd like to leverage smartparens if I can. If I write:

    "hello"|

And then I say "world" I'd like the result to be:

    "hello" world|

Not:

    "hello"world|

With my current approach all I can do is put the double quote character in the list of characters that should trigger a space.  But then if I have:

    "|

And I say "hello" I will get:

    " hello|

When I want:

    "hello|

So the problem is I need the behavior to change based on whether the previous character is an opener (no space) or a closer (add a space... unless the character we're inserting is also a closer, so all those trailing closing parens in lisp still look right ;)))))).

What's the best way to detect this situation? Something like `(sp-is-closer (- (point) -1))` would be ideal but AFAICT doesn't exist. I could maybe use sp-get-paired-expression and check the closing extent, but I don't know if that's the best way to do it since it'll search arbitrarily far in either direction when I really only want to know for `(- (point) 1)` (also bug #427 means it might hang but that's a separate issue).

**Comment by Fuco1** [comment]
With pairs where delimiters are the same at both ends it is basically impossible to do any other way than to count parity up to the beginning of the buffer.  I have some ideas about how to implement this with caching but I haven't even started with the implementation yet (plus this also totally break in a language mode without string syntax support).

What follows is a heuristic, but a very good one in practice: check the previous/after context of `"`. If it is `<word-char>"` we're closing, if it is `<whitespace-or-beg-of-buffer>"` we're opening.

For pairs which have different opening and closing delimiters there's `sp--get-opening-regexp` and `sp--get-closing-regexp`, you can use `sp--looking-at-p` and `sp--looking-back-p` with these to check what is the context.

**Comment by jgarvin** [comment]
Thanks, that's actually a nice idea. I'd refine it a little bit, and say that if the preceding character is also an opener then this character is likely an opener too. Since it's common to write things like `foo("|` where the quote should be considered an opener even though the procedding character isn't a word char.

**Comment by jgarvin** [comment]
Here's my attempt:

    (defun md-likely-preceded-by-opener (pos)
      "If the characters preceding pos form a delimeter in a pair
    where the opening and closing delimeters differ, then we can know
    with certainty that the character is an opener and return t.

    When the delimeter is part of a pair where the opening and closing
    strings are the same, like quotes, We use a heuristic to decide 
    if a delimeter is an opener or a closer. If the character prior is
    whitespace, then it's probably an opener. If the string prior
    is an opener, then we're likely an opener too.

    If the string preceeding pos isn't part of any pair, then returns nil."
      (save-excursion
        (goto-char pos)
        (let ((preceding-unmatching-opener)
              (preceding-matching-opener))
          (if (setq preceding-unmatching-opener
                    (sp--looking-back (sp--get-opening-regexp)))
              (goto-char (match-beginning 0))
            (when (setq preceding-matching-opener
                        (sp--looking-back (md-get-matching-opening-regexp)))
              (goto-char (match-beginning 0))))
          (cond
           ;; We have a distinct opener, return t
           (preceding-unmatching-opener t)
           ;; We have neither kind of opener, return nil
           ((not preceding-matching-opener) nil)
           ;; We have a matching opener with nothing in front,
           ;; must be an opener, return t
           ((bobp) t)
           ;; We have a matching opener preceeded by whitespace,
           ;; probably an opener, return t
           ((looking-back "[[:space:]\n]" 1) t)
           ;; We have a matching opener preceeded by an identical
           ;; matching opener, so this is actually the closer,
           ;; return nil
           ((looking-back (regexp-quote (buffer-substring (match-beginning 0) (match-end 0)))) nil)
           ;; We have a matching opener preceeded by another,
           ;; probably this is one too, return t
           ((md-likely-preceded-by-opener (point)) t)))))

**Comment by jgarvin** [comment]
Oh yeah, you can close this, thanks for the help.

**Comment by Fuco1** [comment]
@jgarvin You can also close issues :)

No problem.

**Comment by Fuco1** [comment]
Also thanks for the code! I plan to write a "fast" string parser that would work with this heuristic... in modes like `text-mode` or `org-mode` which don't have string syntax, it should provide satisfactory results.

**Comment by jgarvin** [comment]
Oops, sorry didn't realize I could close. Also I forgot to include the md-get-matching-opening-regexp function and what it uses (I'm sure there are better / more lispy ways to write this but for completeness it's here ;):

    (defun md-matching-pairs ()
      (let ((result))
        (if (and (boundp 'sp-local-pairs)
                 sp-local-pairs)
            (dolist (i sp-local-pairs)
              (when (equal (plist-get i :close) (plist-get i :open))
                (push (plist-get i :close) result)))
          (setq result (list "\"")))
        result))

    (defun md-get-matching-opening-regexp ()
      (regexp-opt (md-matching-pairs)))
