### ISSUE TITLE
Inconsistent behavior with skipping quotes

### ISSUE THREAD

**Issue by myeffort** [Fuco1/smartparens#429]
Provided I set sp-autoescape-string-quote to nil, I can escape strings as I do it quickly.
However if I press anything besides self-insert-command on my way to other side and instead of skipping closing delimiter it will insert a pair of quotes.

Steps to reproduce:
Set sp-autoescape-string-quote to nil.
Correct behavior: 

    "      q w e     "
    "|"    "qwe|"    "qwe"|

Incorrect behavior:

    "      q w e     <DEL>      "
    "|"    "qwe|"    "qw|"      "qw"|""

**Comment by Fuco1** [comment]
This is caused by not having the major mode in `sp-navigate-consider-stringlike-sexp` list.  I'm just doing the last changes to remove this variable so then this won't be a problem anymore.
