### ISSUE TITLE
Auctex LaTeX mode quotes no longer wrap.

### ISSUE THREAD

**Issue by jcpetkovich** [Fuco1/smartparens#432]
As in #415 which is now fixed. LaTeX-mode quotes (<key>``</key>, and <key>''</key>), are no longer wrapped or inserted correctly when pressing <key>"</key>.

**Comment by ddoherty03** [comment]
Similar here, but " with no region works fine, resulting in ``''.  However, is I have a region active and hit ", 
I would like to have the region wrapped in LaTeX double quotes, ``<region>''.

I am using the melpa version 20150813.

Fuco1, thanks for your work on this, btw.

Regards,

**Comment by Fuco1** [comment]
This sort of works with single wrapping (just hitting backtick) but the triggers are still broken somehow.   I have a task opened for this for this week, but it might take longer.

Thanks for the report.

**Comment by ddoherty03** [comment]
Matus,

Thanks for the update.

**Comment by Fuco1** [comment]
Hmm, so I can get a behaviour where if I am with the cursor at the beginning and I hit " I get

    ``foo'

and when I'm at the end it deletes the region and inserts just a `'`.  Terrible terrible code I've written :/

Is this same for you?

**Comment by ddoherty03** [comment]
Yep, exactly the same.

**Comment by Fuco1** [comment]
Well I got this fixed but now hitting 

    ``

doesn't work, it inserts 

    ``''foo'

But we're getting closer!

**Comment by Fuco1** [comment]
@ddoherty03  This works on my end and all tests are passing.  Can you please verify if it works with your setup? Thanks.

**Comment by ddoherty03** [comment]
OK.  All scenarios I could think of do the right thing.  You da man!  Thanks for getting this little burr out my saddle.

**Comment by Fuco1** [comment]
Thanks for confirmation, so I'm closing.

In case of any trouble open a new issue.
