### ISSUE TITLE
sp-unwrap-sexp doesn't remove surrounding quotations

### ISSUE THREAD

**Issue by jacobmoe** [Fuco1/smartparens#433]
`sp-unwrap-sexp` removes pairs surrounding `[remove surrounding pair]` and `(remove surrounding pair)` but not `"remove surrounding pair"` or `'remove surrounding pair'`

**Comment by expez** [comment]
See the documentation for `sp-navigate-consider-stringlike`, this is also major-mode specific, e.g. `'this'` isn't considered stringlike in `emacs-lisp-mode` but it is in `javascript-mode`.
