### ISSUE TITLE
Problem when TeX-electric-math is set to insert \( \)

### ISSUE THREAD

**Issue by dinojr** [Fuco1/smartparens#434]
It seems a recent commit broke the handling of \\( \\) pairs choice for TeX-electric-math. I'm loading smartparens with (require smartparens-config), choosing \\( \\) for TeX-electric-math through customize and now, pressing $ yields:
\\(\\)\\)
Note that at first \\(\\) is inserted but a second \\) is added shortly after.

**Comment by Fuco1** [comment]
Well obviously, if you mix smartparens and electric stuff which both do the same thing. Simply don't use one or the other.

**Comment by dinojr** [comment]
I've been using for setup because I couldn't get smartparens to insert a \\( \\) when I type $. I tried 

(sp-with-modes '(
                 tex-mode
                 plain-tex-mode
                 latex-mode
		 org-mode
                 )
    (sp-local-tag "$" "\\(" "\\)")
  )

but it failed.

**Comment by Fuco1** [comment]
Tags were removed from the master. If you run MELPA, you might get broken code.

If you want to use tags, get the latest tag release from git.  The functionality of tags will be included in the master as ordinary pairs sometime later in the 1.7 release.

**Comment by dinojr** [comment]
I think I can live with typing \\( instead of $, waiting for the next release. In the meantime, I thought about  letting TeX-electric-math take over for this particular pair, using (sp-local-pair "\\(" nil :actions :rem), with no success.

**Comment by Fuco1** [comment]
You need to put two escapes in the string

    (sp-local-pair "\\(" nil :actions :rem)

Or you can use a `:trigger` setting

   (sp-local-pair "\\(" "\\)" :trigger "$")

and then remove the `$` pair.

**Comment by Fuco1** [comment]
I don't understand why I tagged this as a bug as the above does what you seem to want.  I'm going to close it, if you have some more questions you can reopen or start a new issue.
