### ISSUE TITLE
can't find 1.6.3 on emacs package-list-package

### ISSUE THREAD

**Issue by wolfand11** [Fuco1/smartparens#435]
can't find 1.6.3 on emacs package-list-package

**Comment by expez** [comment]
It's right [here](http://stable.melpa.org/#/smartparens).

You probably haven't configured your package manager to use the correct repo.  Check out the code snippets in the melpa [README](http://stable.melpa.org/#/getting-started).

**Comment by wolfand11** [comment]
oh, Thank you! i missed melpa-stable
