### ISSUE TITLE
Various minor problems

### ISSUE THREAD

**Issue by jorgenschaefer** [Fuco1/smartparens#436]
Smartparens is fun, thanks for the package. I came across some problems that I am not sure if they are me being stupid or smartparens doing something weird.

My configuration:

```Lisp
(when (load "smartparens" t t)
  (load "smartparens-config")
  (setq sp-base-key-bindings 'sp
        sp-highlight-pair-overlay nil)
  (sp-use-smartparens-bindings)
  ;; Used otherwise in e.g. org-mode                                            
  (define-key smartparens-mode-map (kbd "<M-up>") nil)
  (define-key smartparens-mode-map (kbd "<M-down>") nil)

  (smartparens-global-mode))
```

The things I noticed (with `|` being point):

- In org-mode, typing `'` will insert the expected `'|'`, but typing backspace will leave me with `|'`, i.e. it does not remove the second tick. For `""`, it works, so not sure what's going on there.
- In org-mode, typing `""` results in `""|""`, I would expect `""|`
- In Circe, typing `""` results in `"\"|\""`, I would expect `""|`
- In Circe, typing `''` results in `''|''`, I would expect `''|`

Any idea what those might be about?

**Comment by expez** [comment]
>In org-mode, typing ' will insert the expected '|', but typing backspace will leave me with |', i.e. it does not remove the second tick. For "", it works, so not sure what's going on there.

`''` aren't defined as strings in `org-mode` as far as I can tell, but `""` are.  This set set by the syntax table of the major mode.

>In org-mode, typing "" results in ""|"", I would expect ""|

See the documentation for `sp-autoskip-closing-pair`, specifically the part about `sp-navigate-consider-stringlike-sexp'.  

>In Circe, typing "" results in "\"|\"", I would expect ""|
In Circe, typing '' results in ''|'', I would expect ''|

Same as above

**Comment by jorgenschaefer** [comment]
Thank you for the response. Based on the answer, I have now added this to my configuration:

```Lisp
(add-hook 'org-mode-hook 'fc/org-mode-smartparens-fixup)
(defun fc/org-mode-smartparens-fixup ()
  (modify-syntax-entry ?\' "\""))
```

This seems to fix the first issue.

I am afraid I do not understand the docstring of `sp-autoskip-closing-pair`. It uses a lot of nomenclature and internal details of smartparens that I do not know. As a stab in the dark, I tried this:

```Lisp
(setq-default sp-autoskip-closing-pair 'always-end
              sp-navigate-consider-stringlike-sexp '(latex-mode
                                                     org-mode))
```

This did not change the behavior in org-mode. I created a new I must be missing something essential, but I am not sure what it is. Any suggestions? :-)

**Comment by Fuco1** [comment]
`sp-autoskip-closing-pair 'always-end` should be the default actually.

The other setting is similar for me.

Typing `''` ends up as `''|`, typing `""` ends up as `""|""`. In the 1.6.3 version there's also `sp-autoinsert-if-followed-by-same` (which has since been removed because it's totally useless).

What value does that have?

**Comment by jorgenschaefer** [comment]
`sp-autoinsert-if-followed-by-same` is set to 3 here. Setting it to 1 fixes the problem in org-mode. Judging from the docstring, that'd be my preferred behavior in any case. Thank you!
