### ISSUE TITLE
Commit "75ed703" caused huge org-mode buffer unusable

### ISSUE THREAD

**Issue by YorkZ** [Fuco1/smartparens#437]
Commit 75ed703, subject "Rework wrapping", has caused my huge org-mode buffer extremely slow, to the point that no matter what I type, it takes the character I've typed a few seconds to show up in the buffer. I profiled and figured out that more than 90% of the time have been spent in some `smartparens` function. Finally I've tracked down to commit 75ed703.

Hope this helps.

**Comment by Fuco1** [comment]
I have noticed this too but wasn't sure about the source.  I was about to go work on it now :)

Thanks for confirming.

**Comment by Fuco1** [comment]
Fixed by above commit.
