### ISSUE TITLE
Make sp--lisp-modes customizable.

### ISSUE THREAD

**Issue by BernardHurley** [Fuco1/smartparens#438]
The maxima computer algebra system is written in Common Lisp and the maxima language uses the single quote in exactly the same way as in lisp as well as allowing for embedded Lisp.  So these modes are sufficiently lisp-like to be added to sp--lisp-modes permanently.

However I have been using imaxima a lot recently, this uses the maxima language but runs in Comint mode.  So, for my purposes, it would be quite convenient for Comint mode to be added to sp--list-modes, however I don't think it could be justified to hard code this as others may not want it to happen.  The best solution to this would be to make sp--lisp-modes customizable.

**Comment by Fuco1** [comment]
Well, for now you can `add-to-list`, but sure, I don't see any particular problem with making this customizable.

Do you want to make a patch?

**Comment by BernardHurley** [comment]
On Tue, Feb 10, 2015 at 09:37:49AM -0800, Matus Goljer wrote:
> Well, for now you can `add-to-list`, but sure, I don't see any particular problem with making this customizable.

This is what I have done.

> 
> Do you want to make a patch?

I will make one tomorrow, I don't have time today.

Bernard.

**Comment by expez** [comment]
ping @BernardHurley :)
