### ISSUE TITLE
New autoescaping

### ISSUE THREAD

**Issue by Fuco1** [Fuco1/smartparens#442]
Basic tasks

* Wrapping
  * When we have `"foo"` and wrap it with another layer of quotes, it becomes `"\"foo\""`
  * When we wrap again `"\"foo\""` becomes `"\"\"foo\"\""` (so the inner escaped quotes are not escaped)
  * When we wrap within the string `"foo |bar| baz"` becomes `"foo \"bar\" baz"`
  * If we wrap again `"foo |qux \"bar\" bux| baz"` becomes `"foo \"qux \"bar\" bux\" baz"` (the inner escaped quotes aren't escaped again.)
  * If we wrap `""` with `''` or other way round (in languages where this is supported) it should not escape.
* Inserting
** Similarly, typing `"` or `'` inside a string delimited by the same delimiter should escape the inserted pair (or single quote... depends on how the user set the autopairing)

This should be implemented as a stand-alone function which can be called on a region (or "at point" which is a region of zero length) to perform the escaping.  It will then be put on a post-wrap/insertion hook to perform the autoescape if the user wants it.  But it should not depend on `sp--wrap` or `sp-insert-pair` at all.

**Comment by Silex** [comment]
One task I had the other day way to rewrap from `:onclick => 'foo("bar")'` to `:onclick => "foo('bar')"` and `sp-rewrap-sexp` only worked for the outer parenthesis but not ones inside the string.

Not saying SP should support this sketchy use-case tho, just mentionning it :)

**Comment by Fuco1** [comment]
That probably depends on the mode.  ISTR this worked for me in PHP. Or at least changing `''` to `()` or something similar.

Though if you change the inner pair to `"` (where outside is also `"`) you've now created two disconnected strings with `bar` outside the string.

There could be a special routine to just swap the quotes of the "quoted inside quoted" string.  Should probably go in a new issue/FR (if you want to open and describe it that would be cool)

**Comment by Fuco1** [comment]
Fixed on `feature/autoescape`
