### ISSUE TITLE
Using smartparens with company within sexp adds double closing.

### ISSUE THREAD

**Issue by pronobis** [Fuco1/smartparens#445]
The following advice in smartparent.el:

```
(defadvice company--insert-candidate (after sp-company--insert-candidate activate)
  "If `smartparens-mode' is active, we check if the completed string
has a pair definition.  If so, we insert the closing pair."
  (when smartparens-mode
    (sp-insert-pair))
  ad-return-value)
```

results in some funny behavior when trying to complete with company and SP enabled. Typically typing e.g. \ref{ will already generate \ref{} and then add another } when completion starts resulting in \ref{}}. This happens for any completion within a pair such as e.g. `#include <|>`.

What is the reasoning behind this advice? Can using it be an option?

**Comment by Fuco1** [comment]
The reason is that if you type e.g. `beg` and then it completes to `begin` you want to insert `end`.  If the candidate already has a pair, it will insert twice indeed.  I don't see a good way to fix this now.

**Comment by Fuco1** [comment]
When you type `beg` and complete to `begin` you might want to add `end` automatically (ruby).  If the completed string already cmpletes the pair, it will be inserted again by SP, that's true.

I don't see any good way to fix this now.
