### ISSUE TITLE
Incorrect behaviour of `sp-...` nav commands when there's a paren inside a string

### ISSUE THREAD

**Issue by vkz** [Fuco1/smartparens#446]
This is likely to be related to this #367 issue, except I'm not using **evil**. 

Probably non-exhaustive list of faulty commands include:
```elisp
sp-up-sexp
sp-beginning-of-sexp
sp-end-of-sexp
```
and their **backwards** cousins.

Trying one of the above commands on the following lines jumps to the outer most parens ignoring inner wrapped expressions, which is not at all the expected behaviour (point denoted with `|`):
```elisp
(define-key sp-keymap (kbd | "C-(") 'sp-down-sexp)
(define-key sp-keymap (kbd | "C-[") 'sp-up-sexp)
(define-key sp-keymap (kbd | "C-{") 'sp-beginning-of-next-sexp)
```

With point inside string literals in the above expressions both `sp-beginning-of-sexp` and `sp-end-of-sexp` report **Unmatched expressions**.

Experienced on:
```
GNU Emacs 24.4.1 (x86_64-apple-darwin14.0.0, NS apple-appkit-1343.16)
 of 2014-12-29 

smartparens-20150218.1058 freshly installed from elpa
```

**Comment by vkz** [comment]
unfortunately this renders **sp** almost completely useless in lisp modes when one wants to navigate and edit AST instead of strings, cause errors and unexpected behaviour like this demands that one has char/string nav commands bound somewhere. I was rather hoping I'd be able to completely replace common navigation bindings when editing lisp. Do you think I'll have more luck with **paredit**?

**Comment by vkz** [comment]
`sp-previous-sexp` is also effected. Reports unmatched expression and gets stuck at point (denoted with `|`) when in the following text:
```elisp
;; (define-key sp-keymap (kbd ")") nil)
;; (define-key sp-keymap (kbd "C-(") 'sp-backward-up-sexp)
```

**Comment by Fuco1** [comment]
There was a bug indeed which triggered when there was an unmatched paren inside a string which directly touched a closing paren (pretty involved right? :D)

It should be fixed now.  I'll add your cases to the test suite so we don't run into it again.

Can you test if it works for you now?
