### ISSUE TITLE
Binding nav commands to Control sequences steals all global Meta bindings

### ISSUE THREAD

**Issue by vkz** [Fuco1/smartparens#447]
Introducing these bindings makes all global `M-...` bindings unbound:
```elisp
(define-key sp-keymap (kbd "C--") 'negative-argument)
(define-key sp-keymap (kbd "C-f") 'sp-forward-sexp)
(define-key sp-keymap (kbd "C-b") 'sp-backward-sexp)
(define-key sp-keymap (kbd "C-(") 'sp-down-sexp)
(define-key sp-keymap (kbd "C-{") 'sp-backward-up-sexp)
(define-key sp-keymap (kbd "C-)") 'sp-backward-down-sexp)
(define-key sp-keymap (kbd "C-[") 'sp-up-sexp)
(define-key sp-keymap (kbd "C-n") 'sp-next-sexp)
(define-key sp-keymap (kbd "C-p") 'sp-previous-sexp)
(define-key sp-keymap (kbd "C-c C-a") 'sp-beginning-of-sexp)
(define-key sp-keymap (kbd "C-c C-e") 'sp-end-of-sexp)
(define-key sp-keymap (kbd "C-a") 'sp-beginning-of-next-sexp)
(define-key sp-keymap (kbd "C-e") 'sp-end-of-next-sexp) 
```
So that for instance `M-n` and `M-p` which I have bound like so:
```elisp
(global-set-key (kbd "M-p") 'backward-paragraph)
(global-set-key (kbd "M-n") 'forward-paragraph)
```
are reported as unbound. This is in fact true for all global Meta bindings. `turn-off-smartparens-mode` gives them back.

Is that the intended behaviour?

System:
```
GNU Emacs 24.4.1 (x86_64-apple-darwin14.0.0, NS apple-appkit-1343.16)
 of 2014-12-29 

smartparens-20150218.1058
```

**Comment by vkz** [comment]
oh, wow. Appears `(kbd "C-[")` translates into `ESC-` which is somehow equivalent to Meta. God knows why, how or when. Point is, **smartparens** can't be blamed.

If such translation is the default for Emacsen may I suggest verifying it and maybe adding a note in **sp** docs somewhere that rebinding `C-[` maybe dangerous or better yet some way to do it without messing up Meta bindings. Given that **sp** works with parentheses, binding stuff to paren-combos is all too plausible so unsuspecting newbs like myself may get it rough. 

**PS**: I'm gonna close this, but if anyone knows how to safely break the translation between `C-[` and Meta I'd be grateful for pointers

**Comment by vkz** [comment]
Appears [this is the way to do](http://superuser.com/questions/173851/linux-remap-ctrl-key) albeit not without some low level trickery. Oh, how I wish we didn't bring all this terminal cruft to XXI century

**Comment by vkz** [comment]
Unfortunately, the above mentioned solution doesn't appear to work, hopefully the [discussion on stackexchange](http://emacs.stackexchange.com/questions/10271/how-to-bind-c-for-real-seriously-for-real-this-time) will produce a satisfactory result

**Comment by Fuco1** [comment]
This works

```
(define-key key-translation-map [escape] [?\e])
(define-key input-decode-map [?\C-\[] [(control left_bracket)])
(define-key function-key-map [escape] nil)
(define-key function-key-map [?\e] nil)
```

The catch is that you have to bind `<left_bracket>` instead of `[`, so `"C-<left_bracket>"`

**Comment by vkz** [comment]
thank you!

**Comment by Jonta** [comment]
Thanks @Fuco1, that seems to work for this as well:

`(define-key key-translation-map [(meta ?")] [?\®])

turned into:

(define-key key-translation-map [(meta ?<double_quotes>)] [?\®])`

But gives me this error on restarting Spacemacs: "Spacemacs encountered an error while loading your \`Users/jonta/.spacemacs' file."

Checking *Messages* (`C-x C-b`):

"Error loading .spacemacs: (invalid-read-syntax "?")"

GNU Emacs 26.3

**Comment by Fuco1** [comment]
@Jonta I would try to write only `[(meta double_quotes)]`.  The `?` syntax is for reading the *single next character* (`?"` turns into ascii code of `"`).

Unless there is something special about evil-mode/spacemacs it should work.
