### ISSUE TITLE
`wrong-type-argument number-or-marker-p nil` in sp-select-next-thing when no thing to select

### ISSUE THREAD

**Issue by pronobis** [Fuco1/smartparens#449]
Placing cursor before end of empty buffer (e.g. minibuffer) and using sp-wrap-with-pair generates an error in `sp-select-next-thing`. It should fail gracefully without an error.

Full backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  sp-select-next-thing(1 nil)
  sp-select-next-thing-exchange(1 nil)
  sp-wrap-with-pair("(")
  (lambda (&optional arg) (interactive "P") (sp-wrap-with-pair "("))(nil)
  call-interactively((lambda (&optional arg) (interactive "P") (sp-wrap-with-pair "(")) nil nil)
  command-execute((lambda (&optional arg) (interactive "P") (sp-wrap-with-pair "(")))
```

**Comment by Fuco1** [comment]
This happens also in non-empty buffer when point is at the end.  Should be an easy fix, hopefully someone will try it before I get to it.

**Comment by ned2** [comment]
I noticed this when enabling `fundamental-mode` on an empty buffer. So I keep getting an error when loading non-existent files. Only happens when `show-smartparens-global-mode` is enabled. My debugger output looks slightly different:

```Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  buffer-substring-no-properties(nil nil)
  sp-get-thing(nil)
  #[(match &optional back) "\304!\211\2034	\305\n\306\"`X\2050`\305\n\307\"X\2050\310\305\n\306\"\305\n\307\"\305\n\311\"G\305\n\312\"G$)\202H\203C\313`GZG\"\202H\313`G\")\207" [back ok struct match sp-get-thing plist-get :beg :end sp-show--pair-create-overlays :op :cl sp-show--pair-create-mismatch-overlay] 8]("")
  sp-show--pair-function()
  apply(sp-show--pair-function nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 0 125000 t sp-show--pair-function nil idle 0])```

**Comment by Wilfred** [comment]
@ned2 OK, I'm writing a patch for `sp-select-next-thing`, but I can't reproduce your error. Would you mind opening a separate bug with more details?

I tried to do the following:

1. `M-x show-smartparens-global-mode`
2. `M-: (get-buffer-create "*test-buffer*")` to create an empty buffer
3. `C-x b` to switch to that buffer.

I don't get any errors in this case.

**Comment by ned2** [comment]
It's possible there could be some interaction with other packages I have. I tried to isolate the behavior to smartparens alone, however I only found out afterwards that calling `emacs -q -l test_init.el` doesn't call result in `init-hook` being triggered. So perhaps I'll do this again properly and open a new bug if it persists.

**Comment by ned2** [comment]
The error I I was experiencing has now gone. I've been fiddling with emacs config and i think have also upgraded smarparens, so not sure where the problem was coming from. At any rate, no longer a problem.
