### ISSUE TITLE
add ')' at the end 

### ISSUE THREAD

**Issue by yitang** [Fuco1/smartparens#454]
Hi, I started to use `smartparens` since Monday and in the process of changing my typing behaviour to adopt `smartparens` as I have high expectation for it after reading the wiki. 

One thing I am struggle with is this:  

Supposed I have checked the `sum(x)` and feel it is correct and then I would like to apply a function `f` to the results of `sum(x)`, so I

1. browse the command history and choose `sum(x)`, 
2. move the point to the font and type `f(`, 
3. then move the point to the end and type `)`.

But with `(smartparens-mode 1)`, there is actually one extract step: to remove the auto inserted `)` in `f()sum(x)`.

and I wonder if I can configure the package so when I type `(` and if the next character is not an blank space, in this case is _s_, then the `)` will be inserted to be very end? If I can do this, the whole process can simplified into only two steps and save me a lot typing in a day.  

-Yi

**Comment by jgarvin** [comment]
Not a fix but an alternate workflow:

1. move the point to the front and type `f`
2. Set the mark
3. Go to end of line
4. Press `(`

Now the whole `sum(x)` call is wrapped.

**Comment by Silex** [comment]
Also possible: 

- `C-q ( C-e C-q )` to insert parens literally
- `f(` followed by `sp-slurp-sexp`

**Comment by yitang** [comment]
@jgarvin  thanks for sharing your workflow. I like it! @Silex

**Comment by Fuco1** [comment]
It is possible to change when a pair should be inserted using [Filters](https://github.com/Fuco1/smartparens/wiki/Permissions#filters), but I recommend the above mentioned workflow.

You can also set SP in a way that the prefix before `(` is understood as "sexp prefix" (similar to how `'` is treated in lisp modes), then it is part of the sexp and you can wrap it with a single key---SP can automatically figure out where the sepx ends.

To add keybinding for wrapping with a specific pair, use the `:wrap` option with `sp-pair` or `sp-local-pair`

For example

    (sp-local-pair 'emacs-lisp-mode "(" nil :wrap "C-(")

sets wrapping with `()` on `C-(` in `emacs-lisp-mode`.
