### ISSUE TITLE
Could Rainbow Delimiters be included with Smartparens?

### ISSUE THREAD

**Issue by XQLRSZ** [Fuco1/smartparens#466]
[Rainbow Delimiters](https://github.com/Fanael/rainbow-delimiters) is an Emacs minor mode that highlights parentheses (along with brackets and braces) based on their nesting level. [This post](http://emacs-fu.blogspot.com/2011/05/toward-balanced-and-colorful-delimiters.html) describes it as
>*"a new helper in the quest for balance in delimited universe."*

Also, the [Emacs Wiki](http://www.emacswiki.org/emacs/RainbowDelimiters) has a pretty comprehensive page on it.

I'm not sure everyone likes it, but I haven't heard many complaints.

**Comment by Fuco1** [comment]
I don't understand whar you are asking.

**Comment by wasamasa** [comment]
@XQLRSZ smartparens is no starter kit. It is a standalone package, just like rainbow-delimiters is. Therefore, speaking of inclusion and "default distribution" doesn't make much sense here.

**Comment by XQLRSZ** [comment]
@Fuco1 Smartparens is a package dedicated to making parentheses easier to work with. It does this by taking some useful packages an putting them in the same place. Would it be feasible to add the package Rainbow Delimiters to Smartparens?

@wasamasa I see your point. I have reading about Linux too much lately. I have edited the title accordingly.

**Comment by Fuco1** [comment]
We do not include packages. Maybe the readme is unclear in which case it should be updated.  Everything in SP is reimplemented from scratch, the listed packages just provide similar features but are incomplatible with one another.

**Comment by XQLRSZ** [comment]
Oh. I get it now. I was confused from the README. I didn't realize that you were reimplementing everything. I thought you were merging packages together.
