### ISSUE TITLE
Braces in Eshell aren't paired

### ISSUE THREAD

**Issue by joostkremers** [Fuco1/smartparens#467]
`eshell` uses braces (curly brackets, `{}`) for subprocesses and loops, e.g.:

    for i in {seq 10} {wget http://some.server/photo$i.jpg}

With `smartparens-mode` turned on, these aren’t paired, however. (That is, when I type the opening brace is the line above, the closing brace isn’t automatically added.) Since the default config does pair braces, they seem to be excluded specifically for `eshell`, though I haven’t been able to figure out where this happens.

Could this be a bug, or have I overlooked something in the configuration?

**Comment by Fuco1** [comment]
> `eshell` uses braces (curly brackets, `{}`) for subprocesses and loops, e.g.:
>
>     for i in {seq 10} {wget http://some.server/photo$i.jpg}
>
> With `smartparens-mode` turned on, these aren’t paired, however. (That is, when I type the opening brace is the line above, the closing brace isn’t automatically added.) Since the default config does pair braces, they seem to be excluded specifically for `eshell`, though I haven’t been able to figure out where this happens.
>
> Could this be a bug, or have I overlooked something in the configuration?

I'm a heavy eshell user myself and it works.

The problem is that eshell is a special buffer (mode-class special) and
smartparens ignores those buffers.  Are you sure the mode is on?  If you
only start SP as the global mode, it won't be enabled in eshell by
default.

**Comment by joostkremers** [comment]
Yes, I realised that shortly before you posted your reply. I disabled the mode line lighter for smartparens right after installing it, so I didn’t notice.

Sorry about the noise…

**Comment by Fuco1** [comment]
No worries, it's probably nowhere advertised anyway.  I updated the docstring to reflect this fact.
