### ISSUE TITLE
convenience keybindings

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#469]
I was a little surprised to see that the following keybindings must be set by the user:

```elisp
(define-key smartparens-mode-map (kbd "C-M-f") 'sp-forward-sexp)
(define-key smartparens-mode-map (kbd "C-M-b") 'sp-backward-sexp)
(define-key smartparens-mode-map (kbd "C-M-d") 'sp-down-sexp)
(define-key smartparens-mode-map (kbd "C-M-a") 'sp-backward-down-sexp)
(define-key smartparens-mode-map (kbd "C-S-d") 'sp-beginning-of-sexp)
(define-key smartparens-mode-map (kbd "C-S-a") 'sp-end-of-sexp)
(define-key smartparens-mode-map (kbd "C-M-e") 'sp-up-sexp)
(define-key smartparens-mode-map (kbd "C-M-u") 'sp-backward-up-sexp)
(define-key smartparens-mode-map (kbd "C-M-t") 'sp-transpose-sexp)
(define-key smartparens-mode-map (kbd "C-M-n") 'sp-next-sexp)
(define-key smartparens-mode-map (kbd "C-M-p") 'sp-previous-sexp)
(define-key smartparens-mode-map (kbd "C-M-k") 'sp-kill-sexp)
(define-key smartparens-mode-map (kbd "C-M-w") 'sp-copy-sexp)
(define-key smartparens-mode-map (kbd "M-<delete>") 'sp-unwrap-sexp)
(define-key smartparens-mode-map (kbd "M-<backspace>") 'sp-backward-unwrap-sexp)
```

I find it hard to believe that somebody would invoke `smartparens-mode` but **not** want to have the `sp-` variants of `sexp` navigation instead of the emacs defaults.

Can you please consider adding these in the `smartparens-config`, or perhaps bundle a `smartparents-defaults` so that these lines don't appear in every user's `init.el`? :smile:

**Comment by Fuco1** [comment]
You can call `sp-use-paredit-bindings` or `sp-use-smartparens-bindings` to set up bindings according to prefered style.  There is also a customize option which you can use.

**Comment by fommil** [comment]
great! How come you don't do that in your example config?
