### ISSUE TITLE
``'' in LaTeX mode doesn't work properly

### ISSUE THREAD

**Issue by mrkkrp** [Fuco1/smartparens#471]
I can't believe such an obvious bug exists, but nevertheless, \`\`'' thing doesn't work in LaTeX. How to reproduce:

```
emacs -Q

(package-initialize) ; to load the package
(require 'smartparens-config)
(smartparens-global-mode 1)
```

Now go to any LaTeX file and enter ". Actually \`\`' is entered! I guess it should be \`\`''. Maybe it has to do with auctex thing, because it has it has its own trickery to handle things like \`\`stuff''.

But after all I always disable this nasty conversion anyway, because entering quotes like “” is not a problem. So, I just wanted to disable the whole \`\`'' pair. Here is what I've got:

```
(advice-add 'TeX-insert-quote :filter-args (lambda (&rest stuff) '(t)))
;; ↑ disables ``'' magic in vanilla LaTeX mode, I've tried with and without
;; it, with this thing smartparens inserts ``''' — which is no better.

(sp-local-pair '(tex-mode plain-tex-mode latex-mode)
               "``" "''"
               :trigger "\""
               :unless '(sp-latex-point-after-backslash)
               :post-handlers '(sp-latex-skip-double-quote)
               :actions nil)
;; ↑ I've read documentation for ‘sp-local-pair’ and decided that this
;; should disable this thing, but it does so only when I manually evaluate
;; it after entering LaTeX mode, it doesn't work in config.
```

I really hope that I just don't understand something, otherwise I don't know what to think.

P.S. Emacs is compiled from repo a few days ago. smartparens is from MELPA.

**Comment by Fuco1** [comment]
You can think that emacs is a complex piece of software and interaction between various packages and built-in code is difficult to handle.

**Comment by mrkkrp** [comment]
> You can think that emacs is a complex piece of software and interaction between various packages and built-in code is difficult to handle.

@Fuco1, I didn't mean to offend you or something. I like smartparens, I think you've done a great job. But the way you answer feels condescending. If it's bug you could just say "we know about this bug", or "thanks for reporting this issue".

**Comment by Fuco1** [comment]
I didn't mean to offend you either, I just replied in the same style you did.

It used to work for me last time I used latex and so I missed this case in my test suite.  I've added a rule there to catch it in the future.

**Comment by mrkkrp** [comment]
@Fuco1, I'm really sorry if my post is offending. I've seen that you've written LaTeX-specific configuration yourself, so I concluded that you edit LaTeX source often and such a bug would be immediately noticed, so I decided that it's highly unlikely that it's really a bug.

**Comment by Fuco1** [comment]
Fair enough, I had a bad day today... maybe I was reading too much into it as well :)

Thanks for the heads up, I'll see what I can do.

As a temporary fix, you can remove the single `' pair, that will make it work (might or might be a solution for you, depending on your use ot latex quotes).

**Comment by mrkkrp** [comment]
Is my method of disabling the pair theoretically correct?

**Comment by Fuco1** [comment]
This configuration function is one of the areas which could really get improved... I quite hate it tbh.

What you do is theoretically correct but I probably simply ignore it when resolving the list of pairs for possible insertion ~_~.  If you put `:actions :rem` that should completely get rid of it inside latex mode.  See if that fixes the problem. `nil` should definitely have the same effect though (or at least, not listing `insert` as a possible action).

**Comment by Fuco1** [comment]
Right, the issue is that if the point is after two backticks and you have the single pair enabled, it thinks it should insert the closing ' for one of the openings.  If you have single and double pair enabled, it should prefer the longest prefix possible but it doesn't (here lies the bug).

So even if you disable the double quote, it still catches the single quote rule.  Meh.

**Comment by mrkkrp** [comment]
Just like `nil`, `(:rem)` disables this pair but only when I'm already in LaTeX mode, after manual (re?)evaluation. Anyway it's not really important or urgent right now, I'll just wait until it's fixed :)

**Comment by Fuco1** [comment]
Beware, not `(:rem)`, just `:rem` (yes, the syntax is silly.... `:rem` removes the pair entirely, `(:rem ...)` is used to remove settings inherited from the parent).  But as per the post above, that's not the issue here.

**Comment by mrkkrp** [comment]
Please note that:

1. When I put `:action :rem` into my config, it says

  > Wrong type argument: consp, nil

and Emacs fails (enters debugger) on startup.

2. Yes, it works if I evaluate it manually when I'm in LaTeX buffer. As an opinion, this is strange, normally there should be no difference *when* to evaluate the thing. For me this would be much more serious bug to fix.

**Comment by Fuco1** [comment]
> 1. When I put `:action :rem` into my config, it says

It should be `:actions`

**Comment by mrkkrp** [comment]
Oh, I'm really sorry, it's a typo, I don't have this typo in my config though, it's `:actions` there. Just rechecked it...

**Comment by rdiaz02** [comment]
In case it matters, using 1.6.3 does not show this bug. Is there any strong reason not to use 1.6.3 and use, instead, the MELPA version?

**Comment by Fuco1** [comment]
@rdiaz02 THe contrary, there is no good reason to use MELPA. The 1.6.3 release is considered "stable", whatever is on master might be broken in silly ways.

As I don't have as much time as I used to I fix bugs that somehow relate to my work as a priority, so things move slow now.

**Comment by rdiaz02** [comment]
@Fuco1 : thanks for the clarification. I'll use 1.6.3 then.

**Comment by Fuco1** [comment]
Possibly fixed in a40114d and 640c95d

**Comment by djr7C4** [comment]
It works now for me.

**Comment by mrkkrp** [comment]
Closing this, thanks @Fuco1 for fixing this.

**Comment by Fuco1** [comment]
Thanks both for confirmation
