### ISSUE TITLE
Putting point inside empty strings in python breaks w/ sp-navigate-consider-stringlike-sexp

### ISSUE THREAD

**Issue by jgarvin** [Fuco1/smartparens#473]
I like sp-navigate-consider-stringlike-sexp because it makes smartparens treatment of strings more consistent (e.g. without it on I can use sp-beginning-of-sexp to go to the front of a string, but I can't use sp-down-sexp to go into it). So I tried turning it on for python mode, running SP 1.6.3 and got the backtrace below. To reproduce enable smartparens-global-mode and show-smartparens-global-mode, make an empty foo.py file and just write a single double quote, which smartparens will match, putting point inside the double quote, and then the backtrace will appear.

I tried to test with marmelade 1.4, but it gave me a backtrace when I tried to do anything at all in any mode, I think maybe my settings are just too new for it. Then I tried melpa, the exact same steps reproduce but the backtrace was different, forgot to save it.

    Debugger entered--Lisp error: (wrong-type-argument characterp t)
    char-to-string(t)
    (let ((c (char-to-string (nth 3 (syntax-ppss pos))))) (cons c c))
    (save-excursion (let ((c (char-to-string (nth 3 (syntax-ppss pos))))) (cons c c)))
    (progn (save-excursion (let ((c (char-to-string (nth 3 (syntax-ppss pos))))) (cons c c))))
    (if (and (sp-point-in-string) (save-excursion (forward-char) (not (sp-point-in-string))) (save-excursion (backward-char) (not (sp-point-in-string)))) (progn (save-excursion (let ((c (char-to-string (nth 3 ...)))) (cons c c)))))
    sp-point-in-empty-string()
    (cond ((sp-point-in-empty-string) (sp-get-string nil)) (t (sp-skip-forward-to-symbol t nil t) (cond ((and (memq major-mode sp-navigate-consider-sgml-tags) (looking-at "<") (sp-get-sgml-tag))) ((and (sp--looking-at (sp--get-opening-regexp (sp--get-allowed-pair-list))) (not (sp--skip-match-p (match-string 0) (match-beginning 0) (match-end 0)))) (sp-get-sexp nil)) ((and (sp--looking-at (sp--get-closing-regexp (sp--get-allowed-pair-list))) (not (sp--skip-match-p (match-string 0) (match-beginning 0) (match-end 0)))) (sp-get-sexp nil)) ((eq (char-syntax (following-char)) 34) (sp-get-string nil)) ((and (memq major-mode sp-navigate-consider-stringlike-sexp) (and (sp--looking-at (sp--get-stringlike-regexp)) (not (sp--skip-match-p ... ... ...))) (sp-get-stringlike-expression nil))) (t (let* ((sym (sp-get-symbol nil)) (sym-string (and sym ...))) (if sym-string (progn (goto-char ...) (if ... ... sym))))))))
    (save-excursion (cond ((sp-point-in-empty-string) (sp-get-string nil)) (t (sp-skip-forward-to-symbol t nil t) (cond ((and (memq major-mode sp-navigate-consider-sgml-tags) (looking-at "<") (sp-get-sgml-tag))) ((and (sp--looking-at (sp--get-opening-regexp ...)) (not (sp--skip-match-p ... ... ...))) (sp-get-sexp nil)) ((and (sp--looking-at (sp--get-closing-regexp ...)) (not (sp--skip-match-p ... ... ...))) (sp-get-sexp nil)) ((eq (char-syntax (following-char)) 34) (sp-get-string nil)) ((and (memq major-mode sp-navigate-consider-stringlike-sexp) (and (sp--looking-at ...) (not ...)) (sp-get-stringlike-expression nil))) (t (let* ((sym ...) (sym-string ...)) (if sym-string (progn ... ...))))))))
    (if (not sp-navigate-consider-symbols) (sp-get-sexp nil) (save-excursion (cond ((sp-point-in-empty-string) (sp-get-string nil)) (t (sp-skip-forward-to-symbol t nil t) (cond ((and (memq major-mode sp-navigate-consider-sgml-tags) (looking-at "<") (sp-get-sgml-tag))) ((and (sp--looking-at ...) (not ...)) (sp-get-sexp nil)) ((and (sp--looking-at ...) (not ...)) (sp-get-sexp nil)) ((eq (char-syntax ...) 34) (sp-get-string nil)) ((and (memq major-mode sp-navigate-consider-stringlike-sexp) (and ... ...) (sp-get-stringlike-expression nil))) (t (let* (... ...) (if sym-string ...))))))))
    (if back (if (not sp-navigate-consider-symbols) (sp-get-sexp t) (save-excursion (cond ((sp-point-in-empty-string) (sp-get-string t)) (t (sp-skip-backward-to-symbol t nil t) (cond ((and ... ... ...)) ((and ... ...) (sp-get-sexp t)) ((and ... ...) (sp-get-sexp t)) ((eq ... 34) (sp-get-string t)) ((and ... ... ...)) (t (sp-get-symbol t))))))) (if (not sp-navigate-consider-symbols) (sp-get-sexp nil) (save-excursion (cond ((sp-point-in-empty-string) (sp-get-string nil)) (t (sp-skip-forward-to-symbol t nil t) (cond ((and ... ... ...)) ((and ... ...) (sp-get-sexp nil)) ((and ... ...) (sp-get-sexp nil)) ((eq ... 34) (sp-get-string nil)) ((and ... ... ...)) (t (let* ... ...))))))))
    (cond (sp-prefix-tag-object (sp-get-sgml-tag back)) (sp-prefix-pair-object (sp-get-paired-expression back)) (sp-prefix-symbol-object (sp-get-symbol back)) (t (if back (if (not sp-navigate-consider-symbols) (sp-get-sexp t) (save-excursion (cond ((sp-point-in-empty-string) (sp-get-string t)) (t (sp-skip-backward-to-symbol t nil t) (cond ... ... ... ... ... ...))))) (if (not sp-navigate-consider-symbols) (sp-get-sexp nil) (save-excursion (cond ((sp-point-in-empty-string) (sp-get-string nil)) (t (sp-skip-forward-to-symbol t nil t) (cond ... ... ... ... ... ...))))))))
    sp-get-thing()
    (let ((ok (sp-get-thing))) (if ok (let ((struct ok)) (sp-show--pair-create-overlays (plist-get struct :beg) (plist-get struct :end) (length (plist-get struct :op)) (length (plist-get struct :cl)))) (sp-show--pair-create-mismatch-overlay (point) (length match))))
    (lambda (match) (let ((ok (sp-get-thing))) (if ok (let ((struct ok)) (sp-show--pair-create-overlays (plist-get struct :beg) (plist-get struct :end) (length (plist-get struct :op)) (length (plist-get struct :cl)))) (sp-show--pair-create-mismatch-overlay (point) (length match)))))(#("\"" 0 1 (fontified t syntax-table (15) face font-lock-string-face)))
        funcall((lambda (match) (let ((ok (sp-get-thing))) (if ok (let ((struct ok)) (sp-show--pair-create-overlays (plist-get struct :beg) (plist-get struct :end) (length (plist-get struct :op)) (length (plist-get struct :cl)))) (sp-show--pair-create-mismatch-overlay (point) (length match))))) #("\"" 0 1 (fontified t syntax-table (15) face font-lock-string-face)))
                (cond ((and (not (sp--evil-normal-state-p)) (not (sp--evil-visual-state-p)) (sp--looking-back (if sp-show-pair-from-inside allowed closing))) (funcall --cl-create-backward-- (match-string 0))) ((or (sp--looking-at (if sp-show-pair-from-inside allowed opening)) (and (memq major-mode sp-navigate-consider-stringlike-sexp) (looking-at (sp--get-stringlike-regexp))) (and (memq major-mode sp-navigate-consider-sgml-tags) (looking-at "<"))) (funcall --cl-create-forward-- (match-string 0))) ((or (sp--looking-back (if sp-show-pair-from-inside allowed closing)) (and (memq major-mode sp-navigate-consider-stringlike-sexp) (sp--looking-back (sp--get-stringlike-regexp))) (and (memq major-mode sp-navigate-consider-sgml-tags) (sp--looking-back ">"))) (funcall --cl-create-backward-- (match-string 0))) (sp-show-pair-overlays (sp-show--pair-delete-overlays)))
                (let* ((pair-list (sp--get-allowed-pair-list)) (opening (sp--get-opening-regexp pair-list)) (closing (sp--get-closing-regexp pair-list)) (allowed (and sp-show-pair-from-inside (sp--get-allowed-regexp))) match) (cond ((and (not (sp--evil-normal-state-p)) (not (sp--evil-visual-state-p)) (sp--looking-back (if sp-show-pair-from-inside allowed closing))) (funcall --cl-create-backward-- (match-string 0))) ((or (sp--looking-at (if sp-show-pair-from-inside allowed opening)) (and (memq major-mode sp-navigate-consider-stringlike-sexp) (looking-at (sp--get-stringlike-regexp))) (and (memq major-mode sp-navigate-consider-sgml-tags) (looking-at "<"))) (funcall --cl-create-forward-- (match-string 0))) ((or (sp--looking-back (if sp-show-pair-from-inside allowed closing)) (and (memq major-mode sp-navigate-consider-stringlike-sexp) (sp--looking-back (sp--get-stringlike-regexp))) (and (memq major-mode sp-navigate-consider-sgml-tags) (sp--looking-back ">"))) (funcall --cl-create-backward-- (match-string 0))) (sp-show-pair-overlays (sp-show--pair-delete-overlays))))
                (let (--cl-create-forward-- --cl-create-backward--) (setq --cl-create-forward-- (function (lambda (match) (let ((ok (sp-get-thing))) (if ok (let (...) (sp-show--pair-create-overlays ... ... ... ...)) (sp-show--pair-create-mismatch-overlay (point) (length match))))))) (setq --cl-create-backward-- (function (lambda (match) (let ((ok (sp-get-thing t))) (if ok (let (...) (sp-show--pair-create-overlays ... ... ... ...)) (sp-show--pair-create-mismatch-overlay (- ... ...) (length match))))))) (let* ((pair-list (sp--get-allowed-pair-list)) (opening (sp--get-opening-regexp pair-list)) (closing (sp--get-closing-regexp pair-list)) (allowed (and sp-show-pair-from-inside (sp--get-allowed-regexp))) match) (cond ((and (not (sp--evil-normal-state-p)) (not (sp--evil-visual-state-p)) (sp--looking-back (if sp-show-pair-from-inside allowed closing))) (funcall --cl-create-backward-- (match-string 0))) ((or (sp--looking-at (if sp-show-pair-from-inside allowed opening)) (and (memq major-mode sp-navigate-consider-stringlike-sexp) (looking-at (sp--get-stringlike-regexp))) (and (memq major-mode sp-navigate-consider-sgml-tags) (looking-at "<"))) (funcall --cl-create-forward-- (match-string 0))) ((or (sp--looking-back (if sp-show-pair-from-inside allowed closing)) (and (memq major-mode sp-navigate-consider-stringlike-sexp) (sp--looking-back (sp--get-stringlike-regexp))) (and (memq major-mode sp-navigate-consider-sgml-tags) (sp--looking-back ">"))) (funcall --cl-create-backward-- (match-string 0))) (sp-show-pair-overlays (sp-show--pair-delete-overlays)))))
                (progn (let (--cl-create-forward-- --cl-create-backward--) (setq --cl-create-forward-- (function (lambda (match) (let ((ok ...)) (if ok (let ... ...) (sp-show--pair-create-mismatch-overlay ... ...)))))) (setq --cl-create-backward-- (function (lambda (match) (let ((ok ...)) (if ok (let ... ...) (sp-show--pair-create-mismatch-overlay ... ...)))))) (let* ((pair-list (sp--get-allowed-pair-list)) (opening (sp--get-opening-regexp pair-list)) (closing (sp--get-closing-regexp pair-list)) (allowed (and sp-show-pair-from-inside (sp--get-allowed-regexp))) match) (cond ((and (not (sp--evil-normal-state-p)) (not (sp--evil-visual-state-p)) (sp--looking-back (if sp-show-pair-from-inside allowed closing))) (funcall --cl-create-backward-- (match-string 0))) ((or (sp--looking-at (if sp-show-pair-from-inside allowed opening)) (and (memq major-mode sp-navigate-consider-stringlike-sexp) (looking-at ...)) (and (memq major-mode sp-navigate-consider-sgml-tags) (looking-at "<"))) (funcall --cl-create-forward-- (match-string 0))) ((or (sp--looking-back (if sp-show-pair-from-inside allowed closing)) (and (memq major-mode sp-navigate-consider-stringlike-sexp) (sp--looking-back ...)) (and (memq major-mode sp-navigate-consider-sgml-tags) (sp--looking-back ">"))) (funcall --cl-create-backward-- (match-string 0))) (sp-show-pair-overlays (sp-show--pair-delete-overlays))))))
                (unwind-protect (progn (let (--cl-create-forward-- --cl-create-backward--) (setq --cl-create-forward-- (function (lambda (match) (let (...) (if ok ... ...))))) (setq --cl-create-backward-- (function (lambda (match) (let (...) (if ok ... ...))))) (let* ((pair-list (sp--get-allowed-pair-list)) (opening (sp--get-opening-regexp pair-list)) (closing (sp--get-closing-regexp pair-list)) (allowed (and sp-show-pair-from-inside (sp--get-allowed-regexp))) match) (cond ((and (not ...) (not ...) (sp--looking-back ...)) (funcall --cl-create-backward-- (match-string 0))) ((or (sp--looking-at ...) (and ... ...) (and ... ...)) (funcall --cl-create-forward-- (match-string 0))) ((or (sp--looking-back ...) (and ... ...) (and ... ...)) (funcall --cl-create-backward-- (match-string 0))) (sp-show-pair-overlays (sp-show--pair-delete-overlays)))))) (set-match-data save-match-data-internal (quote evaporate)))
                (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let (--cl-create-forward-- --cl-create-backward--) (setq --cl-create-forward-- (function (lambda (match) (let ... ...)))) (setq --cl-create-backward-- (function (lambda (match) (let ... ...)))) (let* ((pair-list (sp--get-allowed-pair-list)) (opening (sp--get-opening-regexp pair-list)) (closing (sp--get-closing-regexp pair-list)) (allowed (and sp-show-pair-from-inside ...)) match) (cond ((and ... ... ...) (funcall --cl-create-backward-- ...)) ((or ... ... ...) (funcall --cl-create-forward-- ...)) ((or ... ... ...) (funcall --cl-create-backward-- ...)) (sp-show-pair-overlays (sp-show--pair-delete-overlays)))))) (set-match-data save-match-data-internal (quote evaporate))))
                (progn (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let (--cl-create-forward-- --cl-create-backward--) (setq --cl-create-forward-- (function (lambda ... ...))) (setq --cl-create-backward-- (function (lambda ... ...))) (let* ((pair-list ...) (opening ...) (closing ...) (allowed ...) match) (cond (... ...) (... ...) (... ...) (sp-show-pair-overlays ...))))) (set-match-data save-match-data-internal (quote evaporate)))))
                (if show-smartparens-mode (progn (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let (--cl-create-forward-- --cl-create-backward--) (setq --cl-create-forward-- (function ...)) (setq --cl-create-backward-- (function ...)) (let* (... ... ... ... match) (cond ... ... ... ...)))) (set-match-data save-match-data-internal (quote evaporate))))))
                sp-show--pair-function()
                apply(sp-show--pair-function nil)
                byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
                timer-event-handler([t 0 0 125000 t sp-show--pair-function nil idle 0])

**Comment by Fuco1** [comment]
I can't replicate this.  Do you still get this problem on the master?

**Comment by Wilfred** [comment]
Looking at the traceback, I believe this was fixed in https://github.com/Fuco1/smartparens/commit/a5f8692e055f7efbe856af224cfdf98accd35348.
