### ISSUE TITLE
sp-comment-string, docu-bug or other

### ISSUE THREAD

**Issue by andreas-roehler** [Fuco1/smartparens#478]
Docu says: "The value of `comment-start' is used if the major mode is not found."

However, AFAIK, comment-start is set by the major-mode, otherwise is empty.
Having a look across the code, seems some protection being needed here, i.e. if comment-start is not set, no way to deal with comments.

**Comment by Fuco1** [comment]
Example: emacs lisp mode sets `;` but I want to insert `;; ` when I press ;.  SP provides me this option.  If I don't specify anything special, it falls back to `comment-start`.  If that doesn't exist, it just prints the character.

**Comment by andreas-roehler** [comment]
Is it about customizing the comment start-string? Than write maybe "Customize comment-start" as docu?

**Comment by Fuco1** [comment]
No, it is not.

`comment-start` is language specific comment opening character. Emacs uses this for all sorts of things.

Smartparens can comment out (= prefix) a sexp with a sequence you give it in preference to `comment-start`.  This is not syntactic, rather a style choice. `comment-start` is syntactic.

**Comment by andreas-roehler** [comment]
I'm afraid can't follow. So let's close that, preserving your time.
