### ISSUE TITLE
extra padding when expanding braces in scala-mode

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#480]
X-posting to https://groups.google.com/d/msg/gnu.emacs.help/XYcrfOjDfKA/y5z_e6yLXXQJ but I'll extract the smartparens relevant parts here:

Let's say we start with this (point denoted by pipe) 

```
  blah | 
```

Type `{` and smart-parens will insert the closing brace 

```
  blah {|} 
```

I'd actually prefer it to be:

```
  blah { | } 
```

and what I'd **really** like is if I start with (i.e. no space after `blah`)

```
  blah|
```

and type `{` for three regions of space padding to be inserted so I end up with

```
  blah { | }
```

From there, I could newline if I wanted to construct a larger code block, but retaining the behaviour at the beginning incase I started with space padding.

**Comment by fommil** [comment]
RTFM :smile:

```
(sp-local-pair 'scala-mode "{" nil :post-handlers '(("||\n[i]" "RET") ("| " "SPC")))
```

does what I need. Absolutely awesome.

The only erk I have is that I have to set this when I load `smart-parens` mode, not as a `scala-mode-hook`, which would be nicer.

**Comment by Fuco1** [comment]
> The only erk I have is that I have to set this when I load
> `smart-parens` mode, not as a `scala-mode-hook`, which would be nicer.

Agreed, I have this as a feature I'd like to implement (using
"buffer-local" config) so you could throw it into mode hooks as other
config.

-- 
Best regards,
  Matúš Goljer

**Comment by fommil** [comment]
and while we're doing requests :smile: it would also be really nice if inheritance of modes was preserved.

e.g. this is my setup for c/java/scala

```elisp
            (sp-local-pair 'c-mode "(" nil :post-handlers '(("||\n[i]" "RET")))
            (sp-local-pair 'c-mode "{" nil :post-handlers '(("||\n[i]" "RET")))
            (sp-local-pair 'java-mode "(" nil :post-handlers '(("||\n[i]" "RET")))
            (sp-local-pair 'java-mode "{" nil :post-handlers '(("||\n[i]" "RET")))
            (sp-local-pair 'scala-mode "(" nil :post-handlers '(("||\n[i]" "RET")))
            (sp-local-pair 'scala-mode "{" nil :post-handlers '(("||\n[i]" "RET") ("| " "SPC")))
```

but obviously there is some room for `java-mode` and `scala-mode` to inherit from `c-mode` (I am pretty sure this is true as far as major modes go). But instead, I have to explicitly list everything again.
