### ISSUE TITLE
How to navigate balanced <> without declaring them as smart parens?

### ISSUE THREAD

**Issue by vspinu** [Fuco1/smartparens#485]
I want `sp-forward-sexp` to navigate on `<>` in C++ but I don't want to declare those as smart parens. What do I do? The native `forward-sexp` behaves as expected. 

Thanks.

**Comment by Fuco1** [comment]
Add the pair and only allow its `navigate` action.  See the wiki [permissions](https://github.com/Fuco1/smartparens/wiki/Permissions#actions).

**Comment by vspinu** [comment]
That was it! Thanks.
