### ISSUE TITLE
Problems with Emacs Lisp mode

### ISSUE THREAD

**Issue by mrkkrp** [Fuco1/smartparens#486]
Two things have ceased to work:

1. Quotes `'` are always inserted by pairs, in Lisp modes!

2. Backticks are inserted by pairs \`\`, previously \`' were inserted instead, I found the old behavior very useful.

I understand that MELPA version is supposed to be unstable, but since your package is available there and many people use only MELPA packages (not melpa stable), can you fix at least this? MELPA is supposed to be used by people too, after all. Better yet, create separate branch and keep unstable development there until it's usable, then merge it with master.

Thank you.

**Comment by Fuco1** [comment]
Did you set the pair not to autoinsert? If not, it will.

That code hasn't been touched in years.

**Comment by mrkkrp** [comment]
Oh, I'm sorry. Now I understand cause of this... I did some reorganization of my init files and forgot to require `smartparens-config` this time. I'm closing this.
