### ISSUE TITLE
Haskell pragmas fail search

### ISSUE THREAD

**Issue by rpglover64** [Fuco1/smartparens#487]
(Possibly related to #399)

To reproduce:

1. Open a new Haskell file
2. Type <kbd>{</kbd><kbd>-</kbd><kbd>#</kbd>
3. Notice that although the closing delimiter is inserted correctly, one or the other of the delimiters is highlighted in red and a "Search failed" message appears.

**Comment by Fuco1** [comment]
Yes indeed.  Thanks for confirming that this doesn't work with pragmas either.

I'll close this, if you have any more questions please ask in #399.

**Comment by Fuco1** [comment]
This should be fixed on the master.  The related issue also seems to be fixed.
