### ISSUE TITLE
sp-sexp-prefix seems broken

### ISSUE THREAD

**Issue by willghatch** [Fuco1/smartparens#488]
I've been working with racket lately, in which there are various syntax-quote/unquote prefixes:  <code>#' #` #, #,@</code>.  When I want to forward-slurp these, it will break up the # from the other character.  I read about the sp-sexp-prefix variable and set it to a regex to match "#,", but then sp-forward-slurp-sexp fails, giving the error message <code>Args out of range: #<buffer (current buffer)>, 0, 0</code>.  I note, however, that slurping these sorts of things in elisp mode works correctly, even when sp-sexp-prefix is nil, so perhaps I'm going about this the wrong way.  But either way, slurping is definitely not working when I customize sp-sexp-prefix.

**Comment by willghatch** [comment]
Probably worth noting here:  I'm using [racket-mode](https://github.com/greghendershott/racket-mode), which I set as the mode in the customization of sp-sexp-prefix.

**Comment by willghatch** [comment]
Also, I'm not sure what markdown is doing, but the error message is being garbled -- the first argument is being shown as just # but it should be the current buffer object.

**Comment by Fuco1** [comment]
You need to put the error message into backquotes, because the hash symbol introduces links to issues... in which case github thinks `<buffer ...` is an issue identifier.

`racket-mode` seems not to set the syntax classes for the prefix characters properly, that's why it doesn't work.  However, the regexp you set should override it.  Didn't you forget to escape some characters in the regexp or something like that? Emacs regexpses are rather weird in this respect.

**Comment by Fuco1** [comment]
Also, the regexp must match *all* the text up until the parens, so if you just set it to hash as you say in the first post (I somehow missed it when I wrote my first reply) it won't match the ticks, quotes, or @ and won't work.

**Comment by willghatch** [comment]
I put the buffer thing in html code tags, because in my comment I had a backquote in an example, so using backquotes would make things even worse.  And as far as I know markdown should treat backquotes and code tags equally.  At any rate, the regex I used was "#," with the comma included (in my first post I had another comma outside the quotes, which might have lead to some confusion).  [The docs](http://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Special.html#Regexp-Special) say that neither of those characters is special for regex, so no escaping should be necessary unless the docs are wrong.  So I did have a good regex, an it did match everything up to the paren -- the form I was testing on was something to the effect of `(form I wanted to slurp into) #,(form I wanted to slurp up)`.  So I think there is something up with smartparens.

However, I'm also perfectly happy to work with racket mode, though I know nothing about emacs' syntax classes and such.  How do the prefixes need to be set up, or what class do they need to be in?

Either way, thanks for all your work with this excellent package.  I enjoy smart-parens quite a bit.

**Comment by Fuco1** [comment]
Okey. I will try to install racket mode and test it to see what's going on.

**Comment by Fuco1** [comment]
So, this had nthing to do with racket, the bug was there all along.  It should be fixed now.

**Comment by Fuco1** [comment]
Btw, the regexp I tried for racket was 

    "#?[`',]@?"

I'm not sure if it catches everything (it doesn't have to be correct wrt grammar i.e. not matching more, but it must match all you want to treat as prefix).

I also discovered different bug but that will have to wait until I find time again.  Thanks again for reporting.

**Comment by willghatch** [comment]
Thanks!
