### ISSUE TITLE
consider shippable instead of travis?

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#489]
shippable.com let you use docker images instead of being bound by travis' setups. I was using them for a while, but I ended up opting for a self-hosted drone.io.

the `ensime/ensime:latest` docker image has emacs 24.{1,2,3,4,5} feel free to use! Although its running debian wheezy and the version of git is too old for magit so I might create some more images shortly (just for elisp, no JDK support)

**Comment by Fuco1** [comment]
Is there any advantage for me switching to such a setup? I don't know docker and I only need to mess with travis once every year or two when new emacs comes out.

**Comment by fommil** [comment]
You don't need to know docker if an image already exists. Would be cool if there was a kind of community Emacs testing image.

**Comment by Fuco1** [comment]
I don't oppose what you propose but I (still) don't understand the benefit.

If you want to make this happen and think it is worth while, please, I'm all for it.  Unfortunately, I'd rather use my very limited time to fight some of the bugs on my long list than setting up another CI.  The last release was 7 months ago, it's bout time I finished the 1.7 milestone :/

**Comment by fommil** [comment]
Hehe, that'd be nice. When I build an image I'll send you a PR.
