### ISSUE TITLE
sp-wrap-with-pair with re-indent

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#490]
I just created a binding "C-(" to `sp-wrap-with-pair` and it is absolutely fantastic!

It would be even better if the lines that have been wrapped were re-indented, can you think of an easy way to do that? If `sp-wrap-with-pair` returned the `point` positions I could do it as a step after, or should I use some utility to get the `point` of the parens at point after having inserted them?

**Comment by fommil** [comment]
not only is this documented, but it is exactly what `(sp-pair "(" ")" :wrap "C-(")` does! Doh! :smile:

**Comment by Fuco1** [comment]
For the future, all the `:wrap` option does is binds this 

```
`(lambda (&optional arg)
     (interactive \"P\")
     (sp-wrap-with-pair ,OPEN))
```

to the key you provided.

**Comment by fommil** [comment]
it also does the indentation, I noticed
