### ISSUE TITLE
 suboptimal failure mode of sp-backward-up-sexp

### ISSUE THREAD

**Issue by expez** [Fuco1/smartparens#492]
with point at the beginning of a buffer containing 

``` clj
(ns superstring.core-test
  )
```

and a bunch of commented out clojure code (eagerly awaiting a port to clojurescript) I run `sp-backward-up-sexp`. After waiting for around 10 seconds, while emacs appears to be hanging, sp moves point beyond a closing paren, 73% down the buffer, leaving `(point)` returning 19687.

I noticed this because `evil-smartparens` calls `sp-backward-up-sexp` programmatically, expecting it to return `nil` when it cannot move further backward up.

**Comment by Fuco1** [comment]
Can you give me some minimal example? I have a hard time visualising what is going on.

**Comment by expez** [comment]
https://gist.github.com/expez/27edb318dd1fb5f9136a

Put point at beginning of buffer and hit `sp-backward-up-sexp`.  I expected no movement of point and a return value of `nil`

**Comment by Fuco1** [comment]
I tried it now and I get an error, which when dismissed leaves the point at the beginning.  It should probably not error though.

**Comment by Fuco1** [comment]
This might have been fixed by bea02ee

**Comment by expez** [comment]
Problem persist

**Comment by Fuco1** [comment]
I'm trying to reporduce this but I can't.  I'm on the head.  Can you post some other buffer where it fails? I tried it on the paste above.

**Comment by expez** [comment]
@Fuco1 did you try the gist I posted?  That's what I used to reproduce the issue when I attempted to verify the fix.

**Comment by Fuco1** [comment]
> @Fuco1 did you try the gist I posted?  That's what I used to reproduce the issue when I attempted to verify the fix.

Yes, the one with about 500 lines.

**Comment by expez** [comment]
I can't reproduce this in fundamental mode, but if I enable `clojure-mode` I see it.  I suppose that's needed to identify comments etc correctly.

**Comment by Poquaruse** [comment]
I don't know whether to open a new bug report or add this one here.

Same problem happens in bibtex-mode:

1) type: "asdf asdf asdf() asdf"
2) do backward slurp in ()
3) end up with "asdf asdf (                  asdf) asdf"
4) similar problem with forward slurp...

Best regards

**Comment by expez** [comment]
@Poquaruse open a new issue

**Comment by Fuco1** [comment]
Any updates?  Maybe try to send me another buffer where you can reproduce this?  I still don't know what this is about :/

**Comment by expez** [comment]
Perhaps my previous comment was unclear.  I see it in the gist here: https://gist.github.com/expez/27edb318dd1fb5f9136a but only if I enable `clojure-mode`.  I suppose that's because `clojure-mode` determines what a comment is etc.

**Comment by Fuco1** [comment]
Yes, I also enabled clojure mode.

**Comment by Fuco1** [comment]
I tried to reproduce this from the initial description and what data is still available.  The gists don't exist anymore unfortunately.  I'm not getting any weird behaviour, so I'm going to close this for now.
