### ISSUE TITLE
sp-splice-sexp-killing-backward broken

### ISSUE THREAD

**Issue by benswift** [Fuco1/smartparens#495]
Used to work, until I updated this morning:

```scheme
(some-func|)
;; do sp-splice-sexp-killing-backward
;; result: delete whole sexp
```
Now, 
```scheme
(some-func|)
;; do sp-splice-sexp-killing-backward
;; result: 
(some-func
```

Emacs 24.5.1, OSX 10.10 (railwaycat emacs port)

**Comment by Fuco1** [comment]
what mode

**Comment by benswift** [comment]
I'm running `smartparens-20150811.1507` from MELPA.  I can reproduce the bug with a clean (`emacs -q`) emacs, only loading in the (required) `dash-20150804.1354` and `smartparens-20150811.1507` libs. 

I start SP with `M-x smartparens-mode`, and the problem manifests itself in the `*scratch*` buffer, and other lisp-derived modes as well (e.g. `scheme-mode`).

Hope that helps.  Sorry the last bug report was a bit short on details.
