### ISSUE TITLE
sp-unwrap-pair doesn't work on outer sexp when inside string

### ISSUE THREAD

**Issue by gsingh93** [Fuco1/smartparens#496]
If I'm working in a mode that's not in `sp-navigate-consider-stringlike-sexp`, then I'd expect calling `sp-unwrap-pair` to unwrap `(foo "b|ar")` to `foo "b|ar"` (`|` indicates point), but this doesn't work. Is my understand of this function wrong or is this the correct behavior? If this is the correct behavior, what do you think of modifying this behavior to what I expected?

**Comment by Fuco1** [comment]
You forgot to say what actually happens though.

**Comment by gsingh93** [comment]
Oops. Nothing happens.

**Comment by Fuco1** [comment]
Right.  That sounds like a bug indeed.

**Comment by Fuco1** [comment]
So, your mode probably defines `""` as syntactic strings in which case there's not much to do.  Please check if that's the case:

1.  put point on `"`.
2. hit `C-u C-x =`
3. look for `syntax:` field and tell me what it says.

If it says "string" then we're out of luck---it would be very disruptive to override this and I'm not likely to going to do that.

The setting `sp-navigate-consider-stringlike-sexp` will probably get removed too in soon future and the navigation will be controled by adding or removing that action from the pair.

**Comment by Fuco1** [comment]
The setting was removed in 1.8.  Syntactic strings are always expressions and this can not be changed.  "Semantic" strings like `$` in latex or `*` in markdown can be disabled by removing the navigate action.
