### ISSUE TITLE
Unable to do slurp 

### ISSUE THREAD

**Issue by turbopape** [Fuco1/smartparens#497]
When I try to slurp something, emacs gives me the following error:
forward-sexp: Scan error: "Containing expression ends prematurely", 1083, 1084
GNU Emacs 25.0.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.14.13) of 2015-08-23, using Latest Cider 
Ubuntu 15.04

**Comment by Fuco1** [comment]
There is not a single mention of `forward-sexp` in the smartparens source code.  Are you sure you aren't using paredit?

**Comment by turbopape** [comment]
No, there is only SP shown on my status bar...

**Comment by Fuco1** [comment]
Try to provide a MWE then, thanks.

**Comment by turbopape** [comment]
And what is an MWE? Plz excuse my noobness:)

**Comment by Fuco1** [comment]
Minimal working example, an example of a buffer where I can reproduce the problem without all the irrelevant content.

**Comment by turbopape** [comment]
OK. 
As I'm showing in the next screenshot, If I try to slurp 'a' , it gives me the error.
Notice that there's no paredit in my modeline.
![emacs-impossible-slurp](https://cloud.githubusercontent.com/assets/2779167/9467473/e424415a-4b33-11e5-9dd2-65a02da2d62c.png)

**Comment by Fuco1** [comment]
Protip: when someone asks for an example, try not to give a screenshot.  If it weren't 3 characters I woudn't bother retyping it into my emacs :)

So now, check what is called when you invoke slurp.  SP doesn't use the built-in parser at all so I really don't think this is coming from here.  Use `C-h k` and then do the slurp keybinding, it will pop up a window with description of the command called.

If it indeed is SP then it is most peculiar and I'll have to dig deeper.

**Comment by turbopape** [comment]
I've done as you said and noticed that it was some vanilla emacs function
that was triggered by my key. And then I had the idea to see what
smartparens base keybinding I was using, to notice that fir an unknown
reason it has changed to "no default" . After I fixed that, everything
worked great again.

Thank you for Your time and excuse the obscure configuration change that
messed things up:)

**Comment by Fuco1** [comment]
Great, I'm happy we sorted it out :)
