### ISSUE TITLE
Cannot activate pair with shortcut

### ISSUE THREAD

**Issue by legendre6891** [Fuco1/smartparens#498]
According to the manual, I put the following

`(sp-local-pair 'org-mode "\\\\left(" "\\\\right)" :insert "C-b l" :trigger "\\\\l(")`

in my configuration file. But pressing `C-b l` does nothing (as if no key was pressed). Doing `C-h k C-b l` shows the following:

````
C-b l runs the command (lambda nil (interactive) (sp-insert-pair
"\\\\left(")), which is an interactive Lisp function.

It is bound to C-b l.

(anonymous)

Not documented.

[back]
````

However, the following works; insert the following text (the `|` denotes the cursor position):
`\\left(|`, then press `C-b l`. The end result is `\\left(\\left(\\right)`. 

I can confirm that this bug is reproducible with a minimal `init.el` consisting only of
````
(package-initialize)
````
The package version (the folder name of the package as downloaded) is `20150813.1451`.

(As a side note, `\\left( \\right)` is incorrect -- there should only be one backslash.)

**Comment by Fuco1** [comment]
If your pair is `"\\\\left("` you will have two backslashes.

The bug is a bug though. Thanks for reporting.

**Comment by legendre6891** [comment]
Thanks for confirming. 

Just wanted to point out that
`(sp-local-pair 'LaTeX-mode "\\\\left(" "\\\\right)" :insert "C-b l" :trigger "\\\\l(")` is verbatim from the manual [here](https://github.com/Fuco1/smartparens/wiki/Pair-management); it should probably just be `(sp-local-pair 'org-mode "\\left(" "\\right)" :insert "C-b l" :trigger "\\l(")`.

**Comment by Fuco1** [comment]
Unfortunately, that's due to stupid github wiki rendering... I reckon they fixed/changed it somehow.  I used to have troubles with quotes on a daily basis.  Thanks for reporting that as well :)
