### ISSUE TITLE
show-smartparens-mode inconsistent on closing parens

### ISSUE THREAD

**Issue by darkfeline** [Fuco1/smartparens#499]
show-smartparens-mode behavior is inconsistent on closing parens.

On opening parens:

    *    *
    ((()))
    ^

When the cursor is at the caret, the two starred parens are highlighted, but for closing parens it does this:

     *  *
    ((()))
         ^

In constrast show-paren-mode does the following which is more intuitive:

    *    *
    ((()))
         ^

**Comment by Fuco1** [comment]
Cursor is never at character in emacs, and parens aren't highlighted from inside.

If you use evil this is somehow bastardized to simulate vim behaviour, and evil might include support for show-paren-mode to bastardize it as well.

**Comment by Fuco1** [comment]
You might want to try setting `sp-show-pair-from-inside` to `t`, I recall we added it to handle some evil issues.

**Comment by darkfeline** [comment]
>Cursor is never at character in emacs

That's just a semantic issue as far as I'm concerned, sort of like arguing whether an array index points to an array element or to the gap between two array elements.

>If you use evil this is somehow bastardized to simulate vim behaviour, and evil might include support for show-paren-mode to bastardize it as well.

Sorry, I thought that was default behavior for `show-paren-mode`.

>You might want to try setting sp-show-pair-from-inside to t, I recall we added it to handle some evil issues.

Thanks, that fixes it nicely.

**Comment by Fuco1** [comment]
> That's just a semantic issue

Every issue ever is a semantic issue, that's what the word means. 

> as far as I'm concerned

As far as majority of people in emacs are concerned, point before `)` is inside the list, that's how emacs is (and you can test this with the built-in parser and all related tools).  This is an issue of what is the convention and how we stick to it.
