### ISSUE TITLE
Allow customization of position of cursor in sp-wrap--finalize

### ISSUE THREAD

**Issue by IvanMalison** [Fuco1/smartparens#501]

**Comment by Fuco1** [comment]
To get the current position, use `(point)`.

**Comment by IvanMalison** [comment]
> To get the current position, use (point).

Hah, sorry - accidentally pressed enter before I was done making the issue.

**Comment by Fuco1** [comment]
Would you be ok with behaviour described in #311 ?

**Comment by Fuco1** [comment]
See also #508
