### ISSUE TITLE
No matching parens with geiser/quack

### ISSUE THREAD

**Issue by vikraman** [Fuco1/smartparens#502]
When using geiser/quack, `(` gets bound to
`quack-insert-opening-paren` which inserts the `"("` but smartparens
doesn't insert the matching `")"`.

**Comment by Fuco1** [comment]
Try adding `quack-insert-opening-paren` to `sp--special-self-insert-commands`.

**Comment by vikraman** [comment]
Thank you, that works as expected. I have also sent a PR.
