### ISSUE TITLE
sp-transpose-sexp

### ISSUE THREAD

**Issue by 3246251196** [Fuco1/smartparens#503]
What is different from transpose-sexp ?

I concede that I have not read the documentation, but I just tried this on a whim expecting this sort of thing to be available with this package.

If I have

if ( SomeNamespace::SomeSymbol == [A]notherSymbol )

where the cursor is at [A] and then run sp-transpose-sexp I get the result (as I do with built-in transpose-sexp)

if ( SomeNamespace::AnotherSymbol == SomeSymbol )

when I really want:

if ( someSymbol == SomeNamespace::SomeSymbol )

**Comment by Fuco1** [comment]
`SomeNamespace::AnotherSymbol` is not a sexp so it doesn't work, nor it should.  If you want that you need to set `:` to be symbol constituent.

What is different is that `sp-transpose-sexp` supports user pairs while the built-in version doesn't.

**Comment by 3246251196** [comment]
Hi, thank you for the correction. So,

Is there no way to add an option for this?

if ( ( SomeNamespace::SomeSymbol ) == ( AnotherSymbol) ) - works, since they are now two sexps?

**Comment by Fuco1** [comment]
There is no way to do this without modifying syntax tables.  You can learn about syntax tables in the emacs info manual.
