### ISSUE TITLE
sp-get-paired-expression gets confused by pairs inside strings

### ISSUE THREAD

**Issue by luxbock** [Fuco1/smartparens#505]
I believe this and #367 might be duplicates, but I wasn't sure so I created a new issue.

The most minimal case I can come up with is this:

```emacs-lisp
(foo (bar "foo("))
```
With point on `bar`, calling `(sp-get-paired-expression)` thinks that the we are dealing with the outer list instead. If I insert a space after the string then it returns the object for the `bar` list just fine.

I can fix this by removing the `1+` of `(cdr bounds)` from here:

https://github.com/Fuco1/smartparens/blob/044ea99cc51d71b6a6d27d100657ff178fcfc6ee/smartparens.el#L3696

...but I don't know if it would break something else. I assume it is there for a reason?

**Comment by Fuco1** [comment]
Uhm... I don't know why the `1+` is there... some time in the past the behaviour was inconsistent between some comment handling functions getting +/- 1 differences... I tried to make it consistent and probably forgot to update the code there.  I'll need to look at it more.

**Comment by Fuco1** [comment]
I've removed the +/- 1 and fixed a bunch of other annoying edge cases... there are also tests for this now so if you catch some more don't hesitate to post the broken cases so we can add them to the test suite.

**Comment by luxbock** [comment]
Thanks! Will do.
