### ISSUE TITLE
Can't get autoescape working

### ISSUE THREAD

**Issue by expez** [Fuco1/smartparens#506]
E.g. in elisp mode

```
"my |string"
```

If I now hit <kbd>"</kbd> I get:

```
"my "|"string"
```

`sp-autoescape-string-quote` is `t`.

What am I doing wrong here?

**Comment by Fuco1** [comment]
This was removed in master, even if some settings are left there (they should be removed too).  The old autoescape system was so bad (and, worse, hardcoded) it's better to have it removed.

In the future, it should be implemented as a hook on some insert/wrap action so we can change it based on mode or user preference.

**Comment by expez** [comment]
The section on [autoescaping](https://github.com/Fuco1/smartparens/wiki/Automatic-escaping) is also slightly misleading until this is re-implemented.

**Comment by Wilfred** [comment]
I've added a note to the wiki page.
