### ISSUE TITLE
Jump to begin of region

### ISSUE THREAD

**Issue by Pitometsu** [Fuco1/smartparens#508]
Can it be configured to use `(` for wrap & jump to begin and `)` for wrap and jump to end of region?

**Comment by Fuco1** [comment]
See comment in #311.

**Comment by Fuco1** [comment]
Actually, this is already implemented in the master :D (see 75ed703)

**Comment by Pitometsu** [comment]
Cool, thanks a lot!

**Comment by Fuco1** [comment]
Hmm, true, it only obeys the closing one.

Well okey then, reopening again. Sorry for all the spam.

**Comment by Fuco1** [comment]
See `sp-wrap-respect-direction`.

**Comment by Pitometsu** [comment]
With that option enabled all right! But if it disabled, it still jump on closing only. It's ok for me, but is it correct behavior?

**Comment by Pitometsu** [comment]
And many thanks for this feature! I was waiting for this for a long time!!!

**Comment by Fuco1** [comment]
Well if it behaved the same there wouldn't be any need for the option :)

I actually prefer the current behaviour where the opening paren stays wherever it was before I wrapped.  Most of the time I use `sp-select-*-thing` and then hit `[` and it does the right thing (being before or after the thing).

**Comment by Pitometsu** [comment]
I just suggest that maybe you would not prefer jumping on closing as well. But if it's ok for you, so, it's okay :)

**Comment by Fuco1** [comment]
Right.  It somehow makes sense to me that if I deliberatly go for the closing one it should jump to end, but not so with the opening one.  I guess I could extend the option for third option where it would always stay wherever it was no matter what delimiter you use, but in practice I don't see much value in that.

If someone asks we can add it later.

Thanks for all the feedback.
