### ISSUE TITLE
(sp-get-paired-expression 'back) gets stuck after haskell pragmas

### ISSUE THREAD

**Issue by unhammer** [Fuco1/smartparens#510]
If I put this into debug.el:
    
    (add-to-list 'load-path "~/.emacs.d/elpa/smartparens-20151007.1331")
    (add-to-list 'load-path "~/.emacs.d/elpa/dash-20151006.221")
    (add-to-list 'load-path "~/.emacs.d/elpa/haskell-mode-20151003.0")
    
    (require 'smartparens)
    (require 'smartparens-haskell) ; or don't, doesn't matter
    (require 'haskell)
    (smartparens-global-mode)
    
and this into Main.hs:

    {-# LANGUAGE OverloadedStrings #-}
    
    module Main where
    
    main = putStr "hi"
    
and run `emacs -Q -l debug.el Main.hs`, and put point on line 3 (the empty line before `module Main`) and do `M-: (sp-get-paired-expression 'back) RET` then emacs gets stuck until I `C-g`

(Basically, this means I have to use regular kill-sexp to delete pragma lines, can't use the sp functions.)

**Comment by Fuco1** [comment]
This was probably fixed in 9b4dcc1.  Note that when the context around the point is `code` the comments are ignored, so in your case the returned value is now `nil` which is correct.  When you put your cursor before the pragma line the context changes to `comment` and the pragma sexp is returned.

**Comment by unhammer** [comment]
that seems to work now :-)
