### ISSUE TITLE
 sp-region-ok gives nil on haskell pragmas

### ISSUE THREAD

**Issue by unhammer** [Fuco1/smartparens#511]
Assuming `beg` and `end` covers a pragma like`{-# LANGUAGE ScopedTypeVariables       #-}`
in a haskell-mode buffer, where smartparens-haskell has set `"{-#" "#-}"` as a pair in haskell-mode, a `(sp-region-ok beg end)` call gives nil.

Originally posted as https://github.com/expez/evil-smartparens/issues/26
since it doesn't seem to affect smartparens itself, but it does affect evil-smartparens operations (and I don't know if sp-region-ok is meant to be used outside smartparens itself).

**Comment by Fuco1** [comment]
I'll put this on @expez as he wrote that function.

From what I can see the fix seems to be to check the context of closing delimiter at its start (that is, inside end of the sexp).
