### ISSUE TITLE
Don't treat ' as a delimiter in rust-mode

### ISSUE THREAD

**Issue by Wilfred** [Fuco1/smartparens#512]
In rust, lifetime specifiers look like this: `'foo`. Whilst it's also possible to use `'` for single characters, e.g. `'h'`, lifetime specifiers are more common.

**Comment by Fuco1** [comment]
Is there some heuristic we could follow?  How does the rust parser know what is going on?

**Comment by Wilfred** [comment]
I don't know how the parser handles it exactly.

Here's an example from [the docs](https://doc.rust-lang.org/book/lifetimes.html):

```rust
fn x_or_y<'a, 'b>(x: &'a str, y: &'b str) -> &'a str {
```

A good heuristic might be if the `'` occurs directly after a `<` or a `&`. This would cover a large number of use cases. You could even use `syntax-ppss` to see if point is enclosed in a `<...>` and that would cover all the cases I can think of (looking at a few larger Rust projects I have checked out).

**Comment by Fuco1** [comment]
Do you want to provide a patch?

**Comment by Fuco1** [comment]
Any updates?

**Comment by Wilfred** [comment]
I'm still planning on sending a PR.

**Comment by Fuco1** [comment]
Thanks.  No worries, I was just doing a fall-cleanup :)
