### ISSUE TITLE
sp-show-pair-match-face should inherit from show-paren-match

### ISSUE THREAD

**Issue by justmytwospence** [Fuco1/smartparens#516]
I could have sworn that it used to work this way - did it change for some reason? Same fo sp-show-pair-mismatch-face.

**Comment by Fuco1** [comment]
If it changed that's probably a bug, I remember someone making a PR for this... (although it might have been other faces).

If @show-paren-match@ and co is still built-in I see no reason not to have it inherit.  Do you want to write a patch? :)
