### ISSUE TITLE
Disable ` pair in racket-mode

### ISSUE THREAD

**Issue by vikraman** [Fuco1/smartparens#518]
How do I prevent \` from turning into \`\` in `racket-mode`? I have tried adding it to `sp--lisp-modes` but that doesn't help.

**Comment by Fuco1** [comment]
Redefine the pair locally https://github.com/Fuco1/smartparens/wiki/Pair-management#local-pair-definitions

and set its actions to nil

**Comment by vikraman** [comment]
Thanks.
