### ISSUE TITLE
$ pairing doesn't work in LaTeX

### ISSUE THREAD

**Issue by djr7C4** [Fuco1/smartparens#521]
I am running Emacs 24.5 with -Q.

After starting the current version of smartparens installed from mepla (20151025.833) in an empty .tex file with LaTeX-mode active and starting smartparens-mode, when "$" is pressed, a matching closing "$" is not added.  Oddly, other delimiters such as "\(" automatically pair with "\)" in LaTeX-mode as one would expect.

**Comment by Fuco1** [comment]
Works for me.  Any other specifics you can think of?

**Comment by djr7C4** [comment]
This was my mistake.  It turned out that it failed due to incompatibility with another package, and I had the same problem with "emacs -Q" because I forgot to load "smartparens-config.el" after starting emacs without the config file.

Thanks for looking into it and sorry for the noise.

**Comment by Fuco1** [comment]
So we can close?
