### ISSUE TITLE
Don't change indentation when deleting words/symbols

### ISSUE THREAD

**Issue by Wilfred** [Fuco1/smartparens#529]
Consider the code:

```python
def foo():
    if bar:
        baz()
    quuz = biz.boz|
```

`sp-backward-kill-word` and `sp-backward-kill-symbol` in `python-mode` both produce:

```python
def foo():
    if bar:
        baz()
        quuz = biz.|
```

This doesn't seem to occur for other whitespace sensitive languages (e.g. coffeescript).

**Comment by Fuco1** [comment]
This behaviour is biting me all over... it seems emacs can only reindent reasonably in lisps :D

See #403 and #522.

**Comment by Wilfred** [comment]
It's nice that smartparens tries to reindent, so all editing operations end up with code that's correctly indented. However in any language that lacks explicit close delimeters (python, haskell, coffeescript, yaml) there are multiple possible indentations. For these languages, it's probably better to avoid changing indentation.

**Comment by Wilfred** [comment]
Aha, and smartparens already has configuration for this. I've sent a PR with a unit test.
