### ISSUE TITLE
Incorrect condition in sp--wrap-repeat-last

### ISSUE THREAD

**Issue by pronobis** [Fuco1/smartparens#530]
There seems to be an incorrect condition in `sp--wrap-repeat-last`:

            (and
               (cond
                ((= 1 sp-wrap-repeat-last)
                 (equal (car active-pair) op))
                (= 2 sp-wrap-repeat-last))
               (memq sp-last-operation '(sp-self-insert sp-wrap-region))
               (or (= (point) (+ b oplen acolen))
                   (= (point) e)))

Inside `cond`, either brackets are missing or it should become `or` and `and`.
This results in errors when `sp-wrap-repeat-last==2`

**Comment by Fuco1** [comment]
Are you getting "void variable =" error?

**Comment by Fuco1** [comment]
Yep, missing parens.  See the commit message :)

Thanks!

**Comment by pronobis** [comment]
:-) Thanks!
