### ISSUE TITLE
Re-wrapping not working for a custom local pair 

### ISSUE THREAD

**Issue by pronobis** [Fuco1/smartparens#531]
I have the following definition of a local pair:
`(sp-local-pair "*" "*" :actions '(wrap) :wrap "M-*")`

which works well, as long as `*` is pressed once. However, despite `sp-wrap-repeat-last` being set to 1, I cannot re-wrap the word by pressing `*` another time as it normally works e.g. for `(`.

**Comment by Fuco1** [comment]
Yea, this is related to another issue I discovered recently when trying to fix a long opened issue with markdown.  Currently impossible to have that I'm afraid :(  I'm trying to think up a solution, it's pretty fundamenal issue.

**Comment by pronobis** [comment]
Sure, no big deal. That's more of an extra feature anyways.
