### ISSUE TITLE
sp-slurp-hybrid-sexp should not surround punctuation

### ISSUE THREAD

**Issue by Wilfred** [Fuco1/smartparens#534]
Given the JS:

```js
var foo = |baz;
```

I want to wrap `baz` in a call to `bar`. I type `bar(` and get:

```js
var foo = bar(|)baz;
```

I now call `sp-slurp-hybrid-sexp`:

```js
var foo = bar(|baz;)
```

whereas I wanted:

```js
var foo = bar(|baz);
```

A similar issues occurs in Python with `for i in len()foo.bar:` to `for i in len(foo.bar:)`.

**Comment by Fuco1** [comment]
Does #379 help?

**Comment by Wilfred** [comment]
Thanks, that looks relevant. I see this issue occurs in c-mode too.
