### ISSUE TITLE
sp-next-sexp alternative fallback

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#541]
"If there is no next expression at current level, jump one level up (effectively doing `sp-backward-up-sexp`)."

I'm not too keen on this fallback behaviour, what do you think about changing it to:

"If there is no next expression at the current level, jump one level up and retry." (which would have the effect of going to the next s-exp at whatever level has one)

**Comment by Fuco1** [comment]
So you mean `(foo |) (bar)` -> `(foo) |(bar)`.

What we get now is one more step `(foo |) (bar)` -> `|(foo) (bar)` -> `(foo) |(bar)`.

I wouldn't change the default but I think we could add a defcustom to change it.

However this would be a problem if the function is used from code.  Since it wasn't prohibited someone might've used it in elisp and now changing the behaviour will break other code seemingly randomly.

**Comment by fommil** [comment]
ah, good point.

**Comment by fommil** [comment]
any plans on the defcustom for this?

**Comment by Fuco1** [comment]
This would need to be implemented in such a way that the defcustom would only be considered when the function is called interactively.

I'm adding an enhancement tag, but it is somewhat low priority for me.  I'm happy to assist anyone in implementing it though.

**Comment by fommil** [comment]
I might have time sporadically over the holiday period. Should I just start by looking in this function or is it all implemented elsewhere?

**Comment by Fuco1** [comment]
It's implemented using `sp-forward-sexp` and the logic seems rather
simple, though I don't immediately understand the point of "true" branch
after `(= arg 1)` condition.  But it is all implemented in `sp-next-sexp`. 

> I might have time sporadically over the holiday period. Should I just start by looking in this function or is it all implemented elsewhere?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Fuco1/smartparens/issues/541#issuecomment-167249974

-- 
Best regards,
  Matúš Goljer

**Comment by fommil** [comment]
Done it in my branch, working on the `previous` variant too, as it doesn't DWIM.

**Comment by Fuco1** [comment]
Implemented in 40eccef
