### ISSUE TITLE
Error running timer `sp-show--pair-function'

### ISSUE THREAD

**Issue by smendozabarrera** [Fuco1/smartparens#542]
Good morning, since a couple of weeks this error message appear when I load an html5 file with web-mode + smartparents

Error running timer `sp-show--pair-function': (void-function my/sp-web-mode-is-code-context)

I search in internet but without results. Using prelude as framework for Emacs GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)  of 2015-04-10 on builder10-9.porkrind.org

Best!

**Comment by Fuco1** [comment]
You are missing a function `my/sp-web-mode-is-code-context`.  Having a prefix `my` this clearly belongs either to you, your config or prelude.  This is hardly something I could fix.

**Comment by smendozabarrera** [comment]
*Good morning,*
I agree with you, thank you so much anyway, and thank you for this great
package!


*best!*
*Sergio*




*-- BizLand*


*#Hacking #entrepreneurship*
*http://www.bizland.biz <http://www.bizland.biz>*







*Dreams matterMéxico 2015.--Aviso de Privacidad:*



*En cumplimiento a lo previsto en la Ley Federal de Proteccion de Datos
Personales en Posesión de los Particulares (en lo sucesivo “la Ley”), nos
permitimos informarle lo siguiente:http://www.bizland.biz/avisoprivacidad
<http://www.bizland.biz/avisoprivacidad> (Texto intencionalmente sin
acentos) La informacion contenida en este correo electronico es
privilegiada y confidencial y para uso exclusivo de los destinatarios de la
misma y/o de quienes hayan sido autorizados especificamente para leerla.Si
usted ha recibido este correo electronico por error, favor de destruirlo y
notificarlo al remitente a la direccion electronica indicada. Cualquier
divulgacion, distribucion o reproduccion no autorizada de este comunicado
esta estrictamente prohibida y sujeta a las sanciones establecidas en las
leyes correspondientes.*

*EOF*

**Comment by Fuco1** [comment]
Thanks for the update.
