### ISSUE TITLE
Pair is inserted in overwrite-mode

### ISSUE THREAD

**Issue by wasamasa** [Fuco1/smartparens#549]
I'm editing some Python code and want to replace `""` with `''`, so I go the lazy way, position point before the quotes, enter `overwrite-mode` and type `''`.  This does insert a new pair though...

Positioning point:

```
foo = |""
```

Entering `overwrite-mode`:

```
foo = █""
```

Typing the first `'`:

```
foo = '█'"
```

Typing the second `'`:

```
foo = ''█'"
```

Expected result:

```
foo = ''█
```

In other words, inserting pairs in `overwrite-mode` shouldn't happen.

**Comment by Silex** [comment]
There's `sp-rewrap-sexp` to rewrap from any of `{["'` to anything

**Comment by wasamasa** [comment]
Oh, sure, I'd have used `surround-change` weren't it utterly broken, but my point is that doing this differently has exposed an oversight in Smartparens.  I'll leave the final judgement to @Fuco1 though.

**Comment by Wilfred** [comment]
I think the sensible behaviour would be to still insert the matching item, but overwriting the current character. Do you agree @wasamasa?

**Comment by wasamasa** [comment]
@Wilfred Would that result in more characters than before or overwrite a pair of characters?

**Comment by Wilfred** [comment]
This is what I'd expect:

    foo = |""

Entering `overwrite-mode`:

    foo = █""

Typing the first `'`:

    foo = ''█

**Comment by Fuco1** [comment]
I haven't even known overwrite mode exists.  This seems like a feature that could go totally bonkers and the ROI is quite minimal, no?

**Comment by wasamasa** [comment]
Very much so.  I thought of just inhibiting pair insertion trickery if `overwrite-mode` is truthy.  @Wilfred's suggestion would make for a more satisfying, but harder to implement solution.

**Comment by Fuco1** [comment]
Well that *should* happen... as soon as SP sees there's a `'` after the cursor it inserts the matching `'`.  The only problem now is that that insertion should delete that many characters from up front.
