### ISSUE TITLE
Incorrect paren deleted in python-mode with smartparens-strict-mode

### ISSUE THREAD

**Issue by Wilfred** [Fuco1/smartparens#552]
```python
return foo(bar, lambda x: baz(x))|
```

Pressing backspace will remove the end paren, leaving the parens unbalanced.

**Comment by Fuco1** [comment]
`python-mode` binds backspace to `python-indent-dedent-line-backspace`, I'm not sure what to do with this... it does its own magic, if we simply remap to `sp-backward-delete-char` the python specific stuff stops working.

If we want to handle this properly we would probably need to reimplement the `python-mode` function in sp-aware way.

**Comment by PythonNut** [comment]
As far as I can tell, the python magic purely involves whitespace so it should be safe to let one wrap the other. The following seems to behave correctly:

```emacs
;; We're luck that sp-backward-delete-char does not use delete-backwards-char.
;; Otherwise, we'd have some nasty recursion issues.
(defun sp/python-indent-dedent-line-backspace (old-fun &rest args)
  (cl-letf (((symbol-function 'delete-backward-char)
             (lambda (arg &optional killp)
               (sp-backward-delete-char arg))))
    (apply old-fun args)))

(advice-add 'python-indent-dedent-line-backspace
            :around
            #'sp/python-indent-dedent-line-backspace)
```

Not sure how to integrate this cleanly into `smartparens-python.el`, though.

**Comment by Fuco1** [comment]
We would also need to support emacsen without the new advice system.

**Comment by PythonNut** [comment]
@Fuco1 of course. I don't know if you want to use the old advice system, or just make your own wrapper. I can't tell which technique you favor.

**Comment by Fuco1** [comment]
I think I prefer advice on the python function, at least that way it shows in the documentation that something is going on.  I think it would be awesomly difficult to make the rebinding work correctly depending on what mode/buffer you're in.

Do you want to submit a PR?

**Comment by PythonNut** [comment]
Sure. I'll try to get it in as soon as I have a free moment.
