### ISSUE TITLE
turn-off-smartparens-mode has no effect when called via mode hooks

### ISSUE THREAD

**Issue by lmichelbacher** [Fuco1/smartparens#553]
I have 

     (smartparens-global-strict-mode)

in my `.emacs` to use SP in all modes.

However, in Emacs Lisp modes, I don’t want to use SP so I added

    (add-hook 'lisp-interaction-mode-hook '(lambda () (turn-off-smartparens-mode)))

When Emacs starts, the `*scratch*` buffer loads with `lisp-interaction-mode`. At that point, SP is active. It seems that `(turn-off-smartparens-mode)` had no effect.

Running 

    M-x turn-off-smartparens-mode

does turn off SP.

**Comment by Fuco1** [comment]
What happens if you call it without the lambda (you can use `'turn-off-...` directly.

**Comment by lmichelbacher** [comment]
Same result, I’m afraid.

**Comment by Fuco1** [comment]
The way global minor modes are handled is quite annoying.  It seems they are called after the regular hooks...

Try to add the modes you don't want to `sp-ignore-modes-list` (it has to be the mode as returned by `major-mode`, not a parent mode like `prog-mode`)

**Comment by lmichelbacher** [comment]
Thanks for the suggestions.

I’ve decided to enable smartparens explicitly in each mode where I want it.

**Comment by Fuco1** [comment]
Okey. Sorry for the inconvenience.

**Comment by lmichelbacher** [comment]
No worries.
