### ISSUE TITLE
convert matching pairs from ( to { and vica versa

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#554]
this would be a really neat feature that I'd use a lot in Scala!

e.g. I have this code

```scala
    teapots.foreach { t => RichGraph.insertT(t) }
```

and I want to rewrite it as

```scala
    teapots.foreach ( t => RichGraph.insertT(t) )
```

**Comment by Wilfred** [comment]
`sp-rewrap-sexp` does what you want. The third animation in this GIF demonstrates it:

![sp-rewrap-sexp](https://github.com/Fuco1/smartparens/raw/master/images/smartparens-wrap.gif)

**Comment by fommil** [comment]
doh! (awesome!)
