### ISSUE TITLE
sp-get-enclosing-sexp failure case

### ISSUE THREAD

**Issue by luxbock** [Fuco1/smartparens#556]
With:

```elisp
(f ; ()
  'x)
```

- Calling `(sp-get-enclosing-sexp)` with point before the comment returns `nil`.
- Calling it inside the comment but not inside the empty list returns a plist with `:beg` 3 (i.e. just before the comment) and `:end` of 10 or just before the quote.
- Calling it on the next line returns the expected sexp object.

**Comment by Wilfred** [comment]
I can confirm. Assuming | represents the point:

```lisp
(f| ; ()
 'x)
```

`(sp-get-sexp)` returns nil here, whereas it should return `(:beg 1 :end 13 :op "(" :cl ")" :prefix "" :suffix "")`.

**Comment by Fuco1** [comment]
If called from inside a comment but not a sexp (which is inside a comment) it returns comment boundaries, so the 2nd point is expected.  The first behaviour is a bug indeed.

**Comment by Fuco1** [comment]
@luxbock should work now, please check in your context (of evil-cleverparens)

**Comment by luxbock** [comment]
@Fuco1 all good. Thanks!
