### ISSUE TITLE
unable to delete single parens in comments in strict mode

### ISSUE THREAD

**Issue by huahaiy** [Fuco1/smartparens#560]
E.g.

;; This is in comment :-)

Deleting the above line still leaves ")" in place

**Comment by Fuco1** [comment]
That's by design, parens are also parsed inside comments.

**Comment by Fuco1** [comment]
What mode and what command do you do when you delete the line?  I missed your comment about deleting the entire line.  C-k (sp-kill-hybrid-sexp) works for me.

**Comment by Fuco1** [comment]
This was fixed in 9ae8d4f
