### ISSUE TITLE
Pressing " does not step over closing " when overlay is inactive

### ISSUE THREAD

**Issue by Wilfred** [Fuco1/smartparens#562]
In e.g. Python, using `"` steps over the closing `"`:

``` python
# before
"foo|"
# after pressing "
"foo"|
```

However, this only works when the smartparens overlay is active. Otherwise, I get `"foo"|"". Is this intentional, or a bug?

**Comment by Fuco1** [comment]
Probably a bug, but there is also some setting you can change.  Check `sp-autoskip-closing-pair`, try the `'always` option.

**Comment by Fuco1** [comment]
This works for me in both strict and non-strict modes.

If `sp-autoskip-closing-pair` is set to `t` it properly inserts an escaped `\"`.

**Comment by Wilfred** [comment]
Hmm, seems to work for me too. Closing.
