### ISSUE TITLE
Support "infinite" (C-u) slurp and barf

### ISSUE THREAD

**Issue by PythonNut** [Fuco1/smartparens#564]
Let `|` represent the point.
```emacs 
(((|1) 2 3 4) 5 6 7)
;; C-u sp-forward-slurp-sexp
(((|1 2 3 4)) 5 6 7)
;; C-u sp-forward-slurp-sexp
(((|1 2 3 4 5 6 7))) ; maybe?
;; C-u sp-forward-barf-sexp
(((|)1 2 3 4 5 6 7))
```
I really love how judicious use of <kbd>C-u</kbd> can save a ton of repeated keystrokes, and I think it would be cool if this was supported for barfing and slurping as well.

**Comment by Fuco1** [comment]
Hmm, it has been like that for at least 3 years now :O

**Comment by PythonNut** [comment]
You know what? I'm really dumb. :| I swear, it wasn't working for me for some reason, but now it's fine. 

Thanks for putting up with me.

**Comment by Fuco1** [comment]
I got afraid for a bit that I broke something in the master :D No problems!
