### ISSUE TITLE
sp-splice-sexp-killing-around misbehaviour

### ISSUE THREAD

**Issue by cruegge** [Fuco1/smartparens#569]
`sp-splice-sexp-killing-around` behaves weirdly for me. I'm using a fairly recent Emacs from Git and smartparens from Melpa. Steps to reproduce from `emacs -Q`, `(progn (package-initialize t) (package-activate 'smartparens) (smartparens-mode))`, using the same notation as the smartparens docs:

- `(" " f|oo)  ->  |foo`
- `(" " |foo)  ->  |" "`
- `("x" |foo)  ->  (|"x" foo)`

**Comment by Fuco1** [comment]
I can reproduce the first two, and that is expected behaviour.

The third one gives me `|foo`.

**Comment by Fuco1** [comment]
Oh wait, the second one should give `foo` as well...

What is the setting of `sp-navigate-consider-stringlike-sexp`?

**Comment by cruegge** [comment]
Oh, sorry, I should have stated what the expected is to make it easier to read. Was a bit in a hurry.

`sp-navigate-consider-stringlike-sexp` is `(latex-mode)` (my test buffer is `*scratch*` in `lisp-interaction-mode`).

I tried the third example on a stable Emacs (24.4.1 from Debian Jessie) and also got the correct result, so maybe that one is a different issue. The second one still fails, though.

**Comment by Fuco1** [comment]
Well, it's because of that variable.  To have strings as sexps you need to list the mode there.

It's mostly an obsolete setting and I think I will simply remove it or make it an opt-out instead.

**Comment by cruegge** [comment]
Right, that fixes it. I didn't know that option; came from paredit and expected smartparens to work the same. Thanks a lot.
