### ISSUE TITLE
sp-backward-kill-sexp should remove punctuation too

### ISSUE THREAD

**Issue by Wilfred** [Fuco1/smartparens#572]
I'm trying to kill expressions in non-sexp languages (this example is from Python):

```
# Starting with this:
foo = bar.baz - biz()|

# sp-backward-kill-word ignores delimiters
foo = bar.baz - biz()|
foo = bar.baz - |()

# sp-backward-kill-symbol ignores delimiters too
foo = bar.baz - biz()|
foo = bar.baz - |()

# sp-backward-kill-sexp does what I want for delimeters, but doesn't like infix -:
foo = bar.baz - biz()|
foo = bar.baz - biz|
foo = bar.baz - |
foo = bar. - |
```

Previously, I used `backward-kill-word`. However, that falls down with functions with arguments:

```
# backward-kill-word produces unbalanced parens
foo = bar.baz - biz(quux, qox)|
foo = bar.baz - biz(quux, |
```

I think I should be using `sp-backward-kill-sexp`. Is it intended to work for non-lisps?

**Comment by Fuco1** [comment]
I'm not sure what you're after :O Do you want to kill the entire `biz()` thing in one go?

**Comment by Wilfred** [comment]
Yep, I want to kill the whole `biz()` in one go. However, `sp-backward-kill-sexp` is confused by infix operators:

```
foo = bar.baz|
foo = bar.|
foo = .|

x - y|
x - |
 - |
```

`sp-backward-kill-sexp` is nearly perfect, but it's confused in these cases. Is this command intended to work in non-lisps (so this would be a bugfix/improvement) or do we need a `sp-backward-kill-hybrid-sexp`?

**Comment by Fuco1** [comment]
I'm not sure, but I think nuking punctuation in the way isn't a terrible idea.
