### ISSUE TITLE
Change to smartparens-python.el breaks single quote pairing

### ISSUE THREAD

**Issue by butala** [Fuco1/smartparens#573]
Hi,

This is in reference to: 065fa38e9e2c10a26b523016d521e0be0a021e0b.

The prior (and desired) behavior was that a single quote would generate an auto-pair when in python mode. With this change, no pair is generated when I hit the single quote key in python mode. I have confirmed that this latest change caused the change in behavior, i.e, when I remove the change the behavior returns to normal.

To me this is a regression. Could the change please be undone or corrected?

**Comment by Wilfred** [comment]
Argh, you're right. The intent of that change was stop `'` being automatically paired in strings. I tested that case, but not the case of `'` being paired in code.

**Comment by butala** [comment]
Thanks for taking care of this --- I appreciate it!

**Comment by Wilfred** [comment]
:)
