### ISSUE TITLE
Add config to disable auto-indent

### ISSUE THREAD

**Issue by Skinney** [Fuco1/smartparens#576]
I'm sorry if there already is an option for this, however, I've not found it.

I'm using smartparens-strict-mode when coding elm, and I would really like to disable smartparens way of auto-indenting after performing an action. Most of the time in elm, it performs indentation when it shouldn't, and it's easy for me to re-indent anyway. The most anoying thing is when I go to start of line, then perform C-k to delete the whitespace, only for the whitespace to reappear due to auto-indent.

This is of course a problem with every language that doesn't have clear indentation semantics, but there are also cases, though rare, in other languages where I want to perform an action without performing any indentation.

I therefore suggest to add an option to disable auto-indentation.

**Comment by Fuco1** [comment]
Look at the options with "indent" or "reindent" in the name.

**Comment by Wilfred** [comment]
Specifically, `sp-no-reindent-after-kill-modes` is usually what you need to change. Would you like to send a patch for elm?
