### ISSUE TITLE
Remove whitespace remaining whitespace when moving parens

### ISSUE THREAD

**Issue by Skinney** [Fuco1/smartparens#578]
Simple example. Given the following code.

``` js
test()something.happens(2);
```

If I position my cursor on the first pair of parens, then barf right twice. I get the following.

``` js
test( something. happens)(2);
```

Is there any way to remove the resulting whitespace that is left behind when moving the parens?

**Comment by Fuco1** [comment]
This was recently fixed for python, so someone will have to do the same for javascript.  I don't have a good system solution yet. 

Now we primarily support the lisp syntax where this makes more sense.  It is a long-standing issue however.

**Comment by Fuco1** [comment]
Plus, slurping is hard in languages where there isn't a clear rule of what is a "token" and what not.  In lisps, everything is either a form or a list and you work on that.  In js/c/ruby etc... things are much more ambiguous.

**Comment by Wilfred** [comment]
Have you tried `sp-slurp-hybrid-sexp`? I appreciate there's no barf equivalent yet (that's #570) but this command generally handles whitespace much better in non-lisps.

**Comment by zck** [comment]
Would it be possible to track, for example, if the previous Emacs command was also a slurp? If it was, we could not add a space upon moving the close-parenthesis.

**Comment by Fuco1** [comment]
@zck, the problem is that sometimes you have to add the space.  For example `(foo)bar` can't change into `(foobar)`, it has to become `(foo bar)`.  There are other issues like this in every language.

**Comment by PythonNut** [comment]
> Plus, slurping is hard in languages where there isn't a clear rule of what is a "token" and what not.

This is probably outside the scope of this package, but couldn't this be solved with a real parser? If I understand correctly, the expression/statement must be clearly defined by the language in order for it to make sense. Obviously, a full-blown recursive-descent parser may not a reasonable addition to this package, but that's the only way I can see the generic language support without weird and/or contrived hacks.

**Comment by Fuco1** [comment]
Right.  I played with an idea of adding some interface to hook parsers into smartparens so that it can use them to navigate, but so far nothing came out of it.  Most of the time the crude hacks work good enough (until somone complains obviouly :D)

**Comment by zck** [comment]
I can't seem to reproduce a slurp creating `(foo)bar`. Slurping `()foo bar` results in `(foo) bar`. If the text *starts* as `(foo)bar`, smartparens inserts a space, as seems to make sense.

As far as I can tell, this comes up only when there's a word-constituent next to a symbol, as in slurping:

    whatever()someFunction()

One slurp results in:

    whatever(someFunction)()

And a second in:

    whatever(someFunction ())

The space after `someFuction` of the *second* slurp is undesired. And I think we can avoid it. Smartparens can track, for the most recent slurp, whether it put a parenthesis between two non-space characters (as the first slurp in this example), or in the same place as a space character.

If we do that, *then* if the user slurps twice in a row (that is, without moving point, or inserting text, or taking some other action), and we move the parenthesis, we can know whether to replace the parenthesis with a space (if we put the paren in the same place as a space character on the *previous* slurp) or not (if we put the paren between two non-space characters on the previous slurp).

**Comment by Fuco1** [comment]
Hm, this makes sense :)  I'll think about it in the morning, but it seems doable.

**Comment by Fuco1** [comment]
In a situation where I have `(|)(foo)(bar)` and I slurp twice I would want to end up with `((foo) (bar))` in lisp, but the above heuristic would result in `((foo)(bar))`.

Ideally, the slurp shouldn't even land between `function` and `()` and just treat the parens as part of the function token.  This can be achieved by setting the prefix argument somehow (I use it in latex similarly for `{}` macros).

**Comment by aij** [comment]
@Fuco1 I don't understand that lisp example. When would you have that starting situation?
