### ISSUE TITLE
Customisations of sp-ignore-modes-list are overridden 

### ISSUE THREAD

**Issue by ned2** [Fuco1/smartparens#581]
I'm trying to disable smartparens for `fundamental-mode` in order to get around issue #449. The problem I'm finding is that I can't work out how to customise the value of `sp-ignore-modes-list` from Emacs' `after-init-hook`. It seems that it doesn't yet exist at this point/the value I give it gets clobbered by smartpares' config. Or do I just need better Emacs-fu?

**Comment by Fuco1** [comment]
`defvar`s should handle `setq`'d variables properly after reloading.  Do you use customize?  I don't know how that handles overloading.

**Comment by ned2** [comment]
No, not using customize, I was just doing `(add-to-list 'sp-ignore-mode-list 'fundamental-mode)` after the package was loaded. Although I don't seem to having the issue I was trying to get around so no longer bugging me at the moment.

**Comment by Fuco1** [comment]
Are you using spacemacs or some other distribution?  I think this really should work just fine, especially if called from `after-init-hook`.

I've been using emacs for years but I still competely don't understand the startup process... it's rather silly at times.

**Comment by ned2** [comment]
Aha, so turns out I had a typo and was trying to use the variable `sp-ignore-mode-list`. Oops! Sorry about that.

**Comment by Fuco1** [comment]
Uh, thanks for reporting back :)
