### ISSUE TITLE
Apostrophe handling in text-mode with smartparens-strict-mode

### ISSUE THREAD

**Issue by rpglover64** [Fuco1/smartparens#584]
##### Repro
1. Type a word with an apostrophe (e.g. "isn't").
2. Backspace until you're back at the beginning of the buffer.
3. Observe that the apostrophe isn't deleted.

**Comment by Fuco1** [comment]
Works for me, so I guess we just have silly defaults.

Do you load `smartparens-config` file?  If not, try adding `(sp-pair "'" nil :unless '(sp-point-after-word-p))` somewhere to your config.

**Comment by rpglover64** [comment]
I haven't checked my configs yet, but evaluating said sexp does not solve the problem.

I'm using spacemacs (and thus evil), and the problem occurs both in insert state and in emacs state.

**Comment by braham-snyder** [comment]
With `smartparens-mode`, `smartparens-strict-mode`,`(require 'smartparens-config)`, and `eval-expression` of that snippet you posted, repeatedly calling `sp-backward-delete-char` from the end of this (in `text-mode`):

```
"this" doesn't
```

will delete the `t` but then skip over ` doesn'`, jumping into the double quotes (just after `s`).

**Comment by Fuco1** [comment]
@braham-snyder I can reproduce this, but I think the issue is unrelated (the OPs problem I can't reproduce anymore).  Would you be so kind and open a new issue (just copy over the text from here I guess).  Thanks!

**Comment by braham-snyder** [comment]
gladly--here it is: https://github.com/Fuco1/smartparens/issues/709
