### ISSUE TITLE
sp-kill-sexp behaves differently inside comments

### ISSUE THREAD

**Issue by djr7C4** [Fuco1/smartparens#585]
To reproduce run `emacs -Q --eval "(progn (package-initialize) (require 'smartparens-config))"` and enter the following in the *scratch* buffer (where | is the cursor):

    ;; 1: |"abc"
    "def" ;; 2

After running `M-x sp-kill-sexp`, the buffer changes to

    ;; 1: |""
    "def" ;; 2

while I would expect the quotes to be killed as well.  Starting with

    ;; 1: "abc"
    |"def" ;; 2

and running `M-x sp-kill-sexp` yields

    ;; 1: "abc"
    | ;; 2

as one would expect.  A similar problem occurs with some other commands such as `sp-forward-sexp`.

**Comment by Fuco1** [comment]
Yes, this has to do with the `sp-navigate-consider-stringlike-sexp` setting. You need to add modes where you want to parse strings there.

In the near future we are planning to remove it and make it an opt-out instead.

**Comment by djr7C4** [comment]
Thank for the reply.  It works perfectly now.
