### ISSUE TITLE
Incorrect wrapping for some pairs in LaTeX

### ISSUE THREAD

**Issue by ThibautVerron** [Fuco1/smartparens#586]
This is mainly these 3 pairs (https://github.com/Fuco1/smartparens/blob/master/smartparens-latex.el#L139-L141):

```
  (sp-local-pair "\\lfloor" "\\rfloor" :post-handlers '(sp-latex-insert-spaces-inside-pair))
  (sp-local-pair "\\lceil" "\\rceil" :post-handlers '(sp-latex-insert-spaces-inside-pair))
  (sp-local-pair "\\langle" "\\rangle" :post-handlers '(sp-latex-insert-spaces-inside-pair))
```

If you wrap for example `F` with `\lfloor...\rfloor` you obtain `\lfloorF\rfloor`, which is incorrect LaTeX (the compiler will look for a `\lfloorF` command which doesn't exist).

An easy work-around is to add a space at the end of the left delimiter, but it will require that space to be inserted when typing the paren (e.g. then inserting `\lfloor{` won't trigger the insertion iiuc), and with `sp-latex-insert-spaces-inside-pair`, it will cause 3 spaces to be inserted.

The best solution imo would be to change the definition of `sp-latex-insert-spaces-inside-pair` to insert 1 space after the left delimiter and 1 space before the right delimiter (I'm not sure if this one is ever needed, actually), and make it apply to `wrap` as well.

**Comment by Fuco1** [comment]
Thanks for reporting, this was indeed quite annoying misconfiguration.  I've implemented the suggestion you provided, seems like the best idea indeed.
