### ISSUE TITLE
Hydra keybindings

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#587]
You have **got** to see this hydra mode for s-expression navigation with smartparens https://twitter.com/lunaryorn/status/717795780510220288

**Comment by Fuco1** [comment]
Wouldn't it be too annoying to hit `C-c k` all the time? `C-M-f` seems a lot simpler.  Tell me what am I missing :D

If this is useful I'm not against incorporating it into SP somehow, I've seen hydra getting a lot of attention lately.

cc @lunaryorn

**Comment by lunaryorn** [comment]
@Fuco1 Well, the whole point of Hydra is that do *not* have to press `C-c k` all the time :wink:

`C-c k` is just the entry point but after the first command all other commands need no prefix key until `q` (or any other non-hydra key) is pressed.

I.e. to raise the current sexp three levels and then slurp two times, I'd press `C-c k <up> <up> <up> <right> <right>`.  Or `C-c k ( <right> j` to wrap the symbol at point in parens and the slurp forward and join with the next sexp.

**Comment by lunaryorn** [comment]
It's hard to describe how Hydra feels until you've seen it in action.  If you know vim, you can think of a hydra as a localized command mode, entered through the hydra prefix, and offering only a limited amount of command keys.

**Comment by manuel-uberti** [comment]
I'll chime in in favour of Hydra (and this one in particualr, thanks @lunaryorn!). Hydra just makes it simpler when you need to move around sexps like lunaryorn described.

**Comment by Fuco1** [comment]
I see.  I use hydra in my config but it always terminates right away.  I guess I have some really old version... and that was the only workflow I wanted out of it anyway (something like magit popups... which at tha ttime wern't available as a separate package).

So, is it a good idea to put this into SP?  I can't tell how individual peoples' tastes might be.  spacemacs and other distributions probably configure SP in their own way as well and it might clash... hmm.  I always hated keybindings :P

**Comment by lunaryorn** [comment]
@Fuco1 I wouldn't.  After all, it's just sugar for key bindings, and everyone has their own preferences there.  If there's general interest I can package it up for MELPA, but I'd recommend that you write your own hydras to suite your needs and don't just copy my keybindings.

**Comment by fommil** [comment]
I was thinking it would be well suited for a wiki page, as a suggestion for setup.

**Comment by lunaryorn** [comment]
@fommil @Fuco1 Feel free to copy :relaxed:

**Comment by Fuco1** [comment]
@fommil Good idea.  Maybe I could start a "community wiki" page, spacemacs has something like that and I see that hydra itself as well.  Then we could add neat setups there.  Or just submit it to hydra's wiki and link there (might cut on the duplication)

**Comment by Fuco1** [comment]
I've added a link and some explanation to the tips and tricks page on the wiki.
