### ISSUE TITLE
sp-forward-slurp-sexp should know about Clojure set literal, lambda

### ISSUE THREAD

**Issue by lvh** [Fuco1/smartparens#593]
Example, `|` being point

```
(abc|) #{1 2 3}
```

`sp-forward-slurp-sexp` results in:

```
(abc| #){1 2 3}
```

Doing it a second time results in:

```
(abc| # {1 2 3})
```

(having introduced a space between `#` and `{`).

Instead, I would have liked it to:

```
(abc| #{1 2 3})
```

The same thing is true for Clojure lambda expressions, e.g. `#(inc %)`; where the `#` is captured separately.

I think smartparens currently gives me the configurability to fix this for my setup, but I wanted to report it upstream since this seems generally useful.

**Comment by Fuco1** [comment]
It should be enough to do what we did for racket, that is adding the # as a prefix symbol.

Thanks for reporting, it's a nice feature to add.

**Comment by lvh** [comment]
This also affects conditional read statements for `cljc` files, which have `#?(...)` and `#?@(...)` which should be interpreted as one token.

**Comment by Fuco1** [comment]
Where could I find all the possible prefixes clojure supports?

**Comment by lvh** [comment]
That's a good question! Here's an attempt at an exhaustive list:

Reader macros (http://www.clojure.org/reference/reader):

- `#{...}` (sets)
-  ^{:a 1}` (metadata maps , appear to be handled correctly already)
- `#"..."` (regex pattern)
- `#'xyzzy` (varquote)
- `#(xyzzy 1 2 %)` (anonymous fn)
- `#_` (comment reader macro). This comments the next form. This appears to be an edge case, since it correctly captures the `#_` entirely, but it doesn't capture the thing it comments out... Perhaps that's OK; the user can just slurp twice :) Same thing with tagged literals.
-  Reader conditionals, e.g.:

```clojure
#?(:clj     Double/NaN
   :cljs    js/NaN
   :default nil)
```

and 

```clojure
#?@(:clj [3 4] :cljs [5 6])
```

**Comment by Fuco1** [comment]
The issue is that some of those characters are correctly set as `prefix` class by the clojure mode but others are not.  Since characters can only have one class, in SP we do the ugly thing and just recognize prefixes by a regexp... that's why I asked :)  I would also need all the valid combinations (for example in elisp you can have a prefix `',@` and theoretically it can be infinitely nested (like `'''''',@'''`).

So the best thing, and I should've asked right away, would probably be if you could write a regexp to recognize the prefixes, at least the most common variants.

**Comment by vspinu** [comment]
> if you could write a regexp to recognize the prefixes

Where can I hook this regexp for generic use?

This is what I have so far:
```elisp

(let ((clj-prefix "\\([@`'#~,_?^]* *\\)"))
  (sp-local-pair 'clojure-mode "(" ")" :prefix clj-prefix)
  (sp-local-pair 'clojure-mode "[" "]" :prefix clj-prefix)
  (sp-local-pair 'clojure-mode "{" "}" :prefix clj-prefix))
```

This works correctly on the following patterns:

```clojure
#{...}
^{:a 1}
#(xyzzy 1 2 %)
#_ (comment reader macro)
#?(:clj     Double/NaN
   :cljs    js/NaN
   :default nil)
~unquote-me
`~'unquote-me
~@(splice-me)
`(quote-me)
```quote-me
@(deref-me)
@deref-me
#?@(:clj [3 4] :cljs [5 6])
```

but fails in the following cases

```clojure
#"..."
#'xyzzy
````

**Comment by Fuco1** [comment]
`sp-sexp-prefix` applies to the mode, then the `:prefix` setting on each pair can override it specifically for that pair.

**Comment by vspinu** [comment]
Aha. Thanks. 

The following works except for the same two troublesome cases from above.

```clojure
(add-to-list 'sp-sexp-prefix '(clojure-mode regexp "\\([@`'#~,_?^]* *\\)"))
```

**Comment by Fuco1** [comment]
Why is the space there in the regexp? I think the engine might just match "nothing" as a prefix and be happy with it.

**Comment by vspinu** [comment]
That's for matching optional spaces like in `#_   (comment reader macro)`. Without the space `#_` is treated as a separate construct.

**Comment by Fuco1** [comment]
Huh, that's an odd syntax...  Then I guess you need to make the regexp in such a way that it doesn't allow matching the whitespace without also having at least one special character in front.

**Comment by vspinu** [comment]
Yeh. That space is causing problems on repeated invocation of `sp-forward-slurp-sexp`. So far I have settled on `"\\([@`'#~,_?^]+\\)"`. 

That space is not a big deal. I am personally more concerned about it not working with  `#"..."`. Is there anything that could be done about that? Thanks.

**Comment by Fuco1** [comment]
Sure, it's a bug (I think).  I will look at it.  So far what you've done should work with strings as well as single tokens.  Would you mind doing a PR with the settings so far?
