### ISSUE TITLE
Wrapping does not work with current Emacs master

### ISSUE THREAD

**Issue by mrkkrp** [Fuco1/smartparens#597]
With current Emacs master, in scratch enter:

```
something
```

Place cursor on the word `something` and execute `sp-select-next-thing`. After that press <kbd>(</kbd>. The result looks like this:

```
something()
```

Instead of:

```
(something)
```

**Comment by Lompik** [comment]
I cannot reproduce this.

However I had the exact same issue recently. It was caused by `aggressive-indent-mode` but is now fixed in version later than 27-Apr.

it's always a good idea to have steps to reproduce with `emacs -Q`

**Comment by mrkkrp** [comment]
Indeed, I use `agressive-indent-mode` too and now it's fixed. Sorry, I was too lazy to try with `emacs -Q'. Closing.

**Comment by Fuco1** [comment]
Thanks for the info @Lompik !
