### ISSUE TITLE
not auto paired in sh-mode in some case.

### ISSUE THREAD

**Issue by zw963** [Fuco1/smartparens#598]
My propose is input `cut -d':' -f1`

```sh
cut -d'|               # here ' not auto paired.
```

But

```sh
cut -d"|"            # " is worked
```

**Comment by Fuco1** [comment]
It thinks you are using the quote as an apostrophe, that is caused by the global setting

   (sp-pair "'" nil :unless '(sp-point-after-word-p))

You can disable it in `sh-mode` by doing

    (sp-local-pair 'sh-mode "'" "'" :unless nil)

**Comment by zw963** [comment]
It worked. 

Thank you.
