### ISSUE TITLE
`sp-delete-pair` not worked correctly

### ISSUE THREAD

**Issue by futurist** [Fuco1/smartparens#601]
Think below code to define a pair:

``` lisp
(sp-local-pair 'org-mode "#" "#" :insert "C-c C-x l" :trigger "#")
```

Press <kbd>#</kbd> will insert the pair `#|#` correctly.

But then call `(sp-delete-pair 1)`, only one `#` deleted, not the pair.

**Comment by Fuco1** [comment]
That is arguably not a bug. The function was only intended to be called from the advice on `backward-delete-char`, which takes care of deleting the "opening" `#`.  If you type `#`, `#|#` is inserted and then hitting backspace should remove both of them.

Do you need the behaviour to work non-interactively as well?  You can use `sp-kill-sexp` or `sp-unwrap-sexp` from code.

**Comment by futurist** [comment]
Have you tried in `org-mode`? I've tried `(sp-delete-pair 1)`, `sp-kill-sexp`, `sp-unwrap-sexp`, none can work correctly.

**Comment by Fuco1** [comment]
Can you give a sample buffer?  I tried it and it works on my setup.

**Comment by Fuco1** [comment]
The function `sp-backward-delete-char` can be used stand-alone to delete pairs
