### ISSUE TITLE
Change Highlight color

### ISSUE THREAD

**Issue by der-Daniel** [Fuco1/smartparens#604]
Hi,

i am using the `seti` theme. 
When I am opening a parenthese the highlight color is really bright white.

Is there a way to match the seti mark color?

For Frodo :)

**Comment by der-Daniel** [comment]
Never mind found this:
https://github.com/Fuco1/smartparens/wiki/User-interface

**Comment by Fuco1** [comment]
All the smartparens themes should be visible in the customize for the group.  You can submit a patch to the theme upstream to theme them accordingly :)

I guess you figured it out already tho.
