### ISSUE TITLE
LaTeX mode single quotes

### ISSUE THREAD

**Issue by legendre6891** [Fuco1/smartparens#611]
There seems to be a confusing with single quotes in LaTeX. When a single quote is entered, the minibuffer shows "Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file."

Moreover, I still see that the backtick  is still matched with ' even though the line `  (sp-local-pair "'" nil :actions nil)` exists in `smartparens-latex.el`.

I tried removing the pair via `(sp-pair "'" nil :actions :rem)`, but that has no apparent effect.

**Comment by Fuco1** [comment]
Backtick is matched with `'` because that is latex syntax.  If you are removing a pair `"'"` you are specifying the opening, not the closing delimiter, so that won't affect the backtick pair in any way.
