### ISSUE TITLE
Automatic deletion of complete pairs

### ISSUE THREAD

**Issue by mrmagooey** [Fuco1/smartparens#615]
Currently if I have a balanced pair of quotes, and the cursor is inside, like:

    "|"

backspace will give me

    "

Rather than deleting both quotes, it just deletes the one. However, the expected pair deletion works on parenthesis and brackets just fine.

I've tried adding a few random `(sp-pair)` combinations at it seems like the automatic deletion of balanced pairs seems a bit selective as to when it fires? E.g.

    (sp-pair "&" "*")
    &|* => 
    (sp-pair "a" "e")
    a|e => e
    (sp-pair "q" "w")
    q|w => w
    (sp-pair "<" ">")
    <|> => 

Smartparens normally gets loaded with my spacemacs, but I loaded emacs with --no-init-file and manually started up smartparens (loading dash, loading and requiring smartparens, turning smartparens on) and the behaviour seemed to be the same.

**Comment by Fuco1** [comment]
Try adding the major mode where you tried this to `sp-navigate-consider-stringlike-sexp`, that should at least fix the quote issue.

This is quite an old setting which is rather meaningless nowadays, we will remove it with the next release.

**Comment by mrmagooey** [comment]
I'm not sure what changed but this does not appear to be a problem any longer.

**Comment by Fuco1** [comment]
The setting above was removed and the issue fixed.  It seems I forgot to mention the issue id in the commit.  Thanks for verifying anyhow :)
