### ISSUE TITLE
Wrong extra doublequote

### ISSUE THREAD

**Issue by andreas-roehler** [Fuco1/smartparens#618]
With python-mode: Inserting a doublequote at EOF insert two quotes, while one is needed.

class TestInit(unittest.TestCase):
    def setUp(self):
        self.bot = bot.Bot("jid", "password

**Comment by Fuco1** [comment]
Starting with 1.8, an escaped double quote will be inserted by default.  To close the string, use `C-q "`.  It is impossible to know what you want to do in this case.

Smartparens ensures you should never be in this situation.  When the cursor is at the end before a closing `"` it will be skipped over.

I labeled this as a bug but I think it isn't a bug after all.
