### ISSUE TITLE
sp-forward-barf-sexp breaks with `sp-sexp-prefix` specification

### ISSUE THREAD

**Issue by vspinu** [Fuco1/smartparens#621]
```elisp 
(setq sp-sexp-prefix '(list emacs-lisp-mode regexp "\\(?:[_]+\\)"))
```

In elisp with  `(|_(abc))`  I call `sp-forward-barf-sexp` and see `(_)(abc)` instead of `()_(abc)`. 

Interestingly the problem seems to depend on the character. If  `_` is  replaced by `#` it works as expected in elisp (but still breaks in clojure).

**Comment by vspinu** [comment]
I have tracked it down to [this line](https://github.com/Fuco1/smartparens/blob/clojure/smartparens.el#L4908). The problem is that `_` is symbol but `#` is prefix. 

Same reason this was failing with clojure-mode with `#` and working with `@`.  `#` is symbol and `@` is prefix.

**Comment by vspinu** [comment]
To clarify the finding. 

With `(_|(abc))` in elisp `M-: (sp-get-thing t)` returns `(:beg 2 :end 3 :op "" :cl "" :prefix "" :suffix "")`. 

With `(#|(abc))` it returns `(:beg 1 :end 9 :op "(" :cl ")" :prefix "" :suffix "")`.

**Comment by Fuco1** [comment]
The problem is that the `_` has the symbol class and so when smartparens tries to grab "next thing" it thinks the `_` itself is a symbol; and because it comes before the `(abc)` it is treated as a separate entity.  This is probably wrong, we should prefer a sexp with prefix over a symbol + sexp without prefix.

**Comment by Fuco1** [comment]
By the way `(setq sp-sexp-prefix '(list emacs-lisp-mode regexp "\\(?:[_]+\\)"))` has to be `(setq-local sp-sexp-prefix '((emacs-lisp-mode regexp "\\(?:[_]+\\)")))`, it's an alist and further, you quote the `list` constructor.
