### ISSUE TITLE
smartparens changes yasnippet behavior

### ISSUE THREAD

**Issue by Dickby** [Fuco1/smartparens#625]
If I insert a bracket in a yasnippet template field with smartparens completing the closing bracket, I have to C-f out of the brackets to TAB into the next yas template field.
If I don't exit the brackets with C-f and press TAB nothing happens.

**Comment by Fuco1** [comment]
Hm, both packages seem to create an overlay with priority 100.  Apparently SP comes later and so its map takes precendece.

How to solve this... probably I'll lower the priority to 99.

**Comment by Dickby** [comment]
Thanks!
