### ISSUE TITLE
3 test failures on 25.0.95.1

### ISSUE THREAD

**Issue by dunn** [Fuco1/smartparens#627]
This is on Mac OS 10.11.5.
```
3 unexpected results:
   FAILED  sp-test-ruby-barf-forward
   FAILED  sp-test-ruby-slurp-backward
   FAILED  sp-test-ruby-slurp-forward
```
Full logs: https://gist.github.com/dunn/4220a74cdf5c5a1baae448f3430cf8f6

**Comment by Fuco1** [comment]
It would be interesting to add nightlies to travis builds now that travis supports tagging builds as "can fail"

**Comment by dunn** [comment]
I see evm offers a 'git-snapshot' recipe, but the download is a tarball from a few months ago: https://github.com/rejeep/evm/blob/master/recipes/emacs-git-snapshot-travis.rb

**Comment by Fuco1** [comment]
There is a branch for tests on emacs 25 so this will get fixed when it is merged.
