### ISSUE TITLE
sp-backward-kill-word doesn't properly append kill

### ISSUE THREAD

**Issue by Malabarba** [Fuco1/smartparens#630]
1. In ruby-mode, write: `some_long_symbol`.
2. Invoke `sp-backward-kill-word` 3 times (with a keybind).
3. Yank back the text with `C-y`.

You'll get this: `symbollong_some_`.

**Comment by Fuco1** [comment]
Thanks :)

FYI, when calling `kill-region` if you do `(kill-region beg end)` it appends the kill and if `(kill-region end beg)` it prepends (that is, first argument < second argument means prepend).  I did not know that.
