### ISSUE TITLE
Repeated forward-slurp alters whitespace (scala)

### ISSUE THREAD

**Issue by aij** [Fuco1/smartparens#632]
In Scala, using "C-<right>" (sp-forward-slurp-sexp) repeatedly results in changing the whitespace of the text being parethesized.

Eg:

```
val x = f(1) + 2 * f(3)
val x = ()f(1) + 2 * f(3)
val x = (f)(1) + 2 * f(3)
val x = (f (1)) + 2 * f(3)
val x = (f (1) + 2) * f(3)
```

Note the added space between `f` and `(1)`.

**Comment by Fuco1** [comment]
Thanks for reporting the issue!

This is a classic.  I'm starting to think it would be better to wrap the logic and make lisps the special case :D

If you search the issues you will find an explanation (I think it was reported for javascript first)

**Comment by aij** [comment]
Indeed. #578 seems to be pretty much the same, although the wording is a bit confusing.

I was thinking it should neither add nor remove whitespace when slurping, but now I realize that may be more language-specific than I thought at first.

I *think* it would be OK to always preserve whitespace in Scala, although it may depend on how barf works. For example, `f(1)` slurp-> `(f1)` wouldn't make sense, but `(f 1)` also wouldn't make sense in Scala, so neither way is better in that regard, except I'm guessing barf may need the later form in order to be able to undo the slurp. Making a single barf after that slurp turn that into `f1()` just seem like it would be very confusing.

In other languages like OCaml/SML/Haskell `(f 1)` actually would make sense...

I guess this is a lot more complicated than I was thinking.

**Comment by Fuco1** [comment]
Yea :) We first designed this for lisps, then, just as you, thought it would just work everywhere right?!  But then you start bumping into languages with syntax not at all like what you had in mind... and the special rules can get pretty wild (look at `smartparens-ruby.el` for example).

I don't know scala at all so I can't really make a good judgement of what to do when.  I think with ruby we also have some situations where you can't undo the slurp/barf but I'm not 100% sure.
