### ISSUE TITLE
Behavior of backspace

### ISSUE THREAD

**Issue by sagarjha** [Fuco1/smartparens#633]
Hi,
First of all, thanks for the awesome package!
I import all the smartparens-config in my emacs. It binds `backspace` (`DEL` actually) to `sp-backward-delete-char`. Without smartparens configurations, emacs runs `backward-delete-char`.  
Starting from some newer version of emacs (I have `emacs 24.5.1`), `backward-delete-char` deletes the whole region if a region is active and delete active region is true (source: first comment in this answer - http://stackoverflow.com/a/637544/2938004).
I was fond of using backspace to kill a region because it doesn't pollute the kill-ring.  Can smartparens be updated to accommodate this feature? After all, I would expect `sp-backward-delete-char` to conform to `backward-delete-char`, but thinking more about it, the semantics may not be so clear since you have to ensure that the parens are matched all the time.

**Comment by Fuco1** [comment]
It works like you describe for me on 24.5.2.  There might be something more going on.  Do you use spacemacs or similar?  I think they set up hungry delete mode which might clash with this.

**Comment by Fuco1** [comment]
That is, I get your expected behaviour.  `delete-active-region` is set to `t`.

**Comment by sagarjha** [comment]
No, I use GNU emacs on Ubuntu 16.04.
But, I understand the issue now. In smartparens-mode, backspace is bound to `backward-delete-char-untabify` which is same in emacs without smartparens, but in smartparens-strict-mode, it is bound to `sp-backward-delete-char` which does not delete the region.

**Comment by sagarjha** [comment]
So, I guess I am fine in `smartparens-mode`, but not in `smartparens-strict-mode`.

**Comment by bolivier** [comment]
@sagarjha, I don't know if you're still having issues with this, but I ran into it today as well.  This little snippet fixes the behavior for me.

```
(defun bso/delete-region-if-should (ARG)
  (interactive "P")
  (if (and  delete-active-region (region-active-p))
	  (kill-region (mark) (point))))
(advice-add 'sp-backward-delete-char :before 'bso/delete-region-if-should)
```

**Comment by sagarjha** [comment]
It works. Thanks!

**Comment by bolivier** [comment]
@sagarjha This modification makes it better.  The other version would delete backward after the region was killed, which means one too many chars would get deleted.  This one fixes that by using `:around` instead of `:before`

```
(defun bso/delete-region-if-should (oldfun &rest r)
  (if (and  delete-active-region (region-active-p))
	  (kill-region (mark) (point))
	(apply oldfun r)))

(advice-add 'sp-backward-delete-char :around #'bso/delete-region-if-should)
```

@Fuco1 Does this seem like behavior we could add somewhere?
