### ISSUE TITLE
Please create a release for melpa stable

### ISSUE THREAD

**Issue by Trevoke** [Fuco1/smartparens#635]
I think all you need to do is tag a particular commit with a version number (e.g. `1.0.1`) and push the tag to Github. Melpa will do the rest.

And, of course, keep on pushing new tags when you have a new stable release, so that the version on melpa stable will remain current :)

**Comment by Fuco1** [comment]
There is a release.

**Comment by Trevoke** [comment]
Oh yes, indeed there is. For some reason I didn't "see" it. My apologies, and thank you for a wonderful tool!

**Comment by Fuco1** [comment]
No problem :) New one's coming soon!
