### ISSUE TITLE
Escaped quotes inside quotes parse incorrectly

### ISSUE THREAD

**Issue by Fuco1** [Fuco1/smartparens#637]
In the buffer

     adasd "asdasd \"  asda asd \" | asd " asd

parsing backwards jumps to the opening unescaped quote.  Parsing forward from the escaped quote jumps to the closing escaped quote properly.

**Comment by Fuco1** [comment]
Same thing happens in modes like python when we mix `'` and `"`.  It can't correctly handle nested quotes of different type.

**Comment by benwbooth** [comment]
I have also noticed a problem with parens inside quotes. For example, in perl mode:
```
my $str = '()';
```
When I type the closing parens, it creates another parens instead of overwriting the automatically inserted parens:

```
my $str = '())';
```
