### ISSUE TITLE
possible to have a custom "wrap region"

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#639]
Apologies if you've documented this, I can't find it in https://github.com/Fuco1/smartparens/wiki/Wrapping

I often want to wrap a block of code and reindent, like so (using `^` for the region)

```scala
def foo = ^bar^
```

=>

```scala
def foo = {
  bar^
}
```

in a single command, is there a way to do that with smart parens, assuming the major mode can handle the indentation?

**Comment by fommil** [comment]
or sometimes I want to do it in a different way, outputting to

```scala
def foo = { foo^ }
```

(note space padding instead of newlines)

**Comment by Fuco1** [comment]
This should be doable with the similar hook as for insertion, you would just listen on a different action type.  Look to the documentation on post-handlers (which is the old name for hooks)

**Comment by Fuco1** [comment]
Here's the link: https://github.com/Fuco1/smartparens/wiki/Permissions#pre-and-post-action-hooks

**Comment by fommil** [comment]
cool! I'll try this out and reopen only if it doesn't work.

**Comment by fommil** [comment]
although this isn't technically an `sp-mode` thing, I ended up creating this

```elisp
(defun scala-sp-blockify-region ()
  (interactive)
  (when (region-active-p)
    (kill-region (region-beginning) (region-end))
    (insert ?{) (insert ?}) (left-char)
    (comment-indent-new-line)
    (comment-indent-new-line)
    (forward-line -1)
    (yank)
    (call-interactively 'indent-region)))

(bind-key "s-<return>" 'scala-sp-blockify-region)
```

I need to sit down and understand how to use the sp API to achieve the same thing, as I think it would be useful for generalised languages and not just scala (or C-derived language syntax)

**Comment by Fuco1** [comment]
I tested this in C mode but it should work the same.  Feel free to adjust the final point (right now it ends after the braces which might not be what you want

```elisp
(defun my-sp-wrap-with-brackets (_ action _)
  (when (eq action 'wrap)
    (sp-get sp-last-wrapped-region
      (let ((beg :beg-in)
            (end :end-in))
        (save-excursion
          (goto-char end)
          (newline))
        (save-excursion
          (goto-char beg)
          (newline))
        (indent-region beg end)))))

(sp-local-pair 'c-mode "{" nil :post-handlers '(:add my-sp-wrap-with-brackets))
```

**Comment by Fuco1** [comment]
For the `:beg-in` magic, check the docs of macro `sp-get`.

**Comment by Fuco1** [comment]
As for `kill-region`, you can use `delete-and-extract-region` which gives you back the string and deletes (safely) the content.

**Comment by Fuco1** [comment]
Finally, a general emacs hack is the following idiom

```elisp
(let ((kill-ring kill-ring))
  ;; whatever code here, kill ring is protected
  )
```

This protects the `kill-ring` which is dynamic variable, after the let is gone the local binding is gone and global value is restored ;)  Another common usage to protect `this-command` is `(let (this-command) code-here)`

**Comment by fommil** [comment]
your wrapper is the best way to do it :smile:

but the final bracket is not indented. e.g. if I start with

```scala
  foo
  bar
```

I end up with

```scala
  {
    foo
    bar
}
```

instead of

```scala
  {
    foo
    bar
  }
```

**Comment by fommil** [comment]
simple fix, the first `newline` should be `newline-and-indent`.

This is awesome, thank you so much for looking into it! Now I see how you did it, it was very easy to implement using the sp API.

FYI this is my full C-like (scala here) config. I hope this function makes it into sp proper! Very useful.

```
(defun fommil-sp-wrap-with-brackets (_ action _)
  ;; by Fuco1
  ;; https://github.com/Fuco1/smartparens/issues/639
  (when (eq action 'wrap)
    (sp-get sp-last-wrapped-region
      (let ((beg :beg-in)
            (end :end-in))
        (save-excursion
          (goto-char end)
          (newline-and-indent))
        (save-excursion
          (goto-char beg)
          (newline))
        (indent-region beg end)))))

(sp-local-pair 'scala-mode "{" nil
               :post-handlers '(("||\n[i]" "RET") ("| " "SPC") fommil-sp-wrap-with-brackets))
```

**Comment by Fuco1** [comment]
Feel free to submit it to `smartparens-scala.el` (if we have that) or start one if we don't.  I usually grant commit rights to people who manage these language modes so they can improve them independently.

**Comment by fommil** [comment]
oh cool! I didn't know that existed. I should definitely add that and update our docs http://ensime.github.io/editors/emacs/hacks/
