### ISSUE TITLE
Smartparens seems to require a space after a closing quotation mark

### ISSUE THREAD

**Issue by zck** [Fuco1/smartparens#641]
Reproduction instructions:

Put this text in a text-mode buffer

    "Test"with no space until "I" say so

Put point at beginning (indicated with a `|`)

    |"Test"with no space until "I" say so

Then #'sp-forward-sexp, and I expected this to happen:

    "Test"|with no space until "I" say so

But this happens:

    "Test"with no space until "I"| say so

Smartparens version 20160706.649 from Melpa
Emacs 25.1.50.2 built from git version 466ee1b3ea76425d201b5d59950e88251870c836

**Comment by Fuco1** [comment]
In some modes which do not define the syntax properly (in text mode `"` is class `.` which is punctuation) we use a rule-based parsing heuristic.

Read the docs on `sp-get-textmode-stringlike-expression`.  The setting can be adjusted with `sp-navigate-use-textmode-stringlike-parser`.  If you disable it, we have another parser in place which tries to reconstruct the state 100% correctly, but can be so slow in places as to become inpractical.
