### ISSUE TITLE
Closing angle bracket in rust-mode not autoskipping

### ISSUE THREAD

**Issue by fmdkdd** [Fuco1/smartparens#642]
`emacs -Q`, with `(require 'smartparens-config)`, then `rust-mode` and `smartparens-mode`.

Type `T<`, and smartparens adds a matching closing angle bracket: `T<|>`.  Type `E>` and you get `T<E>|>`, regardless of the setting of `sp-autoskip-closing-pair`.

Same thing happens without the `E`.

smartparens version:  20160821.152
rust-mode version: 20160820.255
Emacs version: 24.5.1

**Comment by Fuco1** [comment]
Any chance `rust-mode` has its own paren handling which could cause conflicts?.  Could you also call `(sp-get-pair "<")` in a `rust-mode` buffer and paste here what it gives you?

**Comment by fmdkdd** [comment]
@Fuco1 Without smartparens, there is no auto-insertion of angle brackets pairs done by `rust-mode`.   There *is* a `rust-match-angle-brackets` custom variable, but it appears to be only used for font-locking.

Here is the output of `(sp-get-pair "<")` in `rust-mode`:

```
(:open "<" :close ">" 
 :actions (wrap insert autoskip navigate)
 :when (sp-rust-could-be-parameterized)
 :unless nil :pre-handlers nil :post-handlers nil)
```

**Comment by fmdkdd** [comment]
@Fuco1 Let me know If I can help in anyway to debug/fix this issue.  I am not familiar with the internals of smartparens, but I can write elisp.  Do you have maybe some intuition over the possible cause for this issue?  Some places I should look in particular?  Some important variables/functions?

**Comment by Fuco1** [comment]
Well, it's probably something in `sp-skip-closing-pair` or `sp-insert-pair` (which calls it as well, but usually there it only matters for opening delimiters).  Instrumenting it with edebug and stepping through should reveal something.

**Comment by Fuco1** [comment]
Also remember that the permissions system is totally fucked so it is entirely possible it uses some other permission for the check (like the `'insert` action)... For 2.0 I have an overhaul planned, but that's still a long way to go (I'm just finishing release 1.8).

**Comment by fmdkdd** [comment]
@Fuco1 Thanks for the hints. I will dive into it and try to find the cause.
