### ISSUE TITLE
Strange Colors/Text Appears on Specific Behavior

### ISSUE THREAD

**Issue by MellowMaroon** [Fuco1/smartparens#643]
If I have a string "%s", when I highlight the contents and type "\", a bunch of really strange characters appear.  I've seen this happen a few times before, but this is the only time I've been able to reproduce this.
I have delete-selection-mode enabled if that's relevant.

![smartparens](https://cloud.githubusercontent.com/assets/21314322/18057970/3ab0d022-6de0-11e6-97be-217a143b602c.png)

**Comment by Fuco1** [comment]
That's a feature, it shows you the possible pairings (green = openings, red = closings).  This happens because when a region is active, smartparens allows you to "wrap" it with a pair.

I think there's a toggle to disable it somewhere, look for settings with `sp-wrap` prefix.
