### ISSUE TITLE
sp-autoinsert-if-followed-by-word is not working for me

### ISSUE THREAD

**Issue by nivaca** [Fuco1/smartparens#645]
Hi, I am using smartparens (20160828.1136) but the `sp-autoinsert-if-followed-by-word` variable is not working for me. I have set it to `nil`, but smartparens keeps inserting both parentheses (opening and closing) right before a word. Like so:

![out](https://cloud.githubusercontent.com/assets/2309005/18321227/b3b4a386-74f2-11e6-912a-ef7d1ead06a2.gif)

Any ideas as to what's going on here?

Thanks!

**Comment by nivaca** [comment]
Just found out that the variable I needed to change was `sp-autoinsert-pair` (and not `sp-autoinsert-if-followed-by-word`).

**Comment by Fuco1** [comment]
That variable was removed and no longer does anything.  Where have you found it?  We should update the documentation or the source.

Current solution is to add a `:when` or `:unless` condition on the pair you want to disable.  There is currently no global solution.

**Comment by nivaca** [comment]
Thanks! This was pretty helpful. I still have a question, though. How can I make pairs like `\[ \]` work in this manner? For instance, this code doen't work as expected:

`(sp-local-pair 'latex-mode "\[" nil :unless '(sp-point-before-word-p))`

**Comment by Fuco1** [comment]
You need to escape the backslash, so instead of `"\[` use `"\\["`.  In elisp the former evaluates to just `"["`.

Don't forget to also add `sp-latex-point-after-backslash` predicate (which is included by default), it fixes some end-of-line silliness on this pair. (e.g. in tables when you end with `\\`)

**Comment by nivaca** [comment]
Thanks! That worked.
