### ISSUE TITLE
sp-unwrap-sexp cannot unwarp a string

### ISSUE THREAD

**Issue by ambjlon** [Fuco1/smartparens#647]
When the cursor is at the middle of a string, sp-unwrap-sexp cannot unwrap this string. 
For example, 
"he|ro", the cursor is at the behind of "e" charactor, but M-x sp-unwrap-sexp simply didn't work.
 
I think that "hero" is a sexp, but why does sp-unwrap-sexp not work?

How can unwarp a string?

**Comment by Fuco1** [comment]
Works for me.  What major mode are you using, and what emacs version?

**Comment by ambjlon** [comment]
emacs version 24.5.1
major mode: php-mode
I had updated smartparens from 20150710.202 to 20160828.1136 and the problem was solved.

**Comment by Fuco1** [comment]
OK, seems it *doesn't* work for me in `php-mode` :D  I'll check it out.
