### ISSUE TITLE
backtick and single quote should not be pairs in racket-mode

### ISSUE THREAD

**Issue by jgarvin** [Fuco1/smartparens#649]
Title pretty much says it all, like other lisps they are used for macros and quoting, not for delimiting anything.

**Comment by xiongtx** [comment]
This also occurs with docstrings in Clojure. A backtick is matched with a single quote, which is the right thing to do in Emacs Lisp but not Clojure. Instead, a backtick should be matched with another backtick.

Where is this behavior controlled in source?

**Comment by Fuco1** [comment]
https://github.com/Fuco1/smartparens/blob/master/smartparens-config.el#L66

You would need to write a new rule for clojure in `smartparens-clojure.el`

**Comment by Fuco1** [comment]
@jgarvin looking at `smartparens-racket.el` it seems that backtick is already disabled.  So what should be the correct behaviour?

**Comment by Fuco1** [comment]
Seems to be fixed in `smartparens-racket`.
