### ISSUE TITLE
TeX-electric-math

### ISSUE THREAD

**Issue by malb** [Fuco1/smartparens#652]
Hi there,

I'm trying to realise a better version of 

```
(setq TeX-electric-math '("\\(" "\\)"))
```

i.e. that any "$" gets replaced by "\(" and "\)", using smartparens. So far I've got:

```
(sp-local-pair '(tex-mode plain-tex-mode latex-mode org-mode) "$" "$"
                           :unless '(sp-point-before-word-p
                                     sp-point-before-same-p
                                     sp-latex-point-after-backslash))

(sp-local-pair '(tex-mode plain-tex-mode latex-mode org-mode) "\\(" "\\)"
                           :unless '(sp-point-before-word-p
                                     sp-point-before-same-p
                                     sp-latex-point-after-backslash)
                           :trigger "\$")
```

If I remove the first local pair for "$" then wrapping doesn't seem to work any more, i.e. selecting some text and pressing `$` would overwrite said text instead of wrapping it. When I keep it, wrapping works but it uses "$" instead of "\(" and "\)" Is this a bug or am I just using it wrong?

**Comment by Fuco1** [comment]
Yea, I think wrapping using the trigger isn't implemented.  Your best bet now would be to write a special handler for `$` pair and post-wrap change the delimiters to whatever you need.

I'll tag this as enhancement, but I'm not sure when I'll get to it.

**Comment by malb** [comment]
Thanks, I'll give that a try.

**Comment by Fuco1** [comment]
```elisp
(sp-local-pair 'latex-mode "$" nil :post-handlers '(:add my-latex-replace-dollar))

(defun my-latex-replace-dollar (_id action _context)
  (when (eq action 'wrap)
    (sp-get sp-last-wrapped-region
      (let ((at-beg (= (point) :beg-in)))
        (save-excursion
          (goto-char :beg)
          (delete-char :op-l)
          (insert "\\("))
        (save-excursion
          (goto-char :end-in)
          (delete-char :cl-l)
          (insert "\\)"))
        (setq sp-last-wrapped-region
              (sp--get-last-wraped-region
               :beg :end "\\(" "\\)"))
        (goto-char (if at-beg (1+ :beg-in) :end))))))
```

This should work.  It's not so simple as I thought since you have to update the `sp-last-wrapped-region` properly for the rest to work.

In the future this should all be simplified by allowing the trigger for wrapping as well.

**Comment by malb** [comment]
Nice! Ta!

**Comment by Fuco1** [comment]
I'll spin a new task from this to add the wrap trigger.  Thanks for the suggestion.

**Comment by Fuco1** [comment]
@malb A new keyword `:trigger-wrap` was added, so you can now simplify the setup to just something like

    (sp-local-pair 'latex-mode "\\(" "\\)" :trigger-wrap "$")

(adjust to modes where you want to use this)

**Comment by malb** [comment]
Great, thanks! I'm using

```
            (sp-with-modes
                '(tex-mode plain-tex-mode latex-mode)

              (sp-local-pair "\\(" "\\)"
                             :unless '(sp-point-before-word-p
                                       sp-point-before-same-p
                                       sp-latex-point-after-backslash)
                             :trigger-wrap "$"
                             :trigger "$")

              (sp-local-pair "\\[" "\\]"
                             :unless '(sp-point-before-word-p
                                       sp-point-before-same-p
                                       sp-latex-point-after-backslash)))
```

FWIW the only behaviour I'm observing which doesn't quite replace 

```
(setq TeX-electric-math '("\\(" "\\)"))
```

is when I type `$` when right before a word e.g. 

1. `|Word` 
2. press `$` 
3. I get `$$Word` presumably because I'm suppressing the `\(` `\)` pair from triggering.

**Comment by Fuco1** [comment]
Yea, that would be it.  What would you like to happen?  If you won't figure it out open a new issue, that seems like a different problem :)

**Comment by malb** [comment]
Giving it one more try here to see if this is worth an issue or not, might be rightfully considered a non-issue:

I'd like:

1.`|Word`
2. press `$`
3. get `\(Word`

Is that within scope?
