### ISSUE TITLE
Wrapping with double-quotes chops off ending character

### ISSUE THREAD

**Issue by dakrone** [Fuco1/smartparens#655]
Given the following region from left-to-right:

```
|blah|
```

(`|` used to denote what is part of the region), hitting `"` to wrap with double-quotes gives me the following:

```
"bla"
```

Chopping off the 'h' at the end.

**Comment by dakrone** [comment]
Here's my configuration for Smartparens, if it's helpful: https://gist.github.com/dakrone/03176fceafff24eef2376798004f5e70

**Comment by dakrone** [comment]
Actually, please ignore, I had `electric-pair-mode` enabled at the same time, sorry for the confusion!

**Comment by Fuco1** [comment]
Maybe I could add a warning when we detect other parens mode is active.
