### ISSUE TITLE
How to disable smartparens-mode completely in some mode?

### ISSUE THREAD

**Issue by c02y** [Fuco1/smartparens#657]
I enable **smartparens-mode** globally, but since **LaTeX-electric-left-right-brace** is more useful for tex file, so I disable sp using **(turn-off-smartparens-mode)** inside **LaTeX-mode-hook** (Emacs+AUCTeX), it is disabled from the start, but sp will always be triggered somehow after some time of editing tex file, typeing **{** will insert **{}}**, I don't know what triggered it, then I have to disable sp using **M-x smartparens-mode**, so I don't know how to completely in LaTeX-mode. Any idea?

**Comment by Fuco1** [comment]
Add the mode to `sp-ignore-modes-list`
