### ISSUE TITLE
Autoescape broken without autoinsert?

### ISSUE THREAD

**Issue by muflax** [Fuco1/smartparens#658]
So I don't use auto-insertion of pairs, like so:

    (setq       	sp-autoinsert-pair                     	nil)
    (setq       	sp-cancel-autoskip-on-backward-movement	nil)
    (setq       	sp-autodelete-pair                     	nil)
    (set-default	'sp-autoskip-opening-pair              	nil)
    (set-default	'sp-autoskip-closing-pair              	nil)

But that seems to break the new auto-escaping of quote characters. In Ruby or Emacs Lisp for example, I can't close quotes because the second quote character always auto-escapes. I tried setting `sp-escape-quotes-after-insert` and `sp-escape-wrapped-region` to nil, but that changes nothing.

(If there's an obvious debug point, I can take a look in case any of my other configs cause the breakage, but I didn't see any.)

**Comment by Fuco1** [comment]
Remove the `escape` action from the pair. `(sp-pair ... :actions '(:rem escape))`

**Comment by muflax** [comment]
You're sure that's right? `sp-pair` doesn't indicate that this as a valid option (ie `:rem` in a list; it only mentions `:rem` instead of a list to remove a pair completely, though it doesn't mention `escape` either). 

Also, that removes all my actions on strings, so I lose `wrap` etc. I can of course just explicitly state them instead of the default list, which is what I'm currently doing:

    (sp-pair "\""	"\""	:actions '(insert wrap autoskip navigate))
    (sp-pair "'" 	"'" 	:actions '(insert wrap autoskip navigate))

but it's surprising that that's apparently necessary.

**Comment by Fuco1** [comment]
Sorry, `:rem` only works like that for local definitions.  What you're doing is probably correct.

Your use-case is pretty rare so the interface isn't optimized for that... which is not to say that it doesn't suck.  I'm currently drafting new interface which will address most of the oddities of the current system.

I'll have to update the docstring, thanks for catching that.

**Comment by muflax** [comment]
Thanks! Sounds good, I'll just keep the (pretty minor) workaround until then.

**Comment by Fuco1** [comment]
Okey, I'm going to close this then since we solved it (albeit in a suboptimal way).  For now, I'm going to put more focuse on finishing the next release than optimizing for a rare case, I'm sure you understand.
