### ISSUE TITLE
non-strict mode being very strict with matching unmatched parens

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#665]
since a recent melpa upgrade, I've been getting errors in non-strict scala-mode. An example file looks like this (point is at `^^^`, which is just an indicator) and then type `"` to close off `"bootstrap`

``` scala
ensimeScalaCompilerJarModuleIDs := {
  val v = (scalaVersion in LocalProject("bootstrap^^^)).value
  Seq(
    scalaOrganization.value % "scala-compiler" % v,
    scalaOrganization.value % "scala-library" % v,
    scalaOrganization.value % "scala-reflect" % v,
    scalaOrganization.value % "scalap" % v
  ).map(_ % org.ensime.EnsimePlugin.EnsimeInternal.name intransitive ())
}
```

but I get this stacktrace instead :cry: 

```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  sp--escape-region(("\"") 138 139)
  sp-escape-open-delimiter()
  sp--post-self-insert-hook-handler()
  self-insert-command(1)
  funcall-interactively(self-insert-command 1)
  call-interactively(self-insert-command nil nil)
  command-execute(self-insert-command)
```

Anything obvious broken here or should I go investigate when it bothers me enough?

**Comment by Fuco1** [comment]
I can't repro this.  Would you mind testing this on the latest master?

The result I get in both strict and non-strict mode is an insertion of `\"`

**Comment by fommil** [comment]
I can confirm I still get it with the latest stable release, I'll try melpa unstable later today.

**Comment by fommil** [comment]
yes, confirming I still get it on melpa unstable.

Hmm, must be something in my config then.

**Comment by Fuco1** [comment]
What version of `scala-mode` do you have?  Apparently mine is ancient (scala-mode-20141205.1251).  I'll upgrade that and try again.

**Comment by fommil** [comment]
I always run the most recent version of `scala-mode`. My config is public https://github.com/fommil/dotfiles/blob/master/.emacs.d/init.el#L611-L746

**Comment by Fuco1** [comment]
After upgrading I get the behaviour described in OP.

The quote character before `bootstrap` has "punctuation" syntax, which is something quite odd and I think might be the issue.  In the old version it had string syntax which is why it worked.

Oh how much I hate font-lock syntax hacks :)

**Comment by fommil** [comment]
thanks for the workaround! I think our `scala-mode` regexes really need an overhaul. They can also be quite slow sometimes. Somebody wrote some good ones for Sublime but I just haven't had the motivation to look into it.
