### ISSUE TITLE
Broken autoskip in python-mode in certain contexts

### ISSUE THREAD

**Issue by rsbowman** [Fuco1/smartparens#668]
When I insert a pair inside a string in python mode following a backslash continued line, autoskip does not work.  For example, when point is at "|" here:

``` python
from sys import stdin, \
    stdout

a = "|"
```

and I press "()" I end up with the string "())".  This is especially bad for Python format strings which use {} lots.

When inserting before the backslash continued line there is no issue.  Furthermore, if I change backslash to be an escape character with

```(modify-syntax-entry ?\\ "\\" python-mode-syntax-table)```

I get the correct autoskip behavior (although I'm not sure what other consequences this might have for Python editing).

I get this behavior under 24.5.1 and snapshot 26.0.50.2, and I can reproduce it with a bare config that only loads smartparens.  I've only noticed it in python-mode but I don't have any reason to believe that it's Python specific.

I'd appreciate any help you can offer towards a more complete solution than modify-syntax-entry.  (Or confirmation that that's the right way to go.)  Thanks for the excellent package!  :heart:  :clap:

**Comment by Fuco1** [comment]
I think it is python specific in as much as `python-mode` not declaring the backslash to be escape syntax.  

Try to set `sp-escape-char` to `"\\"` in python hook or some time after you load python mode and see if it goes away.

**Comment by rsbowman** [comment]
`(set-local sp-escape-char "\\\\")` in my `python-mode-hook` works perfectly, thanks so much!

**Comment by Fuco1** [comment]
Thanks for confirming this.  We should add it to `smartparens-python.el` then.  Would you be interested in providing a patch?

**Comment by rsbowman** [comment]
Sure, but I noticed the same problem in c++-mode with escaped characters in strings; for example,

``` cpp
std::string a = "foo\nbar";
"|";
```

gives the same behavior as in python mode.   The same solution works (setting `sp-escape-char`) but the confusing thing is that `C-h s` tells me that `\` is an escape char...  This is on snapshot 26.0.50.2.

Do you know what's going on here?

**Comment by Fuco1** [comment]
Ouch, okey.  I'll look into the detection mechanism then, maybe it is broken after all.

**Comment by Fuco1** [comment]
I think this was duplicate of #669, can you please check?

**Comment by rsbowman** [comment]
Works beautifully!  Thanks very much!

**Comment by Fuco1** [comment]
Thanks for the confirmation!
