### ISSUE TITLE
duplicate closing brace after \t

### ISSUE THREAD

**Issue by unhammer** [Fuco1/smartparens#669]
After writing `\t` and then `[`, the closing `]` is inserted. Then, when typing the `]` to skip over the closing brace, a second `]` is inserted. This doesn't happen if there's no `\t` before. Newlines after the `\t` don't help, and it goes for other parens types too. Extra `\t`'s do not cancel the effect.

See https://asciinema.org/a/1uzd1icbenzjtrif1d55w0lty for demonstration running under emacs -Q.

[![asciicast](https://asciinema.org/a/1uzd1icbenzjtrif1d55w0lty.png)](https://asciinema.org/a/1uzd1icbenzjtrif1d55w0lty)

**Comment by Fuco1** [comment]
Thanks, this looks annoying, I'll look into it.
