### ISSUE TITLE
What is `sp-kill-hybrid-sexp` designed to be ?

### ISSUE THREAD

**Issue by Yevgnen** [Fuco1/smartparens#676]
Hi,

Thanks for the great package. I have a question about `sp-kill-hybrid-sexp`. At first I wonder `sp-kill-hybrid-sexp` will only work for s-exp in lisp, therefore I asked a [question](http://emacs.stackexchange.com/questions/28729/how-to-make-sp-kill-hybrid-sexp-work-with-custom-local-pair) .

But now I find that `sp-kill-hybrid-sexp` seems work for global pairs defined by `sp-pair`. For example, having `(sp-pair "《" "》")`, I can kill `《Foo ! bar》` anything after `!`, leaving the `《Foo !》`, where `!` is the cursor.

So does `sp-kill-hybrid-sexp` ONLY work for global pairs or there are bugs in killing between local pairs ? Thanks!

**Comment by Fuco1** [comment]
It works with all pairs, it just doesn't work with strings, probably.  What mode did you try the single-quote sexp in?  It works in `python-mode` for example.

```python
'asdasd asdas| dasdas dasd'
# gives
'asdasd asdas|'
```

SP doesn't care if the definition is local or not as at the moment of buffer creation the local list is compiled by merging the global and local definitions.

**Comment by Yevgnen** [comment]
Hi, thanks for you reply. I confirm it works in `python-mode`, but failed in `matlab-mode`, with the minimal config 

```
(package-initialize)
(use-package smartparens-config
  :ensure smartparens
  :init
  (setq sp-autoescape-string-quote nil
        sp-highlight-pair-overlay nil
        sp-base-key-bindings 'paredit)

  (add-hook 'prog-mode-hook #'smartparens-mode)
  (add-hook 'matlab-mode-hook #'smartparens-mode)

  :config
  (smartparens-strict-mode t)
  (show-smartparens-global-mode t)

  (bind-keys :map smartparens-mode-map
             ("C-M-k" . sp-kill-hybrid-sexp))
  
  (sp-with-modes 'matlab-mode
    (sp-local-pair "'" nil :unless '(sp-point-after-word-p))))

```

**Comment by Fuco1** [comment]
Then it seems it's probably something to do with syntax definition in `matlab-mode`.  We'll look into it :)

**Comment by Fuco1** [comment]
Hi.  Is this problem fixed with `(modify-syntax-entry ?' "\"")`?  I'm not sure if it's a great idea to add this code to smartparens since I don't understand why the syntax is set as it is by default.  Do you have any problems using this setup?

**Comment by Yevgnen** [comment]
Hi, it seems that there are still some problems with this setting. After the syntax entry modification, `sp-kill-hybrid-sexp` works sometimes while sometimes not. For example
![sp](https://cloud.githubusercontent.com/assets/16749790/21673344/78c97678-d363-11e6-8dd0-7558e8b6cd96.gif)

We can see that at least two issues here. At the beginning, `sp-kill-hybrid-sexp` worked as expected. This is looks like because there's no single quote(matrix/vector transpose) in the buffer. Then at the second `fprintf`, `sp-kill-hybrid-sexp` killed to the wrong position where some chars before the right position('underkill', in my true snippets, it sometimes 'overkill` the contents). Please note that `...` is a multi-line source code notation for matlab files.

Also, we can see that at the last ')', it warned `Unmatched expression.`. Putting the content into single line of the last `fprintf` call did not fix the problem. So I guess it's related to the `'`, not the multi-line syntax.

The test is under small config

```elisp
(package-initialize)

(require 'use-package)
(require 'smartparens)

(setq sp-autoescape-string-quote nil
      sp-highlight-pair-overlay nil
      sp-base-key-bindings 'paredit)

(smartparens-strict-mode t)
(show-smartparens-global-mode t)

(bind-keys :map smartparens-mode-map
           ("<backspace>" . sp-backward-delete-char)
           ("C-d" . sp-delete-char)

           ("C-M-k" . sp-kill-hybrid-sexp)
           ("C-M-t" . sp-transpose-sexp)

           ("C-M-f" . sp-forward-sexp)
           ("C-M-b" . sp-backward-sexp)

           ("C-M-n" . sp-next-sexp)
           ("C-M-p" . sp-previous-sexp)

           ("M-F" . sp-forward-symbol)
           ("M-B" . sp-backward-symbol)

           ("C-M-d" . sp-down-sexp)
           ("C-M-a" . sp-backward-down-sexp)
           ("C-M-e" . sp-up-sexp)
           ("C-M-u" . sp-backward-up-sexp)

           ("C-S-a" . sp-beginning-of-sexp)
           ("C-S-e" . sp-end-of-sexp)

           ("C-)" . sp-forward-slurp-sexp)
           ("C-(" . sp-forward-barf-sexp)
           ("M-)" . sp-backward-barf-sexp)
           ("M-(" . sp-backward-slurp-sexp)

           ("M-s" . sp-splice-sexp)
           ("M-<up>" . sp-splice-sexp-killing-backward)
           ("M-<down>" . sp-splice-sexp-killing-forward)
           ("M-r" . sp-splice-sexp-killing-around)

           ("M-i" . sp-change-inner)
           ("M-o" . sp-change-outer))

(sp-with-modes 'matlab-mode
  (sp-local-pair "'" nil :unless '(sp-point-after-word-p) :actions '(insert wrap autoskip)))

(defun sp/fix-matlab-single-quote ()
  (modify-syntax-entry ?' "\""))
(add-hook 'matlab-mode-hook #'sp/fix-matlab-single-quote)

(require 'matlab)
(add-hook 'matlab-mode-hook #'smartparens-mode)
```

**Comment by Fuco1** [comment]
@vxe What do you mean by that? It should work but will only work with pairs, there's no code to handle the indentation structure.

**Comment by vxe** [comment]
if the cursor is at the beginning of any block like construct (class, def, if, for) it will kill that construct and if its a single line statement it will behave like a normal kill (my workaround does not do this).  

This works wonderfully for curly languages out of the box, but for python `sp-kill-hybrid-sexp` is indistinguishable from `kill-line` for me

**Comment by Fuco1** [comment]
This package works with pairs of characters and not the implicit indentation structure that python uses.  It can be worked in somehow but it's not supported yet.

**Comment by vxe** [comment]
ughh, I see now, it works on brace languages because you match on brace pairs.  ignore me then.


here's the glorified keyboard macro I'm using to deal with indentation

```elisp
(defun vxe:python-kill-hybrid-sexp-hack ()
  (interactive)
  (let ((block-indicators (list "class" "if" "else" "elif" "def" "for" "try" "except"))
        (keyword-region '())
        (blk-region '()))
    (add-to-list 'keyword-region (point))
    (set-mark (point))
    (forward-word)
    (add-to-list 'keyword-region (point))
    (if  (member (buffer-substring-no-properties (first keyword-region) (second keyword-region))
                block-indicators)
        (progn
          (backward-word)
          (setq deactivate-mark 1) 
          (add-to-list 'blk-region (point))
          (set-mark (point))
          (python-nav-forward-sexp)
          (add-to-list 'blk-region (point))
          (kill-region (first blk-region) (second blk-region)))
      (progn
        (backward-word)
        (setq deactivate-mark 1)
        (call-interactively 'sp-kill-hybrid-sexp)))))
```

**Comment by Fuco1** [comment]
I checked on the latest matlab-mode version and the issues from the gif are all fixed.  The other python issue is not related to OP, so I'm going to close this.

**Comment by vxe** [comment]
regarding python issue, the solution is to use [Combobulate](https://github.com/mickeynp/combobulate) mode + treesitter mode
