### ISSUE TITLE
How to insert <> in C++ code?

### ISSUE THREAD

**Issue by c02y** [Fuco1/smartparens#679]
When I'm editing C++ code, the `<` key will insert ` < |`, the `|` is the position after typing `<` symbol, this is perfect when you use `<` as less-then, what if I want to insert something like:

    std::vector<int>

it will become

    std::vector < int >

and I have to delete the spaces manually.

**Comment by Fuco1** [comment]
Check what function is bound on `<`, this sounds like some other mode doing this.

**Comment by c02y** [comment]
< runs the command c-electric-lt-gt, which is an interactive compiled Lisp function in `cc-cmds.el'.

**Comment by Fuco1** [comment]
This is managed by `c++-mode`.  We could add some compat but I'm not in a position to do that as I'm not a C++ user.

**Comment by Fuco1** [comment]
I can't reproduce this with the electric flag turned on.  Did you use some other minor mode as well?

**Comment by c02y** [comment]
Sorry about this, I guess the problem was caused by [electric-operator](https://github.com/davidshepherd7/electric-operator), after I tweaked electric-operator a little, this is not a problem now, sorry about taking this so long.

**Comment by Fuco1** [comment]
No problem, I'm doing a cleanup and I've recently started writing C++ so I was curious how this worked as I couldn't replicate the problem.

Thanks for getting back to us!
