### ISSUE TITLE
inserting extra symbol on enclose region with pair

### ISSUE THREAD

**Issue by oneness** [Fuco1/smartparens#681]
Steps:
1. select a region
2. Type the symbol
3. End up with extra symbol at the end

For example, select the word foo, then type " and it becomes "foo"". See the extra " here.

**Comment by oneness** [comment]
Found the issue, not a but in sp but rather the enabling of electric-pair-mode. Once you turn that off, it works thus closing.

**Comment by nickmccurdy** [comment]
If it helps anyone in the future, double check that you've disabled `electric-pair-mode` mode in customize and your hooks.
