### ISSUE TITLE
how to disable the popup messages in min-buffer

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [Fuco1/smartparens#682]
sometimes the messages in min-buffer is useful until there are many codes in window
so I want to know how to disable it.

<img width="589" alt="2016-12-09 2 40 17" src="https://cloud.githubusercontent.com/assets/16307328/21040087/89c9fb74-be1d-11e6-91d6-0999ce992707.png">

**Comment by Fuco1** [comment]
This is not a smartparens feature.
