### ISSUE TITLE
Configuration: never add pair inside strings

### ISSUE THREAD

**Issue by sooheon** [Fuco1/smartparens#683]
How can I achieve the behavior of never auto inserting a pair or auto deleting pairs when editing inside strings? This is often an annoyance:

For example, with the default config with smartparens-strict-mode, try typing the following:

"("

It's just not happening because the pair comes along together, and gets deleted together.

**Comment by Fuco1** [comment]
You can use `C-q (` to insert only the opening delimiter (`C-q` runs quoted insertion, it's a built-in emacs function).

Currently you can't disable this globally, you would need to add a permission on every pair to stop insertion inside strings.  It's documented in the wiki.

**Comment by sooheon** [comment]
Thanks for the pointer. For posterity, if you want the above behavior, you need something like the following in your config, repeated for every delimiter:

` (sp-pair "(" nil :unless '(sp-in-string-p))`

**Comment by Fuco1** [comment]
I've been playing with the idea of global conditions but so far you're the first person who actually asked for it, so I think there's not much demand and it would complicate things.  If more people make the request I will consider adding such a feature.

Thanks for bearing with us :)
