### ISSUE TITLE
Configuration: do not escape pair \(

### ISSUE THREAD

**Issue by sooheon** [Fuco1/smartparens#684]
The recommended way to remove a default pair is:

`(sp-pair "\\(" nil :actions :rem)`

However,  if you try the above and try typing `\(`, you get `\()`, which is even worse than the default of `\(\)`, because it is unbalanced. I've tried something weird like:

`(sp-pair "\\(" "" :actions '(insert))`, which seems to work, but then navigation commands such as `sp-end-of-sexp` hangs indefinitely. 

What is the correct way to customize so that escaped delimiters such as `\(` `\)` `\[` `\{` are never treated as pairs? 

Thank you.

**Comment by Fuco1** [comment]
You get `\\()` because it pairs `(` with `)`.  If you want to remove such behaviour you would need to write your own check and add it into the `:unless` condition for the `(` pair.

**Comment by sooheon** [comment]
Thanks. Do you think we could use a fn like this is smartparens master?

```
(defun sp-after-backslash-p (id action context)
    (when (eq action 'insert)
      (save-excursion
        (backward-char 1)
        (looking-back "\\\\"))))
```

**Comment by Fuco1** [comment]
Sure! Feel free to open a pull request.

**Comment by Fuco1** [comment]
We should add a feature that would check the `sp-escape-char` and if the escaped pair is not configured treat it as non-pairable.

**Comment by Fuco1** [comment]
I've added the snippet from above as `sp-char-escaped-p`.
