### ISSUE TITLE
What about a `sp-mark-sexp` that behaves like `mark-sexp` but with smartparens's notion of sexp?

### ISSUE THREAD

**Issue by oantolin** [Fuco1/smartparens#685]
Is there a good reason not to include a `sp-mark-sexp` command that is just like `mark-sexp` but internally using `sp-forward-sexp`? It seems odd to have smartparens versions of `forward-sexp`, `backward-sexp`, `kill-sexp`, `transpose-sexp`, but not `mark-sexp`.

It can be implemented by copying the source code of the builtin `mark-sexp` and replacing `forward-sexp` with `sp-forward-sexp`.

I know (in the `sp` keybindings) I can use `C-M-S-f` if `shift-select-mode` is `t`, but my fingers are used to `C-M-SPC`, so I have a `sp-mark-sexp` for personal use. I think it makes sense to add it to smartparens.

**Comment by Fuco1** [comment]
Seems to me this is the same as `sp-select-next-thing-exchange`.  When I wrote these I wasn't very fluent in emacs lingo :) 

Try it out, if it behaves like `sp-mark-sexp` should we can add an alias.

**Comment by oantolin** [comment]
They behave identically when called once, possibly with a numeric
argument. But they differ when called several times in a row.

Consider the following S-expression:
`(a b (c (d e f)) (g h (i j k)) (l m n))`

For example, if you are just to the left of `(c` both
`sp-select-next-thing-exchange` and the builtin `mark-sexp` when
called with the numeric argument 3 will select until until after `n)`.
That is, using `<` for point and `>` for mark, you get this:

`(a b <(c (d e f)) (g h (i j k)) (l m n)>)`

But if instead of calling them with the argument 3, you call them with
no argument 3 times in a row they do very different things:

`mark-sexp` just selects additional S-expressions to the right:

1. `(a b <(c (d e f))> (g h (i j k)) (l m n))`
2. `(a b <(c (d e f)) (g h (i j k))> (l m n))`
3. `(a b <(c (d e f)) (g h (i j k)) (l m n)>)`

`sp-select-next-thing-exchange` descends into the sexp on succesive
calls:

1. `(a b <(c (d e f))> (g h (i j k)) (l m n))`
2. `(a b (<c (d e f)>) (g h (i j k)) (l m n))`
3. `(a b (<c> (d e f)) (g h (i j k)) (l m n))`

The behaviour of `mark-sexp` is, as you'd expect, analogous to
`mark-word`, `mark-paragraph`, etc. I still think that since
smartparens has pair-aware versions of lots of Emacs's `*-sexp`
commands it would make sense for there to be a `sp-mark-sexp`. (The
one I'm using now is literally what you get by taking the source code
of `mark-sexp` and replacing `forward-sexp` with `sp-forward-sexp`.)

(By the way, I just realized I don't really know what the `next`
family of functions do. I'll play around for them to get a feel for
when I'd want `next` instead of `forward`.)

**Comment by Fuco1** [comment]
Okey.  I never really used `mark-sexp` so I had a vague idea of what it is.  I'm happy to add a SP version of it if it is not yet included.

Would you care cooking up a pull request with your code, since as I understand it you already implemented this :)  Thanks!

**Comment by oantolin** [comment]
Sure, I've been meaning to (re)learn how to do that.

**Comment by oantolin** [comment]
Done. It's #686.
