### ISSUE TITLE
Strict mode: allows insertion of unmatched closing pair but skips over on backspace

### ISSUE THREAD

**Issue by crowding** [Fuco1/smartparens#688]
SP allows insertion of an unmatched closing delimiter:

    "[this (is a | ) test]" -> `]`
    "[this (is a ]| ) test]"

but (when in strict mode) sometimes makes it difficult to delete an unmatched delimiter:

    "[this (is a ]| ) test]" -> DEL
    "[this (is a |] ) test]"

It would be preferable if one of these two didn't happen in strict mode.

**Comment by Fuco1** [comment]
Yes, the insertion should be impossible.

**Comment by Fuco1** [comment]
This is a duplicate of #421 which was recently fixed, so this problem should be gone.
