### ISSUE TITLE
sp-backward-delete-char mistakes end of line in comint buffers as end of buffer

### ISSUE THREAD

**Issue by dwcoates** [Fuco1/smartparens#690]
sp-backward-delete-char seems to not work at end of line in comint buffers. It thinks it's at the end of the buffer when at the end of the line. 

`C-e sp-backward-delete-char` yields `End of buffer`

Occasionally it also hangs. Some `C-g` spam successfully quits

**Comment by Fuco1** [comment]
Thanks for the report.  Comint is our eternal enemy, it does *weird* shit :P

**Comment by dwcoates** [comment]
I still love it, though <3
