### ISSUE TITLE
In js2-mode, killing a line right before an expression breaks next line's indentation

### ISSUE THREAD

**Issue by davazp** [Fuco1/smartparens#696]
The probem happens with `js2-version` 1.8.5 and smarparents from melpa: `smartparens-20170104.410`. I tried with Emacs 25.1 and no extra configuration besides js2-mode and smartparens.

To reproduce it:

```javascript
function f () {
  <|>
  return 42;  // 2 spaces of indentation
}
```

After `C-k`, I get:

```javascript
function f () {
<|> return 42;  // 1 space of indentation, point at the beginning of the line
}
```

**Comment by davazp** [comment]
As a workaround, I defined the following advice to get it as with the other modes:

```emacs-lisp
  ;; Fix weird behaviour in js2-mode when we kill an empty line right
  ;; before an expression.
  (defun davazp/reindent-after-sp-kill-hybrid-sexp (&rest args)
    (when (eq major-mode 'js2-mode)
      (indent-for-tab-command)))
  (advice-add 'sp-kill-hybrid-sexp :after #'davazp/reindent-after-sp-kill-hybrid-sexp)
```

**Comment by davazp** [comment]
I looked at the problem, it seems to be  in the `sp--cleanup-after-kill` function, but it looks intentional:

```emacs-lisp
(unless (memq major-mode sp-no-reindent-after-kill-modes)
   ...
```

and `js2-mode` is listed in `sp-no-reindent-after-kill-modes`. Why is that?

**Comment by Fuco1** [comment]
To be honest I don't remember :/ Maybe it was a hack for some earlier version when things were broken.

Would you mind removing it from the list and test to see if it works or not?

**Comment by davazp** [comment]
Sure 👍 .  It seems to work, at least in that simple case, but I will try for the next days to see if it breaks with other code.

**Comment by davazp** [comment]
I have used it this week and I cannot find any issue related to it.

Maybe somebody else can also have a look?

**Comment by Fuco1** [comment]
I'll look at the `git blame` output to find some context but I think it will be safe to remove.  Thanks for reporting back!
