### ISSUE TITLE
[clojure] Goof with slurping set literals.

### ISSUE THREAD

**Issue by harold** [Fuco1/smartparens#698]
Hello, first, thanks for `smartparens`, it has improved my life measurably and I love it.

When writing clojure code I occasionally encounter the following situation...

I _want_ to slurp a set literal into some parens:
`(atom) #{}` :arrow_right: `(atom #{})`

So I arrange my cursor as:
`(❘atom) #{}` and execute `sp-forward-slurp-sexp`

And I arrive at the slightly awkward:
`(❘atom #){}`

And if I `sp-forward-slurp-sexp` again, I hit the syntactically invalid:
`(❘atom # {})`

---

In general, smartparens so assiduously avoids this kind of damage that I must assume this is but a minor blunder. With appreciation for your time, I'd love to gain insight here from someone more knowledgeable than myself about how this can be avoided.

**Comment by Fuco1** [comment]
Uh... we already fixed this but I forgot to add the autoload for clojure :P

Put `(require 'smartparens-clojure)` somewhere in your config for the meanwhile.

**Comment by harold** [comment]
Dreamy. That worked first try.

Glad to be of service; keep up the good work, as I said it's super-appreciated.

**Comment by Fuco1** [comment]
Thanks for the confirmation, cheers! :)
