### ISSUE TITLE
Better integration with hungry-delete?

### ISSUE THREAD

**Issue by therockmandolinist** [Fuco1/smartparens#705]
It seems sp-backward-delete-char clashes with/blocks hungry delete. Is there a way to integrate a fix into smartparens?

There was a workaround posted [on stackexchange](https://emacs.stackexchange.com/questions/29476/always-remove-brackets-by-pairs-fix-hungry-delete-mode-and-smartparens-strict/29484#29484) which may be relevant to this, though it doesn't seem to work very well for me (only works in the scratch buffer?)

**Comment by Fuco1** [comment]
We could probably wrap it and do what we do with subword mode.

**Comment by Fuco1** [comment]
Closed in #764.
