### ISSUE TITLE
Attempting to delete an apostrophe in `text-mode` may jump into a prior pair instead of deleting the apostrophe

### ISSUE THREAD

**Issue by braham-snyder** [Fuco1/smartparens#709]
With `smartparens-mode`, `smartparens-strict-mode`, `sp-navigate-use-textmode-stringlike-parser` set to its default `((derived . text-mode))`, and `(require 'smartparens-config)`, repeatedly calling `sp-backward-delete-char` from the end of this (in `text-mode`):

```
"foo" bar's
```

will first delete the trailing `s`, then skip over ` bar'`, jumping into the double quotes (just after `foo`). 

This bug is not limited to double quotes (e.g., backticks also cause this behavior).

edit: this issue might only apply to pairs with identical start and end characters (I'd originally written that the issue remained when the double quotes were replaced with parentheses, but I'm not seeing that behavior right now, nor with, e.g., `<foo> bar'`, nor `[foo] bar'`

**Comment by Fuco1** [comment]
I'll mark this as the duplicate even though you reported it first, just for the fact that the discussion evolved in the other task.  I will leave this open though and then close both of them when this is fixed.
