### ISSUE TITLE
How to stop inserting ending paren when in front of nonwhitespace?

### ISSUE THREAD

**Issue by introom** [Fuco1/smartparens#717]
Suppose | is the cursor position,

|foobar

how to make typing ( get (foobar, not ()foobar?

**Comment by Fuco1** [comment]
You can add the `:unless` property with `sp-point-before-word-p` predicate to the pairs you wish disabled in that situation.  For example:

```elisp
(sp-pair "(" ")" :unless '(sp-point-before-word-p))
```

**Comment by introom** [comment]
possible to add this configuration for all pairs?

All I have to do that manually for each pair ?

Thanks.

**Comment by Fuco1** [comment]
You will have to do this for each pair manually.  Beware that setting the `unless` globally will wipe all other settings which might be present from previous config.

I'm currently working on a better configuration DSL so this should get easier in the future.
