### ISSUE TITLE
Error: (use-package): smartparens :config Symbol's function definition is void: wrap

### ISSUE THREAD

**Issue by category** [Fuco1/smartparens#720]
## Expected behavior
Spacemacs startup without error

## Actual behavior
Spacemacs starts up with error:

`Error: (use-package): smartparens :config Symbol's function definition is void: wrap`

## Steps to reproduce the problem

`emacs --debug-init`

## Backtraces if necessary (`M-x toggle-debug-on-error`)

`emacs --debug-init` output [here](https://gist.github.com/category/404b0154fd4fbfed297d238902b3fd3b)

## Environment & version information

- `smartparens` version: /root/.emacs.d/elpa/smartparens-20170311.548 (I think that indicates the version)
- Emacs version (`M-x emacs-version`): 25.1.1
- OS: Centos7

**Comment by Fuco1** [comment]
This is a duplicate to #719.

**Comment by Fuco1** [comment]
However, this one has much nicer description, so I guess I'll close the other one ;D

**Comment by holocronweaver** [comment]
FWIW, issue also present in Emacs 25.1.91.1.
