### ISSUE TITLE
Remove "def" "end" pair from smartparens.

### ISSUE THREAD

**Issue by adc17** [Fuco1/smartparens#728]
## Expected behavior
Typing "def" doesn't autogenerate "end" when in ruby-mode.

## Actual behavior
Typing "def" does autogenerate "end" when in ruby-mode.

## Steps to reproduce the problem
`(sp-pair "def" "end" :actions :rem)` doesn't work as suggested in [pair management](https://github.com/Fuco1/smartparens/wiki/Pair-management#removing-pairs).
`(sp-local-pair ruby-mode "def" "end" :actions :rem)` is also unsuccessful. Apologies if I've misunderstood the configuration instructions.
n.b. I'm interested in removing all multi-line pairs (e.g. "do" "end" as well).

## Backtraces if necessary (`M-x toggle-debug-on-error`)
n\a on this occasion.

## Environment & version information

- `smartparens` version: 20170401.315
- Active major-mode: ruby-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.1.1
- OS: macOS Sierra

**Comment by Fuco1** [comment]
You need to quote the mode name symbol:

    (sp-local-pair 'ruby-mode "def" nil :actions :rem)

**Comment by Fuco1** [comment]
I see there is a missing quote in the docs, I've fixed that just now :blush:

**Comment by adc17** [comment]
Hmm, this throws `Error (use-package): smartparens :config: Wrong type argument: consp, nil`. Do you think it's a problerm with `use-package`?

**Comment by Fuco1** [comment]
I just executed it from the `M-:` prompt and it worked there.  Can you paste some minimal `use-package` example where it errors?

Also try to replace the `"end"` with `nil`, maybe it gets confused there for some reason (though it shouldn't I've tried both variants)

**Comment by adc17** [comment]
Sure, here's a minimal case where it errors:
```
(use-package smartparens
  :ensure t
  :init
  (add-hook 'prog-mode-hook 'smartparens-strict-mode)
  :config
  (use-package smartparens-config)
  (sp-local-pair 'ruby-mode "def" nil :actions :rem))
```
I've also tried without use-package, but I get the same error.
i.e. this doesn't work either:
```
  (require 'smartparens-config)
  (add-hook 'prog-mode-hook 'smartparens-strict-mode)
  (sp-local-pair 'ruby-mode "def" nil :actions :rem)
```
Like you, this works fine for me when I use the `M-:` prompt, but I can't get it to work in the `init` file.

**Comment by Fuco1** [comment]
It might be because the ruby config is not loaded yet, so you remove the pair in the config but when you open a ruby buffer it loads the SP config and adds the pair back.

I guess you would need to put that line in ruby init hook:

    (add-hook 'ruby-mode (lambda () (sp-local-pair 'ruby-mode "def" nil :actions :rem)))

**Comment by Fuco1** [comment]
Alternatively add an `eval-after-load` block for `'smartparens-ruby`

**Comment by adc17** [comment]
Thanks, the `eval-after-load` option works. 

I'm also using evil-smartparens, which still treats `def` `end` as a pair, even though I've disabled them. Is there anything in smartparens that might create that behaviour?

If I just remove the config line that calls `smartparens-ruby`, or create my own without the pairs, I don't get this problem. But if I load and _then_ remove the pairs, it creates issues.

**Comment by Fuco1** [comment]
I'm not sure, maybe `evil-smartparens` re-loads the configs somehow?

Either way I should document this somehow so that in the future people won't have to deal with this problem (loading after eval).

**Comment by adc17** [comment]
That solution definitely solves the initial problem, so I'll close this now.

I'll also try to figure out what's going on with `evil-smartparens`, and I'll open another issue if it's primarily `smartparens` that's creating the strange behaviour.
