### ISSUE TITLE
Unexpected behavior upon backspace over escaped double quote in Python

### ISSUE THREAD

**Issue by dsedivec** [Fuco1/smartparens#731]
## Expected behavior
Starting with point at `|` in `" \"| "`, pressing backspace yields either `" \| "` or (probably ideally) `" | "`

## Actual behavior
Starting with point at `|` in `" \"| "`, pressing backspace actually leaves you with `" \`

## Steps to reproduce the problem

* `emacs -Q`
* Get smartparens and dependencies in your `load-path` (I just did `(package-initialize)`)
* `(require 'smartparens-config)`
* Open a new python-mode buffer, e.g. `C-x C-f /tmp/scratch.py RET`
* `M-x smartparens-mode RET` to turn on smartparens-mode
* Type `" SPC SPC C-b "` which yields `" \"| "` with point at `|`
* Press backspace and you're left with `" \|"` with point at `|`

## Environment & version information

- `smartparens` version: Git a5f39550d4 (HEAD as of right now)
- Active major-mode: python-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0) of 2017-02-18
- OS: OS X 10.11.6

Thank you for Smartparens!

**Comment by Fuco1** [comment]
This does not happen on Emacs 24.5 so it must be some changes in the 25's version of python-mode that does this.  Probably they changed how syntax tables work (again! Ghahaah).

I guess downgrading isn't an option for you :D I still haven't made the push towards E 25, but there is increasingly so many bug reports related to this version that I might just do the switch (maybe over my easter vacation :))

Thanks for the report!

**Comment by Fuco1** [comment]
This is not actually a python problem but a general one.  I now see the mistake I made when trying to reproduce this (you used spaces around the escaped quote, I didn't.  I'm now working on a general fix.
