### ISSUE TITLE
`sp-convolute-sexp` in the middle of a sexp

### ISSUE THREAD

**Issue by xiongtx** [Fuco1/smartparens#734]
## Expected behavior

`sp-convolute-sexp` should detect whether point is in the middle of a sexp and move to end of sexp before convolving, instead of splitting the sexp.

E.g. in the following, where `|` is point:

```emacs-lisp
(foo (bar b|az (quux)))
;; M-x sp-convolute-sexp
;; => (bar b(foo az (quux)))
```

**Note**: `paredit` behaves similarly to `smartparens` in this regard, with a small difference:

```emacs-lisp
(foo (bar b|az (quux)))
;; M-x paredit-convolute-sexp
;; => (bar b (foo az (quux)))
```

Note the space after `b`.

## Actual behavior

`sp-convolute-sexp` splits the sexp at point, which is almost never what is intended.

## Steps to reproduce the problem

See examples above.

## Backtraces if necessary (`M-x toggle-debug-on-error`)

N/A

## Environment & version information

- `smartparens` version: `20170129`
- Active major-mode: `emacs-lisp-mode`
- Emacs version (`M-x emacs-version`): `25.1.50.1`
- OS: `Darwin C02RW05YFVH6 15.6.0`

**Comment by Fuco1** [comment]
Yea this is rather silly behaviour.  The question now is if it should go to the beginning or the end of the symbol (I suppose this is only an issue when the point is inside a symbol).

Would you be interested in providing a patch?  There's a predicate `sp-point-in-symbol` in smartparens that can be used to test whether point is inside a symbol and `sp-forward-symbol` to move to its end.

**Comment by xiongtx** [comment]
Thanks, created PR.

It also appears that there's another difference b/t `sp-convolute-sexp` and `paredit-convolute-sexp` in how they treat whitespace.

`sp-convolute-sexp`:

```emacs-lisp
(foo (bar    |baz))                     ; 4 spaces between bar/baz
;; sp-convolute-sexp
;; => (bar    (foo baz))
```

`paredit-convolute-sexp`:

```emacs-lisp
(foo (bar    |baz))
;; paredit-convolute-sexp
;; => (bar (foo baz))
```

Not sure if there's a use case for preserving extra whitespace?

**Comment by Fuco1** [comment]
Hm, `sp-convolute-sexp` already calls `indent-according-to-mode` if you do something with multi-line sexp but it doesn't clean up when on one line.  We could call `just-one-space` around the point or something like that, that would be cool indeed.

One GitHub tip, if you include the string `Fixes #issue` (you wrote `Address`) somewhere in the pull request post body it will automatically close the linked issue: https://github.com/blog/1506-closing-issues-via-pull-requests  Pretty cool feature :)

**Comment by xiongtx** [comment]
Took a look at `paredit-convolute-sexp` source and it says:

> The effects of convolution on the surrounding whitespace are pretty random.  If you have better suggestions, please let me know.

So :man_shrugging:; still, getting rid of extra whitespace is probably right behavior.

Another difference between `smartparens` and `paredit`:

`smartparens`:

```emacs-lisp
(foo (bar| baz))
;; sp-convolute-sexp
;; => (bar (foo |baz))
```

`paredit`:

```emacs-lisp
(foo (bar| baz))
;; paredit-convolute-sexp
;; => (bar |(foo baz))
```

Note that the location of point is different. 

I'm not sure which is better; is there a reason `smartparens` behaves as it does, or is it just something that occurred by chance?

>  if you include the string `Fixes #issue`

I prefer to manually close issues after there's agreement that it's fixed :smile:.

**Comment by Fuco1** [comment]
I usually want to stay inside the sexp.  Very often I use this with `sp-get` macro, sometimes when I realize I would like the inner form to be more complex, I convolute the get out of it and then continue adding stuff to the form.  So

```elisp
(when a (sp-get enc |:beg))  ;; start

(sp-get enc (when a |:beg))  ;; convolute

(sp-get enc (when a (|:beg)))  ;; wrap next with ()

(sp-get enc (when a (delete-region :beg |))) ;; insert more stuff

(sp-get enc (when a (delete-region :beg :end|)))
```

This is my usual workflow when using convolution.

**Comment by xiongtx** [comment]
Sounds good. We'll keep the current behavior then.

**Comment by xiongtx** [comment]
Just made a commit that adds a call to `just-one-space` to `sp-convolute-sexp`. Not sure if it's the most elegant way of handling this issue--it doesn't address the following case:

```emacs-lisp
(foo    (bar  |  baz))
;; sp-convolute-sexp
;; => (bar (foo    |baz))
```

I wonder if the `whitespace` can be utilized, but I can't see what it is because `sp-get` forms don't evaluate. E.g. for `inner-close`:

```emacs-lisp
(sp-get (sp-get-enclosing-sexp)
  (delete-and-extract-region
   (save-excursion
     (goto-char :end-in)
     (sp-backward-whitespace))
   :end))
```

throws an error:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  -(nil 0)
  (goto-char (- (plist-get struct :end) (length (plist-get struct :cl))))
  (save-excursion (goto-char (- (plist-get struct :end) (length (plist-get struct :cl)))) (sp-backward-whitespace))
...
```
