### ISSUE TITLE
Incorrect indentation with Emacs 26 and sp-splice-sexp-killing-backward

### ISSUE THREAD

**Issue by ptrv** [Fuco1/smartparens#742]
Hi,

commit 6fa9cc0593150a318f0e08e69ec10672d548a7c1 in emacs git introduced an improved version of `indent-sexp` and `lisp-indent-region` in lisp mode. With these changes indentation is incorrect after `sp-splice-sexp-killing-backward` (more precisely, after `sp--indent-region`) call.

## Expected behavior

Indentation should remain as it is

## Actual behavior

After calling `sp-splice-sexp-killing-backward` indentation is wrong

## Steps to reproduce the problem

Open `smartparens.el` and go to `sp--indent-region` function and put cursor to `|`

```emacs-lisp
(cl-letf ((|(symbol-function 'message) #'ignore))
      (indent-region start end column))
```
Call `sp-splice-sexp-killing-backward`. See how indentation is wrong now

## Environment & version information

- `smartparens` version: version `smartparens-20170424.505` from Melpa
- Active major-mode: `emacs-lisp-mode`
- Emacs version (`M-x emacs-version`): GNU Emacs 26.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.12) of 2017-04-30
- OS: GNU/Linux Fedora 25

**Comment by Fuco1** [comment]
Hi, first of all thanks for the report!

Excuse my ignorance, but what exactly is Emacs 26? I was under the impression that the latest release was 25.2.  Is this the "trunk" release?  I'm just asking so I know how to properly tag this.

**Comment by ptrv** [comment]
Yes, it's the trunk version

**Comment by ptrv** [comment]
I could reproduce the bug also without smartparens with emacs -Q and using `indent-region` on a `defun`. I found the issue while using smartparens commands and thought first it's related to sp. I reported the issue on emacs-devel mailinglist. Sorry for the noise.

**Comment by Fuco1** [comment]
Oh, okey, no problem :)
