### ISSUE TITLE
Performance Problem in Emacs 25.1

### ISSUE THREAD

**Issue by quanyufang** [Fuco1/smartparens#743]
## Expected behavior
Input quick, emacs's CPU cost few.

## Actual behavior
Input very slow, CPU almost 100%

## Steps to reproduce the problem

In a big php file, for example 2000 lines code , at the beginning of the file, try to input like
`define('SOME_DEFINE', 'SOME_VAL');`
when type the first ```, you will meet the prolem.

Additional information:
1. After some time(for example one hour) typing, Emacs become more and more slow.
2. Emacs 24.5 won't meet the problem

## Environment & version information

- `smartparens` version: elpa , smartparens-20170424.505
- Active major-mode:php-mode
- Emacs version (`M-x emacs-version`):25.1
- OS:Mac OS 10.12.4

**Comment by Fuco1** [comment]
@quanyufang Did you fix the issue or was this accidental close?
