### ISSUE TITLE
Local pair for inline code or italic words in org-mode?

### ISSUE THREAD

**Issue by tddsg** [Fuco1/smartparens#747]
Hi,

I'd like to ask if it is possible to make a local pair for inline code or italic words in org-mode? Currently, I don't know how to make `smartparens` using regular expression in defining local pair.

* Inline code is wrapped by a pair of `=`, where the left-`=` is succeeded by a non-whitespcae character, and the right-`=` is also preceded by a non-whitespace character. Forexample `=plus(1,2)=`

* Italic words are wrapped by a pair of `/` in the same concept. For example, `/italic/`

Thanks.

**Comment by Fuco1** [comment]
Absolutely is, look at [my own config](https://github.com/Fuco1/.emacs.d/blob/master/files/smartparens.el#L122) and take whatever you feel like you might need.

I have it on my TODO list to actually package this configuration in smartparens itself so it is available by default (for `org-mode`).

**Comment by tddsg** [comment]
Thank you so much! It works like a charm! :-D

**Comment by tddsg** [comment]
Hi,

Just a follow up from your setting for org-mode:

```
(sp-with-modes 'org-mode
  (sp-local-pair "*" "*" :actions '(insert wrap) :unless '(sp-point-after-word-p sp-point-at-bol-p) :wrap "C-*" :skip-match 'sp--org-skip-asterisk)
  (sp-local-pair "_" "_" :unless '(sp-point-after-word-p) :wrap "C-_")
  (sp-local-pair "/" "/" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC")))
  (sp-local-pair "~" "~" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC")))
  (sp-local-pair "=" "=" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC")))
  (sp-local-pair "«" "»"))
```
I can use the feature `sp-splice-sexp` for `\foo\` (italic) but not for `*foo*` (bold).
How to fix that for the pair `*...*` so that it will have any side effect with the headings of org?

**Comment by Fuco1** [comment]
Internally some time ago I have added some actions like `navigate` to better distinguish between various events SP has to handle.  The config probably comes from before then... the solution is to just add `navigate` into the `:actions` list on the pair and it should work.

Somehow I never used the splice on `**` pair in the last 3 years so I've never noticed :D (I use `//` a lot though)

**Comment by tddsg** [comment]
Maybe because you always prefer `//` to `**`? :-D 

I tried your suggestion, however, another error came up:

`sp--skip-match-p: Symbol’s function definition is void: sp--org-skip-asterisk`

I guessed that the function `sp--org-skip-asterisk` is now removed from your `smartparens`.
If I removed the part `:skip-match 'sp--org-skip-asterisk` from your configuration, when splicing the expression `*foo*`, only the first `*` was removed, and the result become `foo*`.

**Comment by tddsg** [comment]
Hi, just a follow-up from my comment above. 

I discover that the issue of splicing `*foo*` to become `foo*` happen when `*foo*` is at the end of the file, and there is no whitespace after it. Otherwise, splicing `*foo*` works file, i.e., when the text is in the middle of the file. The same issue happens to `/foo/`.

Here is my updated configuration for the pair `* *`, could you please give me your opinion about it?

`(sp-local-pair "*" "*" :unless '(sp-point-after-word-p sp-point-at-bol-p) :wrap "C-*")`

Thank you!

**Comment by Fuco1** [comment]
The function is somewhere in my config, it is there to prevent the initial `*` which are used for headlines to be treated as markup.
