### ISSUE TITLE
Add sp-backward-delete-symbol

### ISSUE THREAD

**Issue by amosbird** [Fuco1/smartparens#751]
This would be useful to bypass kill ring.

**Comment by Fuco1** [comment]
Do you need this for interactive use or from program?  From elisp you can temporarily let-bind `kill-ring` to preserve its value.

**Comment by amosbird** [comment]
hmm, I'm not aware of that. Could you show me an example?

**Comment by Fuco1** [comment]
This is the consequence of how dynamic binding works in elisp.

```elisp
(let ((kill-ring kill-ring))
  (do whatever))

;; after the `let' form `kill-ring' reverts to its old value
```

**Comment by amosbird** [comment]
oh, that won't work as expected IMO since my system clipboard will also store the kill ring content when `kill-word` happens.

**Comment by Fuco1** [comment]
If it happens through Emacs during the let binding it will revert.

**Comment by amosbird** [comment]
well, I tested this. It bypassed emacs kill ring but ends up in my system's clipboard.
```elisp
  (defun test-kill ()
    (interactive)
    (let* ((kill-ring kill-ring))
      (sp-backward-kill-symbol 1)))
```

**Comment by Fuco1** [comment]
Can you try it with also locally `let`-binding `select-enable-clipboard` to `nil`?

If it will work that way we can make a patch to SP to add the delete variants.  I don't mind much having that included.  Do you want to create a pull request then?

**Comment by amosbird** [comment]
ah, this works. pr #759
