### ISSUE TITLE
`\[' in LaTeX-mode should insert a closing `\]'

### ISSUE THREAD

**Issue by d125q** [Fuco1/smartparens#757]
## Expected behavior

Typing `\[` in `LaTeX-mode` should insert a closing `\]`, just like `\(` inserts a `\)`.

## Actual behavior

Typing `\[` inserts only a `]`.

## Steps to reproduce the problem

Straightforward.

## Environment & version information

- `smartparens` version: `243513e0d53846d7b47387f39ce538da515f6d2f`
- Active major-mode: `LaTeX-mode`
- Emacs version (`M-x emacs-version`): 26.0.50
- OS: Linux

**Comment by d125q** [comment]
I am sorry; this works as intended.

**Comment by Fuco1** [comment]
Hi.  For future reference, could you describe what was the problem?  So that people with a similar issue might find the solution.  Thanks!

**Comment by d125q** [comment]
My `.emacs` was kinda broken and `(require 'smartparens-latex)` was never evaluated.
