### ISSUE TITLE
smartparens interferes with delete-selection-mode when smartparens has been turned off

### ISSUE THREAD

**Issue by dsedivec** [Fuco1/smartparens#763]
## Expected behavior

In a buffer where smartparens-mode was on *but is now off*, and where delete-selection-mode is on, inserting any character while region is active always deletes the text in region before inserting the typed character.

## Actual behavior

Region becomes inactive, character is inserted at point.  Selection is not deleted as desired.

## Steps to reproduce the problem

1. Start a fresh Emacs (e.g. `mkdir /tmp/emacs && HOME=/tmp/emacs emacs`)
1. Install latest smartparens from MELPA
1. `(require 'smartparens-config)`
1. Go to any Emacs Lisp buffer, such as `*scratch*`
1. `M-x delete-selection-mode RET` to turn on delete-selection-mode
1. `M-x smartparens-mode RET` *twice* to turn smartparens on and back off in the buffer
1. Type "foo"
1. `M-SPC M-b` to select the "foo" you just typed
1. Type "("

I expected "foo" to be deleted and replaced by "(", but instead I now have no active region and the buffer contains "(foo".

## Environment & version information

- `smartparens` version: 20170619.149 (from MELPA as of a few minutes ago)
- Active major-mode: lisp-interaction-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1421)) of 2017-04-24
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
- OS: OS X 10.11.6

## Comments

I'm guessing the problem here is that `sp-pair-list` remains a set buffer-local variable when smartparens has ever been turned on in the buffer.  The advice on `delete-selection-pre-hook` calls `sp-wrap--can-wrap-p` which consults `sp--get-pair-list-wrap`.  Neither the advice nor either of these functions ever check if smartparens-mode is currently active in the buffer in question, so the advice never calls `delete-selection-pre-hook` because it expects we'll instead wrap the region later on.

Therefore my first guess at a fix for this is that either the advice or `sp-wrap--can-wrap-p` should check if smartparens is even active in the current buffer.

**Comment by Fuco1** [comment]
Yes, that's a good analysis.  Do you want to make the patch? :)  I would add the check to the advice to leave the function generically available even with the mode off.

There have been some changes in E25 surrounding the delete-selection-mode and CUA so some of the hacks employed in SP might become obsolete some day, but so far I think we can't get rid of it easily.

**Comment by dsedivec** [comment]
> Yes, that's a good analysis. Do you want to make the patch? :) I would add the check to the advice to leave the function generically available even with the mode off.

OK, I will try!

> There have been some changes in E25 surrounding the delete-selection-mode and CUA so some of the hacks employed in SP might become obsolete some day, but so far I think we can't get rid of it easily.

I did find `self-insert-uses-region-functions`, and electric pair mode adds its own `electric-pair-will-use-region` to that.  But I'm not sure that adding a new hook function there is enough to get rid of that advice, so I'm currently inclined to take the known way out and modify the advice as you suggest.

**Comment by Fuco1** [comment]
Agreed.
