### ISSUE TITLE
smartparens-strict-mode and hungry-delete-mode break sp-delete-char

### ISSUE THREAD

**Issue by CSRaghunandan** [Fuco1/smartparens#765]
## Expected behavior

enable `hungry-delete-mode`, press `C-d` which is bound to `sp-delete-char` should delete work just like `delete-char` when not attempting to delete any non-whitespace character.

## Actual behavior

Pressing `C-d` which is bound to `sp-delete-char` gives me this error:

```
sp-delete-char: Wrong number of arguments: #[(n &optional killflag) "¨ÄÅÆD\"Ç .	.ÈU.	É=(ÊË Ì \"Ë Ì |
7Í\"Î " [n delete-active-region current-prefix-arg killflag signal wrong-type-argument integerp use-region-p 1 kill ...] 4 ("/Users/csraghunandan/.emacs.d/elpa/hungry-delete-20170411.1802/hungry-delete.elc" . 1966) "p
P"], 0
```

## Steps to reproduce the problem
enable `hungry-delete-mode` and `smartparens-strict-mode` and press `C-d` to delete a non-whitespace character

## Backtraces if necessary (`M-x toggle-debug-on-error`)

```
Debugger entered--Lisp error: (wrong-number-of-arguments #[(n &optional killflag) "\250\204\304\305\306D\"\210\307 \203.	\203.\310U\203.	\311=\203(\312\313 \314 \"\207\313 \314 |\207
\2037\315\"\207\316 \207" [n delete-active-region current-prefix-arg killflag signal wrong-type-argument integerp use-region-p 1 kill kill-region region-beginning region-end delete-char hungry-delete-forward-impl] 4 ("/Users/csraghunandan/.emacs.d/elpa/hungry-delete-20170411.1802/hungry-delete.elc" . 1966) "p
P"] 0)
  hungry-delete-forward()
  sp-delete-char(nil)
  funcall-interactively(sp-delete-char nil)
  call-interactively(sp-delete-char nil nil)
  command-execute(sp-delete-char)
```

## Environment & version information

- `smartparens` version:  20170629.1338
- Emacs version (`M-x emacs-version`): 26.0.50 built from emacs master build
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla 
- OS: Mac OS Sierra

ps: one of the latest commits caused breakage. I used to use the answer provided for workaround for `hungry-delete-mode` and `smartparens-strict-mode` in [here](https://emacs.stackexchange.com/questions/29476/always-remove-brackets-by-pairs-fix-hungry-delete-mode-and-smartparens-strict)

**Comment by therockmandolinist** [comment]
Oh hey, I think this is my fault - pretty sure it's cause the call to `(hungry-delete-forward)` should actually be `(hungry-delete-forward 1)` as with the `hungry-delete-backward` case.

**Comment by therockmandolinist** [comment]
@CSRaghunandan The recent commit was me trying to not have to resort to the workaround there. It should be as simple as calling the right hungry-delete function instead of the emacs default when hungry-delete is on. 

Without your workaround, did deleting back (whitespace or not) work as you'd expect with hungry-delete? Also, does the small fix in my recent pull fix this issue (it does for me, I think)?

**Comment by CSRaghunandan** [comment]
@therockmandolinist  Latest pull fixed the issue. Thanks for the really quick fix.
