### ISSUE TITLE
Unable to kill-region of empty line in strict mode 

### ISSUE THREAD

**Issue by dakrone** [Fuco1/smartparens#776]
## Expected behavior
When in strict-mode, I expect to be able to highlight empty lines and hit `C-w` to invoke `kill-region`, which should remove the empty lines.

## Actual behavior
Instead, smartparens complains about an "Unbalanced region"

## Steps to reproduce the problem
I reproduced it with a .js file, but any file where `smartparens-strict-mode` is enabled will work.

Starting with a file like:

```js
{
  "foo": "bar"
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
|
}
```

Where `|` is the cursor and `XXXXX` is the highlighted region (see screenshot)

![screenshot_2017-07-20_09-46-17](https://user-images.githubusercontent.com/19060/28426562-b93d046a-6d30-11e7-9051-0cd3addf2762.png)

(Basically I hit `C-SPC` on the line below "foo": "bar" and then moved the cursor down one line with `C-n` to highlight the entire empty line)

Hit `C-w`, and instead of removing the empty line, I get the error about "Unbalanced region".

It's interesting to note that if I hit `backspace` to issue a `delete-backwards-char`, the region is correctly deleted.

## Backtraces if necessary (`M-x toggle-debug-on-error`)
(none)

## Environment & version information

- `smartparens` version: smartparens-20170716.1328
- Active major-mode: js-mode (though it reproduces in other programming modes such as java-mode)
- Emacs version (`M-x emacs-version`): `GNU Emacs 25.2.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.15) of 2017-06-01`
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Regular Emacs
- OS: `Linux 4.11.8-200.fc25.x86_64 #1 SMP Thu Jun 29 16:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Fuco1** [comment]
This has already been fixed in #775.

**Comment by Fuco1** [comment]
Thanks for the report however, I value the early feedback very much!

**Comment by dakrone** [comment]
You're right, I should have updated to the latest package this morning before filing this, thanks for the quick fix @Fuco1, I've confirmed it's fixed now!

**Comment by Fuco1** [comment]
Great, thanks for confirming!
