### ISSUE TITLE
Rust: skipping forward over function return type doesn't work

### ISSUE THREAD

**Issue by antifuchs** [Fuco1/smartparens#793]
## Expected behavior

In strict mode, using `C-M-f` to jump over a function's return type and killing a region that contains a whole function definition should operate as well as `C-M-b` and `C-k` do. Example:

``` rust
fn foo() -> u32 {}
```

Marking this whole function definition and killing it should put the region on the kill ring. Similarly, `C-M-f` from the beginning of the buffer should reach the end of the buffer.

## Actual behavior

`C-M-f` complains that there's an unmatched expression, and `C-w` errors with "Unbalanced region" when marking a whole buffer and killing it.

## Steps to reproduce the problem

I've written up some tests for this:

``` elisp
(ert-deftest sp-test-rust-skip-forward-over-return-type ()
  "Moving forward over a function's return type."
  (sp-test-with-temp-buffer "fn foo() |-> u32"
      (rust-mode)
    (execute-kbd-macro (kbd "C-M-f"))
    (execute-kbd-macro "{")
    (should (equal (buffer-string) "fn foo() -> u32 {}"))))

(ert-deftest sp-test-rust-skip-backward-over-return-type ()
  "Moving backward over a function's return type."
  (sp-test-with-temp-buffer "foo() -> |u32 {}"
      (rust-mode)
    (execute-kbd-macro (kbd "C-M-b"))
    (execute-kbd-macro "fn ")
    (should (equal (buffer-string) "fn foo() -> u32 {}"))))

(ert-deftest sp-test-rust-kill-defun ()
  "Deleting a region containing a rust function definition."
  (sp-test-with-temp-buffer "|fn foo() ->u32 {}"
      (rust-mode)
    (execute-kbd-macro (kbd "C-x h"))
    (execute-kbd-macro (kbd "C-w"))
    (should (equal (buffer-string) ""))))
```

## Backtraces if necessary (`M-x toggle-debug-on-error`)

No backtraces are emitted.

## Environment & version information

- `smartparens` version: 20171005, from melpa
- Active major-mode: rust-mode
- Emacs version (`M-x emacs-version`): 25.2.1
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: emacs-mac
- OS: macOS

## Additional information from my own adventures debugging this

I've tracked this down to the function `sp-rust-filter-angle-brackets` - it appears to use `looking-back` in circumstances when (point) is at the beginning of the expression that it's trying to match. I am going to experiment with a second condition with `looking-at`, but so far results haven't been very encouraging. I'd love a few more pairs of eyes on this if possible (:

**Comment by Fuco1** [comment]
Thanks for the test cases, that is an awesome way to report a bug!  I'll try to squeeze this somewhere in my schedule, I think it shouldn't be very difficult (hopefully).
