### ISSUE TITLE
Support for origami-fold-style: triple-braces in emacs

### ISSUE THREAD

**Issue by aaronjensen** [Fuco1/smartparens#796]
Hi, I'm using origami with `origami-fold-style` set to `triple-braces` to allow me to fold up sections of my emacs config. Smartparens doesn't work great with it and I'm wondering what I could do to improve that.

```elisp
;; -*- origami-fold-style: triple-braces -*-

;; example {{{
(lisp-code)
;; }}}
```

There are two issues, one is that when the point is on a `{`, I get:

```
Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file.
```

The other is that it'd be great if when I typed `{{{` it inserted `;; }}}` on its own line. As it is now, I type `;; {{{` and end up with `;; {{{}}}`, then if I press return followed by `;`, it jumps me to a random place in the document rather than insert a `;`. `C-q ;` works.

Thanks!

**Comment by Fuco1** [comment]
Yea, the pairs in comments are limited to the comment where they start, it doesn't search in any following comments.  I had this feature in my TODO for ages, I wanted it for something similar, except we used `@{` and `@}` for folding.

I think it would require some additional configuration options like deciding if the pair should extend over multiple comments or not.  Haven't really given it much thought.

For the second issue, something like this should be a good start

```elisp
(sp-local-pair 'emacs-lisp-mode "{" nil :post-handlers '(:add my-tripple-brace))

(defun my-tripple-brace (id action context)
  (when (and (looking-at "}}}")
             (sp-point-in-comment))
    (save-excursion (insert "\n;; "))
    (newline)))
```

**Comment by aaronjensen** [comment]
Thanks! It turned out lispy was handling my `{` insertion, so I was able to take what you suggested and adapt it:

```elisp
(defun my-triple-brace (&rest args)
  "Insert newline after typing {{{."
  (when (and (looking-at "}}}")
             (lispy--in-comment-p))
    (save-excursion
      (lispy-newline-and-indent-plain)
      (insert ";; "))
    (lispy-newline-and-indent-plain)))
(advice-add 'lispy-braces :after 'my-triple-brace)
```

**Comment by Fuco1** [comment]
So I take this is solved? I'm going to close, feel free to reopen if there is some more to be solved.

**Comment by aaronjensen** [comment]
Yes, aside from the search failed for `{` in comments. If there's another issue for that or if you don't think that warrants an issue hanging around then no problem.

**Comment by Fuco1** [comment]
Yea, I have a separate issue for that already.
