### ISSUE TITLE
string-trim in sp-show--pair-echo-match requires subr-x

### ISSUE THREAD

**Issue by jonatanlinden** [Fuco1/smartparens#799]
It seems the library "subr-x" is required by the changes introduced in #788. It is also mentioned in the code in #787.

## To reproduce
Activate show-smartparens-mode, place the cursor after some parenthesis, whose matching parenthesis is offscreen. (provided subr-x is not loaded)

## Expected output in minibuffer

Matches: "\<text following opening parenthesis\>"

## Actual behavior in minibuffer

Error running timer ‘sp-show--pair-function’: (void-function string-trim)

## To resolve

Evaluating (require 'subr-x) gives expected behaviour. For me, (featurep 'subr-x) is nil after emacs has started, I don't know if this is standard.

## Environment & version information

- `smartparens` version: 20171015.1259
- Active major-mode: any
- Emacs version (`M-x emacs-version`): Gnu Emacs 25.3.1
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
- OS: macOS 10.13

**Comment by Fuco1** [comment]
It seems like the library isn't loaded by default.  The recommendation in the `subr-x` file is to use `(eval-when-compile (require 'subr-x))` so I think I'll just add that on top.

It's quite lucky that you stumbled upon this, probably you didn't "accidentally" load any other package which might have already loaded `subr-x`.

**Comment by Fuco1** [comment]
Thanks! :heart:

**Comment by jonatanlinden** [comment]
Well, thank you!
