### ISSUE TITLE
Newline and indent on appropriate pairs

### ISSUE THREAD

**Issue by rdallasgray** [Fuco1/smartparens#80]
Hi Fuco -- this isn't an issue so much as a suggestion/request for comment.

I'm using [this code](https://github.com/rdallasgray/graphene/blob/master/src/graphene-smartparens-config.el) to get autopair-like functionality on braces and brackets, where a newline should enter the created sexp and indent according to mode. I wonder if some sort of adaptation of this would be a useful addition to the default config, in order to achieve parity of behaviour with autopair?

**Comment by raxod502** [comment]
@Fuco1 This functionality is great! Are there any plans to enable it by default, or add a user option to  make it more obvious how to get the behavior (without reading this thread)?

**Comment by Fuco1** [comment]
We can set it up for some of the languages in their default configurations; and some of them already have a setup like this.  I would not go with the global flag but leave it on a per-langauge basis at least.  We can have defcustoms for each language probably.

I like it when software works out of the box but I'm very afraid to implement those defaults myself, especially in Emacs, where people always expect something else (no two people seem to share a workflow :D).  I'll be happy to merge patches if some sort of minimal consensus is reached somehow.

**Comment by raxod502** [comment]
By now, I have code covering a lot of major modes:

```elisp
(defun radian-enter-and-indent-sexp (&rest _ignored)
  "Insert an extra newline after point, and reindent."
  (newline)
  (indent-according-to-mode)
  (forward-line -1)
  (indent-according-to-mode))

(dolist (mode '(c-mode c++-mode css-mode objc-mode java-mode
                       js2-mode json-mode
                       python-mode sh-mode web-mode))
  (sp-local-pair mode "{" nil :post-handlers
                 '((radian-enter-and-indent-sexp "RET")
                   (radian-enter-and-indent-sexp "<return>"))))

(dolist (mode '(js2-mode json-mode python-mode web-mode))
  (sp-local-pair mode "[" nil :post-handlers
                 '((radian-enter-and-indent-sexp "RET")
                   (radian-enter-and-indent-sexp "<return>"))))

(dolist (mode '(python-mode))
  (sp-local-pair mode "(" nil :post-handlers
                 '((radian-enter-and-indent-sexp "RET")
                   (radian-enter-and-indent-sexp "<return>")))
  (sp-local-pair mode "\"\"\"" "\"\"\"" :post-handlers
                 '((radian-enter-and-indent-sexp "RET")
                   (radian-enter-and-indent-sexp "<return>"))))
```

It seems kind of unwieldy, though, and I have to update it every time I use a new mode. Is there a way I can enable this for every pair?

**Comment by Fuco1** [comment]
@raxod502 Unfortunately not, you can probably hack an advice together that would do this for you, but there is nothing built-in for a "global" configuration of these hooks.

**Comment by raxod502** [comment]
Would you be open to the idea of configuring pairs globally? This seems like it would be a very useful feature, and you suggested the same in [your comment above](https://github.com/Fuco1/smartparens/issues/80#issuecomment-16745691).

**Comment by Fuco1** [comment]
@raxod502 There's a proposition for a new configuration API https://github.com/Fuco1/smartparens/blob/master/dev/sp-defpair.org which has been sitting around for quite some time.  I think there is also some support for global config there.

The very early versions of SP had global configuration but we decided to remove it because it very soon became apparent that it's not going to really work universally... and we opted for configuring everything for every mode/pair explicitly.

We might want to add some API to do this in a less annoying way.

**Comment by jD91mZM2** [comment]
I'm incredibly sorry for pinging everyone here a year after the last message, but I wanted to add that one can make @raxod502's code work on all major programming modes by using `'prog-mode`, which most (if not all) of them are derived on.

```elisp
(sp-local-pair 'prog-mode "{" nil :post-handlers '((my/newline-indent "RET")))
```
This might affect some modes you don't actually want this behavior in, so beware of that.

**Comment by zw963** [comment]
For the user want a function can do this trick anytime, even support code like this:

```rb
x = {x: 100, |}

# with change to

x = {
      x: 100,
      |
    }
```


 please check my config [here](https://github.com/zw963/.emacs.d/blob/master/plugins/ruby/ruby-meta-return_init.el#L6-L15)

for the simplest cases, e.g. (|), [|], {|}, following code is enough.

```rb
(defun no-moving-newline-and-indent ()
  (interactive)
  (save-excursion
    (newline-and-indent)))


   (when (and (member (char-before) '(123 91 40)) ; { [ (
         (member (char-after) '(125 93 41))) ; } ] )
    (progn
      (no-moving-newline-and-indent)
      (newline-and-indent))
    )
```

**Comment by rofrol** [comment]
I use this:

```elisp
(defun rf/sp-insert-curly-braces-newlines ()
  "Insert `{`, followed by a newline, an indented line for content, and then another closing brace on its own line."
  (interactive)
  (insert "{\n")
  (indent-according-to-mode)
  (insert "\n}")
  (indent-according-to-mode)
  (forward-line -1)
  (indent-according-to-mode))

(define-key prog-mode-map "{" 'rf/sp-insert-curly-braces-newlines)
```
