### ISSUE TITLE
C-u breaks the balance.

### ISSUE THREAD

**Issue by sirikid** [Fuco1/smartparens#800]
## Expected behavior
Each parenthesis has a pair.

## Actual behavior
The first n - 1 parentheses do not have a pair.

## Steps to reproduce the problem
Type <kbd>C-u n (</kbd>.

## Environment & version information

- `smartparens` version: 20171019.608
- Active major-mode: `emacs-lisp-mode`, `cc-mode` (probably all)
- GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19) of 2017-09-16
- Vanilla
- OS: Linux b560 4.13.4-1-ARCH #1 SMP PREEMPT Thu Sep 28 08:39:52 CEST 2017 x86_64 GNU/Linux

**P.S.** Sorry for unclear title, I can not think up better.

**Comment by Fuco1** [comment]
Yea, I understand what you mean.  This is actually "by design" now, we have a todo for this

```
;; TODO: this introduces a regression, where doing C-4 [ inserts [[[[]
;; figure out how to detect the argument to self-insert-command that
;; resulted to this insertion
```

Unfortunately I still quite don't know how to fix it :(  The change was necessary sacrifice to make other (arguably more useful) features work.

**Comment by Fuco1** [comment]
The value of `current-prefix-arg` seems to hold the prefix argument even in the post insert hook.

So we can basically run the whole operation that many times and it should work out fine (in case we fell into the insertion mode).  Also probably we would need to clean-up the context and then reinsert one by one `n` times.
