### ISSUE TITLE
Pair "\\[" produces unexpected result

### ISSUE THREAD

**Issue by noaham** [Fuco1/smartparens#803]
The following is in my configuration. 

    (sp-pair "\\[" nil :actions :rem)
    (sp-pair "\\[ " " \\]" :trigger "\[")

## Expected behavior

In LaTeX-mode typing `\\[` should insert `\[ | \]` with | the point.

## Actual behavior

If typed at the start of a document, then `\\[ | \]` is produced.

If typed after `{}|`, for example, `{ \] \ |` is produced.

## Steps to reproduce the problem

A minimal configuration loading smartparens with
    (sp-pair "\\[" nil :actions :rem)
    (sp-pair "\\[ " " \\]" :trigger "\[")

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: 20171021.718
- Active major-mode: LaTeX-mode
- Emacs version (`M-x emacs-version`): 25.3.1
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
- OS: osx

**Comment by Fuco1** [comment]
I'm really confused about the backslashes here... I think in emacs strings you always need two to have a literal backslash, so the trigger shouldn't even work (or rather, should just be equivalent to `[`

    (equal "\[" "[") ;; => t

Better way than adding spaces to the pairs is to add a post insertion hook (smartparens calls this handlers).  I think spaces in pairs are actually not supported at all... maybe I should add a check and error out when the user tries that.

This should do what you expect

```elisp
(sp-local-pair 'latex-mode "\\[" "\\]" :post-handlers '(("| " "SPC")))
```

The syntax for the post handler can be found in the docs: http://smartparens.readthedocs.io/en/latest/permissions.html#pre-and-post-action-hooks

**Comment by noaham** [comment]
Thanks! Super helpful. The suggested configuration does exactly what I want. 

I should also note that the unexpected behaviour only started a few months ago, the above configuration worked as expected before that.

The spaces in pairs seems to work for other pairs, e.g. `\(`. So maybe an error would prevent inconsistencies. Thanks again.

**Comment by Fuco1** [comment]
Yea, I'll look into that, it is a bit weird.  There were some changes regarding the parsing of the input so that is probably what broke your setup (and possibly other peoples').  Sorry 'bout that :P

**Comment by Fuco1** [comment]
The problem was with the fact that we broke `:rem` so the `\[` pair was never actually removed :D  This was discovered in #932 and fixed.  So your old configuration should probably work again on the latest master.

Another issue was that we've added latex-mode configuration for `\[` and you only removed the global value, but the local value was still applied.

**Comment by Fuco1** [comment]
So to remove our config and then add your own you also would need to call 


    (sp-local-pair 'latex-mode "\\[" nil :actions :rem)

But this is not recommended, it's better to only tweak the settings.
