### ISSUE TITLE
C-_ gets redefined in markdown-mode

### ISSUE THREAD

**Issue by nidrissi** [Fuco1/smartparens#804]
## Expected behavior

In base emacs, `C-_` is [undo](https://www.gnu.org/software/emacs/manual/html_node/emacs/Undo.html). It's very practical for users with AZERTY keyboards, for example, with which typing `C-/` is not convenient at all.

## Actual behavior

In markdown-mode, the package redefines `C-_` to wrap with underscores. Redefining such basic keybindings is typically not what a package should do.

## Steps to reproduce the problem

Type `C-_` in markdown-mode.

## Environment & version information

- `smartparens` version: 20171029.354
- Active major-mode: lisp-interaction-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
- OS: windows-nt

**Comment by Fuco1** [comment]
Agreed, I will remove the rebinding.  It got included accidentally when I ported the settings from my personal configuration.
