### ISSUE TITLE
smartparens requires emacs 24.4

### ISSUE THREAD

**Issue by eivt** [Fuco1/smartparens#810]
Smartparens fails to load on 24.3.1 due to lack of subr-x module, which was introduced in emacs 24.4.

Please update following wording in readme.md:

"We generally target GNU Emacs version 24.3 and newer"

- Emacs version: 24.3.1
- Vanilla
- OS: RHEL 7.4

**Comment by Fuco1** [comment]
I think I'll add a compat polyfill, we only need it for one function (checking if string is a prefix of another) which can be just copy-pasted and conditionally evaluated on older Emacs.
