### ISSUE TITLE
Function key (F5-F12) in terminal (emacs -nw) not working after smartparens enabled

### ISSUE THREAD

**Issue by lllllllllllllllllllllllllllllllllllllll** [Fuco1/smartparens#817]
## Expected behavior
In xterm, the `F5` key sends character `^[[15~`, if smartparens is enabled, the `[` before `15~` will activate smartparens pairing. So emacs can not discern that I actually pressed `F5`.  I have no problem with `F1`, as `F1` sends `^[OP`, which does not contain `[`. 

## Actual behavior
Key `F5`-`F12` is considered as a series of key press, i.e.  `[15~`-`[24~`.

I added the following to my `~/.emacs.d/init.el`
```
(sp-pair "^[[" nil :actions :rem)
(sp-pair "\E[" nil :actions :rem)
(sp-pair "[" nil :actions :rem)
```
It did not work. How can I make smartparens ignore key sequence like `^[[`?

## Steps to reproduce the problem
Just open `emacs -nw` and press `F5`-`F12` with smartparens enabled.

## Environment & version information

- `smartparens` version: smartparens-20171101.244
- Active major-mode: lisp-interaction-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19) of 2017-09-17
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: prelude
- OS: Arch Linux
- Terminal Emulator: urxvt

**Comment by Fuco1** [comment]
I can not reproduce that.  You say `xterm` in the beginning but `urxvt` at the end.  I've tried it in xterm and while most things seem totally broken with or without smartparens (not even M-x works) but F5-F12 works.

I use emacs in urxvt daily and everything works fine.  Are you sure you don't have some fancy translation maps active?  Try starting emacs also with a `-Q` flag which will ignore X resources as well as local config files.

**Comment by lllllllllllllllllllllllllllllllllllllll** [comment]
Sorry for the inconsistence.

I use `urxvt`, but I actually defined all function keys to be `xterm`-like in my `.Xresources`.
```
URxvt*keysym.F1: \033OP
URxvt*keysym.F2: \033OQ
URxvt*keysym.F3: \033OR
URxvt*keysym.F4: \033OS
URxvt*keysym.F5: \033[15~
URxvt*keysym.F6: \033[17~
URxvt*keysym.F7: \033[18~
URxvt*keysym.F8: \033[19~
URxvt*keysym.F9: \033[20~
URxvt*keysym.F10: \033[21~
URxvt*keysym.F11: \033[23~
URxvt*keysym.F12: \033[24~
```

The function keys work both with `emacs -Q -nw` and with smartparens-mode disabled. Moreover if I delete the lines
```
URxvt*keysym.F1: \033OP
URxvt*keysym.F2: \033OQ
URxvt*keysym.F3: \033OR
URxvt*keysym.F4: \033OS
```
then when I press `F1`, I will insert `11~` into the text. This is because `urxvt` by default sends `\033[11~` when `F1` is pressed. Only by defining `F1` to be `\033OP` will the `F1` key works properly.

I will try a clean install of smartparens to see if my config files is to blame.

**Comment by Fuco1** [comment]
If Emacs sends the keys one by one then smartparens will pick up the after insert event and will act on it.  But this is more a problem with emacs itself.  You can look at translation maps https://www.gnu.org/software/emacs/manual/html_node/elisp/Translation-Keymaps.html and make it so that emacs knows how to interpret the keys.

**Comment by lllllllllllllllllllllllllllllllllllllll** [comment]
Yes, it is my config file that caused the problem after all. Alas, my config file is absolutely a disaster. It  is not easy for me to nail down the exact line of breaking. Anyway, thank you for your patience, sorry for the disturbance. Have a good day (or maybe night)!

**Comment by Fuco1** [comment]
I would start by removing the `.Xresources` settings.  Do you remember why you use that?  I've been using `urxvt` for at least 5 years and never had to do that, and I use terminal vim, emacs, tmux, mutt and all sorts of other apps.  Everything works fine.  Sometimes we just keep "legacy" settings around "just in case", but I think the translations are no longer necessary :P
