### ISSUE TITLE
C-_ gets remapped in org-mode

### ISSUE THREAD

**Issue by jabranham** [Fuco1/smartparens#819]
This issue is similar to #804 but for org mode instead of markdown mode

In addition to overwriting the built in undo map, remapping C-_ makes undo-tree refuse to turn on

**Comment by Fuco1** [comment]
Oh yes.  There was a bug until 3 or so days ago that the org config did not even load :D So nobody reported it and I haven't noticed either since I haven't restarted my emacs for about 50 days now :D Thanks!
