### ISSUE TITLE
smartparens-org overrides undo keybinding

### ISSUE THREAD

**Issue by jethrokuan** [Fuco1/smartparens#826]
## Expected behavior
Using `(require 'smartparens-config)` overrides the `C-_` keybinding, which is a commonly used keybinding for `undo`.

## Actual behavior
`C-_` should be left untouched, and the function that wraps regions in underscores should be bound to something else.

## Steps to reproduce the problem
Install smartparens on vanilla emacs, and `(require 'smartparens-config)`.

## Backtraces if necessary (`M-x toggle-debug-on-error`)
NIL

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: 20171129.412
- Active major-mode: org-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2017-11-29
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
- OS: NixOS

**Comment by Fuco1** [comment]
This is already fixed in master #819
