### ISSUE TITLE
Equivalent to paredit-close-(round|square|curly)

### ISSUE THREAD

**Issue by raxod502** [Fuco1/smartparens#828]
In Paredit, when I am inside a sexp of any type and type _any_ closing delimiter, point jumps to the end of the sexp. In Smartparens, this only happens if the closing delimiter I type is _the same kind_ as the enclosing sexp (otherwise I get an error).

In Paredit, typing any of `)`, `]`, `}`* produces:

```
   (foo| bar)
=> (foo bar)|
```

Whereas in Smartparens I get an error for `]` or `}`.

Is there an option in Smartparens to act like Paredit and be agnostic about which closing delimiter was actually typed? (I'd be fine if it was limited to just `)`, `]`, and `}` rather than working on arbitrary delimiters.)

\* `}` only if you bind it to `paredit-close-curly`

**Comment by Fuco1** [comment]
It's not possible right now but should theoretically be possible and maybe even quite simple to do.  I'm not sure how the "limiting" factor would work, that is, how to make it only work for the three delimiters you describe.  But in principle there could be an option for that.

**Comment by Fuco1** [comment]
I've looked into this briefly now.  In the function `sp-skip-closing-pair` there are two checks with `equal` which compare `last` (the key you typed) with `cl` (the closing delimiter of the current sexp).

If those two are replaced by some sort of equivalence relation (we can add a configurable variable with the equivalence classes, if the pair is not found then assume reflexivity by default) then I can imagine this should work as you want.

Would you be interested in trying to implement this?

**Comment by raxod502** [comment]
After a couple of months, I got used to the Smartparens behavior ^_^

I think it's a cool feature, so I've put this on my todo list, but I won't have time to address it anytime soon. @PythonNut has also expressed interest in this feature, perhaps he'd be able to do it?

**Comment by ailisp** [comment]
@raxod502 I also come from paredit, for me, i just bind `sp-up-sexp` to ")" "]" "}" and seems give the paredit like close parens behavior for me (not testing for a long time, seems no problem after a few days with clojure, smartparens-strict-mode-map, not tested with other langs and non strict mode)
```lisp
(define-key smartparens-strict-mode-map (kbd ")") 'sp-up-sexp)
(define-key smartparens-strict-mode-map (kbd "]") 'sp-up-sexp)
(define-key smartparens-strict-mode-map (kbd "}") 'sp-up-sexp)
```

**Comment by raxod502** [comment]
It does work well enough, although the fact that typing an unbalanced closing `)` in a string literal causes point to jump out of the literal is a bit annoying :)
