### ISSUE TITLE
allow sp-rewrap to remove pairs?

### ISSUE THREAD

**Issue by jabranham** [Fuco1/smartparens#841]
This is a feature request.

I'd like it if I could use the rewrap commands to remove pairs. If this is something you'd accept a PR for, I can look into implementing it.

## Expected behavior

"|GPL" with | as point calling `M-x sp-rewrap-sexp RET RET` should remove the quotes around GPL

## Actual behavior
error: Impossible pair prefix selected: RET

**Comment by Fuco1** [comment]
There exists `sp-unwrap-sexp` but you probably know that right?

So what you mean is that supplying an "empty pair" in rewrap should unwrap... yea that makes sense to me.  And it should be rather simple to implement.

**Comment by jabranham** [comment]
> There exists sp-unwrap-sexp but you probably know that right?

Yes, but I'd prefer one keybinding that could either rewrap or unwrap, since unwrapping is basically rewrapping with nothing.

> So what you mean is that supplying an "empty pair" in rewrap should unwrap... yea that makes sense to me. And it should be rather simple to implement.

Great, I'll look into doing this and submit a PR when ready.

**Comment by Fuco1** [comment]
@jabranham I've already implemented it, writing tests as we speak :D

**Comment by jabranham** [comment]
Wow, that's quick. Thanks! :-)

**Comment by Fuco1** [comment]
Yea, I like the idea, it is quite convenient indeed.  Should work on master, MELPA will pick this up in couple hours at most.

**Comment by jabranham** [comment]
Works like a charm, thanks!
