### ISSUE TITLE
require help-mode before let binding help-xref-following

### ISSUE THREAD

**Issue by vspinu** [Fuco1/smartparens#85]
Hi,

```lisp
╭──────── #87 ─ /home/vitoshka/Dropbox/ELPA/smartparens-20130426.242/smartparens.el ──
│       (let ((standard-output (current-buffer))
│             (help-xref-following t))
╰──────── #88 ─
```

is causing similar bug as reported here: http://comments.gmane.org/gmane.emacs.bugs/74027

To reproduce call sp-cheat-sheet after emacs is loaded.

A workaround is just to require help-mode beforehand.

**Comment by ginabythebay** [comment]
I just installed smartparens (20160821.152) and ran into this issue (running sp-cheat-sheet gave me blankness).

I was able to work around it by putting the require statement before installing smartparens.  My init.el looks like:

(require 'help-mode) ;; smartparens cheat sheet will fail without this
(use-package smartparens
    :ensure t
    :config
....

**Comment by Fuco1** [comment]
I run this in clean emacs: `cask exec emacs -L . -nw -q` and it worked after `(require 'smartparens)` without any additional setup.

This leads me to believe it is a problem with your config.
