### ISSUE TITLE
can not kill-region on arrow functions with rjsx-mode & smartparens-strict-mode

### ISSUE THREAD

**Issue by merrickluo** [Fuco1/smartparens#872]
## Expected behavior

should be able to `kill-region` on a javascript arrow function in rjsx-mode with smartparens-strict-mode.

## Actual behavior

`user-error: Can not kill the region: the buffer would end up in an unbalanced state after deleting the active region`

## Steps to reproduce the problem

1. create a javascript file and turn on rjsx-mode
2. write a javascript arrow function
```javascript
const test = () => {
  console.log('test')
}
```
3. select whole function and call `kill-region` 

## Environment & version information

- `smartparens` version: 20180308.1042
- Active `major-mode`: `rjsx-mode`
- Smartparens strict mode: t
- Emacs version (`M-x emacs-version`): GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2018-02-09
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

I think  `>` is the problem here since it also needed to be paired in HTML, I wonder if this can be done? 
I really like the idea of smartparens-strict-mode, and want to use it in every mode. I can also press C-k before the function twice to do the same thing, but the muscle memory is really hard to resist(

**Comment by Fuco1** [comment]
I remember we had a somewhat similar issue in the past but I'm not sure if it was javascript or rust or something else.  Should not be extremly difficult to fix.

**Comment by Fuco1** [comment]
I think it would  better fit in `smartparens-javascript.el`, after all the arrow is part of js syntax.

Would you be interested in creating a pull request?

**Comment by merrickluo** [comment]
I'd like to.

**Comment by Fuco1** [comment]
Fixed in 04f94b8ce207f9476b39eb397486e87c8507c84e
