### ISSUE TITLE
Support deleting ' in HTML comments

### ISSUE THREAD

**Issue by Wilfred** [Fuco1/smartparens#878]
## Expected behavior

Pressing backspace on `'` inside a comment in HTML deletes the `'`.

## Actual behavior

Point just moves over the `'`.

## Steps to reproduce the problem

Given the following HTML, where `|` is the cursor:

```html
<-- foo doesn'|t bar -->
```

Pressing backspace does not remove the `'`.

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: 20170209
- Active major-mode: html-mode
- Emacs version (`M-x emacs-version`): 25.3.1
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
- OS: Linux

Sorry this is so old, it's an old system I've used. I'll confirm this still occurs on the latest smartparens code when I can.

**Comment by Wilfred** [comment]
I think this could be fixed by changing `sp-pairs` in smartparens.el to add `sp-in-comment-p` to the `:unless` block for `"'"`.

**Comment by Fuco1** [comment]
We should probably enable this in contractions only, there is a setup like that somewhere already. Maybe for lisps.

**Comment by Fuco1** [comment]
I've tried this now and can't reproduce it.

By the way

```
<-- foo doesn't bar -->
```

is not correct html comment syntax, maybe that was the issue?  Or you just typed it here incorrectly?

**Comment by Wilfred** [comment]
OK, I've tried to reproduce this and it required a slightly larger snippet. This demonstrates the issue:

```html
<html>
    <head>
        <style type="text/css">
            .footer { background: 'foo.png'}
        </style>
        <!-- foo doesn't bar' -->
    </head>
</html>
```

I can't delete the last `'` in this comment.

**Comment by Wilfred** [comment]
I've replicated this on version 20180614.425 with `smartparens-strict-mode`.

**Comment by Fuco1** [comment]
Yea, can confirm this doesn't work.
