### ISSUE TITLE
Configuration is ignored when in terminal emacs

### ISSUE THREAD

**Issue by c02y** [Fuco1/smartparens#880]
I wrote a piece of configuration about sp in my init.el

    (sp-local-pair '(c-mode c++-mode java-mode python-mode) "{" nil :post-handlers '((insert-c-block-parentheses-without-indent "M-RET")))
    (defun insert-c-block-parentheses-without-indent (&rest _ignored)
      "Open a new brace or bracket expression, with relevant newlines and indent. "
      (message "abc"))

the `insert-c-block-parentheses-without-indent` function contains multiple lines, here it just prints "abc", I found that when I use this feature in GUI emacs and emacs in terminal (emacs -nw), the effects are different, the `insert-c-block-parentheses-without-indent` function is not called at all in terminal emacs, in GUI emacs, it works correctly.

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: smartparens-20180325.438
- Active major-mode: 
- Emacs version (`M-x emacs-version`): GNU Emacs 25.3.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla:
- OS: Ubuntu 16.0.4 LTS

**Comment by Fuco1** [comment]
`M-RET` is probably not available in terminal or is translated to a different event.  Not much we can do about it.

You can try to bind something to it and see if it works or what it translates to.

**Comment by c02y** [comment]
Sorry about, I didn't mention I did bind "M-RET" to something.

    (defun Meta-return ()
      (interactive)
      (progn
            (call-interactively (key-binding (kbd "C-M-j")))
            (indent-according-to-mode)))


and I `M-x describe-key" in terminal emacs, it is bounded.

**Comment by Fuco1** [comment]
The `"M-RET"` in `((insert-c-block-parentheses-without-indent "M-RET"))` is the raw event name.  It might be that in terminal emacs outputs something else and we can't hook onto it.
