### ISSUE TITLE
Sending email to users which is present in text file using python

### ISSUE THREAD

**Issue by swapnali42** [Fuco1/smartparens#885]
## I wrote below code for that
import smtplib
import re
import urllib.parse 

in_file = open("D:\\\mailout.txt","rt")
for line in in_file:
    if re.match(r'[\w\.-]+@[\w\.-]+', line):
        print (line)

term = "'" + line + "'"
print('term')
print(term)
TO = term

SUBJECT = "Send emil using smtplib in python"

TEXT = "Here is the message we would like to send"
 #GMail Credentials
gmail_sender = 'abc@example.com'
gmail_passwd = 'swasdff'

server = smtplib.SMTP('smtp.gmail.com', 587)
server.ehlo()
server.starttls()
server.login(gmail_sender, gmail_passwd)

BODY = '\r\n'.join([
'To:%s' % TO,
'From: %s' %gmail_sender,
'Subject: %s' %SUBJECT,
'',
TEXT])
try:
    server.sendmail(gmail_sender, [TO], BODY)
    print('email sent')
except: print ('error sending email')

server.quit()

**Comment by swapnali42** [comment]
please help how to get string with single quote.

**Comment by swapnali42** [comment]
I want to send email to user which is present in mailout.txt file but it gives error

D:\Web-Scrapping\23-5-2018>python send-email.py
swapnalibotre43@gmail.com
term
'swapnalibotre43@gmail.com'
error sending email

D:\Web-Scrapping\23-5-2018>
## how to solve this issue

**Comment by Fuco1** [comment]
I fail to see how is python programming related to this package.
