### ISSUE TITLE
sp-forward-slurp-sexp is broken in python-mode

### ISSUE THREAD

**Issue by xelibrion** [Fuco1/smartparens#896]
Hi, recently upgraded a version of smartparens and it seems something broke in python-mode. Both `smartparens-1.11.0` and `smartparens-20180430.220` are affected by the problem. `smartparens-20170723.1205` works as expected.

## Expected behavior
```python
(logging).basicConfig(level=logging.INFO)
# sp-forward-slurp-sexp
(logging.basicConfig)(level=logging.INFO)
# sp-forward-slurp-sexp
(logging.basicConfig(level=logging.INFO))
```

## Actual behavior
```python
(logging).basicConfig(level=logging.INFO)
# sp-forward-slurp-sexp
(logging basicConfig).(level=logging.INFO)
# sp-forward-slurp-sexp
(logging basicConfig(level=logging.INFO)).
```

## Steps to reproduce the problem
See above

## Environment & version information

- `smartparens` version: smartparens-1.11.0, smartparens-20180430.220
- Active major-mode: python-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, X toolkit) of 2018-06-03
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla:  Vanilla
- OS: Linux 4.16.8-gentoo x86_64 GNU/Linux

**Comment by Fuco1** [comment]
I wanted to blame this on new Emacs version but you're still on 25 :) :+1: 

Something might also have changed in python mode, is that built-in or you use something external?  I don't recall any changes to python setup but of course there might be some other issue spilling over into this.

**Comment by xelibrion** [comment]
I do use built-in python mode + elpy. But I'm pretty sure that the problem is in smartparens, since downgrading to `smartparens-20170723.1205` fixes the issue with all other packages remaining the same versions.

**Comment by Fuco1** [comment]
That's probably right.  I'm pretty sure this has to do with `sp--get-suffix` method.

However I'm now on master and can't reproduce the issue, it keeps the dot where it is for me.  I can even barf the things out and the paren lands after `logging` as expected.

What is the value of `sp-sexp-suffix`?  You can get this by `M-: sp-sexp-suffix RET`

**Comment by Fuco1** [comment]
It should contain `(python-mode regexp "")`, if not try to push that there.

```elisp
(--each '(python-mode inferior-python-mode)
  (add-to-list 'sp-sexp-suffix (list it 'regexp "")))
```

**Comment by Fuco1** [comment]
You can also try `(require 'smartparens-python)`.

Sorry for the spam :D

**Comment by xelibrion** [comment]
`sp-sexp-suffix` is `nil` when my emacs gets loaded. `(require 'smartparens-python)` magically fixes the problem as it populates `sp-sexp-suffix`. 

Does it mean that the problem is with my set up?

**Comment by Fuco1** [comment]
It is odd that the config was loaded in the older versions of smartparens.

It is recommended to `(require 'smartparens-config)` as that will setup many settings for specific major modes.  For python it just adds the python require on the `eval-after-load` list.

Try to only put this somewhere in your config

```elisp
(--each '(python-mode python)
  (eval-after-load it                      '(require 'smartparens-python)))
```

and let's see if opening a python file triggers this.  If not then we might need to update the form in smartparens to include whatever symbol your python mode is triggering (and by extension other people probably also have this problem).

**Comment by xelibrion** [comment]
This didn't work for some reason. Looked like a syntax error somewhere
```
(--each '(python-mode python)
  (eval-after-load it                      '(require 'smartparens-python)))
```
Putting `(require 'smartparens-config)` fixed the problem. 
As far as I understand this behaviour is by design, so I'm going to close this issue. Thanks for your help!
