### ISSUE TITLE
wrap-with-* functions failes

### ISSUE THREAD

**Issue by amno1** [Fuco1/smartparens#899]
Hi guys, I installed smartparens yesterday from melpa and am experiencing some problems. Any of wrap-with-* functions fails. I get following message:

> command-execute: Autoloading file /home/arthur/.emacs.d/elpa/smartparens-20180614.425/smartparens.elc failed to define function wrap-with-parens

It is same for curly braces, square brackets etc. 

However sp-wrap-* functions work.

When I look at messages, I see this is reported at package initialisation:

>  Configuring package smartparens...done (0.103s)
> command-execute: Autoloading file /home/arthur/.emacs.d/elpa/smartparens-20180614.425/smartparens-config.elc failed to define function wrap-with-parens
> You can run the command ‘sp-wrap-square’ with M-x sp-sq RET
> user-error: At end of buffer
> You can run the command ‘sp-wrap-square’ with M-x sp-sq RET
> Undo branch point!
> You can run the command ‘sp-wrap-square’ with M-x sp-sq RET
> Undo branch point! [2 times]
> You can run the command ‘sp-wrap-round’ with M-x s-ro RET
> Undo branch point!
> Configuring package smartparens...done

**Comment by Fuco1** [comment]
Does this also happen when you first `(require 'smartparens)` or is this only an autoload issue?

The functions

```elisp
(defun sp-wrap-round ()
  "Wrap following sexp in round parentheses."
  (interactive)
  (sp-wrap-with-pair "("))

(defun sp-wrap-square ()
  "Wrap following sexp in square brackets."
  (interactive)
  (sp-wrap-with-pair "["))

(defun sp-wrap-curly ()
  "Wrap following sexp in curly braces."
  (interactive)
  (sp-wrap-with-pair "{"))
```

are not autoloaded so I'm not sure where the autoload thing is coming from.  However, they probably should be autoloaded so I will add the setup for that.

**Comment by Fuco1** [comment]
Actually they shouldn't be autoloaded because they won'twork without smartparens mode being on.  So you should first ensure the buffer has that active.

**Comment by amno1** [comment]
Hmm njah. Still does not work. I have (smartparens-global-mode t) in my init file, but when I try to manually call smartaprens-mode it says "smartparens mode enabled" for current buffer. However when I try to call those functions I get same error.

**Comment by amno1** [comment]
I have bound sp-wrap-* function to keys, but I saw them as completition options when I run M-x.

I also see some strange behaviour when using lisp in org-mode (in my init file). For example sp-end-of-sexp
will jump to some random place forward in file if I put it after the closing paranthesis. For example here is my configuration for smartparens:

> * Smartparens
> #+BEGIN_SRC emacs-lisp
> (use-package smartparens
>      :config
>            (require 'smartparens-config)
>            (require 'smartparens-html)
>            (require 'smartparens-python)
>            (smartparens-global-mode t)
>            (smartparens-strict-mode t)
>            ;;(add-hook 'js-mode-hook #'smartparens-mode)
>            (show-smartparens-global-mode t)
>        :bind (
>                  ("C-z <down>" . sp-down-sexp)
>                  ("C-z <up>"   . sp-up-sexp)
>                  ("C-z C-<down>" . sp-backward-down-sexp)
>                  ("C-z C-<up>"   . sp-backward-up-sexp)
>                  ("C-z a" . sp-beginning-of-sexp)
>                  ("C-z e" . sp-end-of-sexp)
>                  ("C-z f" . sp-forward-sexp)
>                  ("C-z b" . sp-backward-sexp)
>                  ("C-z n" . sp-next-sexp)
>                  ("C-z p" . sp-previous-sexp)
>                  ("C-S-f" . sp-forward-symbol)
>                  ("C-S-b" . sp-backward-symbol)
>                  ("C-z <right>" . sp-forward-slurp-sexp)
>                  ("C-z C-<right>" . sp-forward-barf-sexp)
>                  ("C-z <left>"  . sp-backward-slurp-sexp)
>                  ("C-z C-<left>"  . sp-backward-barf-sexp)
>                  ("C-z t" . sp-transpose-sexp)
>                  ("C-z C-k" . sp-kill-sexp)
>                  ("C-z k"   . sp-kill-hybrid-sexp)
>                  ("C-z C-k"   . sp-backward-kill-sexp)
>                  ("C-z c" . sp-copy-sexp)
>                  [("C-z d" . delete-sexp)]
>                  ("C-z <backspace>" . backward-kill-word)
>                  ("C-z C-<backspace>" . sp-backward-kill-word)
>                  ([remap sp-backward-kill-word] . backward-kill-word)
>                  ("C-z ]" . sp-unwrap-sexp)
>                  ("C-z C-t" . sp-transpose-hybrid-sexp)
>                  ("C-z ("  . sp-wrap-round)
>                  ("C-z ["  . wrap-with-brackets)
>                  ("C-z {"  . wrap-with-braces)
>                  ("C-z '"  . wrap-with-single-quotes)
>                  ("C-z \"" . wrap-with-double-quotes)
>                  ("C-z _"  . wrap-with-underscores)
>                  ("C-z `"  . wrap-with-back-quotes)))
> #+END_SRC

If I place cursor after the closing paranthesis in some of keybinding definition, it jumps at some random place many lines forward in my init file. I would expect it to jump to the end of closing use-package, but maybe I missunderstand the intended behaviour.

**Comment by Fuco1** [comment]
In org blocks things might work crazily because the major mode is not lisp but org and so org-mode rules apply.  This is something I would like to fix but it's pretty damn difficult.  What you can do is use `C-c '` to pop-up a buffer with the code in elisp mode, there everything will work as expected.


About the wrap functions, so they don't work even when you manually require smartparens?

**Comment by amno1** [comment]
I definitely understand that. I had suspicions that org-mode is messing things up so I didn't file that as an issue before, I just took it up now when we talk anyway. However, wrap-with-* functions still does not want to work :-(.  
I have done a change to my init file and instead of: (smartparens-global-mode t) , I am using (smartparens-global-mode 1) and now the smartparens mode seem to be loaded. I just tested in a C++ file I am working on, and the mode was loaded. However when I called "wrap-with-quotes" it still didn't worked. This the error from backtrace: 

> Debugger entered--Lisp error: (error "Autoloading file /home/arthur/.emacs.d/elpa/smartparens-20180614.425/smartparens-config.elc failed to define function wrap-with-back-quotes")
>   autoload-do-load((autoload "smartparens" nil t nil) wrap-with-back-quotes)
>   command-execute(wrap-with-back-quotes record)
>   execute-extended-command(nil "wrap-with-back-quotes" #("wrap-wi\nemmet-wrap-with-markup\nwrap-with-back-quotes\nwrap-with-braces\nwrap-with-brackets\nwrap-with-double-quotes\nwrap-with-single-quotes\nwrap-with-underscores" 7 8 (read-only nil) 8 14 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) face ivy-current-match read-only nil) 14 20 (face (ivy-current-match ivy-minibuffer-match-face-2) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 20 30 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) face ivy-current-match read-only nil) 30 31 (read-only nil) 31 37 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 37 52 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 52 53 (read-only nil) 53 59 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 59 69 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 69 70 (read-only nil) 70 76 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 76 88 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 88 89 (read-only nil) 89 95 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 95 112 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 112 113 (read-only nil) 113 119 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 119 136 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 136 137 (read-only nil) 137 143 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 143 158 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil)))
>   funcall-interactively(execute-extended-command nil "wrap-with-back-quotes" #("wrap-wi\nemmet-wrap-with-markup\nwrap-with-back-quotes\nwrap-with-braces\nwrap-with-brackets\nwrap-with-double-quotes\nwrap-with-single-quotes\nwrap-with-underscores" 7 8 (read-only nil) 8 14 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) face ivy-current-match read-only nil) 14 20 (face (ivy-current-match ivy-minibuffer-match-face-2) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 20 30 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) face ivy-current-match read-only nil) 30 31 (read-only nil) 31 37 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 37 52 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 52 53 (read-only nil) 53 59 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 59 69 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 69 70 (read-only nil) 70 76 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 76 88 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 88 89 (read-only nil) 89 95 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 95 112 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 112 113 (read-only nil) 113 119 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 119 136 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 136 137 (read-only nil) 137 143 (face ivy-minibuffer-match-face-2 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 143 158 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil)))
>   call-interactively(execute-extended-command nil nil)
>   command-execute(execute-extended-command)

**Comment by Fuco1** [comment]
There is no such function as `wrap-with-back-quotes` in smartparens.  Did you define it yourself?

Can you try to reproduce this with some minimal setup.  I have a hard time understanding what's going on.  Everything works fine on my end.

**Comment by Fuco1** [comment]
Can it be `use-package`?  Maybe the `:bind` expands to some code that assumes something that we do not provide.

**Comment by amno1** [comment]
Forgive me, it was me typing instead of copy-pasting :-). I meant (wrap-with-quotes) :-)

**Comment by amno1** [comment]
No, I didn't. Where do they come from? :-) 
![em-wrap-with](https://user-images.githubusercontent.com/7167943/41595580-3368020e-73bf-11e8-83c9-f2808c06a145.png)
Maybe it is use-package. I will try without doing any ":bind".

**Comment by Fuco1** [comment]
Now I see the problem.  **ALL** smartparens functions always start with `sp-` prefix, so these are not coming from this package.  So you are trying to autoload them from smartparens.el but they are defined elsewhere which triggers the error.  I have no idea where they come from though.  You might have some luck if you look at the documentation with `C-h f`.

**Comment by amno1** [comment]
Yepp, you are correct. Now when I disabled :bind shortcuts they are not showing up longer :-). So it's just me being a noob :+1: Thanks!

**Comment by Fuco1** [comment]
Yea, you need to bind those in the package that defines them because `use-package` automatically uses the package in which the `:bind` is to set up autoloads.
