### ISSUE TITLE
Escape quotes after insert unexpectedly in c/c++ mode.

### ISSUE THREAD

**Issue by moyotar** [Fuco1/smartparens#915]
## Expected behavior
![image](https://user-images.githubusercontent.com/22092607/43813942-813c4096-9afa-11e8-9fd0-441bd89ddd73.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/22092607/43813917-6653797a-9afa-11e8-84b3-0219a8c8b50f.png)

## Steps to reproduce the problem
In c/c++ mode, just insert a single quote.

## Environment & version information

- `smartparens` version: up-to-date
- Active major-mode: C++ mode
- Emacs version (`M-x emacs-version`): GNU Emacs 26.1
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: None
- OS: debian

**Comment by Fuco1** [comment]
This seems to be the same issue as https://github.com/Fuco1/smartparens/issues/783, can you apply the workaround from there for now?

**Comment by Fuco1** [comment]
You can do it in C++ buffers locally with `setq-local` in the init hook.

**Comment by moyotar** [comment]
Thanks. It works with hook `cc-mode`. That reason for this issue exist is that I prefer a  better way to solve this. Is there a way to get whether quotes should be escaped appropriately in `smartparens` itself ?

**Comment by Fuco1** [comment]
I don't think there is a way now as I still haven't figured out why this bug happens.

**Comment by liyunteng** [comment]
i try add (setq sp-escape-quotes-after-insert nil) to smartparens configure
but when i input single-quote i can't delete it.
and echo area report:
`
Error running timer ‘sp-show--pair-function’: (end-of-buffer)
sp-get-string: End of buffer
`

**Comment by Fuco1** [comment]
Tracked in the linked issue.
