### ISSUE TITLE
sp-local-pair for docblock with post-handler doesn't indent last line

### ISSUE THREAD

**Issue by kermorgant** [Fuco1/smartparens#916]
## Expected behavior

I was expecting that after inserting a docblock in php with post-handler defined as below, all 3 lines should be indented correctly. 

## Actual behavior

![image](https://user-images.githubusercontent.com/10561580/43882085-1488afd0-9bb7-11e8-8342-217712405e5f.png)

## Steps to reproduce the problem
I have this configuration in a hook

```elisp
  (add-hook 'php-mode-hook
            (sp-with-modes '(php-mode)
              (sp-local-pair "/**" "*/" :post-handlers '(:add ("* ||\n [i]" "RET"))))
...
```

On the other hand, if I don't insert an extra line in the docblock, the last line is indented correctly.

```              (sp-local-pair "/**" "*/" :post-handlers '(:add ("||\n [i]" "RET"))))```

## Environment & version information

- `smartparens` version: 20180717.335 
- Active major-mode: php-mode
- Emacs version (`M-x emacs-version`): 26.1
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: vanilla with evil
- OS: linux

**Comment by rue92** [comment]
I have found a solution to this for anyone who stumbles upon this issue by using
`(" [i]* ||\n[i]" "RET")` as the specification. My intuition is that this is an order of execution issue, which may actually be intentional, in which case maybe it's worthwhile adding to the documentation.

**Comment by kermorgant** [comment]
Thanks @rue92 ! :+1:
