### ISSUE TITLE
Unable to remove pair for quote (")

### ISSUE THREAD

**Issue by Hi-Angel** [Fuco1/smartparens#932]
## Expected behavior

Only one quote is inserted

## Actual behavior

Two quotes are inserted

## Steps to reproduce the problem

1. Install smartparens
2. run `emacs -Q`, evaluate `(package-initialize)` and `(smartparens-global-mode 1)`
3. Now disable a pair for quote character by evaluating `(sp-pair "\"" nil :actions :rem)`
4. In \*scratch\* buffer, press <kbd>"</kbd>

## Additional information

I also tried:

```lisp
(sp-pair "\"" nil :actions :rem)
(sp-pair "\"" nil :actions :nil)
(sp-pair "\"" "\"" :actions :rem)
(sp-pair "\"" "\"" :actions :nil)
```

None of them worked.

## Environment & version information

The `sp-describe-system` didn't do anything, so I filled the fields below manually.

- `smartparens` version: 20180912.1750
- Active major-mode: lisp-mode
- Emacs version (`M-x emacs-version`): yesterday's git build; but reproducible also on Remacs 26.0.60.
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: vanilla.
- OS: Archlinux.

**Comment by Fuco1** [comment]
Can you try

    (sp-pair "\"" nil :actions nil)

that is, there is no `:` in front of the last `nil`.  That should work.  `:rem` should be only for local pairs or pairs overloaded in specific major-modes

**Comment by Fuco1** [comment]
But the `:actions` is set to nil so it shouldn't do anything.  Does it do something?  Also if some major mode configures the pair it will be added no matter the global config.

Not the best UX for sure.

Btw `sp-describe-system` puts the output in the clipboard so you can paste it here.  Also not the best way to show the user... we should pop a buffer open or something.

**Comment by Hi-Angel** [comment]
> But the `:actions` is set to nil so it shouldn't do anything. Does it do something? Also if some major mode configures the pair it will be added no matter the global config.

Yes, it adds two quotes, and puts the caret in between them.

Without smartparens mode being enabled it adds a single quote, so doesn't seem to be anything outside.

> Btw `sp-describe-system` puts the output in the clipboard so you can paste it here. Also not the best way to show the user... we should pop a buffer open or something.

Oh, thank you, I see. Here it is:

- `smartparens` version: 20180912.1750
- Active `major-mode`: `lisp-interaction-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-09
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

-----

Does it work for you correctly?

**Comment by Fuco1** [comment]
OK when I do the line with `:rem` it correctly removes the pair from `sp-pairs` configuration but somehow it still ends up in the buffer locally (`sp-local-pairs` is a version with all the configuration merged---global + local + parent modes).  But I have no local configuration so I have no idea where the pair is coming from.

Definitely a bug somewhere.  I'm testing this in an `emacs -nw -q` instance with no user config whatsoever.
