### ISSUE TITLE
sp-wrap-* commands don't take function quote into account

### ISSUE THREAD

**Issue by amosbird** [Fuco1/smartparens#934]
## Expected behavior
` "M-("           | #'sp-wrap-round`      ->        `"M-("            (|#'sp-wrap-round)`

## Actual behavior
` "M-("           | #'sp-wrap-round`      ->        `"M-("            #(|'sp-wrap-round)`

- `smartparens` version: <Please specify manually>
- Active `major-mode`: `emacs-lisp-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu) of 2018-10-04
- Starterkit/Distribution: Evil
- OS: gnu/linux

**Comment by Fuco1** [comment]
Possible solution is to execute this after `(require 'smartparens-config)`

    (setf (caddr (assoc 'emacs-lisp-mode sp-sexp-prefix)) (rx (1+ (or "`" "," ",@" "'" "#'"))))
