### ISSUE TITLE
sp-kill-sexp with raw negative prefix argument

### ISSUE THREAD

**Issue by whxvd** [Fuco1/smartparens#948]
According to the docstrings, `C-u - M-x sp-kill-sexp RET` on `(()()|)` should yield `(|)`. But it yields `(()|)`.

Tried with the MELPA and the git master branch versions.

Apart from that the docstrings of `sp-kill-sexp` mention `- C-u` as raw negative prefix argument. However, as far as I understand the Emacs manual, such an argument is given by either `M--`, or by `C-u -`.

- `smartparens` version: 20190103.2309
- Active `major-mode`: `lisp-interaction-mode`
- Smartparens strict mode: t
- Emacs version (`M-x emacs-version`): GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

**Comment by Fuco1** [comment]
It seems that it's not the same

```elisp
(defun my-test-interactive (arg)
  (interactive "P")
  (message "argument is %S" arg))
```

I get this

```
M-- C-u argument is (-4)
C-u - argument is -
C-- C-u argument is (-4)
```

**Comment by whxvd** [comment]
Thank you. That lead me to thoroughly study and understand Emacs raw prefix arguments.

This issue has become a no-issue. But there is a related new issue: #954.
