### ISSUE TITLE
Duplicate paragraph in wiki/Hybrid-S-expressions

### ISSUE THREAD

**Issue by whxvd** [Fuco1/smartparens#952]
The last example on the mentioned wiki page contains two `:=>`. The second one, i.e. the very last `:=>` on the page, should be removed, including what follows.

**Comment by Fuco1** [comment]
@whxvd Thanks! I've enabled public editing of the wiki, can you try to fix the issue so that I see it works?

**Comment by whxvd** [comment]
It worked.

However, after introducing the change I noticed that I was wrong. The second `:=>` is indeed meaningful as it in fact slurps one more statement (`return 0;`). I was too quick in judgment and oversaw that.

I found no way of doing a `git reset HEAD^` in the web interface of the wiki. The only possibility the web interface seems to offer is to put an inverse commit on top of it.

Sorry for the noise.

**Comment by Fuco1** [comment]
I think a revert is fine.  You can also clone locally and do the changes there and then push I suppose, but probably a force push won't work.

**Comment by whxvd** [comment]
> You can also clone locally and do the changes there and then push I suppose, but probably a force push won't work.

I tried three scenarios and all ended with the same error message:
```
ERROR: Permission to Fuco1/smartparens.wiki.git denied to whxvd.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

1. `git reset --hard HEAD^` followed by `git push origin`.
2. `git reset --hard origin/master` followed by `git push origin`. (A push that wouldn't change anything).
3. `git revert HEAD` followed by `git push origin`.

**Comment by whxvd** [comment]
I reverted manually, using the web interface.
