### ISSUE TITLE
Wiki Headings

### ISSUE THREAD

**Issue by whxvd** [Fuco1/smartparens#957]
Some headings in the wiki do not display correctly. They are displayed as normal text. See e.g. "Editing Permissions". Somehow this stems from the headings being written like that:
```
<a name="list-property-inheritance" />
# List property inheritance
```
When the HTML anchor name tags are removed, everything is fine. The anchor name tags contain the headings in lowercase with spaces replaced by dashes. Ids like that are auto-generated, anyway. Links like https://github.com/Fuco1/smartparens/wiki/Permissions#list-property-inheritance still work without the explicit tag.

I tentatively removed the tags in "Pair management". It contains a TOC with a link to every heading in the page. They still work.

 I will change the other pages, too, if I do not hear you scream.

**Comment by Fuco1** [comment]
Yes, I think this is from waaaay back when the anchors were not auto-generated.  If you could also update the other pages that would be much appreciated.

I'm slowly trying to migrate the wiki to sphinx and put it on readthedocs (it has better formatting), but I haven't really done anything there for the last two years, so we can go ahead and update the wiki a bit :)

**Comment by whxvd** [comment]
> If you could also update the other pages that would be much appreciated.

Done.
