### ISSUE TITLE
AST support in LSP protocol planned

### ISSUE THREAD

**Issue by yyoncho** [Fuco1/smartparens#959]
You may take a look at https://github.com/Microsoft/language-server-protocol/issues/613  Q&A section in particular.

**Comment by yyoncho** [comment]
You might be interested in https://github.com/ubolonton/emacs-tree-sitter/ as well.

**Comment by Fuco1** [comment]
Tree sitter is now core but I'm not sure I have the capacity to rewrite smartparens to use that instead of the regexps we use now.  Maybe some new more modern mode will come along.
