### ISSUE TITLE
Removing parentheses in ocaml removes the ~

### ISSUE THREAD

**Issue by Wilfred** [Fuco1/smartparens#966]
## Expected behavior

Call `sp-splice-sexp` on the first parentheses in:

```ocaml
let foo ~(x) y = (x, y);;
```

should produce:

```ocaml
let foo ~x y = (x, y);;
```

## Actual behavior

```ocaml
let foo x y = (x, y);;
```

## Steps to reproduce the problem

Start with the code sample, and press `M-x sp-splice-sexp` on the `(x)`.

## Environment & version information

- `smartparens` version: 20181212.1956
- Active `major-mode`: `tuareg-mode`
- Smartparens strict mode: t
- Emacs version (`M-x emacs-version`): GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31
- Starterkit/Distribution: Vanilla
- OS: darwin

**Comment by Fuco1** [comment]
Can you tell me the syntax class of `~`?  `C-u C-x =` on the point.

Is it _always_ the case that we want to keep it?

**Comment by Wilfred** [comment]
`~` is punctuation:

```
             position: 9 of 32 (25%), column: 8
            character: ~ (displayed as ~) (codepoint 126, #o176, #x7e)
    preferred charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x7E
               script: latin
               syntax: . p	which means: punctuation,
	  is a prefix character for `backward-prefix-chars'
             category: .:Base, >:Not at bol, a:ASCII, l:Latin
             to input: type "C-x 8 RET 7e" or "C-x 8 RET TILDE"
          buffer code: #x7E
            file code: #x7E (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
```

We always want to keep it. An argument `~foo` is a labelled argument in ocaml, allowing callers to specify the name (like `&key foo` for `cl-defun`). Without `~`, the argument is only positional.
