### ISSUE TITLE
Quote in C/C++ mode

### ISSUE THREAD

**Issue by linux40** [Fuco1/smartparens#967]
## Original title: Stop match quote and quasiquote in lisp

There is need to match quote and quasiqute like pairs in lisp. I see `show-smartparens-mode` highlight two quotes in following snippet.
```
(require 'auto-compile)
(auto-compile-on-save-mode)
(setq auto-compile-display-buffer nil)
(setq byte-compile-warnings nil)

(require 'exec-path-from-shell)
```
This also case wrong behaviour. For example, if i execute `sp-forward-barf-sexp` after first `require` above, i will get `funcall-interactively: Wrong type argument: number-or-marker-p, nil`.

My configuration about smartparens is following with some key-binding settings
```
(require 'smartparens)
(smartparens-global-mode 1)
(show-smartparens-global-mode 1)
```

- `smartparens` version: 20190128.1747 (installed from melpa)
- Active major-mode: lisp-*-mode
- Emacs version (`M-x emacs-version`): 27.0.50

**Comment by Fuco1** [comment]
You can do `(require 'smartparens-config)` to set up exceptions for lisp.

**Comment by linux40** [comment]
Thank you.

**Comment by linux40** [comment]
I find another thing about the misbehaviour of smartparens. In any postions of C/C++ code, press `'` lead `\'\'` while the expected result is `''`.

**Comment by raxod502** [comment]
See https://github.com/Fuco1/smartparens/issues/783.
