### ISSUE TITLE
sp-up-sexp from inside string should not remove whitespace

### ISSUE THREAD

**Issue by bymoz089** [Fuco1/smartparens#978]
## Description
using `M-x sp-up-sexp` from inside a string should not remove whitespace

## Steps to reproduce the problem

1. Create a string in you buffer like 

`"|    "`

_Note: `'|'` marks the cursor position_

2. call `M-x sp-up-sexp`

## Expected behavior

this should result in
`" "|`

## Actual behavior
it results in
`""|`

## Further comments
consider following elisp source code (_with cursor at `|`_):
`(concat "foo" "| " "bar")`
which would eval to `"foo bar"`

Using `sp-up-sexp` from this position would change the source code to:
`(concat "foo" "" "bar")`
which would eval to: `"foobar"`

`sp-up-sexp` with its current behaviour introduces a bug in the above elisp source code.

## Environment & version information

- plain emacs 
- current smartparens versions
- all OS

**Comment by Fuco1** [comment]
Set `sp-navigate-reindent-after-up-in-string` to `nil`.

**Comment by bymoz089** [comment]
sorry for reporting this
