### ISSUE TITLE
Question: get different pair for the same prefix depending on context

### ISSUE THREAD

**Issue by Hi-Angel** [Fuco1/smartparens#979]
This kind of answered [in documentation](https://github.com/Fuco1/smartparens/wiki/Pair-management) that pairs has to be prefix-free, but I still wonder is there maybe a hook to change the pair on the fly?

What I want: I deal most often with C-like languages, and it came into my head that it may be nice to configure smartparens so that when I press `(`, smartparens would test *"is caret at end-of-line **and** line has no `switch`, `if`, `else` keywords in it"*, and then will insert either `);` or `)` as a closing pair.

**Comment by Fuco1** [comment]
So, pairs don't have to be prefix-free and I should update the documentation.  What this means is that you can have a pair `{ }` and `{- -}` for example.  You still can't have pairs `( )` and `( );`, so the limitation is that the opening pairs have to be unique.

However, you can achieve what you want with a post-insertion hook: https://github.com/Fuco1/smartparens/wiki/Permissions#pre-and-post-action-hooks

**Comment by Hi-Angel** [comment]
Thank you, works for me! For reference, here's the code I had to implement:

```lisp
(defun maybe-add-semicolon (_id action _context)
  (when (eq action 'insert)
    (save-excursion
      (forward-char) ;; skip closing brace
      (when (and (looking-at "\\s-*$") ;; if at end-of-line and no if/else/switch/for/while/do keywords
                 (not (string-match-p
                       "\\(\\bif\\b\\)\\|\\(\\belse\\b\\)\\|\\(\\bswitch\\b\\)\\|\\(\\bfor\\b\\)\\|\\(\\bwhile\\b\\)\\|\\(\\bdo\\b\\)"
                       (buffer-substring (line-beginning-position) (line-end-position)))))
        (insert ";")))))

(let ((c-like-modes-list '(derived-mode-p 'c-mode 'c++-mode 'java-mode 'csharp-mode 'lua-mode)))
  (sp-local-pair c-like-modes-list "(" nil :post-handlers '(:add maybe-add-semicolon)))
```

Also great that it works nicely with the global customized behavior [that I already had](https://github.com/Hi-Angel/dotfiles/blob/master/.emacs.d/lisp/sp-sublimelike.el#L21).
