### ISSUE TITLE
Byte-compilation warnings during installation

### ISSUE THREAD

**Issue by zs19940317** [Fuco1/smartparens#980]
## Expected behavior
install it correctly

## Actual behavior
Compiling file /home/zhangshuai/.emacs.d/elpa/smartparens-20190522.2234/smartparens.el at Thu Jun  6 10:19:28 2019

Compiling no file at Thu Jun  6 10:19:29 2019
Warning (bytecomp): Unused lexical variable ‘end-line’
Warning (bytecomp): Unused lexical variable ‘allowed-open’
Warning (bytecomp): Unused lexical variable ‘allowed-close’

## Steps to reproduce the problem
use list-packages to intall it

## Environment & version information
fedora 30
smartparens version:20190522.2234
**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version:20190522.2234
- Active major-mode:
- Emacs version (`M-x emacs-version`):26.2
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla:
- OS:fedora

**Comment by Wilfred** [comment]
Those look warnings rather than errors.

**Comment by Fuco1** [comment]
Were fixed in some pull request.
