### ISSUE TITLE
How to decactivate certain properties of smartparens. 

### ISSUE THREAD

**Issue by ofenerci** [Fuco1/smartparens#983]
I wonder there is a way to deactivate LaTeX quote for smartparens. ıt is not working (or something wrong with my setup) as expected.

**Comment by Fuco1** [comment]
Probably there is.  Can you add more details? What are you typing and what is the result.

**Comment by ofenerci** [comment]
I am getting the problem described  in this [post](https://github.com/Fuco1/smartparens/issues/772)

I am using  normal double quotes in my LaTeX documents (I have a figure macro which uses  `"` such as `fig("myfig.png")` I don't want smartparens to trigger ``` ''` when I type double quote` "`

**Comment by Fuco1** [comment]
That behavour is defined in `smartparens-latex.el`.  Setting the trigger to `nil` should do what you want, i.e. deactivate the `"` inserting the "latex quotes"

```elisp
(sp-local-pair "``" "''"
                 :trigger nil
                 :unless '(sp-latex-point-after-backslash)
                 :post-handlers '(sp-latex-skip-double-quote))
```

**Comment by ofenerci** [comment]
I am using Prelude Emacs and in its `prelude-latex.el` file, there are AucTeX commands in which they set the behaviour of quotes. They were set to non-nil.

```
(setq TeX-close-quote "")
(setq TeX-open-quote "")

```

After removing them, the smartparents has started to work properly. Both smartparens and AucTeX were trying to get the hand of quotes. I want to use AucTeX's double quotes and I have used your code to deactivate the quotes in smartparens but it is still interfering with AucTeX's quote commands (it is not deactivating itself). Here is my related code:

```
(use-package smartparens
  :diminish smartparens-mode
  :commands smartparens-mode
  :general
  ('normal smartparens-mode-map "M-l" 'sp-next-sexp)
  ('normal smartparens-mode-map "M-h" 'sp-previous-sexp)
  ('normal smartparens-mode-map "M-k" 'sp-up-sexp)
  ('normal smartparens-mode-map "M-j" 'sp-down-sexp)
  ('normal smartparens-mode-map "C-M-l" 'sp-forward-sexp)
  :init
  (add-hook 'python-mode-hook 'smartparens-mode)
  ;;(add-hook 'lisp-interaction-mode-hook 'smartparens-mode)
  ;; (add-hook 'emacs-lisp-mode-hook 'smartparens-mode)
  (add-hook 'LaTeX-mode-hook 'smartparens-mode)
  (add-hook 'org-mode-hook 'smartparens-mode)
  :config
  (sp-local-pair 'org-mode "_" "_" )
 
  (sp-local-pair 'latex-mode "``" "''"
                 :trigger nil
                 :unless '(sp-latex-point-after-backslash)
                 :post-handlers '(sp-latex-skip-double-quote))
  (sp-local-pair 'org-mode "*" "*" )
  (sp-local-pair 'latex-mode "$" "$")
  (sp-local-pair 'latex-mode "\\left(" "\\right)" :trigger "\\l(")
  ;; highligh matching brackets
  (show-smartparens-global-mode 0)
  ;; so that paren highlights do not override region marking (aka selecting)
  (setq show-paren-priority -1)
  (setq show-paren-when-point-inside-paren t)
  (setq sp-show-pair-from-inside t)
  (setq show-paren-style 'mixed))





```

**Comment by Fuco1** [comment]
(Sorry for the close/open spam, wrong button)

What does it even mean to set those variables to empty strings?

```
(setq TeX-close-quote "")
(setq TeX-open-quote "")
```

Does it then insert nothing when you hit the quote?  Just to clarify, is this what you did to decativate the auctex feature or is this what prelude did?

These kinds of issues are really quite annoying because the package behaves stupidly (which goes against its name) and ultra hard to debug/test/repro because of the package interference (+ possible version differences).

I tried to repro but I can't even get latex-mode to work at my computer :( I'll try again on some other system.

Can you run `M-x sp-describe-system` and paste the output? It will collect versions of some packages, emacs etc.

**Comment by ofenerci** [comment]
Those functions were defined by AucTeX which is LaTeX package for writing TeX files. You can find more what is them  about [them](https://www.gnu.org/software/auctex/manual/auctex/Quotes.html). I will try it in basic Emacs. Here is the about output by ´M-x sp-describe-system´:
```

The content of the buffer underneath the line was
copied to your clipboard.  You can also edit it in this buffer
and then copy the results manually.
------------------------------------------------
- `smartparens` version: 20190622.1750
- Active `major-mode`: `lisp-interaction-mode`
- Smartparens strict mode: t
- Emacs version (`M-x emacs-version`): GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-08-23
- Starterkit/Distribution: Prelude (edited by me)
- OS: gnu/linux

```
