### ISSUE TITLE
How to make smartparens work with prime notation?

### ISSUE THREAD

**Issue by rommeswi** [Fuco1/smartparens#990]
## Expected behavior
In LaTeX documents, frequently the notation f' or f'' is used for derivatives or even for enumeration. Of course, double single quotes are also used for ending a double quote, for example, \`\`Bla''. This creates many error messages and sometimes seems to even mess with syntax highlighting?
Ideally, there should be a way to solve this by differentiating between math mode and text mode. Outside $ $ or \begin{equation} \end{equation}, etc., smartparens should look for the matching \`\` for each ''. Inside math environments, smartparens should ignore single quote characters.

## Actual behavior
Smartparens tries to to match the '' in f'' and of course fails. It frequently displays error messages about unmatched delimiters.

## Steps to reproduce the problem
Type any document that makes use of prime notation.

## Environment & version information
- `smartparens` version: 20190522.2234
- Active `major-mode`: `latex-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 26.2 (build 1, x86_64-w64-mingw32) of 2019-04-13
- Starterkit/Distribution: Spacemacs
- OS: windows-nt

**Comment by Fuco1** [comment]
So the solution you propose is to stop matching of the quotes inside math environments.  I think that's a good solution.

You should be able to test this by running this code in your Emacs

```elisp
(sp-local-pair 'latex-mode "``" "''"
                 :trigger "\""
                 :unless '(sp-latex-point-after-backslash sp-in-math-p)
                 :post-handlers '(sp-latex-skip-double-quote))
```

I've added the `sp-in-math-p` predicate from the "standard smartparens library".  If it works fine we can add this to the master.

**Comment by rommeswi** [comment]
Thank you for this. 

I think the desired solution is indeed for smartparens to not try to find the matching \`\` for f'' in math mode. Similarly, it should not try to find \` for f'.

The following simple modification of your code fixed this case as well:
`
(sp-local-pair 'latex-mode "\`" "\'"
                 :trigger "\\""
                 :unless '(sp-latex-point-after-backslash sp-in-math-p)
                 :post-handlers '(sp-latex-skip-double-quote))
`
Together, they work beautifully! Thank you very much!

**Comment by Fuco1** [comment]
ok thanks for the confirmation!  I'll add this setting to the master branch
