### ISSUE TITLE
SP + org-mode + org-hide-emphasis-markers

### ISSUE THREAD

**Issue by fpopineau** [Fuco1/smartparens#991]
Hi,

It seems to me that there is a bad interaction of org-hide-emphasis-markers with SP
The following is with
(setq org-hide-emphasis-markers t)
so the // fences are invisible
The | denotes the cursor position.

## Expected behavior
I type in:
This is a /|/
This is a /test|/
next, Ctrl+f (or Ctrl-e)
This is a /test/|

## Actual behavior
What I get is the cursor on the next line, not after the invisible / fence.
If I change org-hide-emphasis-markers to nil, the cursor goes after the fence.

## Steps to reproduce the problem
Load org-mode, smartparens, smartparens-config
Try with org-hide-emphasis-markers set to t or nil

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.
- `smartparens` version: 20190904.1742
- Active `major-mode`: `org-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-21
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

Best regards,

**Comment by Fuco1** [comment]
I'm also using the hidden emphasis. I wrote a blog post about this some years ago https://fuco1.github.io/2017-05-03-WAR-STORY:-Prevent-point-jumping-around-invisible-text.html

Do you think you'd be able to debug this with the info provided there?  It seems things work fine for me on Emacs 26, I don't have the newer version available at the moment.
